### ISSUE TITLE
Implement fuzzy search

### ISSUE THREAD

**Issue by vicb** [zealdocs/zeal#100]
Devdocs.io has a feature called fuzzy search, for example "pmsg" would autocomplete to "window.postMessage".

I would like to see this implemented in Zeal.

Thanks for this project, really good !

**Comment by trollixx** [comment]
@vicb Why did you close this issue? It hasn't been implemented yet.

**Comment by vicb** [comment]
because it has been opened 18 months ago and I think it was stall.
happy to learn this is still considered.

**Comment by vicb** [comment]
:+1:

**Comment by jrappen** [comment]
Dropping a reference here to: <https://github.com/forrestthewoods/lib_fts> and the fuzzy_match there. Haven't done any performance comparisons.

**Comment by trollixx** [comment]
@jrappen Thanks, we know about the `fts_fuzzy_match` project.  IIRC @jkozera also had some concerns about potential performance if integrated in Zeal.
