### ISSUE TITLE
After updating c++ docset is not shown

### ISSUE THREAD

**Issue by elch10** [zealdocs/zeal#1001]
Recently, I updated c++ docset. But now I see nothinng, when I choose any c++ category, it only shows the start page.
![default](https://user-images.githubusercontent.com/15147137/46256614-b6374400-c4b5-11e8-8628-c9b07e017372.png)
And I can't find any log files.
Version:
![default](https://user-images.githubusercontent.com/15147137/46256639-04e4de00-c4b6-11e8-973e-cc133031bcea.png)

**Comment by auscompgeek** [comment]
Zeal 0.2.1 is very old. Does it work if you update Zeal?

**Comment by elch10** [comment]
Yes, with new version work fine
Thank you

**Comment by j-ulrich** [comment]
I had a similar issue with Zeal 0.6.1. For me, it simply showed a blank view. But restarting Zeal fixed it.

**Comment by trollixx** [comment]
@j-ulrich might be a bug with Qt WebKit. Please create a new ticket if you manage to reproduce it.
