### ISSUE TITLE
Local file:// links not working in the javascript docset

### ISSUE THREAD

**Issue by GoodGuyNick** [zealdocs/zeal#1010]
Ubuntu 18.04.1, Zeal 0.6.0

Can't open any local link in the javascript docset.

**Comment by nishanthkarthik** [comment]
It looks like an upstream packaging issue. Please rename `JavaScript.docset/Contents/Resources/Documents/developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects` to `Global_Objects`. (Notice the capital `O` in the folder name).

I already reported this to @Kapeli

**Comment by trollixx** [comment]
Duplicate of #1009 (just for linking).
