### ISSUE TITLE
search form“ cpp: keyword ”doesn't work

### ISSUE THREAD

**Issue by XiGou** [zealdocs/zeal#1011]
platform：windows 10

I copied the software folder to “C:\Program Files\”.  then search form“ cpp: keyword ”doesn't work.

after that,I made the main program run through admin premission, it works .

so what's the reason?  
hope someone can solve the problem!  thinks.

**Comment by trollixx** [comment]
I think there's something wrong with your installation and/or permissions. Have you tried the portable version?
