### ISSUE TITLE
Zeal crashes. No clue why.

### ISSUE THREAD

**Issue by Akronix** [zealdocs/zeal#1013]
Since today or yesterday, I don't know, Zeal crashes just after typing few characters in the search box. I only remember to have added the javascript and node docs and, well, I have been installed some other system-wide packaged in my system.
This is the output I get:
```
zeal.core.applicationsingleton: Singleton ID: Q2BPcAoh0mT4ivBMS-4WtmJ239m5sgYFpeeC1GIW8vM
zeal.core.applicationsingleton: Starting as a primary instance. (PID: 8043)
Cannot determine index file for docset Perl
QSpiApplication::keyEventError  "org.freedesktop.DBus.Error.NoReply" "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
QSpiApplication::keyEventError  "org.freedesktop.DBus.Error.NoReply" "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
```
Another example of output:
```
zeal.core.applicationsingleton: Singleton ID: Q2BPcAoh0mT4ivBMS-4WtmJ239m5sgYFpeeC1GIW8vM
zeal.core.applicationsingleton: Starting as a primary instance. (PID: 19222)
Cannot determine index file for docset Perl
QAccessibleTree::indexFromLogical: invalid index:  -1 0  for  QTreeView(0x16f7640, name = "treeView")
Requested invalid tree cell:  -1 0
[1]    19222 segmentation fault (core dumped)
```

I'm on Ubuntu 16.04 and I have this docsets: Perl, Python 3, Pandas, Javascript and NodeJS and React.

**Comment by trollixx** [comment]
Can you try to reinstall the Perl docset?

**Comment by Akronix** [comment]
This is weird. I have rebooted the system and it doesn't crash anymore.
On the way, I realized I'm using a outdated version of Zeal. I'm using the [ppa repo](https://launchpad.net/~zeal-developers/+archive/ubuntu/ppa/+build/14428541), but the last offered version there is 0.5.0 since following buildings [failed](https://launchpad.net/~zeal-developers/+archive/ubuntu/ppa/+build/14428541). Anyway, I'll open an issue in zeal-packaging.

**Comment by Akronix** [comment]
Opened here: https://github.com/zealdocs/zeal-packaging/issues/40
