### ISSUE TITLE
Zeal 0.6.1 Installer for Windows 64 bit - installed Zeal will crash on start

### ISSUE THREAD

**Issue by AuriMoogle** [zealdocs/zeal#1014]
Zeal 0.6.1 Installer for Windows 64 bit

Select in the installer under advanced 'install just for you'.
The installed zeal will crash on start with the following error:
![zealcrash](https://user-images.githubusercontent.com/13130991/47075176-47b7ed00-d1fc-11e8-821b-577e35940974.JPG)

Reinstalling with the same settings will not fix the issue but selecting 'install for all users' in the installer will create a functioning version of zeal.

**Comment by trollixx** [comment]
This has been reported before (zealdocs/zeal-packaging#36), but I haven't looked into it yet. Any help with MSI would be appreciated.

**Comment by trollixx** [comment]
@ThaGazer you problem is different, and can be solved by installin [Microsoft Visual C++ 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=53587).

**Comment by trollixx** [comment]
Closing in favor of #979.
