### ISSUE TITLE
Docset not loading

### ISSUE THREAD

**Issue by hank** [zealdocs/zeal#1015]
I created a new docset, but I can't get it to show up in the interface or produce any errors/debug. Please let me know how I can get some sort of output to debug my docset, or suggest another way to do so. I've created the docset directory in the APPDATA location on Windows along with the other 3 working docsets I have. Thanks!! Looking forward to using this EXTENSIVELY.

**Comment by hank** [comment]
Never mind, it was just that I hadn't generated the sqlite db yet. If you could add some sort of error log, that would be useful!!

**Comment by trollixx** [comment]
Yeah, error reporting needs to be improved. Some errors are reported to console, but on Windows it's trickier to see them.
