### ISSUE TITLE
Accelerator character conflict

### ISSUE THREAD

**Issue by wdscxsj** [zealdocs/zeal#1017]
In Preferences - Content, "Minimum font size" and "Open in desktop browser" use the same keyboard accelerator character "o".

**Comment by trollixx** [comment]
They are in different windows/menus, they cannot conflict with each other...

**Comment by wdscxsj** [comment]
Sorry I don't quite get it. I mean, one has to press Alt+O twice to select "Open in desktop browser", which feels inconvenience (although acceptable).

![](https://i.postimg.cc/BvtTjxB1/Screenshot039.png)

**Comment by trollixx** [comment]
Now I see, thanks for reporting. Will fix!
