### ISSUE TITLE
Pandas documentation broken name of functions

### ISSUE THREAD

**Issue by elch10** [zealdocs/zeal#1019]
In pandas Api reference not displayed name of functions.
It is how it looks like on my zeal desktop app:
![default](https://user-images.githubusercontent.com/15147137/47353070-00ca6b80-d6c4-11e8-9be5-9d0087c19e87.png)
But in site https://pandas.pydata.org/pandas-docs/stable/api.html documentation it looks like:
![default](https://user-images.githubusercontent.com/15147137/47353140-366f5480-d6c4-11e8-90c5-74cb01cfc885.png)
Yes names is also links.
Zeal version: 0.6.1.
OS: Linux 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by auscompgeek** [comment]
Looks like this is probably #903 biting us again.

Can you try changing the monospace font size, in Preferences -> Content?

**Comment by elch10** [comment]
@auscompgeek Yes, after changing it works fine and content is displayed normally.

**Comment by trollixx** [comment]
Closing per above.
