### ISSUE TITLE
How to install docsets without internet connection 

### ISSUE THREAD

**Issue by halloleo** [zealdocs/zeal#1021]
On my Windows machine I don't have a connection to the external internet. 

I do have other machines (without Zeal installed) with Internet connection. I could download the docsets there and then transfer them via LAN to the Windows machine. 

How can I do this in detail: What are the URLs to download  docsets from? 

I am using the portable Zeal version, so from my understanding it should be enough to place the docsets on the Windows machine in the application's directory.

**Comment by trollixx** [comment]
There's no easy way to get complete set of metadata without Zeal itself. The best option would be downloading all the docsets using Zeal on another computer, and then copying docset storage directory to the one without Internet connection.

**Comment by halloleo** [comment]
I see. Thanks. -Can I use Dash on macOS for this? The other computers are all Macs

**Comment by trollixx** [comment]
No, Dash stores docsets differently.
