### ISSUE TITLE
JavaScript is disabled for docsets that need it (0.7.0 regression)

### ISSUE THREAD

**Issue by afajansari** [zealdocs/zeal#1024]
in the active window of docs tabs of content not change in the active page...

**Comment by trollixx** [comment]
Which docset specifically?

**Comment by trollixx** [comment]
Actually if this is about build from master, then this is a regression caused by #1003.

I've found an old email from Bogdan explaining which docsets need to have JS enabled despite not having `isJavaScriptEnabled` set:

> Some older docsets have JS enabled internally in Dash. This was so that I didn't have to post updates to all the already existing docsets when I made the switch to blocking JS.
>
> These are the docsets:
>
> jQuery UI.docset
> jQuery Mobile.docset
> jQuery.docset
> Foundation.docset
> Sass.docset
> UnderscoreJS.docset
> BackboneJS.docset
> Bootstrap.docset
> CSS.docset
> HTML.docset
> XSLT.docset
> XUL.docset
> SVG.docset
> JavaScript.docset
> Lo-Dash.docset
> Dojo.docset
> Elixir.docset
> KnockoutJS.docset
> PhoneGap.docset
> MarionetteJS.docset
> Bourbon.docset
> Puppet.docset
> Neat.docset
> Xojo.docset
> Redis.docset
> sproutcore.docset
> Compass.docset
> Processing.docset
> Laravel.docset
> Sencha Touch.docset
> ExtJS.docset
> Appcelerator Titanium.docset
> Zend_Framework.docset
> AngularJS.docset
> PrototypeJS.docset
> Go.docset
> RubyMotion.docset
> Ruby.docset
> Ruby on Rails.docset
> Cappuccino.docset
> Unity 3D.docset
> CoffeeScript.docset
> Yii.docset
> Scala.docset
> Akka.docset
> YUI.docset
> Haskell.docset
> Android.docset
> Drupal.docset
> CodeIgniter.docset
> Joomla.docset
> Symfony.docset
> TYPO3.docset
> Cocos2D-X.docset
> Zend_Framework.docset
>
> Docsets that have these platforms (either DashDocSetFamily or DocSetPlatformFamily in Info.plist) are also enabled: 
>
> java
> playjava
> groovy
> javafx
> scaladoc

I guess we should address this on the backend side.

CC @nishanthkarthik

**Comment by nishanthkarthik** [comment]
@trollixx I will update with a new PR

**Comment by trollixx** [comment]
Zeal should not contain any metadata for specific docsets, so the only way to fix this is to make the change on the server side to send the information.

**Comment by nishanthkarthik** [comment]
Will the server side change be from kapeli's side or we have an additional endpoint ourselves for the same?
