### ISSUE TITLE
Why download the available docset display `Error creating SSL context ()` !!

### ISSUE THREAD

**Issue by vkkevin** [zealdocs/zeal#1029]
Why download the available docset display `Error creating SSL context ()` 
I don't know how to solve it.

**Comment by trollixx** [comment]
OS, Zeal version, how did you install it?

**Comment by vkkevin** [comment]
OS: Debian 9   x86_64  Linux: 4.9.0-7-amd64
Zeal: 0.3.1
I install the Zeal through apt.

**Comment by trollixx** [comment]
0.3.1 is a super old version, not sure if it's trying to connect to the correct address even. Would it be possible for you upgrade? Zeal is also available as a Flatpak package.

**Comment by vkkevin** [comment]
But I can't build the lastest version..
I don't know how to build zeal?

**Comment by vkkevin** [comment]
I have installed a lastest version.This problem is solved.
But thank you very much.

**Comment by trollixx** [comment]
Closing per above.
