### ISSUE TITLE
"Select search bar" hotkey within search bar should select all text

### ISSUE THREAD

**Issue by mcomella** [zealdocs/zeal#1033]
ctrl+L will focus the search bar and select all the text, like a browser. While the search bar has focus, in a browser ctrl+L will select all the text (i.e. the behavior doesn't change depending on what's focused) while in zeal ctrl+L will do nothing.

I propose we make ctrl+L select all the text no matter what is focused (particularly solving the issue where ctrl+L does nothing while the search bar is focused).

**Comment by mcomella** [comment]
I noticed there are several keyboard shortcuts that can do this from #401:
- ctrl+L
- ctrl+k
- ?

We should consider if these should also have the same behavior.

**Comment by evanricard** [comment]
I would like to just have a keyboard shortcut to navigate directly to the docset bar. Navigating through the different symbolic information of a given docset with the arrow keys (which we can already do by clicking the sidebar then using arrow keys) would be extremely helpful for me personally.

**Comment by trollixx** [comment]
With the referenced change search box handles focus shortcuts more intelligently, and sets selection according to the current selection, or cursor position.

@evanricard Up and Down arrow keys should work exactly as you describe (navigate within the sidebar), if they don't with the most recent version (or better built from master), please create a new ticket.
