### ISSUE TITLE
Windows Defender reports that zeal-portable-0.6.1-windows-x64.7z contains Trojan:Win32/Spursint.F!cl

### ISSUE THREAD

**Issue by larsw** [zealdocs/zeal#1040]
Trojan:Win32/Spursint.F!cl
Alert level: Severe
Category: Trojan
Affected items:
file: C:\Users\xxxxx\Downloads\zeal-portable-0.6.1-windows-x64.7z

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fSpursint.F!cl&threatid=2147717281

**Comment by alex-fgsfds** [comment]
No alerts on my machine though

**Comment by trollixx** [comment]
VirusTotal [says](https://www.virustotal.com/#/url/77651b7165d3f5a68f4b444eb90f1f04217bc15b23ef280c0cb670b7e653c089/detection) everything is fine. 

I guess you didn't get the archive from BinTray or GitHub. Alternatively, your PC was already infected.

**Comment by trollixx** [comment]
[Correct link](https://www.virustotal.com/#/url/5304db78ff8d4be4475a80b8899d4636ff1e7b9ab5dec81f2d2f8db000a8fd08/detection)

Anyway, no issues on our side. Closing.
