### ISSUE TITLE
Why not use libarchive throughout to extract downloaded docsets?

### ISSUE THREAD

**Issue by RJVB** [zealdocs/zeal#1043]
`Extractor::extract()` uses libarchive to extract data from a downloaded archive and then handles all writing to disk itself. Why not instead use one of libarchive's convenience functions to recreate entries on disk?

I'll admit I have never used them but it seems to me that using those functions means you don't have to bother with the chores associated with recreating a directory structure, supporting different filetypes (including links) etc. All that functionality already exists in libarchive. In addition you gain access to extraction options (including 1 or 2 that could be very useful on a not-officially-supported platform ;) ) There is a possibility to register a progress reporting callback so you don't even have to give up showing progress.

**Comment by trollixx** [comment]
Zeal was using Libarchive for everything up until https://github.com/zealdocs/zeal/commit/0785dd4efa506a9cad3b043b9f81baea4429655c, which hasn't been released yet.

You can read about the issues in the linked ticket, but in short the problem is that Libarchive can't handle paths with non-Latin characters. Using Qt for file I/O allows us to work that around.

The new code should work on all platforms Qt supports including macOS.

**Comment by RJVB** [comment]
I install zeal from git/master so I tripped over the commit.

> Libarchive can't handle paths with non-Latin characters.

That's a bit unexpected, given how Apple's tar (aka bsdtar) uses libarchive (opens ticket and has "aha" moment ... MS Windows again :-/).

Sounds like a bug in libarchive which must have been reported and in the process of being fixed? If so it might have been a good idea to use Q_OS_WIN specific code (#ifdef or a _win implementation file) to maintain the pure libarchive code until the bug is fixed upstream. The original code looked a lot simpler judging from the diff.

**Comment by trollixx** [comment]
There's a ticket for Libarchive, but it's been open for years. It was easier to let Qt handle writing the files. 

In the future Zeal should handle compressed docsets (#138), and all this code will go away, so not much sense to invest a lot into it now. If you notice any issues with Qt based implementation, please create a bug report.

**Comment by RJVB** [comment]
>In the future Zeal should handle compressed docsets (#138)

Apparently that's still a vague and possibly distant future. In the meantime I'll just revert the commit in question for my own builds. I just checked: unpacking with HFS compression using libarchive doesn't feel any slower than the Qt-based implementation. And it's orders of magnitude faster than applying HFS compression after the initial extraction.

**Comment by trollixx** [comment]
I am just curious why do you care what actually writes to the file system? Qt implementation should not be slower than the old one, there should be no difference at all.

**Comment by RJVB** [comment]
Wasn't that clear? Libarchive has extraction options, among others for preserving (extended) attributes and more importantly,  to write the extracted files using HFS compression.

> Qt implementation should not be slower than the old one, there should be no difference at all.

I wouldn't bet my life on that, Qt generally comes with a considerable overhead (vs. "direct" implementations). Using the Qt implementation and then apply HFS compression to the extracted docset (using afsctool) is a LOT slower than letting libarchive do the compressing while extracting files.

**Comment by trollixx** [comment]
While I understand possible drawbacks for dropping Libarchive's file writing, I don't want to have two code paths for such an ordinary operation. Eventually compressed docsets will solve this problem for everyone.
