### ISSUE TITLE
Error while setting the maximum protocol version

### ISSUE THREAD

**Issue by nolouch** [zealdocs/zeal#1047]
System:  4.18.6-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 5 11:54:09 UTC 2018 x86_64 GNU/Linux
latest version `zeal-git-0.6.0.r0.gbae9a49-1`， report error when I downloading the docsets:
```
Error while setting the maximum protocol version
```

**Comment by trollixx** [comment]
Strange, is your system up to date? This sounds like an issue with Qt Network or OpenSSL.

**Comment by nolouch** [comment]
@trollixx Yes. It works fine after I upgrade the newly `libqt5network5`. Thanks.
