### ISSUE TITLE
R docset argument small

### ISSUE THREAD

**Issue by Krisselack** [zealdocs/zeal#1048]
The R docset shows the parameters and overall description extremely small. 
![image](https://user-images.githubusercontent.com/15987388/49584441-a9264d80-f95b-11e8-8eac-1c7ef2618141.png)
System: Ubuntu 18.04, Zeal: 0.6.0 (Ubuntu Package Manager)

**Comment by auscompgeek** [comment]
I think this is a lingering affect of #903.

Could you please try changing the default font size in the Zeal preferences?

**Comment by Krisselack** [comment]
Ah yes, thanks, that worked.
