### ISSUE TITLE
Documentations change theme when using dark GTK themes (unreadable)

### ISSUE THREAD

**Issue by LogX7** [zealdocs/zeal#1052]
SYSINFO:
Linux Mint 19 -  cinnamon 3.8.9
Theme - Ant Dracula ( the issue is the same with many other dark themes )

![image](https://user-images.githubusercontent.com/9774613/49703125-7604e800-fc01-11e8-8ac9-3eb8016b2561.png)

**Comment by trollixx** [comment]
What version of Zeal do you have? This problem was fixed in 0.6.1.

**Comment by LogX7** [comment]
i have 0.6.0
but version 0.6.1 isn't available in apt ..

**Comment by knixeur** [comment]
You've to use PPA's to get the latest version on Ubuntu:
- https://zealdocs.org/download.html scroll down to Ubuntu and you'll read 
> When the official package becomes outdated, our own PPA repository provides an up-to-date version. Run the following commands to use the PPA:
- https://launchpad.net/~zeal-developers/+archive/ubuntu/ppa
