### ISSUE TITLE
Postgres documentation rendering is broken

### ISSUE THREAD

**Issue by dbalan** [zealdocs/zeal#1054]
While browsing for `Postgres` documentation, the code blocs are rendered wrongly.

This is what zeal shows me:
![delete_zeal](https://user-images.githubusercontent.com/223910/49996503-78639b00-ff8f-11e8-94f0-582352b989b8.png)

and if I open the same document in browser, that renders it properly:
![delete_browser](https://user-images.githubusercontent.com/223910/49996525-84e7f380-ff8f-11e8-98a1-fd363224140f.png)

**Comment by auscompgeek** [comment]
I think this is #903.

This seems to pop up fairly regularly... Zeal should probably try to fix configurations that were broken by that bug.

**Comment by trollixx** [comment]
I guess the only global fix would be resetting the default monospace font size, if configuration file is coming from 0.6.x.

**Comment by trollixx** [comment]
0.7.0 will reset the font size preference if it's coming from 0.6.0 settings.
