### ISSUE TITLE
update suggestion

### ISSUE THREAD

**Issue by ogcliff** [zealdocs/zeal#1057]
Zeal is a good app but the problem i see is the arrangement of the content in the guides i dont think arranging the contents alphabetically is a good idea because they are not that readable atleast if you would arrange them sequentially as in beginning with introduction going that side

**Comment by trollixx** [comment]
What you see in Zeal is more of an index, than a table of contents. Docsets don't have a concept of ToC, so there's not much we do about it until format is changed. Please follow #386 for updates.
