### ISSUE TITLE
storage is readonly

### ISSUE THREAD

**Issue by p205** [zealdocs/zeal#1059]
zeal-version: 0.6.1
os: Linux archlinux 4.20.0-arch1-1-ARCH

after mkdir (.local/share/Zeal/Zeal/docsets) by myself , it works

**Comment by trollixx** [comment]
There are problems with the read-only detection on Windows (#1036), now we discovered one on Linux. :(

**Comment by brejoc** [comment]
On Ubuntu (bionic) this is not working for me. Are we really talking about `~/.local/share/Zeal/Zeal/docsets` here?

**Comment by yfcube** [comment]
> On Ubuntu (bionic) this is not working for me. Are we really talking about `~/.local/share/Zeal/Zeal/docsets` here?

Yes it's indeed ```~/.local/share/Zeal/Zeal/docsets``` works for me on Ubuntu 16.04

**Comment by rotu** [comment]
:+1: After installing Zeal from apt on Ubuntu, I too had to `mkdir -p ~/.local/share/Zeal/Zeal/docsets`.

**Comment by trollixx** [comment]
@rotu Is there something special about how the home directory setup? Different user/group/permissions?

**Comment by rotu** [comment]
@trollixx Not AFAICT. The permission flags on `~/.local/share` are `drwx------` and I am the owner. AFAICT, Zeal should have had no trouble creating this directory.

**Comment by trollixx** [comment]
https://github.com/zealdocs/zeal/blob/58b92765ce8d2d0233840197e2ff777adb06b642/src/libs/ui/docsetsdialog.cpp#L86

I think it may be failing when path does not exist...

**Comment by LawrenceXia2008** [comment]
On windows, installing with Installer(MSI) style may rise this error. Then you can try install with Portable style, this will not rise any questions in Docset using. Hope this work for others.

**Comment by eromoe** [comment]
After I moved zeal-portable from C: to D:  , it gave me this error .

**Comment by trollixx** [comment]
@eromoe please try the CI build from AppVeyor.

**Comment by DaveFromTheUK** [comment]
The issue is relative vs absolute paths.

It shows up at a full path in Windows E:\blah blah\zeal\docsets

But you click "Browse", and locate it, and select location, it just puts "docset" as the directory. And then it works and finds previous docsets.

**Comment by zany130** [comment]
im getting this issue on garuda linux had to `mkdir -p ~/.local/share/Zeal/Zeal/docsets`

**Comment by iambrojohnson** [comment]
I'm experiencing the same issue too
My OS is PopOs
Tried every solutions here but nothing is woking
