### ISSUE TITLE
Are there any generator to make docsets easily?

### ISSUE THREAD

**Issue by SeasonCCC** [zealdocs/zeal#1067]
I want to build my own docsets. After searching a lot of tools, i generate the docsets by using gitbook and docset-generator in node.js finally. However, i still feel inconvenient about that. Are there any tools can make docsets easily?

**Comment by trollixx** [comment]
In the long run I would want to provide some generation services for common documentation sources, but for now the best way would be setting up a CI pipeline.

**Comment by SeasonCCC** [comment]
> In the long run I would want to provide some kind of generation service for common documentation sources, but for now the best way would be setting up a CI pipeline.

thx
