### ISSUE TITLE
Nuxt support

### ISSUE THREAD

**Issue by chiboreache** [zealdocs/zeal#1075]
please

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.herokuapp.com/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).
