### ISSUE TITLE
css file not loaded on Windows

### ISSUE THREAD

**Issue by schmidh** [zealdocs/zeal#1078]
The newly created docset for Perl 6 does not render well on Windows because the css file is not loaded.

[Windows renders incorrectly](https://github.com/schmidh/Perl6-Dash-Docset-Generator/issues/1)

**Comment by schmidh** [comment]
File path is `./css/app.css?v=7.css`as in the normal web page on https://docs.perl6.org/. File name looks strange but should not be a problem.

**Comment by trollixx** [comment]
Windows does not allow filenames with question marks.

**Comment by schmidh** [comment]
Ok. That explains it. Windows a bit picky. Will use a different downloader.

Thanks!
