### ISSUE TITLE
Clicking on 'expand full source code' scrolls page up to the top

### ISSUE THREAD

**Issue by thesystemsguy** [zealdocs/zeal#1079]
Clicking on **'expand full source code'** when viewing wordpress documentation scrolls page up to the top.
For example: 
1. After searching for the function get_bloginfo
2. Scroll down to the section titled 'Source'
3. Click on 'expand full source code'
4. The code doesn't expand rather the page scrolls to the top.

**Comment by naxvog** [comment]
This issue exists in the WordPress Docset btw

**Comment by nealhuchn** [comment]
Sorry

**Comment by einst3** [comment]
as long as the content of the page changes then this happens then the issue may be resolved.
