### ISSUE TITLE
Git and Github docset?

### ISSUE THREAD

**Issue by kurai021** [zealdocs/zeal#1082]
There is some Git external docset?

**Comment by trollixx** [comment]
I am not aware of any Git docsets.

Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.herokuapp.com/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).
