### ISSUE TITLE
Feature Request: Ctrl-Shift-J and Ctrl-Shift-K for navigating down/up search results

### ISSUE THREAD

**Issue by tsoernes** [zealdocs/zeal#1090]
Would be nice with Ctrl-Shift-J and Ctrl-Shift-K for navigating down/up in the search results in the left pane.

**Comment by trollixx** [comment]
Related to #1007, and #10 (#481). I think instead of adding new non-standard hard-coded shortcuts, the goal should be making them user configurable. Closing in favor of #10.
