### ISSUE TITLE
Feature request: support open new tab

### ISSUE THREAD

**Issue by sighingnow** [zealdocs/zeal#1092]
Zeal supports open link in new tab (#403). It will be great if zeal could support open a new tab directly and search for something.

**Comment by trollixx** [comment]
Just like any browser Zeal supports <kbd>Ctrl+T</kbd>, and `File -> New Tab`, or is it about something else?

**Comment by sighingnow** [comment]
I think it would be super convenient if we have a "+" button at the right of current tabs, just like what we have in web browsers (The rectangle area in the following figures).

Chrome:

![image](https://user-images.githubusercontent.com/7144772/55051705-49ca8580-5091-11e9-8bea-5837690c0ab1.png)

Zeal:

![image](https://user-images.githubusercontent.com/7144772/55051668-27d10300-5091-11e9-8039-ea7f9c1e8652.png)

**Comment by trollixx** [comment]
There's a request for that (#917), and a pull request (#968), which I need to review and test on different platforms. I'll close this ticket in favor of #917 then.

**Comment by sighingnow** [comment]
Thanks!
