### ISSUE TITLE
Net Framework syntax tab in page not changing from c# to vb or any other language

### ISSUE THREAD

**Issue by einst3** [zealdocs/zeal#1094]
Net Framework syntax tab in page not changing from c# to vb or any other language
to reproduce open classes, choose first class, on page there is c#, c++, f#, vb when you click one of these the page does not refresh for the language. zeal portable 0.6.1

**Comment by trollixx** [comment]
I think this is a duplicate of #1079, please try the latest [CI build](https://bintray.com/zealdocs/windows-ci/zeal-portable-unstable).

**Comment by einst3** [comment]
as long as the page content changes to the correct language then the issue may be resolved.
how do i download the latest windows ci portable version for testing?

**Comment by einst3** [comment]
i figured out how to download.

**Comment by einst3** [comment]
![Untitled](https://user-images.githubusercontent.com/7558232/55925057-5e069a80-5bda-11e9-8aab-1edf94306072.png)
the x64 version i tested of 0.6.1-47 did not resolve the issue and it still did refresh and moved back to the top of the page

**Comment by trollixx** [comment]
I forgot that I disabled uploading of unstable artifacts to BinTray :/ Please download the build from [here](https://ci.appveyor.com/project/zealdocs/zeal/build/job/m4cs9ook6xp7k5dr/artifacts).

Also I have just downloaded the docset, and it appears to work fine.
