### ISSUE TITLE
Kindly add ClojureScript docset to the Zeal documenation.

### ISSUE THREAD

**Issue by ahmedgeo13** [zealdocs/zeal#1095]
Zeal have Clojure API docset, but **ClojureScript** docset is missing. Kindly add it. It would help great way to have offline **ClojureScript** documentation offline.

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.herokuapp.com/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).
