### ISSUE TITLE
zoom too large, window size massive. Think zeal is zooming on top of default windows zoom of 250%

### ISSUE THREAD

**Issue by phoenixfel** [zealdocs/zeal#1099]

**Comment by phoenixfel** [comment]
When I open zoom it is opening with a massive window and massive toolbar and side menu. I am able to adjust the zoom in the main page showing the descriptions of certain functions...but the rest remains incredibly large. I think zeal is zooming 250% on top of my default windows setting of 250%.

**Comment by trollixx** [comment]
Which version are you using?

**Comment by phoenixfel** [comment]
> Which version of Zeal are you using?

Hi. I am using zeal version 0.6.1.0
![image](https://user-images.githubusercontent.com/49844868/56542123-3e089c80-6533-11e9-9e90-309dd74d0239.png)

**Comment by trollixx** [comment]
Please try the latest [CI build](https://ci.appveyor.com/project/zealdocs/zeal) (choose x86/x64 and portable/non-portable build, then go to Artifacts tab).

**Comment by trollixx** [comment]
Closing due to no response.
