### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by yourilima** [zealdocs/zeal#11]
Hi I just got a segmentation fault when hiding zeal
what i got is

``` bash
youri:~/ $ zeal                                                       [9:23:24]
QEventLoop: Cannot be used without QApplication
[1]    2803 segmentation fault (core dumped)  zeal
```

My hiding keybinding is alt+d.
It happens only when im on a multimonitor setup.
I'm running arch with fluxbox.
I installed qt5 specifically for using zeal.

Im not sure where I can find more info or log messages.

thanks :) great job btw.

**Comment by stardiviner** [comment]
I got this issue again.
I tried to remove all docsets. still got this error.
Also tried to remove `~/.local/share/Zeal` and `~/.config/Zeal`. Still got this error.
I install Zeal from Arch Linux AUR. I tried both packages `zeal` and `zeal-git`.

**Comment by trollixx** [comment]
@stardiviner, are you sure you have got this issue and not #595/#605?

**Comment by stardiviner** [comment]
@trollixx, sorry, my problem is exactly same with https://github.com/zealdocs/zeal/issues/595
