### ISSUE TITLE
Docset storage read-only when pointing to a non-existent directory, instead of showing a message indicating the directory doesn't exist

### ISSUE THREAD

**Issue by djndl1** [zealdocs/zeal#1102]
I incorrectly set the docset directory to a non-existent directory by directly typing the path instead of browsing into the path and when I tried downloading docsets, it said docset storage was read-only. It should give a warning that the path doesn't exist. At first I though it was a permission issue then I found the directory just didn't exist at all.

**Comment by mfurkanuslu** [comment]
for build of master branch (currently last commit is 2ac644536dfaa804def30c87bff740aa76f0244b) this behavior is already fixed. Its creates the directory if not exists.

**Comment by trollixx** [comment]
Duplicate of #1059. The read-only check fails in certain circumstances.
