### ISSUE TITLE
Fedora 30 builds unavailable in official repositories

### ISSUE THREAD

**Issue by jbirch** [zealdocs/zeal#1105]
The Linux download instructions page lists the following instructions for downloading Zeal for Fedora:

`$ sudo dnf install zeal`

And helpfully provides a link to the official packages for all Fedora versions.

Unfortunately, it looks like versions for Fedora 30 have been deleted at some point, and there are [currently no published Zeal packages for Fedora 30](https://apps.fedoraproject.org/packages/zeal/overview/). The [build for zeal-0.6.1-1.fc30](https://koji.fedoraproject.org/koji/buildinfo?buildID=1161757) notes this once existed, and is now deleted.

**Comment by jbirch** [comment]
In the short term, [zeal-0.6.1-1.fc29](https://koji.fedoraproject.org/koji/buildinfo?buildID=1161760) seems to work flawlessly on Fedora 30, if the RPM is installed by hand.

**Comment by trollixx** [comment]
I have no control over distribution packaging, you might want to create a ticket with the Fedora project.

**Comment by jbirch** [comment]
Oh, my apologies! I had misunderstood the process by which third-party software is included in the Fedora repositories.

I'll try and get in touch with the Fine Fedora Folk. Would you like to keep this ticket open as a "The installation instructions listed for Fedora do not work for the current Fedora version", or would you rather close this ticket as there's nothing to be done here, from a Zeal perspective?

**Comment by jbirch** [comment]
d'oh, it's apparently [already known](https://bugzilla.redhat.com/show_bug.cgi?id=1701666).

It would appear the maintainer of the Fedora package [obsoleted the build in favour of 0install](https://src.fedoraproject.org/rpms/zeal/c/2b4bce6873dac11585bd10bb41110dd33de5ab1c?branch=master). It looks like it's being handled now within the Fedora ecosystem.

**Comment by trollixx** [comment]
It's okay to keep it open to prevent similar questions. Hopefully they will add Zeal back soon.

**Comment by David-Else** [comment]
It is in testing, so almost back :)

**Comment by jbirch** [comment]
Can confirm Zeal is stable present in `updates` and ironically [slurping down this very issue as an open bug](https://bodhi.fedoraproject.org/updates/FEDORA-2019-3d36109433).

```
$ sudo dnf info zeal
...
Last metadata expiration check: 0:08:13 ago on Mon 17 Jun 2019 21:13:52 CDT.
...
Available Packages
Name         : zeal
Version      : 0.6.1
Release      : 2.fc30
Architecture : x86_64
Size         : 468 k
Source       : zeal-0.6.1-2.fc30.src.rpm
Repository   : updates
Summary      : Offline documentation browser inspired by Dash
URL          : https://zealdocs.org/
License      : GPLv3+ and BSD
Description  : Zeal is a simple offline documentation browser inspired by Dash.
```

I think this issue can be resolved now.

**Comment by frenzymadness** [comment]
There was a problem with an unresponsive maintainer and because I like zeal, I stepped in and became a co-maintainer to keep it work and up-to-date in Fedora. This issue can be closed.
