### ISSUE TITLE
CTRL+W for closing tabs?

### ISSUE THREAD

**Issue by carestad** [zealdocs/zeal#1111]
I seem to remember CTRL+W worked for closing tabs before (also #329 confirms that it has worked), but now it is CTRL+F4. Browsers (Firefox, Chrome) and other tab based applications (nautlius, nemo, ++) usually support CTRL+W these days, in Linux at least.

Could it maybe be changed back or added in addition to CTRL+F4? Maybe changing it only in the Linux builds is an option?

**Comment by trollixx** [comment]
This is fixed in 0b2657c44a55a69aaa70420287edf738c4acfbf3 by hard coding <kbd>Ctrl+W</kbd> instead of the platform default.
