### ISSUE TITLE
Feeds are Outdated

### ISSUE THREAD

**Issue by ferronrsmith** [zealdocs/zeal#1114]
https://api.zealdocs.org/v1 is outdated. Is there an automated process to ensure the feed list is kept up-to-date?

Think you might need a crontab.

**Comment by ferronrsmith** [comment]
Ended up forking and pushing the latest feed here : https://gist.githubusercontent.com/ferronrsmith/bfd57c087509cdfc37a44f0c4979b4e2/raw/docset.json

In case anyone is interested.

**Comment by trollixx** [comment]
Fixed, again :(
