### ISSUE TITLE
Docsets not update many times

### ISSUE THREAD

**Issue by husniddin1354** [zealdocs/zeal#1115]
Docsets not update many times

**Comment by trollixx** [comment]
Can you elaborate? If there's an error, please post a screenshot, and a sequence of actions to reproduce. Also information about the version of Zeal, and you operating system would be helpful.

**Comment by vaz-ar** [comment]
If @husniddin1354 problem is that he is not able to update his docsets anymore, then I have the same problem. 
There are no errors, the docsets are just not marked as having updates.
I can still remove and re add the docset to get the latest version without problems.
I am on windows 10 with the latest zeal version (0.6.1).
There is already another issue about outdated feeds (#1114 ), can this be related ?

**Comment by data-man** [comment]
> not able to update his docsets anymore

I have the same problem.
Zeal-git, Arch Linux.

**Comment by iHmD** [comment]
Same problem, zeal package on Arch Linux!

**Comment by vaz-ar** [comment]
I was able to update them just now, has something changed for someone else in this thread ?

**Comment by iHmD** [comment]
same here, I can now update the docs!
