### ISSUE TITLE
Cannot read from archive: gzip decompression failed

### ISSUE THREAD

**Issue by NamelessAshone** [zealdocs/zeal#1116]
After 100% download of C docset, I got this error message `Cannot read from archive: gzip decompression failed`.

- OS: 4.19.59-1-MANJARO
- Zeal:
    - qt5ct: using qt5ct plugin
    - Zeal 0.6.1
- gzip: gzip 1.10

**Comment by NamelessAshone** [comment]
When I download Java EE8 docset, it happen again. But Lua and Bash is ok.

**Comment by fsevenm** [comment]
I also got this problem. I thought this problem is going to happen when we try to install many docs at the same time. So I fixed it by canceling all the download queues, then I download it one by one and the gzip issue is just gone.

**Comment by trollixx** [comment]
I believe this was either a corrupted docset, or an issue with the Internet connectivity. Both C and Java EE8 docsets do not trigger any unpacking issues at this moment.
