### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by u3IFw2wfJ** [zealdocs/zeal#1117]
OS: Win 10 professional build 18362

I get a information from event viewer:

Faulting application name: zeal.exe, version: 0.6.1.0, time stamp: 0x5bbc471e
Faulting module name: Qt5Core.dll, version: 5.11.1.0, time stamp: 0x5b234a92
Exception code: 0xc0000005
Fault offset: 0x00000000001dddea
Faulting process id: 0x3714
Faulting application start time: 0x01d53d9548dd7c82
Faulting application path: C:\Users\bcui\Downloads\zeal-portable-0.6.1-windows-x64\zeal.exe
Faulting module path: C:\Users\bcui\Downloads\zeal-portable-0.6.1-windows-x64\Qt5Core.dll
Report Id: a6453cb2-bc4b-439d-97e0-9ee5a1bc6f20
Faulting package full name: 
Faulting package-relative application ID: 

Looks like a QT related issue.

**Comment by trollixx** [comment]
This usually indicates missing VC++ Runtime, see #979 for details.
