### ISSUE TITLE
Angular docset showing white screen

### ISSUE THREAD

**Issue by jshamg** [zealdocs/zeal#1119]
Hi,

I'am using Zeal version 0.6.1 and every document in the angular (2+) docset is just showing a white page...
Every else docset I downloaded is working properly...

Hope for a fix soon. Greetings!

**Comment by iqfy-joe** [comment]
I'm also seeing this issue, Zeal 0.6.1 on Ubuntu 18.04; Appears to be isolated to the Angular docset

**Comment by jshamg** [comment]
@iqfy-joe Is nobody caring about that? 😅 I mean I'm just using Angular, pretty stupid that I'm keeping this tool... Seems like nobody is fixing it...

**Comment by ergoproxy623** [comment]
Hello! Who knows why Angular 2 does not work?

**Comment by richarson** [comment]
I don't believe it will help, but: Have you tried reinstalling/updating the docset?

Zeal projects doesn't maintain docsets but uses [Dash](https://kapeli.com/dash)'s, you might want to ping @Kapeli about this issue.

**Comment by Kapeli** [comment]
No Dash user has reported any issues with the Angular docsets. If anyone is willing to debug and look at what's going wrong, I'm willing to update the docsets to fix it.

One thing to do would be to check if Zeal is using the correct Angular feeds, which are AngularJS.xml (for 1.x) and Angular.xml (for 2.x to 8.x).

**Comment by makzan** [comment]
It does work when right clicking mouse and open the doc in web browser.

**Comment by jshamg** [comment]
I have tried reinstalling/updating... still not working...

**Comment by jshamg** [comment]
@makzan I cant rightclick and open the docset in the browser... How do you do that? :)

**Comment by trollixx** [comment]
The problem is caused by the webview failing to parse JS (more details in https://github.com/zealdocs/zeal/issues/1127#issuecomment-527287446). Actual browsers have no such issues, so perhaps this will not get addressed until Qt WebKit gets updated to the newer WebKit, or we switch to Qt WebEngine.

I think the root of the issue might be the CORS not working for `file://` URLs, hence polyfills not getting loaded. I see related errors in the real browsers as well, but their JS engines do not require the polyfills to work.

I'll see if I can make a quick change to start serving docset content over HTTP.

**Comment by jshamg** [comment]
@trollixx a quick fix would be fantastical. I'm on vacation right now and taking my laptop everywhere I go... Sometimes I don't have internet, that's why I would really appreciate a quick solution. Thank you very much! :)

**Comment by martine777** [comment]
Same problem, a quick fix would be appreciated.

**Comment by jshamg** [comment]
@trollixx no fix soon?

**Comment by vpArth** [comment]
Looks like Qt webview is using Edge engine, because these pages fail to load in the old Edge(beta chromium edge works fine)

**Comment by jshamg** [comment]
no fix coming?

**Comment by trollixx** [comment]
Okay, for the time being I disabled JS for the Angular docset. I don't see a better solution, until we either switch to QWebEngine, or Qt WebKit is rebased on top of a more recent upstream version.

**Comment by trollixx** [comment]
To get the fix please refresh the list of docsets, and then reinstall the docset.

**Comment by iHmD** [comment]
still giving blank screen even after the refresh and update, am I the only one???

**Comment by jshamg** [comment]
I test that later (:

**Comment by djmbritt** [comment]
> still giving blank screen even after the refresh and update, am I the only one???

Same here.

**Comment by trollixx** [comment]
Please verify that `meta.json` in the docset folder has `isJavaScriptEnabled` set to `false`.

**Comment by djmbritt** [comment]
Can verify.

```
{
    "extra": {
        "isJavaScriptEnabled": false
    },
    "name": "Angular",
    "revision": "0",
    "title": "Angular",
    "version": "8.2.8"
}

```

**Comment by iHmD** [comment]
same content as @djmbritt 
`"extra": {
        "isJavaScriptEnabled": false
    },`

**Comment by jshamg** [comment]
same here... "fix" not working. still showing blank screen.

**Comment by GuillaumeSerrat** [comment]
Same here. Had an older version that was showing fine till I updated yesterday. Till then blank page.

**Comment by trollixx** [comment]
Please try one of the [CI builds](https://ci.appveyor.com/project/zealdocs/zeal/history). It looks like v0.6.1 didn't have a fix for per docset JS enablement.

**Comment by renaldas-kerpe-arria** [comment]
> Please try one of the [CI builds](https://ci.appveyor.com/project/zealdocs/zeal/history). It looks like v0.6.1 didn't have a fix for per docset JS enablement.

Thanks, the latest build seems work fine!

Just FYI: I did notice however that all Angular doc pages now have some seemingly random text at the very bottom of every page, but that seems harmless:
![image](https://user-images.githubusercontent.com/44429840/67081767-b4f3ba80-f18f-11e9-836e-0ce2fd35e6e8.png)

**Comment by trollixx** [comment]
The text says JS is required for the website to work.

**Comment by cuno92** [comment]
still giving blank screen on version 0.6.1

**Comment by Anas-Birikh** [comment]
Will there be a fix on 0.6.1?

**Comment by soichirou** [comment]
Will there be a fix planned for 0.6.1?

**Comment by trollixx** [comment]
Both Chromium and Firefox fail to display the HTML pages as well. I think there's something wrong with base paths:

```
ERROR Error: "The selector "aio-shell" did not match any elements"
ERROR Error: "No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document."
```

It doesn't work when served over HTTP (with #1182) either.

I am not sure how Dash shows the docs, but most likely it puts them under a different internal URL.

**Comment by GuillaumeSerrat** [comment]
If you want to bypass this issue the docset is still valid and accessible via your favorite browser....

Copypasta the following urls in your browser and replace the {drive} and {username} parameters:
-`file:///{drive}:/Users/{userName}/AppData/Local/Zeal/Zeal/docsets/Angular.docset/Contents/Resources/Documents/`

- `file:///{drive}:/Users/{userName}/AppData/Local/Zeal/Zeal/docsets/Angular.docset/Contents/Resources/Documents/material.angular.io.html`

**Comment by thariqnu-ifm** [comment]
> If you want to bypass this issue the docset is still valid and accessible via your favorite browser....
> 
> Copypasta the following urls in your browser and replace the {drive} and {username} parameters:
> -`file:///{drive}:/Users/{userName}/AppData/Local/Zeal/Zeal/docsets/Angular.docset/Contents/Resources/Documents/`
> 
> * `file:///{drive}:/Users/{userName}/AppData/Local/Zeal/Zeal/docsets/Angular.docset/Contents/Resources/Documents/material.angular.io.html`

I can confirm that this trick is working for me.

Basically, we can browse any of the downloaded `docsets` using any browser of our choice. To see where the downloaded `docsets` is being stored on the disk = click `Edit` > `Preferences` > `General` tab > `Docset storage` section > see the path within `Directory`. Then you can copy the path to your browser.

**Comment by Zeioth** [comment]
It's being fixed in the master branch.

**Comment by almeno** [comment]
A quick solution would be to delete the file that starts with "runtime-es5."
which is located in the folder "Angular.docset \ Contents \ Resources \ Documents \ angular.io"
Example: "runtime-es5.dbabbb81d8abd9e65276"

**Comment by vpArth** [comment]
No reason to delete files anyway can't be loaded by CORS of file:// restrictions

**Comment by mkantonio** [comment]
> A quick solution would be to delete the file that starts with "runtime-es5."
> which is located in the folder "Angular.docset \ Contents \ Resources \ Documents \ angular.io"
> Example: "runtime-es5.dbabbb81d8abd9e65276"

this works for me, thanks you so much! :D

**Comment by afajansari** [comment]
not opening angular docs while deleting 'runtine-es'
