### ISSUE TITLE
Progress on support for dash community docs and cheatsheets?

### ISSUE THREAD

**Issue by tacocats** [zealdocs/zeal#1120]
There's a few issues regarding adding support for Dash's cheatsheets and user contributed docsets. I was wondering if anyone was currently working on this? If not I'd be interested in attempting to add support.

**Comment by gcoelho** [comment]
My understanding is that it is being tracked here #170 , targeting v0.7.0 release (https://github.com/zealdocs/zeal/milestone/14).
