### ISSUE TITLE
Benefits of Zeal compared with DevDocs

### ISSUE THREAD

**Issue by ngirard** [zealdocs/zeal#1121]
Reading the available documentation, it is not clear what are Zeal's benefits & features compared with [DevDocs](https://github.com/freeCodeCamp/devdocs).

Could you elaborate a little on them ?

It might help people to choose between both tools, and encourage contributions.

Thanks !

**Comment by tacocats** [comment]
Hey, from user's perspective doesn't seem like there's much of a difference. They both allow searching documentation. 

From development perspective/creating your own docsets I believe zeal's main goal is to be a "Dash" that supports other platforms. It supports dash's docsets and features. I looked at devdocs a bit and it looks like they don't make use of docsets at all. Instead it looks like there are scrapers that grab data from various sites and generate their searchable docs. 

I'm sure there are other differences but looks like they're it's another approach at doing the same thing.

**Comment by ngirard** [comment]
Thanks for your thoughts !

How about adding them to the README file ? If you want, I could come up with a PR based on what you said ?

**Comment by trollixx** [comment]
I guess the main difference is that DevDocs is a web application (although capable to work offline), while Zeal is a plain old desktop app.

As @tacocats pointed out, Zeal relies on the docsets provided by Dash. DevDocs have their own scrapers to generate docs. In many cases both are produced from the same websites, but where Dash docsets are just downloaded webpages with a search index, DevDocs does extra post processing to ensure that all docs have a unified look.

Additionally, Dash docsets contain type information, e.g. classes, methods, etc, but that's not provided by DevDocs.

At some point in the past I was considering adding support for DevDocs docs, but the lack of type information, as well as conflict of interests between DevDocs and Dash made me abandon the idea.
