### ISSUE TITLE
`meta.json` -> `docset.json`

### ISSUE THREAD

**Issue by flokno** [zealdocs/zeal#1126]
I recently contributed some docsets to https://github.com/Kapeli/Dash-User-Contributions and noticed that they require a `docset.json` instead of `meta.json`. Zeal apparently does not recognize these files, if I only provide `docset.json`, it won't show the correct docset name in the overview.

I'm on zeal 0.6.1 on Linux Mint 18.3. Maybe this was already reworked in the past.

**Comment by trollixx** [comment]
`meta.json` is unique to Zeal, and was invented to provide metadata missing from the docset archive, namely icons, docset version and revision, etc. `docset.json` is only present in the user contributed repo, and does not come with built-in Dash docsets. In the future `meta.json` can be superseded by the new docset format (#1046).
