### ISSUE TITLE
angular docs

### ISSUE THREAD

**Issue by lambaaditya24** [zealdocs/zeal#1127]
Angular docs are not getting opened. I tried downloading it two times still nothing shows.

**Comment by Acelator** [comment]
I actually have the same issue. I can't access Angular docs inside Zeal
![image](https://user-images.githubusercontent.com/34861788/63224435-7e67e680-c1c4-11e9-96f2-eac629c77714.png)

**Comment by makzan** [comment]
It does work when right clicking mouse and open the doc in web browser.

**Comment by olegarxs** [comment]
fix please

**Comment by Moto28** [comment]
having the same issue

**Comment by samedwards1989** [comment]
Having this issue too

**Comment by iHmD** [comment]
same issue!

**Comment by trollixx** [comment]
It appears that Qt WebKit can't parse some of the JS files:

```

**Comment by iHmD** [comment]
> Blocking JS allows all the page to load.

@trollixx how did you do that please?

**Comment by trollixx** [comment]
@iHmD by changing the source, but still haven't figured out why it can't parse what other browsers parse without issues.

**Comment by trollixx** [comment]
This one is a duplicate of #1119.
