### ISSUE TITLE
crashes for Qt5 docset "all functions"

### ISSUE THREAD

**Issue by spaceplanet** [zealdocs/zeal#1128]
zeal crashes when:
    I selected qt5 docset in the left and then 
    under Qt Framework section I clicked "API" and next
   clicked "All classes" and next
   clicked "All functions"  ; and now after few seconds zeal crashes
I'm on windows 10 pro and I'm using zeal 0.6.1(64bit MSI installer version)

**Comment by PeeK1e** [comment]
Crashes for me when using the normal search query.
When attaching a debugger this error shows up: 
Exception thrown at **_address_** in zeal.exe: 0xC0000005: Access violation writing location **_address_** .

Im on Windows version 0.6.1

**Comment by PeeK1e** [comment]
Using the portable version for now. Seems to work

**Comment by PeeK1e** [comment]
Using the Portable Version and leaving all things on "factory settings" works for me

**Comment by spaceplanet** [comment]
I got this error when attached to Visual studio 2017 at the moment of its crash :
Exception thrown at 0x00007FFA3CBE2686 (Qt5WebKit.dll) in zeal.exe: 0xC0000005: Access violation writing location 0x000000159609E8D8.

**Comment by trollixx** [comment]
Considering that portable version works, I wonder if this has something to do with missing platform plugin from the MSI. See https://github.com/zealdocs/zeal/issues/1039 for more information.
