### ISSUE TITLE
Crash on startup after fresh install

### ISSUE THREAD

**Issue by Julien-Rozet** [zealdocs/zeal#1129]
Zeal 0.6.1 crashes at launch:
![2019-08-19 15_21_47-Zeal](https://user-images.githubusercontent.com/7222835/63268728-20570400-c295-11e9-80d7-f3faf0ebc8aa.png)

Even after (re)installing Microsoft Visual C++ 2015 Redistributable nor Zeal himself, I got the same error.

The only way I found to fix this is to get the `platforms` directory from portable version and put it in installation directory (`C:\Users\USER\AppData\Local\Apps\Zeal`).

Maybe something is missing on MSI package?

**Comment by trollixx** [comment]
I have never regenerated MSI packages, after this issue was fixed in https://github.com/zealdocs/zeal/issues/1039. :(

Will do shortly.
