### ISSUE TITLE
Freeze when opening doc pages with iframes

### ISSUE THREAD

**Issue by zarunet** [zealdocs/zeal#1131]
When opening a doc page with `iframes` in it for the first time (a prime candidate being the `iframe` page in the HTML docset), Zeal renders the page, then hangs for several minutes before rendering the iframes. Subsequent loads are fine, until the app is restarted.

**Comment by carestad** [comment]
Just came across this by accident. Earlier today and thought I _had_ to kill the app to have it working again, but it turns out waiting also works.

**Comment by trollixx** [comment]
[test-qtwebkit](https://github.com/OtterBrowser/test-qtwebkit) exhibits the same behavior, so apparently it's a Qt WebKit issue. @annulen any ideas?

**Comment by annulen** [comment]
What could be used as a test page?

**Comment by zarunet** [comment]
This is the first page where i witnessed the issue

![image](https://user-images.githubusercontent.com/43345608/66713518-1d1b5880-edac-11e9-915c-d8a093a733bf.png)

**Comment by trollixx** [comment]
@annulen https://www.openstreetmap.org/export/embed.html

**Comment by mitchet** [comment]
I had the same issue, however, under preferences if you choose open external link in Zeal it doesn't freeze anymore.
