### ISSUE TITLE
CI Builds for Windows are outdated

### ISSUE THREAD

**Issue by naxvog** [zealdocs/zeal#1135]
The Windows CI builds linked at https://zealdocs.org/download.html are over a year old

**Comment by trollixx** [comment]
Indeed, CI builds are no longer published to the BinTray, but rather [AppVeyor artifacts](https://ci.appveyor.com/project/zealdocs/zeal). I will update the page.

**Comment by trollixx** [comment]
Fixed the link and instructions.
