### ISSUE TITLE
WordPress Codex is deprecated

### ISSUE THREAD

**Issue by sebastienserre** [zealdocs/zeal#1145]
Hello,

**WordPress Codex is deprecated**. The only doc maintained is this one from https://developer.wordpress.org/reference/

Is it possible to remove the Codex feed ?

Many thanks

**Comment by Kapeli** [comment]
The WordPress docset uses **both** the Codex and the Developer Reference. If something is present in both the Codex and the Developer Reference, you can choose which one you want (in Dash - I don't know if Zeal supports this).

I tried having the docset use only the Developer Reference, but I got complaints from users saying the Codex is more complete for some pages and I had to switch to using both.

I don't know a lot about WordPress but if I compare http://codex.wordpress.org/Class_Reference/WP_User to https://developer.wordpress.org/reference/classes/wp_user/ it looks like the codex page is more complete (i.e. more examples and longer descriptions).

**Comment by sebastienserre** [comment]
Codex i**s not updated** when developer is automaticaly updated by a phpdoc parser... in few months Codex will disapear

**Comment by Kapeli** [comment]
I'll remove the Codex from the docset as soon as it's no longer available online.

**Comment by sebastienserre** [comment]
Thanks, but as it isn't updated... there's chance to have a wrong info in the codex...
Best practices should be to remove it

**Comment by trollixx** [comment]
The WP docset is maintained by @Kapeli, there's nothing to do on our side.
