### ISSUE TITLE
[FR] offline documentation browsing without internet

### ISSUE THREAD

**Issue by rayfoss** [zealdocs/zeal#1157]
I have a computer in a building without internet... I can ferry USB sticks to it, but it can never get connected.

Zeal sounded like a great alternative to the PDFs I've been using... But it doesn't work offline? That seems like an extremely obvious use case. I think I'll survive if my docsets are missing icons.

Meanwhile, the state of cutting edge  offline documentation software:
![Screenshot from 2019-11-12 14-20-25](https://user-images.githubusercontent.com/876076/68707833-21c45f80-0558-11ea-987b-02424e955b2c.png)

**Comment by trollixx** [comment]
Zeal does work offline, but only once you install the docsets. The easiest solution would be copying the whole docset storage directory (check the path in settings).

**Comment by trollixx** [comment]
I think addressing #138 and #1046 will make this situation easier to handle. For now please use the solution from my comment above.

**Comment by trollixx** [comment]
Actually #392 is what needs to be implemented.
