### ISSUE TITLE
Sluggy and slow window focus behaviour under Xmonad

### ISSUE THREAD

**Issue by lordi** [zealdocs/zeal#116]
First of all, great project, this is what I need!
I have the problem that when zeal is open (or hidden), the window focus management of xmonad becomes very sluggy. It feels like some event handling routine does more work than necessary :) I'm willing to test or create patches if you tell me what lines of code could be the trigger.

**Comment by wosc** [comment]
I'm seeing similar behaviour under the cinnamon window manager; while running Zeal, something triggers this that I can't pin down, and the Xorg process starts using close to 100% CPU and all keyboard/mouse input etc. becomes extremely sluggish.

**Comment by trollixx** [comment]
@wosc, what version or commit id are you using?

**Comment by wosc** [comment]
I'm runing Zeal `0.0+1snapshot201411212153-1~211~ubuntu14.10.1`, installed from `ppa:jerzy-kozera/zeal-ppa`

**Comment by trollixx** [comment]
It's quite old. I think, that slowness was caused by the old global shortcut logic. It's been completely redone recently. Could you test Zeal from master branch?

**Comment by wosc** [comment]
Thanks for the heads-up! Sure, I'll give the master version a whirl. Are there any special build instructions? Or simply run `qmake`?

**Comment by trollixx** [comment]
Nothing special, `qmake` and then `make` should do the thing.

**Comment by wosc** [comment]
Okay, I've just built revision 148ec840d28f050cb9e470958c620de3836d79dd, but the sluggishness behaviour still occurs, this time immediately from the time I start zeal.

**Comment by trollixx** [comment]
Is this issue still persist with more recent versions of Zeal and Qt?

**Comment by trollixx** [comment]
Closing this very old issue.
