### ISSUE TITLE
Request for logstash documentation

### ISSUE THREAD

**Issue by MaaniBeigy** [zealdocs/zeal#1166]
I was wondering if you could mind adding the documentation of [logstash](https://www.elastic.co/guide/en/logstash/current/index.html) (part of ELK stack, i.e., Elasticsearch, logstash, and kibana) to zeal. 

Thank you,
Best regards,
Maani

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.herokuapp.com/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).
