### ISSUE TITLE
HTML5, CSS, JavaScript  issue

### ISSUE THREAD

**Issue by Vlad1235** [zealdocs/zeal#1169]
Good day, when I downloaded both I try to open HTML5, CSS JavaScript alls  an error 

*Content rendering error. An unhandled error occurred in the application. We apologize for the inconvenience!*

So far did not meet same issue with other downloads.

**Comment by kikitte** [comment]
> Good day, when I downloaded both I try to open HTML5, CSS JavaScript alls an error
> 
> _Content rendering error. An unhandled error occurred in the application. We apologize for the inconvenience!_
> 
> So far did not meet same issue with other downloads.

me too, but there is not problem with the older version of html, css, js.

**Comment by jaller94** [comment]
Duplicate of #1155.

**Comment by Vlad1235** [comment]
Awaiting for the resolve.

**Comment by sandywu988** [comment]
same issue here, have it solved?

**Comment by drizzer** [comment]
Problem still until this date persistant with docsets(HTML, CSS, JS). **Zeal v0.6.1**

> "Content rendering error.
> An unhandled error occurred in the application. We apologize for the inconvenience!"

![Annotation 2020-05-11 235723](https://user-images.githubusercontent.com/46766033/81616119-35576280-93e3-11ea-8698-cb96dc17a326.png)
