### ISSUE TITLE
Search scope not working with C++

### ISSUE THREAD

**Issue by willkillson** [zealdocs/zeal#1170]
First time posting an issue. So, sorry if this is just user error.

It seems the "C++:" isn't limiting the search scope by C++, and instead limiting everything.
This works fine with Java, and C just fine. 

With C++
![image](https://user-images.githubusercontent.com/26101774/70683530-e654a800-1c5f-11ea-9999-ec6d4fe27ebd.png)

With C
![image](https://user-images.githubusercontent.com/26101774/70684353-2a957780-1c63-11ea-9c9b-355ac99a50f9.png)

With Java
![image](https://user-images.githubusercontent.com/26101774/70684375-3aad5700-1c63-11ea-9cbb-6f2a6aafa8c3.png)

Doc's installed
![image](https://user-images.githubusercontent.com/26101774/70684403-4f89ea80-1c63-11ea-9c8a-73124981b18e.png)

Here is the same issue on a virtual machine running xubuntu.
![image](https://user-images.githubusercontent.com/26101774/70685609-2703ef80-1c67-11ea-924e-880c72a7dbb4.png)

**Comment by ana-ka** [comment]
You can use "cpp" instead. :) Made this mistake myself.
