### ISSUE TITLE
Python modules from CG programs

### ISSUE THREAD

**Issue by Hippypotamus** [zealdocs/zeal#1173]
It would be useful if you add SideFX Houdini's HOM and vex documentation to Zeal. There are many CG programs which have python modules like Nuke, Maya, Houdini.

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.herokuapp.com/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).
