### ISSUE TITLE
javascript docset has error (Content rendering error)

### ISSUE THREAD

**Issue by james-muriithi** [zealdocs/zeal#1174]
![Screenshot (62)](https://user-images.githubusercontent.com/26818458/71169960-3be61180-226b-11ea-8351-9bc4607af157.png)

**Comment by wwwpalmercom** [comment]
have u resolved the problem?

**Comment by james-muriithi** [comment]
No

**Comment by metastork** [comment]
Have also had the same issue for a few weeks, only with the Javascript docset, others work fine. Have tried updating the docset, deleting it and re-downloading it, and same issue. There are around 1.4GB in the Javascript.docset folder in .local/share and the DB seems fine.

Using Ubuntu (Budgie) 19.10. Please let me know if I can provide any other information.

**Comment by intact** [comment]
you can use #1164 patch with some NodeList iterator polyfill

**Comment by AnonymousXuser264** [comment]
I wasted a lot of time figuring it out and also some money for the internet. But the end result as same as always. I just wasted my fucking time...
FUCK U All...

**Comment by m4rii0** [comment]
Duplicate of #1155
