### ISSUE TITLE
today after updating , then content of html,css and javascript   renders error.

### ISSUE THREAD

**Issue by wwwpalmercom** [zealdocs/zeal#1175]
Zeal version: **0.6.1**
Error info:  **Content rendering error.An unhandled error occurred in the application. We apologize for the inconvenience!**

after updating all docs , the content of html , css and js can't be render. However, others' docs show noramlly.

**Comment by DKroot** [comment]
Same here.

**Comment by kid1412621** [comment]
same here.
![image](https://user-images.githubusercontent.com/26278054/71396418-f94e7b80-2654-11ea-8368-5ba58f375565.png)

**Comment by gigi206** [comment]
Same issue

**Comment by m4rii0** [comment]
Duplicate of #1155

**Comment by mano9dev** [comment]
I have same issue after update javascript docset
