### ISSUE TITLE
 reading problem

### ISSUE THREAD

**Issue by Franklin-hyriol** [zealdocs/zeal#1180]
![Capture du 2020-01-22 14-27-36](https://user-images.githubusercontent.com/59871770/72890809-d2529a80-3d23-11ea-951f-6a42fd9e89bb.png)

same for HTML and CSS

**Comment by oussamaghrib** [comment]
all MDN documents have this problem, i don't why, it works in velocity though.

**Comment by trollixx** [comment]
Duplicate of #1155.

I think Velocity is using CEF, which is much newer than Qt WebKit.
