### ISSUE TITLE
Native GTK port of Zeal

### ISSUE THREAD

**Issue by n4n0GH** [zealdocs/zeal#1183]
I've been playing around with some UI concepts for a native GTK port of Zeal:

![zeal_mockup](https://user-images.githubusercontent.com/27410256/73589746-d5474b00-44da-11ea-92a8-844067f4c35e.png)

Now I haven't looked too much into the source of Zeal yet, but I'd love to shoot you questions if they arise. Would that be okay?

**Comment by trollixx** [comment]
@n4n0GH if you want to maintain a GTK version of Zeal, it is better to make it a separate application under a different name. You would need @Kapeli's permission to use the docsets though.

I have no interest in touching GTK, so it would be an independent effort. Majority of Zeal users are using Windows (at least that was the case a few years back when we had some rudimentary analytics), and GTK on Windows was still a disaster last I checked.

Also please do not rely on `api.zealdocs.org` or `go.zealdocs.org`, there's no SLA, or guarantee of no breaking API changes.

BTW, there used to be a now abandoned [fork of DevHelp](https://github.com/jkozera/zevdocs) with support for Zeal/Dash docsets.

And lastly, sure, feel free to reach out on IRC or Gitter, links are in the README.

**Comment by n4n0GH** [comment]
Got it, thanks!

2. Feb. 2020, 01:48 von notifications@github.com:
