### ISSUE TITLE
Adding New Type Icons

### ISSUE THREAD

**Issue by schmidh** [zealdocs/zeal#1185]
Hi,

I want to add new type icons for `Iterators`, `Templates`, `Lets`, `Converters` and `Documents` which are used in [Nim](https://nim-lang.org/). Are there any guides I should follow regarding the layout and design?

Best regards!

**Comment by trollixx** [comment]
There are no guidelines, and in fact all of the icons need to be replaced, as they are taken from Dash. 

I tried to find any existing icon sets for types, but nothing was at least nearly complete.

Perhaps, the way to go would be to generate all the icons automatically, not sure. I am open to suggestions.

**Comment by schmidh** [comment]
Hi Oleg,

do you think they have to replaced because of property rights? We could ask Bogdan from Dash whether we can use them.

How did you copy/download them?

**Comment by trollixx** [comment]
We have permission to use them, and they are available [here](https://github.com/Kapeli/Dash-X-Platform-Resources), but I do have some concerns about their continuous use.

I would much rather prefer to use some open source icon set, or have our own icons for most common types, and generate icons on the fly for custom types defined in docsets.

**Comment by schmidh** [comment]
I think we should use Dash's icon set. So users can e.g. use Dash on MacOS and Zeal on Linux and having pretty much the same user experience when searching for entries. I'm having no concerns here. Quite the contrary. We should copy those icons over to Zeal.

I'd even use a git subproject to refer to Dash's icon set so we are automatically up-to-date. Bogdan is always willing to create new icons when needed.

**Comment by trollixx** [comment]
Zeal already uses those Icons, they just haven't been synced in a while. The once we bundle have fixed metadata, and cleaned up from some random garbage.

I'll update the icons for the 0.7.0 release.

**Comment by schmidh** [comment]
Awesome. Thank you!

**Comment by trollixx** [comment]
I have added missing icons from Dash, but not all types you listed in the first post are present there.
