### ISSUE TITLE
Document fonts do not display properly

### ISSUE THREAD

**Issue by CyangYu** [zealdocs/zeal#1186]
Maybe I used MacType software, and then the fonts of some Zeal documents are not displayed properly.
![Snipaste_2020-02-09_12-06-03](https://user-images.githubusercontent.com/17793260/74096058-92b5ec00-4b34-11ea-8d33-8cab40536f64.png)

**Comment by trollixx** [comment]
Duplicate of #816.

It's a bug in MacType, see the linked ticket for more details.
