### ISSUE TITLE
docsets HTML & CCS not working

### ISSUE THREAD

**Issue by timokluser-dev** [zealdocs/zeal#1190]
The docsets HTML & CSS are not working..

It always shows:
_Content rendering error
An unhandled error occurred in the application. We apologize for the inconvenience!_

I experienced this issue only with the HTML and CSS docset.

**Comment by Bintux** [comment]
I have the same issues with the HTML, CSS and JavaScript docsets with the version 0.6.1 of Zeal in Ubuntu 18.04

**Comment by gcoelho** [comment]
@timokluser-dev , @Bintux This is a known issue and a workaround is described here https://github.com/zealdocs/zeal/issues/1155#issuecomment-574627330
