### ISSUE TITLE
Content rendering error

### ISSUE THREAD

**Issue by lordgodgiven** [zealdocs/zeal#1196]
Hello,

First of all congradulations for you application, offline documentation is very useful because sometimes i've internet connection problem. I've this message "Content rendering error
An unhandled error occurred in the application" when i try to read javascript documentation and same thing with HTML5 documentation. Hope that you going to solve it.

Thanks

![error](https://user-images.githubusercontent.com/1878076/75367777-1efc3900-58c1-11ea-99f9-86a4de21c216.jpg)

**Comment by AdriandeCita** [comment]
dup https://github.com/zealdocs/zeal/issues/1155
