### ISSUE TITLE
the javascript documentation doesn't good rendered

### ISSUE THREAD

**Issue by ariskusnulwiditama** [zealdocs/zeal#1198]
![Screenshot from 2020-03-05 02-55-38](https://user-images.githubusercontent.com/23493295/75917732-0970ab80-5e8d-11ea-8b4b-c7c9f3fdf218.png)

**Comment by ariancruz** [comment]
![error](https://user-images.githubusercontent.com/16599239/76164274-4f976a80-612c-11ea-9147-eea62c9c2a37.png)

**Comment by daymerfillad** [comment]
Same error

**Comment by trollixx** [comment]
Duplicate of #1155.
