### ISSUE TITLE
![error](https://user-images.githubusercontent.com/16599239/76164274-4f976a80-612c-11ea-9147-eea62c9c2a37.png)

### ISSUE THREAD

**Issue by ariancruz** [zealdocs/zeal#1199]
![error](https://user-images.githubusercontent.com/16599239/76164274-4f976a80-612c-11ea-9147-eea62c9c2a37.png)
Same error

_Originally posted by @ariancruz in https://github.com/zealdocs/zeal/issues/1198#issuecomment-596208997_

**Comment by trollixx** [comment]
Duplicate of #1155.
