### ISSUE TITLE
Is there supposed to be advertisements in zeal?

### ISSUE THREAD

**Issue by miss-looptux** [zealdocs/zeal#1201]
I want to know to make sure I'm not infected with an adware
thanks.

**Comment by trollixx** [comment]
The ad has been deleted in the master branch, will be part of the next release.

Duplicate of #779.

**Comment by trollixx** [comment]
I misread the question, if you are seeing ads from Carbon, those are not adware. You can also disable them in settings.

**Comment by miss-looptux** [comment]
i figured it out, this can be closed
