### ISSUE TITLE
Xojo docset - error in Directives

### ISSUE THREAD

**Issue by PsychoAndi** [zealdocs/zeal#1211]
Hi! I get this error in the Xojo docset:
`Failed to load URL file:///C:/Users/andi/AppData/Local/Zeal/Zeal/docsets/Xojo.docset/Contents/Resources/Documents/docs.xojo.com/%25EF%25BC%2583If...html.`  when clicking on "Directives -> # If ...".

Seems that the filname is wrong, should be: ï¼If..html

Same here:
`Failed to load URL file:///C:/Users/andi/AppData/Local/Zeal/Zeal/docsets/Xojo.docset/Contents/Resources/Documents/docs.xojo.com/%25EF%25BC%2583Pragma.html.` when clicking on "Directives -> Pragma...".

Filename should be: ï¼Pragma.html

**Comment by trollixx** [comment]
Basically this is the same problem as #1009. We need to stop extracting individual files from the archive.
