### ISSUE TITLE
zeal icon is not displayed in the task switcher

### ISSUE THREAD

**Issue by augustine98** [zealdocs/zeal#1220]

**Comment by trollixx** [comment]
Please provide more information, such as your OS, desktop environment, version of Zeal. A screenshot would also be helpful.

**Comment by augustine98** [comment]
The icon wasn't displaying on the gnome task switcher. I am on Fedora 32 and I installed it using the DNF repo. Later, I reinstalled it from the flatpack repo and it works fine now.
