### ISSUE TITLE
Zeal display abnormal

### ISSUE THREAD

**Issue by ExplodingFKL** [zealdocs/zeal#1222]
## Version

OS Version: Linux Mint 19.3 / 5.0.0-32-generic

![image](https://user-images.githubusercontent.com/33776693/80499793-003d2000-89a0-11ea-9ce0-07aa1d363431.png)

## Error screenshot: 
![image](https://user-images.githubusercontent.com/33776693/80499981-337faf00-89a0-11ea-90ee-5a74f2dafc54.png)

![image](https://user-images.githubusercontent.com/33776693/80501286-d84ebc00-89a1-11ea-8cad-d52b5d900ee3.png)

There is only "HTML" error, others are ok.

![image](https://user-images.githubusercontent.com/33776693/80500411-c4568a80-89a0-11ea-9b58-bcc89beb501b.png)

I downloaded it from "Tools-> Docsets" and tried to download it again, but I got the same result.

I only set up a network proxy.

![image](https://user-images.githubusercontent.com/33776693/80502085-cc172e80-89a2-11ea-9d1a-c660aa9c0335.png)

![image](https://user-images.githubusercontent.com/33776693/80502237-f23cce80-89a2-11ea-97a1-f6bd50315a22.png)

``` ini
[General]
check_for_update=false
hide_on_close=false
minimize_to_systray=false
show_systray_icon=true
start_minimized=false

[content]
custom_css_file=
dark_mode=false
default_fixed_font_size=13
default_font_family=serif
default_font_size=16
disable_ad=false
external_link_policy=@Variant(\0\0\0\x7f\0\0\0)Zeal::Core::Settings::ExternalLinkPolicy\0\0\0\0\x1)
fixed_font_family=Noto Sans Mono CJK SC
highlight_on_navigate=false
minimum_font_size=0
sans_serif_font_family=Noto Sans CJK SC
serif_font_family=AR PL UMing CN
smooth_scrolling=false

[docsets]
path=/home/dragon/.local/share/Zeal/Zeal/docsets

[global_shortcuts]
show=

[internal]
install_id=bf39ddaf-d0ca-46f1-a124-8d1e32ca7804
version=0.6.1

[proxy]
authenticate=false
host=127.0.0.1
password=
port=8888
type=2
username=

[search]
fuzzy_search_enabled=true

[state]
splitter_geometry=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x1\0\0\0\x4\xb0\0\xff\xff\xff\xff\x1\0\0\0\x1\0)
toc_splitter_state=@ByteArray()
window_geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x1\xf3\0\0\x1\xe\0\0\x5u\0\0\x3\x8d\0\0\x1\xf3\0\0\x1\x36\0\0\x5u\0\0\x3\x8d\0\0\0\0\0\0\0\0\a\x80)

```

**Comment by trollixx** [comment]
Duplicate of #1155.
