### ISSUE TITLE
Zeal isn't properly displaying ClojureScript docset

### ISSUE THREAD

**Issue by oconnor0** [zealdocs/zeal#1223]
I'm not sure if this is a Zeal issue or a ClojureScript docset issue.

1. I installed Zeal via scoop.
2. I installed [zeal-user-contrib](https://github.com/jmerle/zeal-user-contrib).
3. I installed the [ClojureScript docset](https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/ClojureScript): ` zeal-user-contrib --output-directory C:\Users\user\scoop\apps\zeal\current\docsets`, `ClojureScript`.
4. I opened Zeal. 
5. If I click on ClojureScript in the side bar, I see the documentation. The links all appear to work.
6. If I click on anything below ClojureScript, like `Builtins` > `. dot`, I get the following error:

> Error opening C:/api/syntax/syntax dot.html: The system cannot find the path specified

@shaunlebron, maybe this is a docset issue?

**Comment by shaunlebron** [comment]
thanks @oconnor0, lemme dig out my windows netbook to see whats going on

**Comment by shaunlebron** [comment]
Had to remove leading slash from path keys in the database index (e.g. `/foo/bar/` -> `foo/bar`).  Confirmed the fix on Windows.  It’ll be available after the above PR is merged.

Thanks for the report!

**Comment by oconnor0** [comment]
I deleted the ClojureScript docs from Zeal, reinstalled them, reopened Zeal, and browsed the docs from there. They look great now.
