### ISSUE TITLE
error on angularjs some directives

### ISSUE THREAD

**Issue by yanivz** [zealdocs/zeal#1225]
when clicking on angularjs directive number input show this, i have lates version all updated
Error opening C:/zeal-portable-0.6.1-windows-x64/docsets/AngularJS.docset/Contents/Resources/Documents/angularjs/code.angularjs.org/snapshot-stable/docs/api/ng/input/input%25255Bnumber%25255D.html: The system cannot find the file specified

**Comment by trollixx** [comment]
Please try the latest [CI build](https://ci.appveyor.com/project/zealdocs/zeal/build/job/p06l73yauxrsef4i/artifacts).

**Comment by trollixx** [comment]
This is working properly now.
