### ISSUE TITLE
Can't update documentation

### ISSUE THREAD

**Issue by wanggujin** [zealdocs/zeal#1228]
i can't update documentation, the progress is always 0% even if I've opened the internet proxy.
Does anyone else have this problem?

**Comment by wanggujin** [comment]
ubuntu 16.04 OS

**Comment by trollixx** [comment]
It's quite an old version of Ubuntu. Which version of Zeal do you have? Also check if there are any errors logged if you run Zeal from terminal.

**Comment by trollixx** [comment]
Closing due to lack of response.
