### ISSUE TITLE
Add MATLAB and assembly languages?

### ISSUE THREAD

**Issue by GrimPixel** [zealdocs/zeal#1229]
MATLAB
https://www.mathworks.com/help/matlab/index.html?s_tid=CRUX_lftnav

x86 assembly language
https://docs.oracle.com/cd/E26502_01/html/E28388/index.html

**Comment by GrimPixel** [comment]
I just saw that these two are protected by copyright. This may be the reason not to include them.

Octave is an open-source replacement for MATLAB. It has been included in DevDocs:
https://octave.sourceforge.io/docs.php
https://github.com/freeCodeCamp/devdocs/pull/982

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.herokuapp.com/) for Dash user contributed docsets. (Includes Octave!)
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).
