### ISSUE TITLE
Reload page error

### ISSUE THREAD

**Issue by Theocrate33** [zealdocs/zeal#1230]
content rendering error App Zeal. what is a solution provided?

Je rencontre de problème avec certaines documents que j'ai installé dans mon App Zeal mais qui ne s'ouvrent pas et qui nécessitent le rechargement.
Est-ce qu'une solution est prévu pour ça?

**Comment by trollixx** [comment]
My guess you are talking about MDN docsets, if so, this issue is a duplicate of #1155.
