### ISSUE TITLE
Add new Docset

### ISSUE THREAD

**Issue by adejonghm** [zealdocs/zeal#1233]
I would like you to add the Scikit-image docset in the future. It is an image processing library that is popular today. 

Thanks!!

**Comment by oconnor0** [comment]
The Scikit-image docset is available through [Zeal User Contributions](https://zealusercontributions.herokuapp.com/) and can be installed fairly easily via https://github.com/jmerle/zeal-user-contrib.

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.herokuapp.com/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).
