### ISSUE TITLE
No release file for Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by tokoiwesley** [zealdocs/zeal#1234]
```
E: The repository 'http://ppa.launchpad.net/zeal-developers/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

**Comment by trollixx** [comment]
You don't need PPA, Zeal is available from the system repositories.

**Comment by cweiske** [comment]
This also happened on Ubuntu 22.04 LTS.

zeal 0.6.1 (which is the latest tagged in git) is available in the standard ubuntu package repository: https://packages.ubuntu.com/jammy/zeal
