### ISSUE TITLE
External link behavior options are broken

### ISSUE THREAD

**Issue by chris-morgan** [zealdocs/zeal#1238]
I just downloaded the latest CI build for Windows (https://ci.appveyor.com/project/zealdocs/zeal/builds/33113960/job/53od703dr0ousu1q/artifacts, which is daecc956f54a60530a2ec5052dbf01f9a5a566f9, Windows x64, not portable) in order to try out Qt WebEngine.

When I have **External Link Behavior** set to:

- **Ask everytime** (there should be a space in “every time”, BTW):

  Clicking on external links produces the Open in Desktop Browser/Open in Zeal/Cancel message box, and every one of those options works correctly. ✔

- **Open in Zeal**:

  Clicking on external links does nothing. ❌

- **Open in Desktop Browser**:

  Clicking on external links tries and fails to open them within Zeal, producing the standard Chromium error page, for ERR_BLOCKED_BY_CLIENT. (“drafts.css-houdini.org is blocked / Requests to the server have been blocked by an extension. Try disabling your extensions.”) ❌

**Comment by trollixx** [comment]
@chris-morgan please test if 373606a1ede173a0e8037ab46af0acf68ab60594 resolves all problems you spotted.

I have changed how external links and resources are handled, and that hopefully fixes all regressions introduced from the Qt WebEngine migration.
