### ISSUE TITLE
There is no doc can be listed in my zeal... 

### ISSUE THREAD

**Issue by MrKZZ** [zealdocs/zeal#1241]
My OS is win 10 professional.
![image](https://user-images.githubusercontent.com/18312628/85215450-38168180-b3ab-11ea-99ea-90bacb74d070.png)
I wait for a long time several times but there is nothing changed. I click exit and it told me to wait. I can only kill it on win after a real long time.
There is no doc in my zeal can be listed and download. I wonder why and what should I do. Thanks. I really need a docsets software offline like dash.

**Comment by tacocats** [comment]
What version of zeal are you using? Did you download it from the releases tab? Not sure if is will solve it but you can try downloading a much more recent testing build from https://ci.appveyor.com/project/zealdocs/zeal

**Comment by MrKZZ** [comment]
> What version of zeal are you using? Did you download it from the releases tab? Not sure if is will solve it but you can try downloading a much more recent testing build from https://ci.appveyor.com/project/zealdocs/zeal

I download the lastest version on offical network.

**Comment by MrKZZ** [comment]
> > What version of zeal are you using? Did you download it from the releases tab? Not sure if is will solve it but you can try downloading a much more recent testing build from https://ci.appveyor.com/project/zealdocs/zeal
> 
> I download the lastest version on offical network.

![image](https://user-images.githubusercontent.com/18312628/85814466-9327ea00-b798-11ea-8671-4e0541184ac5.png)
Here is my detail information.

**Comment by MrKZZ** [comment]
Also, my computer set proxy connection.  And this website https://ci.appveyor.com/project/zealdocs/zeal is really slow. I can hardly open it. But i can connect googe, github and any other websites. Is there anything wrong with the zeal docsets websites?

**Comment by trollixx** [comment]
Something is wrong with the network connection. Have you set proxy in Zeal or are using system wide settings?

**Comment by MrKZZ** [comment]
> Something is wrong with the network connection. Have you set proxy in Zeal or are using system wide settings?

I set the network connection as follow:

![image](https://user-images.githubusercontent.com/18312628/85968677-4a6e6c00-b9f8-11ea-8327-e37e2fabf601.png)

There is anything wrong with my network setting? My system can connect most of the websites including google, github, ...

**Comment by trollixx** [comment]
It can't reach our API server, check if you can open https://api.zealdocs.org/v1/docsets

**Comment by MrKZZ** [comment]
> It can't reach our API server, check if you can open https://api.zealdocs.org/v1/docsets

I can't open this link https://api.zealdocs.org/v1/docsets. 
this page shows as follow:
![image](https://user-images.githubusercontent.com/18312628/85971966-3713ce80-ba01-11ea-8a19-918604c2c5d0.png)
but it is still loading, really slow.

**Comment by trollixx** [comment]
That's the right content. I'd try setting proxy directly in Zeal.

**Comment by MrKZZ** [comment]
> That's the right content. I'd try setting proxy directly in Zeal.

But what's the problem. Why I can't open this web? Does it need a special setting?

**Comment by tacocats** [comment]
That page is loading properly, from the looks of it. It's responding with a condensed JSON response which is why it might look weird. You're able to access it in your browser, so it's not a connection issue with your computer.

**Comment by trollixx** [comment]
@MrKZZ Were you able to make it work? If JSON loads in the browser, Zeal should also work. Just make sure that browser and Zeal have same proxy settings.

**Comment by MrKZZ** [comment]
> @MrKZZ Were you able to make it work? If JSON loads in the browser, Zeal should also work. Just make sure that browser and Zeal have same proxy settings.

Actually, Nope. I can't load it normally in browser. As you can see, it loads slowly and I don't know why. Zeal is set to have the same proxy setting with my browser and up to now, it doesn't work property.

**Comment by trollixx** [comment]
This is an old issue. Download workflow was updated a bit, and UI is now more indicative of what is going on. I believe this should work or fail with clear error in v0.7.0. Please report if you still encounter the problem
