### ISSUE TITLE
The javascript reference isn't rendering

### ISSUE THREAD

**Issue by eltondouglas** [zealdocs/zeal#1245]
When I open the documentation it gives an error and it does not render the content
![Captura de tela de 2020-06-27 17-21-40](https://user-images.githubusercontent.com/29680456/85931410-b470ff00-b89a-11ea-9505-e5e7cba09e64.png)

**Comment by arkhi** [comment]
You can see a solution in this Issue: https://github.com/zealdocs/zeal/issues/1155#issuecomment-642579981

There are also alternatives for different contexts in the thread.
