### ISSUE TITLE
I can't zoom in documentation browser

### ISSUE THREAD

**Issue by Oscars12** [zealdocs/zeal#1246]

**Comment by trollixx** [comment]
Which version of Zeal do you have? Also on what platform?

**Comment by Oscars12** [comment]
the version is the latest for windows 10
thanks for reply

**Comment by wnkw** [comment]
I experience the same issue. I'm on linux and the latest zeal version.
I can't zoom in or out using the keyboard but I can zoom with the mouse although in a very "undeterministic" way.

**Comment by trollixx** [comment]
Can you try the latest code from the `master` branch or a CI build?

**Comment by trollixx** [comment]
We have AppImage for Linux [here](https://github.com/zealdocs/zeal/actions/runs/192627868).

Windows CI builds are [here](https://ci.appveyor.com/project/zealdocs/zeal/builds/34441402). Pick build type and go to the Artifacts tab.

**Comment by wnkw** [comment]
Thanks for your reply. I've built the latest version from master (rev 994cc5f6b6bfffddd5faaaafdb4fed483c38188f) and the issue is gone!
