### ISSUE TITLE
Can't download docsets

### ISSUE THREAD

**Issue by Carsampa** [zealdocs/zeal#1247]
When trying to download any docset, I'm always getting the message "**SSL handshake failed**". Is there some problem with your site certificate?

**Comment by trollixx** [comment]
Are you using CI build by any chance?

**Comment by Carsampa** [comment]
First I have tried to use "zeal-portable-0.6.1-windows-x64.7z", then "zeal-portable-stable-0.6.1-windows-x64.zip" and last "zeal-0.6.1-windows-x64.msi". All those tests, whether portable or installed,  led to the same message "SSL handshake failed", independent of the specific docset to be downloaded. After that, I have tried to use Velocity and all the selected docsets were downloaded successfully. But I would like to use Zeal instead, which I prefer.

**Comment by Carsampa** [comment]
P.S.: I'm using Windows 10 Pro, version 1909, fully updated until 05-2020 (18363.836). I have all Microsoft Visual C++ Redistributables installed, from 2005 to 2019.

**Comment by dblandin** [comment]
Hey :wave: 

This "SSL handshake failed" error is also affecting the currently published Flatpak release:

```
devon-laptop% flatpak info org.zealdocs.Zeal

Zeal - Documentation browser

          ID: org.zealdocs.Zeal
         Ref: app/org.zealdocs.Zeal/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.6.1
     License: GPL-3.0-only
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 51.0 MB
     Runtime: org.kde.Platform/x86_64/5.12
         Sdk: org.kde.Sdk/x86_64/5.12

      Commit: 8aaaa499f0438d08c39868a9e4ca6d0031c6dda851a6a4d3c474a871dd12f6f3
      Parent: a9e44c7cfe630e5b3c2fa2af7137f1674fa84c07a0401d4e9b7ff4fb55df3bef
     Subject: Set publishing delay to one hour (63733271)
        Date: 2019-03-05 03:37:18 +0000
```

![Screenshot from 2020-07-07 13-40-55](https://user-images.githubusercontent.com/123595/86820863-a029c080-c057-11ea-80c6-99baca0c5590.png)

**Comment by Carsampa** [comment]
After some tests, I could bypass the problem just executing Zeal using a VPN, with a foreign country IP address. That's very strange, as I'm in Brazil, and I never (decades) had any problems like this.

**Comment by rad8329** [comment]
Hey folks,

I'm using Ubuntu 20.04 - Zeal 0.6.1, and I have the same error. I already tried to use some VPN, but no way

![screenshot-2020-07-07](https://user-images.githubusercontent.com/5356143/86870355-e0ac2d00-c09d-11ea-879f-9823ab8cbe7a.png)

**Comment by oblitum** [comment]
Same on ArchLinux.

**Comment by maheswaranm** [comment]
Is there a way to enable additional debug logging to see what exactly the failure is?
I get the same SSL handshake failure when trying to download docsets. 

I can refresh docset list, but not download them.

**Comment by AlexandreQuintela** [comment]
Same on Linux Mint 20.04

**Comment by trollixx** [comment]
Looks like `sydney.kapeli.com` mirror is no longer active. I removed it from the configuration.

@Kapeli was it an intended change?

**Comment by trollixx** [comment]
Just for the context, `sydney.kapeli.com` now resolves to `23.92.22.81`, which is located in Newark, NJ. As the result the GeoIP check in the redirect service started to pick it for a lot North American users.

**Comment by Carsampa** [comment]
Ok. Now working. Thank you.

**Comment by yue1071693411** [comment]
我也是这样的需要怎么解决

**Comment by dpsingh11** [comment]
getting the ssl handshake failed error while trying to download docset on ubuntu 20.04 machine

**Comment by Kapeli** [comment]
@trollixx I've removed the `singapore.kapeli.com` mirror and added `mumbai.kapeli.com` and `sydney.kapeli.com`.

**Comment by trollixx** [comment]
> @trollixx I've removed the `singapore.kapeli.com` mirror and added `mumbai.kapeli.com` and `sydney.kapeli.com`.

Updated, thanks!
