### ISSUE TITLE
Manjaro Linux zeal font too small

### ISSUE THREAD

**Issue by violetu** [zealdocs/zeal#1248]
## information
I get zeal package from aur（Arch user repository）
OS:Manjaro 20.0.3 Lysia
version: zeal-git-0.6.1.r181.g7fa29c9-1

```txt
$  qmake -v
QMake version 3.1
Using Qt version 5.15.0 in /usr/lib
```
## problem

I read about these two issues and tried those methods mentioned but still no effect.
[Unreadable fonts on 0.4 #786](https://github.com/zealdocs/zeal/issues/786#issue-262712378)
[Wrong UI scaling #869](https://github.com/zealdocs/zeal/issues/869#issue-288351043)

zeal screenshot
![image](https://user-images.githubusercontent.com/33022132/86914911-a9985300-c153-11ea-97eb-9c07f9756063.png)

```txt
$ xrandr
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
eDP-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1920x1080     60.02*+  40.03  
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
```

```txt
$ xdpyinfo | grep dots
  resolution:    142x141 dots per inch
```
Note that original the result is `resolution:    96x96 dots per inch`, but after I tried those method mentioned in the two issues and some others it's become `resolution:    142x141 dots per inch`, then I change it back to `resolution:    96x96 dots per inch`.
The commands history I tried:
```
 5092  xrandr --dpi dpi
 5093  xrandr --dpi eDPI
 5094  xrandr --dpi eDP1
 5095  xrandr --dpi
 5096  xdpyinfo | grep dots
 5097  QT_AUTO_SCREEN_SCALE_FACTOR=0 zeal
 5098  QT_AUTO_SCREEN_SCALE_FACTOR=1 zeal
 5099  QT_AUTO_SCREEN_SCALE_FACTOR=1.5 zeal
 5100  QT_AUTO_SCREEN_SCALE_FACTOR=2 zeal
 5101  QT_AUTO_SCREEN_SCALE_FACTOR=10 zeal
 5102  QT_AUTO_SCREEN_SCALE_FACTOR=1.2 zeal
 5103  qtconfig-qt4
 5104  qt5-styleplugins
 5105  qt5-stylepluginsxrandr --output eDP1^[[200~xrandr --output eDP1~
 5106  xrandr --output eDP1
 5107  clear
 5108  xrandr --output eDP1
 5109  xrandr --output eDP-1 -
 5110  xrandr --output eDP-1
 5111  xrandr --output eDP-1 -dpi
 5112  xrandr --output eDP-1 --dpi
 5113  xrandr --output -dpi
 5114  xrandr -dpi
 5115  clear
 5116  xrandr --output eDP1 --scale 1.25x1.25
 5117  xrandr --output eDP-1 --scale 1.25x1.25
 5118  xrandr --output eDP-1 --scale 96x96
 5119  xrandr --output eDP-1 --scale 1x1
 5120  xrandr --output eDP-1 --scale 0.8x0.8
 5121  xrandr --output eDP-1 --scale 0.9x0.9
 5122  xrandr --output eDP-1 --scale 0.95x0.95
 5123  xrandr --output eDP-1 --scale 1x1
 5124  xrandr --dpi eDP-1
 5125  QT_AUTO_SCREEN_SCALE_FACTOR=0 zeal
 5126  QT_AUTO_SCREEN_SCALE_FACTOR=1 zeal
 5127  echo $QT_AUTO_SCREEN_SCALE_FACTOR
 5128  QT_SCALE_FACTOR=0 zeal
 5129  QT_AUTO_SCREEN_SCALE_FACTOR=0 zeal
 5130  QT_AUTO_SCREEN_SCALE_FACTOR=2 zeal
 5131  QT_DEVICE_PIXEL_RATIO=auto
 5132  QT_DEVICE_PIXEL_RATIO=2
 5133  unset QT_QPA_PLATFORMTHEME
 5134  xdpyinfo | grep dots
 5135  xrandr --output eDP-1 --scale 1x1
 5136  xdpyinfo | grep dots
 5137  QT_AUTO_SCREEN_SCALE_FACTOR=0 zeal
 5138  xdpyinfo | grep dots
 5139  QT_DEVICE_PIXEL_RATIO=auto
 5140  xdpyinfo | grep dots
 5141  QT_DEVICE_PIXEL_RATIO=3
 5142  QT_DEVICE_PIXEL_RATIO=auto
 5143  xrandr -s 0
 5144  xdpyinfo | grep dots
 5145  info xrandr
 5146  xrandr -s 1920x1080
 5147  xdpyinfo | grep dots
 5148  xrandr
 5149  xdpyinfo | grep dots
```
somehow I don't have `qtconfig-qt4`, and `xrandr --dpi dpi`, `xrandr --dpi eDP1`  gave the results which are same as the comment below.

https://github.com/zealdocs/zeal/issues/786#issuecomment-334416069

besides, I changed the font about zeal, but it's seems have no effect at all.

![image](https://user-images.githubusercontent.com/33022132/86915467-99cd3e80-c154-11ea-8e66-34be40ecda1b.png)

**Comment by trollixx** [comment]
Aside form the minimum font size, other fonts options you set in settings are used as the default values if webpage doesn't set any.

From the screenshot I don't see what's wrong. Do you actually have a HDPI screen? It doesn't seem so.

Another thing to try is starting Zeal without the custom theme.

**Comment by violetu** [comment]
Thank you for your response!

Maybe, I don't actually konw what is HDPI screen. I just want C, C++ docset default font bigger than what it's now.

I restart Zeal without the custom theme. it didn't work.

> Aside form the minimum font size, other fonts options you set in settings are used as the default values if webpage doesn't set any.

It's seems like there is no change when I change whether the minimum font size or other fonts.

I notice the font of some docset is good, but some others' such as C, C++ is kind of smaller than others. 

Maybe the webpage set some options about the font?, So is there any options of Zeal to make the font of specific docset bigger?

![20200717_154712](https://user-images.githubusercontent.com/33022132/87761939-e1cf1e00-c844-11ea-8c42-e8417c99cae6.png)

**Comment by trollixx** [comment]
This is just how [cppreference.com](https://en.cppreference.com/w/) looks like. I don't think there's anything wrong with your setup.

**Comment by trollixx** [comment]
You can try playing with custom CSS file, that should allow you to override any styles set by the pages.

**Comment by violetu** [comment]
Got it. Thank you!
