### ISSUE TITLE
PDF Support

### ISSUE THREAD

**Issue by hanishkvc** [zealdocs/zeal#1261]
Some pages in the docset expects the c standard related pdfs in 

C.docset/Contents/Resources/Documents/www.open-std.org/jtc1/sc22/wg14/www/docs/[n1256.pdf/....]

But in the filesystem jtc1 is actually created as JTC1

C.docset/Contents/Resources/Documents/www.open-std.org/JTC1/sc22/wg14/www/docs/

So it gives error.

I assume the original source of this docset is using windows or other case insensitive filesystem, so even thou the directory structure is using uppercase dir name, the reference using lowercase dir name is not creating the problem. But in filesystems which are case sensitive like in linux, this creates the problem.

**Comment by trollixx** [comment]
Can you try building from `master` or one of the latest CI builds? For v0.7.0 we switched to serving pages over HTTP, so that may address this specific issue.

**Comment by trollixx** [comment]
After moving to Qt WebEngine this is becoming a lot more doable. I just tested enabling PDF viewer, and overall it works fine except for one strange issue with back/forward navigation when using mouse buttons. It needs some further debugging. I don't want to hold up v0.7.0 any longer, so I'll do this for the release after.
