### ISSUE TITLE
Is the project active?

### ISSUE THREAD

**Issue by purezen** [zealdocs/zeal#1262]
I downloaded Zeal few months back. I just opened it again to find documentation for react-native.

Was surprised to not find it using docsets browser since it is very popular.

Also when I checked for updates it said its on latest even when I updated it long back. Version says 0.6.1.

**Comment by trollixx** [comment]
All docsets are provided by Dash. You can find React Native in the [user contributed docsets](https://zealusercontributions.now.sh).

The project is alive, just slow moving. The next version is coming after major regressions from switching web view backend get addressed.
