### ISSUE TITLE
zeal can not download the javascript doc[has been solved]

### ISSUE THREAD

**Issue by angelpray** [zealdocs/zeal#1263]
system: win10
version:0.6.1
As the title said, I can't use zeal to download the JS doc, zeal is awesome and i need it very much.call for help.
the progress always 0%. 😪
![image](https://user-images.githubusercontent.com/17873970/88938816-5d56b380-d2b8-11ea-9c18-be18220ec8fe.png)

**Comment by trollixx** [comment]
Most likely a proxy issue.

**Comment by trollixx** [comment]
Can you download other docsets?

**Comment by angelpray** [comment]
Yes,I can download all the docsets except the javascript!😪So I think it is not a proxy issue? 
As shown in the following screenshot , I had installed some docsets correctly:
![image](https://user-images.githubusercontent.com/17873970/89044235-45486800-d37c-11ea-9a20-6e0138d1d561.png)
What is the problem?How to solve it?

**Comment by angelpray** [comment]
OK, I had solved it.I copy the `JavaScript.docset` to `C:\Users\AB113\AppData\Local\Zeal\Zeal\docsets`  and unzip it.Then restart the Zeal. Zeal will install JavaScript automatically.Btw,I download the `JavaScript.docset`  which shared on [Baidu yun](https://pan.baidu.com/s/1iwQHvuzWKA6SF9NuvCZ1nw )
code：z5ui
![image](https://user-images.githubusercontent.com/17873970/89114022-b8e89300-d4aa-11ea-862b-7ebd9dcd622b.png)

😂😁

**Comment by trollixx** [comment]
Glad it was solved, no idea what was causing the issue.
