### ISSUE TITLE
C++ docs don't display

### ISSUE THREAD

**Issue by patrikhuber** [zealdocs/zeal#1268]
Hi,

Thanks a lot for developing zeal and for putting it on GitHub! It looks awesome, but got some issue with C++ docs:

Just getting a white screen for all of the C++ docs:

![image](https://user-images.githubusercontent.com/4967343/90319639-c2a1da00-df31-11ea-8c3c-1b5479ed79c7.png)

CMake docs work fine, on the other hand.

Windows 10, used `zeal-0.6.1-windows-x64.msi` to install.

**Comment by trollixx** [comment]
I remember this was an issue with Zeal v0.5.0 (#871) but it was resolved in v0.6.0.

Can you try the latest CI build from [here](https://ci.appveyor.com/project/zealdocs/zeal/history)? Pick the latest non-PR commit, choose one of the four build and click on the Artifacts tab.

**Comment by patrikhuber** [comment]
Thanks for the quick reply!

I just tried this one, latest master: https://ci.appveyor.com/project/zealdocs/zeal/builds/34676546/job/aokog9mefjtjaapp/artifacts

And it does work!

**Comment by trollixx** [comment]
Great, then this is fixed.

**Comment by kswangxing** [comment]
i have got into the AppVeror, but there is no build packets existed. what's the problem?
