### ISSUE TITLE
Heroku server is down, cannot update docsets.

### ISSUE THREAD

**Issue by durhambell** [zealdocs/zeal#1275]
Can't update docsets. This is what I get in the app:
![image](https://user-images.githubusercontent.com/9648408/91663608-ea5b7b00-eab7-11ea-8f25-ae704643f086.png)

If I try to open the XML in my browser, I get this:
![image](https://user-images.githubusercontent.com/9648408/91663547-8f298880-eab7-11ea-8a6b-2cf0211e2f5b.png)

Is there a good reason to serve the docsets from Heroku? Seems like GitHub would be preferable since they are just flat XML files. Just my 2 cents.

**Comment by trollixx** [comment]
That service is a community effort which I have no control over. I believe @xantiagoma maintains it. There is also a mirror at https://zealusercontributions.now.sh/.
