### ISSUE TITLE
Android Docset Navigation not working

### ISSUE THREAD

**Issue by thebughunter1** [zealdocs/zeal#1280]
The Android docs have examples in Kotlin and Java which you can switch between by clicking a button. 

In Zeal it's showing the Kotlin examples by default and switching to the Java examples doesn't work unfortunately. When I opened the html downloaded by Zeal in a Browser it shows that some Javascript sources could not be loaded, I was thinking that might be the cause of the problem? But I'm not sure. 

You can see this in the MediaPlayer Overview document for example.

**Comment by trollixx** [comment]
Looks like a lot of JS files are missing from the docset:

![image](https://user-images.githubusercontent.com/714940/93687031-91647e80-fa88-11ea-8540-e61945f202f5.png)

@Kapeli is there an issue with docset generation?

**Comment by Kapeli** [comment]
Yes. This is an issue with the docset. Also happens in Dash. I'll try to fix it ASAP.

**Comment by Aster0** [comment]
Looks like this issue is still presented? @Kapeli
