### ISSUE TITLE
can't open zeal

### ISSUE THREAD

**Issue by JankingHuang** [zealdocs/zeal#1281]
Error message
```
incompatible Qt library error
Executable 'zeal' requires Qt 5.15.1, found Qt 5.15.0.
```
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.73.0
Qt Version: 5.15.0
Kernel Version: 5.7.19-2-MANJARO
OS Type: 64-bit
Processors: 8 × AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
Memory: 14.6 GiB of RAM
Graphics Processor: AMD RAVEN

**Comment by XEmpty** [comment]
Manjaro : https://forum.manjaro.org/t/testing-update-2020-09-15-kernels-pamac-gamemode-qt-5-15-1-systemd-amdvlk-wine/25346

qt-base 5.15.1 on testing branch. Soon in stable. If u don't wanna waiting install from arch repo.

**Comment by JankingHuang** [comment]
> Manjaro : https://forum.manjaro.org/t/testing-update-2020-09-15-kernels-pamac-gamemode-qt-5-15-1-systemd-amdvlk-wine/25346
> 
> qt-base 5.15.1 on testing branch. Soon in stable. If u don't wanna waiting install from arch repo.

thank you😝

**Comment by trollixx** [comment]
The check is there to make sure that Zeal doesn't run with a Qt version lower than it was built with. I don't know much about Manjaro, but somehow Zeal built against Qt 5.15.1 got into the repos before Qt itself.
