### ISSUE TITLE
JavaScript documentation is not rendered.

### ISSUE THREAD

**Issue by quasiblob** [zealdocs/zeal#1283]
**Only thing that gets rendered is:**
_"Content rendering error
An unhandled error occurred in the application. We apologize for the inconvenience!"_

And a "Reload Page" button below this error.

I think this has been broken for more than 6 months. 

Is there going to be a fix or should I start looking for another viewer?

**Comment by EdricChan03** [comment]
Duplicate of the pinned issue #1155

**Comment by jorgeTalancon** [comment]
I do have the same problem! :)

**Comment by lesar** [comment]
same problem on Ubuntu 20.04 desktop on rpi4

**Comment by iootaa** [comment]
There are some more info **and solutions** there https://github.com/zealdocs/zeal/issues/1155#issuecomment-642579981
