### ISSUE TITLE
What is the frequency of feed update?

### ISSUE THREAD

**Issue by devon-ge** [zealdocs/zeal#1288]
I'm new to Zeal. Maybe this issue is a duplicate.

I check the application and find nowhere to update the docset.  For example, the latest python doc is 3.8.6, postgresql release 13, etc. However, zeal offer python 3.8.5 and postgresql 12.4. 

I tried to add https://docs.python.org/3/ as a feed but failed. Is there a way to update the doc (manually is ok)?

**Comment by Kapeli** [comment]
Docsets are usually updated on a weekly basis, but might have delays sometimes. If you notice any docset that hasn't been updated to the latest version and it's been longer than ~3 weeks since that version was released, please report it at https://kapeli.com/contact.

**Comment by devon-ge** [comment]
@Kapeli Thanks.
