### ISSUE TITLE
Go docset: Zeal becomes unresponsive when trying to open any article

### ISSUE THREAD

**Issue by maxigaz** [zealdocs/zeal#1291]
Using Zeal 0.6.1 under Manjaro Linux, when I try to open any article from the Go docset (installed from Tools menu → Docsets… → Available tab), the UI becomes unresponsive and the application needs to be killed externally.

Other docsets like Python 3 work fine.

**Comment by trollixx** [comment]
Please try building Zeal from the `master` branch. I bet it's just another Qt WebKit bug.

**Comment by maxigaz** [comment]
You’re right. If I install the AUR package `zeal-git`, I no longer have the issue.
