### ISSUE TITLE
SSL Handshake Failed(v_0.6.1)

### ISSUE THREAD

**Issue by Jony378892** [zealdocs/zeal#1292]
I install the 0.6.1 version. When I try to download any Docs , it notify me with **SSL_Handshake_failed**.
![Annotation 2020-10-16 204131](https://user-images.githubusercontent.com/34894127/96272534-09728580-0ff0-11eb-9cd0-8106df2f2f9b.png)

**Comment by hieu10x** [comment]
The cause is possibly this.

![zealdocs_issue](https://user-images.githubusercontent.com/3314143/96347827-6fcdd580-10ce-11eb-9f49-32f968dee44d.png)

**Comment by qk98** [comment]
@hieu10x How to solve it?

**Comment by hieu10x** [comment]
For me, the problem was because zeal was redirected to "singapore.kapeli.com" which is not on the certificate's domain list. I replaced "singapore" with "newyork" and manually downloaded and extracted the docset archive.

**Comment by qk98** [comment]
@hieu10x Thank you very much. I solve this problem by setting a US proxy server with your useful information.

**Comment by trollixx** [comment]
Should be working now. #1247 has a bit more information.
