### ISSUE TITLE
Getting SSL handshake error while downloading a docset

### ISSUE THREAD

**Issue by Pratham82** [zealdocs/zeal#1294]
I've tried running from terminal as well as the GUI app. I also tried using VPN but still not solved.
![zeal error](https://user-images.githubusercontent.com/13178080/96711444-3097d100-13bb-11eb-9c4c-60e226f6025c.png)

System info:
![Screenshot from 2020-10-21 16-38-07](https://user-images.githubusercontent.com/13178080/96711856-dc412100-13bb-11eb-847f-bdf98614e6e8.png)

**Comment by MartyLake** [comment]
Same there for Windows. Works for private repositories though.

**Comment by trollixx** [comment]
Should be working now. #1247 has a bit more information.
