### ISSUE TITLE
[QT_QPA_PLATFORM_PLUGIN_PATH]: Error still persists

### ISSUE THREAD

**Issue by zayne15** [zealdocs/zeal#1295]
Please fix the error by resolving the paths through installation.
I had installed x64 version on Windows 10 1904 twice but the error had persisted and after creating the required path problem was resolved. 

Just found out that I have to set the environment variable `QT_QPA_PLATFORM_PLUGIN_PATH` to point to `c:\Program Files (x86)\Zeal\platforms` to get it working with the link. But actually this should not be necessary.

_Originally posted by @stlehmann in https://github.com/zealdocs/zeal/issues/477#issuecomment-172757038_

**Comment by trollixx** [comment]
What version of Zeal did you install? This should not happen with v0.6.1.

**Comment by sponsfreixes** [comment]
This happens to me with Version 0.6.1 (I downloaded and installed it today, using the binaries on https://zealdocs.org/). I'm on Windows 10 20H2.
