### ISSUE TITLE
HTML pages rendering error

### ISSUE THREAD

**Issue by tup-olev** [zealdocs/zeal#1297]
I get the following display after downloading HTML and CSS docsets:

### Content rendering error
An unhandled error occurred in the application. We apologize for the inconvenience

**Comment by a22a-dev** [comment]
Same error for other docs too.

**Comment by misaka00251** [comment]
#1155

**Comment by chrisfxwolf** [comment]
## Please, correct links.
* [Attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/), for example attribute  _**abbr**_
```
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr
```
* [Guides](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/), for example **_input type="button"_**
```
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
```
* [Tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/), for example **_a_** tag
```
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
```
