### ISSUE TITLE
plugin system for editors

### ISSUE THREAD

**Issue by yourilima** [zealdocs/zeal#13]
Are there bindings that could be used to develop plugins for editors? just like dash has quite a few? most interresting for me would be for sublime text

**Comment by joaomsa** [comment]
@christoffer as far as I know `xdg-open` works perfectly, you just have to register the mime type with `xdg-mime`. For dash:// it would be `xdg-mime default zeal.desktop x-scheme-handler/dash`

**Comment by trollixx** [comment]
Support for `dash://` and `dash-plugin://` on Freedesktop platforms has landed in the master branch.

**Comment by trollixx** [comment]
Windows support has been added as well.

Now all Dash plugins should work with Zeal as well.
