### ISSUE TITLE
Zeal cannot display math formulas in PyTorch docsets

### ISSUE THREAD

**Issue by perok8** [zealdocs/zeal#1302]
The PyTorch docsets I use is from https://zealusercontributions.now.sh. I also tried generating PyTorch docsets myself from https://github.com/pytorch/pytorch/tree/master/docs. Zeral cannot display math formulas in both cases. 

Following is an example: torch.ceil
![Screenshot_20201215_140703](https://user-images.githubusercontent.com/19903807/102177620-e45e9e00-3ede-11eb-8c7c-2cf547a8f904.png)
The line under "Returns a new tensor with the ..." should be a math formula:
![Screenshot_20201215_141101](https://user-images.githubusercontent.com/19903807/102177946-7f577800-3edf-11eb-9e74-9b35e9760c91.png)

archlinux kde plasma desktop 5.20.4

**Comment by trollixx** [comment]
This is happening because the docset doesn't bundle katex library:

<details>
<summary>Details</summary>

```
zeal.browser.urlrequestinterceptor: Blocked request: GET 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/fonts/KaTeX_Math-Italic.woff2' (resource_type=5, navigation_type=0).
zeal.browser.urlrequestinterceptor: Blocked request: GET 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/fonts/KaTeX_Main-Regular.woff2' (resource_type=5, navigation_type=0).
zeal.browser.urlrequestinterceptor: Blocked request: GET 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/fonts/KaTeX_Main-Bold.woff2' (resource_type=5, navigation_type=0).
zeal.browser.urlrequestinterceptor: Blocked request: GET 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/fonts/KaTeX_Size1-Regular.woff2' (resource_type=5, navigation_type=0).
zeal.browser.urlrequestinterceptor: Blocked request: GET 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/fonts/KaTeX_Size4-Regular.woff2' (resource_type=5, navigation_type=0).
zeal.browser.urlrequestinterceptor: Blocked request: GET 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/fonts/KaTeX_Size2-Regular.woff2' (resource_type=5, navigation_type=0).
zeal.browser.urlrequestinterceptor: Blocked request: GET 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/fonts/KaTeX_Size3-Regular.woff2' (resource_type=5, navigation_type=0).
zeal.browser.urlrequestinterceptor: Blocked request: GET 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/fonts/KaTeX_Caligraphic-Regular.woff2' (resource_type=5, navigation_type=0).
zeal.browser.urlrequestinterceptor: Blocked request: GET 'https://cdn.jsdelivr.net/npm/katex@0.10.0-beta/dist/katex.min.css' (resource_type=2, navigation_type=0).
zeal.browser.urlrequestinterceptor: Blocked request: GET 'https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css' (resource_type=2, navigation_type=0).
zeal.browser.urlrequestinterceptor: Blocked request: GET 'https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js' (resource_type=3, navigation_type=0).
zeal.browser.urlrequestinterceptor: Blocked request: GET 'https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js' (resource_type=3, navigation_type=0).
```

</details>

Docset generation needs to be fixed to include files fetched from `cdn.jsdelivr.net`.

**Comment by lf-** [comment]
@trollixx I believe nobody is shipping this docset, so it would have to have been generated manually. How do I include such files with `doc2dash`? I've added `-j` which seems to add a javascript enable setting in the manifest of the docset, but it does not seem to resolve this problem.

**Comment by trollixx** [comment]
[PyTorch docset](https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/PyTorch) is generated from the [official repository](https://github.com/pytorch/pytorch/blob/main/docs/Makefile). It needs a fix to bundle katex library with the docset. Or maybe it's an issue with `doc2dash`, I am not sure. I would suggest reporting this issue to the PyTorch docset maintainers.

The current logic in Zeal prevents local pages from loading resources from the Internet. I'd argue referring to online resources defies the purpose of having offline documentation, and I don't want to change the default.

I believe Dash does allow online resources by default, and then offers [`DashDocSetBlocksOnlineResources`](https://github.com/zealdocs/zeal/issues/955#issuecomment-425327306) property to explicitly block online access. Zeal does not support this property, but I think adding reverse logic would make more sense. If implemented, it would allow docset maintainers to override default blocking logic regardless of what I think is the right way of doing things. I created #1538 to track further work on this.
