### ISSUE TITLE
Zeal cannot show vim documentation in exactly size

### ISSUE THREAD

**Issue by chrisfxwolf** [zealdocs/zeal#1303]
Docset of vim is showing as miniatures of all pages.

![Image](https://i.ibb.co/5F3DYLQ/Screenshot-20201220-180322.png)

- Zeal version:0.6.0
- Operating System: openSUSE Leap 15.2
- KDE Plasma Version: 5.18.6
- KDE Frameworks Version: 5.71.0
- Qt Version: 5.12.7
- Kernel Version: 5.3.18-lp152.57-default
- OS Type: 64-bit
- Processors: 8 × Intel® Xeon® CPU W3530 @ 2.80GHz
- Memory: 31.3 GiB of RAM

**Comment by trollixx** [comment]
You are using a very old version of Zeal, this issue was fixed in v0.6.1. See #903 for more details.
