### ISSUE TITLE
Wordpress Error: No such file or directory

### ISSUE THREAD

**Issue by ahangarha** [zealdocs/zeal#1316]
I just installed Zeal on my Ubuntu and got some of docsets including Wordpress. But if I click on Wordpress I get this error:

![image](https://user-images.githubusercontent.com/11241315/105990950-72ba6800-60b8-11eb-94f1-b299175d0f53.png)

I have checked the file system and there is no `Zeal/Zeal/docsets/WordPress.docset/Contents/Resources/Documents/no_index_test` directory existing there.

**Comment by trollixx** [comment]
This is strange, I have just downloaded the WordPress docset, and it has the index file. Can you try reinstalling the docset?

**Comment by ahangarha** [comment]
I deleted and redownload WordPress but the issue remained the same.

**Comment by trollixx** [comment]
It is indeed a bug in v0.6.1. It is fixed by https://github.com/zealdocs/zeal/commit/c16945bc21ee94e5db55d5e77b94360770102437. Please try a CI build or build Zeal yourself to get the fix prior to the release.

**Comment by ahangarha** [comment]
Tnx
