### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by frenzymadness** [zealdocs/zeal#1317]
Hello.

I'm a maintainer of Zeal RPM package in Fedora and I'd like to kindly ask you whether it'd be possible to release a new version. The last stable release is from 2018-09-28 and the master branch contains more than 200 commits since then.

I've realized that because we have a new version of QT5 in Fedora and the build of the RPM package stopped working because the latest stable release is not compatible. Or better say it is compatible but with some deprecation warning which break the build.

I'd rather package a new version than fix already fixed issues in the old one.

What do you think about it?

**Comment by ruffson** [comment]
I would very much like this. Some languages like Rust are straight up [not supported](https://github.com/zealdocs/zeal/issues/1195) on the current release. I was hoping for at least a minor bugfix release so I can start using Zeal again.

**Comment by David-Else** [comment]
https://github.com/zealdocs/zeal/discussions/1308

**Comment by frenzymadness** [comment]
FTR: the only fix I needed to fix the build in Fedora with QT 5.15.2 is this simple patch: https://src.fedoraproject.org/rpms/zeal/blob/master/f/0001-Fix-QPainterPath.patch

But still, I'd like to update the package.

**Comment by David-Else** [comment]
@frenzymadness Would be great to see an EPEL8 release of the new version too :)

**Comment by Thulium-Drake** [comment]
Any update on this? :-)

I think almost noone is seeing all the work that has been performed since 2018...

**Comment by frenzymadness** [comment]
In Fedora, I'm now using commits instead of tags so Fedora users are only 15 commits behind the master branch. This is only a workaround. A new release would still be great.

> @frenzymadness Would be great to see an EPEL8 release of the new version too :)

I don't see it built for EPEL. If you are a packager, we can build it there together.

**Comment by David-Else** [comment]
@frenzymadness I am afraid I am not a packager, but if you were to build it for EPEL 9 it would be great :)

**Comment by trollixx** [comment]
https://github.com/zealdocs/zeal/releases/tag/v0.7.0 :)
