### ISSUE TITLE
Document view fails to initialize with qt5-webengine 5.15.3

### ISSUE THREAD

**Issue by XeCycle** [zealdocs/zeal#1329]
Using zeal code at d3c5521, qt5-webengine as packaged by Arch Linux at version 5.15.3-2, zeal is able to show main window + search box + sidebar, but document view cannot load successfully, with stderr flooding this same line:

```
[136576:136576:0310/094707.997375:ERROR:network_service_instance_impl.cc(286)] Network service crashed, restarting service.
```

I can confirm zeal is built with headers from qt5-webengine 5.15.3; if I downgrade qt5-webengine to 5.15.2-5 (Arch Linux package), the same zeal (using 5.15.3 headers) runs fine.

**Comment by djmattyg007** [comment]
See #1317

**Comment by wcasanova** [comment]
https://bugs.archlinux.org/task/69902
https://github.com/archlinux/svntogit-packages/commit/fc44efe60954468959c962aec1aee1d888038738#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a

**Comment by XeCycle** [comment]
Thanks, it works with Arch package 5.15.3-3.
