### ISSUE TITLE
Docsets any Download failed

### ISSUE THREAD

**Issue by wcasanova** [zealdocs/zeal#1330]
Download failed!
example Ansible
Error: Socket operation expired 
URL: https://go.zealdocs.org/d/com.kapeli/Ansible/latest
Zeal v0.6.2-dev.217+d3c5521

**Comment by dblando** [comment]
I can reproduce the defect in Zeal v0.6.1 for Windows with any docset that I try to add.

Steps to reproduce: 1) Add one or more docsets to Zeal.
Actual results:

1. Attempt takes 45 seconds before timing out;
2. Download bar never goes beyond zero percent (see '01_arduino_docset_0pct.png');

![01_arduino_docset_0pct](https://user-images.githubusercontent.com/7364306/111084505-b0484880-84e0-11eb-8079-c51f8dfc2a03.png)

3. Popup window: "Connection timed out" (see '02_connection_timed_out.png');

![02_connection_timed_out](https://user-images.githubusercontent.com/7364306/111084506-b0484880-84e0-11eb-90fa-20de4a4220b0.png)

4. Clicking on retry only repeats the time and failure.

Examples:
- Arduino
- C
- Ninja

**Comment by bmarcio20** [comment]
I'm getting the same behaviour on linux (20.04.2 LTS (Focal Fossa)) with zeal V0.6.1

**Comment by FRostri** [comment]
in archlinux the error also appears. I downloaded it from the AUR

**Comment by P-N-L** [comment]
I am having this issue too.

![image](https://user-images.githubusercontent.com/30122827/111489200-4f9f5280-8710-11eb-872f-ea6f9425fde0.png)

**Comment by nathanmcunha** [comment]
Same issue here on win10

**Comment by matheusmartinsx** [comment]
I am having this issue here, on windows 10 too, with  a 'time out' message for every download that I try.

**Comment by mwgamble** [comment]
I'm getting the same issue too.

**Comment by csetera** [comment]
I'm seeing the same thing with a local build from recent sources.

![Screenshot from 2021-03-21 15-18-39](https://user-images.githubusercontent.com/270739/111919691-4b00d400-8a59-11eb-8f35-47843e8fa384.png)

Looking at the network calls, it appears to be a redirect to https://mumbai.kapeli.com:

![Screenshot from 2021-03-21 15-28-08](https://user-images.githubusercontent.com/270739/111919935-4852ae80-8a5a-11eb-9e88-f8b219325136.png)

In https://github.com/zealdocs/zeal/issues/1247, I see @Kapeli added this server in October 2020, but not sure if it still exists?

**Comment by Kapeli** [comment]
`mumbai.kapeli.com` and `sydney.kapeli.com` were removed.

Please consider having Zeal load `<mirror>.kapeli.com/feeds/latencyTest.txt` before trying to use a mirror so you can skip mirrors that were removed or are just down. 

The current active mirrors can be seen in the XML feeds (e.g. at https://kapeli.com/feeds/Ansible.xml - mumbai and sydney are missing).

Alternatively, it might be better to use only `kapeli.com` for all downloads.

**Comment by troycurtisjr** [comment]
Looks like now mumbai.kapeli.com points to the same IP as newyork.kapeli.com. However, the SSL Cert doesn't include that subdomain so all we get is an SSL handshake error. I assume that was @Kapeli trying to help us Zeal users out? Thanks! It does sound like the Zeal redirect needs to be updated to account for disappearing mirrors. I've hacked in to use kapeli.com directly and things are working ok locally.

**Comment by trollixx** [comment]
Mirror list has been updated, downloads should be working for everyone now.

**Comment by llIlI** [comment]
I still have this problem，SSL handshake failed

**Comment by mimr9** [comment]
> I still have this error，SSL handshake failed

I have it, too.

**Comment by mimr9** [comment]
The problem has been solved by installing openssl package:
`sudo apt install openssl`

#1290 
#1088

**Comment by ayang** [comment]
https://tokyo.kapeli.com seems down too.
