### ISSUE TITLE
Custom Stylesheet is not fully applying to UI

### ISSUE THREAD

**Issue by jonstump** [zealdocs/zeal#1331]
I'm fairly certain it's likely that I'm doing something wrong, but zeal doesn't appear to be picking up any of my linux UI settings (I've tried both the .deb and flatpak on Pop_OS!) and when I attempt to use [this custom css](https://raw.githubusercontent.com/ColinDuquesnoy/QDarkStyleSheet/master/qdarkstyle/style.qss) it only applies to the reader area (when it works, when I first clicked apply nothing happened and it doesn't always seem to work).

When I click on darkmode that will only apply to the documentation pane as well, which I assume is the case after reading [this open ticket](https://github.com/zealdocs/zeal/issues/811) for a darkmode for the UI. However from seeing screenshots on that, and [this ticket](https://github.com/zealdocs/zeal/pull/1124) as well, I was under the assumption that the UI would also take on the elements from the css file. Am I incorrect in my understanding?

Any help is appreciated if this isn't a bug. It's kind of difficult staring into what feels like a blazing sun compared to the rest of my desktop 😅

**Comment by AlbertoGP** [comment]
I have the same problem, and it seems that we would have to configure a dark QT5 theme.

In that ticket you mention, [someone else indicated](https://github.com/zealdocs/zeal/pull/1124#issuecomment-631645703) that you can do that by installing the package called `qt5-style-plugins` (was `qt5-styleplugins` in my distribution) and then starting Zeal after the variable `QT_QPA_PLATFORMTHEME` has been set to the value `gtk2`.

You can quickly test Zeal with an environment variable like this:
`QT_QPA_PLATFORMTHEME=gtk2 zeal`
This worked for me: it picked up the gtk dark style same as Firefox etc.

**Comment by jonstump** [comment]
Thanks for this @AlbertoGP! I guess I didn't fully understand this solution the first couple times I've read it. Running apps with variables like this is a little new to me, do you have any good docs or suggestions as to how I can make zeal launch with this every time?

**Comment by jonstump** [comment]
Nevermind I figured it out going over the prior link. Going to close this.
