### ISSUE TITLE
Feature request: Add NestJS doc

### ISSUE THREAD

**Issue by rodlemus30** [zealdocs/zeal#1337]

**Comment by richarson** [comment]
Zeal doesn't provide docsets, it uses Dash's

See https://github.com/zealdocs/zeal/issues/1312#issuecomment-766183527 for more information.

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.herokuapp.com/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).
