### ISSUE TITLE
Zeal crash opening some docsets

### ISSUE THREAD

**Issue by Dominiquini** [zealdocs/zeal#1339]
I recently successfully downloaded the "Java SE16" docstet, but when I try to view it, the application overlaps. The same problem happens with "Java SE15"!
The "Java SE14" docset and any others I tested seem to work well!

This is the only log that I was able to find: [Report.wer.log](https://github.com/zealdocs/zeal/files/6564083/Report.wer.log)

Thanks.

**Comment by nikitabobko** [comment]
Also reproduciable on `Android` docset

**Comment by Dominiquini** [comment]
The Android docset is working for me!

**Comment by Dominiquini** [comment]
> 
> 
> Also reproduciable on `Android` docset

The `Android` docset is working for me!

**Comment by bmix** [comment]
It crashes me, whenever I open the Java 9SE docset, but Java 8SE is fine. I am on Windows 10.

**Comment by alenwesker** [comment]
Me too, java ee15/16 docset crashes when open any page of the conent.

**Comment by VinKang** [comment]
Me too.

**Comment by Dominiquini** [comment]
Java SE 17 docset is also crashing!

**Comment by XaverB** [comment]
Java SE 18 docset is also crashing!

**Comment by nomadbard916** [comment]
for me the latest applicable version is Java SE 14

**Comment by trollixx** [comment]
Duplicate of #868.
