### ISSUE TITLE
14.04 - main menu not displayed

### ISSUE THREAD

**Issue by sheershoff** [zealdocs/zeal#134]
Seems like after some updates, probably because of dropbox update, the main menu stopped displaying it's entries, so I can't get to the docsets downloads now. May be there's some keyboard shortcut for the config menu entry?

Ubuntu 14.04 x64

**Comment by trollixx** [comment]
There's nothing we can do about the problem. We do not force `nativeMenuBar` option anymore. The platform plugin should determine the correct behaviour.

**Comment by ashwin** [comment]
Removing `appmenu-qt5` fixed the problem on XFCE (XUbuntu) too! :+1:

**Comment by ktkization** [comment]
when I try to remove `appmenu-qt5` I'm getting this response
`Package 'appmenu-qt5' is not installed, so not removed`
what should I do because it's still not showing the menu or anything
