### ISSUE TITLE
Error in Docsets Browser (Windows)

### ISSUE THREAD

**Issue by bmix** [zealdocs/zeal#1340]
Using Zeal 0.6.1 on Windows 10, with the `C:\Users\bmix\AppData\Local\Zeal` folder symlinked to a folder on another (local) volume, after opening the *Tools -> Docsets...* menu, I get the following two errors:.

![image](https://user-images.githubusercontent.com/310157/120723976-1b4b5f00-c4d3-11eb-9bdf-03bb5b65c602.png)

This happens each time. It happens while there is some progress bar on the bottom of the dialog, but it's too quick to see, what it is doing. I also don't understand, why it would want to remove them. I checked the folder's permissions, I checked the JSON configs and tried to find any differences to the other, working docsets, but did not find anything. This also happens after reboot.
Thank you.

**Comment by trollixx** [comment]
This is an old report, but I just test the described scenario with symlinks, and everything appears to work as expected. Either the issue was in old Qt, or there were incorrect permission settings at play. Please report if the problem still persists in the newer releases.
