### ISSUE TITLE
Zeal 0.6.1 crashes with  Java SE (9 to 16)

### ISSUE THREAD

**Issue by apietroluongo** [zealdocs/zeal#1341]
#### Describe the bug

Zeal crashes with Java SE docsets. (9 to 16).

on  Windows 10 (Installer and Portable).

**Comment by Dominiquini** [comment]
I'm having problems with Java SE15 and Java SE16! Java SE14 works fine for me!

Duplicate: https://github.com/zealdocs/zeal/issues/1339

**Comment by king0billy** [comment]
ooh  I'm having exactly the same problem as yours, lol

**Comment by trollixx** [comment]
Duplicate of #868.
