### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by hellolukeding** [zealdocs/zeal#1346]
zeal always crashs when i type words after i update to windows 11

**Comment by trollixx** [comment]
Can you obtain a stack trace?

**Comment by hellolukeding** [comment]
I have solved this problem,i remove the docset of javaee,i think that the coexistence of the docset of  javaee and c++ makes the search system crash.

**Comment by trollixx** [comment]
Oh, that's an old Qt WebKit bug. The current code doesn't have that issue. Need to make the CI produce archives for Windows...

**Comment by hellolukeding** [comment]
ok ,thanks a lot
