### ISSUE TITLE
I cannot open Zeal App on Win10

### ISSUE THREAD

**Issue by zihluwang** [zealdocs/zeal#1348]
Zeal App will hold for 2-3 seconds on startup, then crashed. I've already installed the **latest** version of Visual C++ support which  build number of 14.29.30133. I also installed the specified version (build 14.0.24123) on your download page which failed.

**Comment by Lancer907** [comment]
Igot the same problem

**Comment by Lancer907** [comment]
I got the same problem

**Comment by vorbote** [comment]
@Lancer907 Did you opened VPN while you open zealdocs? I found that if I turn off my VPN connection before start using zeal will not cause to this problem.

**Comment by DumbZarro** [comment]
> @Lancer907 Did you opened VPN while you open zealdocs? I found that if I turn off my VPN connection before start using zeal will not cause to this problem.

I got the same problem, and I solve this problem by turn off my VPN connection before start using zeal.Thanks!

**Comment by DumbZarro** [comment]
I found that if I set my HTTP Proxy to no proxy, I can connect VPN  and use zeal at the same time without crash.

**Comment by vorbote** [comment]
@DumbZarro Yes, you can only use zeal or vpn in the same time for now.
