### ISSUE TITLE
Question about CLI

### ISSUE THREAD

**Issue by mrjones2014** [zealdocs/zeal#1360]
I'm the author of a Neovim plugin for Dash.app called [Dash.nvim](https://github.com/mrjones2014/dash.nvim), and I'm looking to add Linux support via Zeal.

The way my plugin currently works relies on Dash's Alfred integration workflow, so that I can send it a query and get back results on the command line (Dash formats them as XML, but JSON would be fine too, I'm using JSON internally).

Is there documentation somewhere on the CLI? And does it offer the ability to run queries and return a result list on the command line? Once an item is selected from within Neovim, it would open that item in Zeal's GUI.

**Comment by mohkale** [comment]
I second this. I'm looking to implement something like a frontend for emacs where I get a fzf like popup and can narrow down to an item in the docset to actually view. Downside is there doesn't seem to be any way to do this with zeal.

**Comment by mrjones2014** [comment]
Seems the project is unmaintained :/

**Comment by mohkale** [comment]
Damn. That sucks. Guess I'll have to find a way to make devdocs interface with dash docsets.

**Comment by mosaleh52** [comment]
https://gitlab.com/ivan-cukic/nvim-telescope-zeal-cli
this could be helpful i was searching for solution and i found none 
@mrjones2014 btw i wish dash was for lunix because of your plugin

**Comment by mrjones2014** [comment]
@mosaleh52 there's a way to get the plugin to work on linux by searching the sqlite docsets directly (the docsets are just sqlite databases). However, it requires adding quite a bit of complexity, and I just haven't had the chance to investigate it further. Some discussion here: https://github.com/mrjones2014/dash.nvim/issues/24

I also don't have a Linux machine (I use macOS). I'd love a well written PR implementing Linux support 😉

**Comment by mosaleh52** [comment]
@mrjones2014 I have not seen the discussion in your repo I will replay there to know how can I help

**Comment by trollixx** [comment]
This is an old issue from, but I added a [new page](https://github.com/zealdocs/zeal/wiki/Plugin-API) in the wiki which explains how plugins can interact with Zeal. It's pretty much a brief summary of the Dash documentation (also linked). Generally, all Dash IDE plugins should work with Zeal. If something doesn't, it's a bug.

**Comment by trollixx** [comment]
Actually, I misread the original question. This is a duplicate of #400. Zeal doesn't support Alfred Workflow API or any other variation of returning search results to outside applications.
