### ISSUE TITLE
how to use  docset for gem — a Bash script to generate docsets from Ruby gems

### ISSUE THREAD

**Issue by OuttaSpaceTime** [zealdocs/zeal#1366]
Hey

I found the script within the wiki https://github.com/zealdocs/zeal/wiki/Third-Party-Resources
I tried to download and run the script, it ran through successfully. Afterwards I was not able to find any generated docsets on my machine.
Can someone guide me on how to use it to download add ruby gem docs to zeal?

Best wishes

**Comment by trollixx** [comment]
Please reach out to the script author.
