### ISSUE TITLE
Font size is too small

### ISSUE THREAD

**Issue by wuliwan** [zealdocs/zeal#1369]
Font size is too small, how can I increase it?

**Comment by undead-carbon** [comment]
This worked for me:
Go to Edit > Preferences > Content 
Change "Minimum font size"

**Comment by ShiinaKaze** [comment]
Vuejs document can not display correctly in Zeal, but it does in browser.

**Comment by trollixx** [comment]
This is fixed in the `main` branch. Please try the latest [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml). Binary artifacts are attached to each build.
