### ISSUE TITLE
when opening doc of  javase15 or 16 ,zeal0.6.1 crashes and exits 

### ISSUE THREAD

**Issue by king0billy** [zealdocs/zeal#1370]
last version of win11：when opening doc of javase15 or 16 , zeal0.6.1  crashes and exits.  I use javase14 instead now. docs' last updated time 2021/12/16.
Duplicate: [#1339](https://github.com/zealdocs/zeal/issues/1339) ，[#1341](https://github.com/zealdocs/zeal/issues/1341)

**Comment by trollixx** [comment]
Duplicate of #868.
