### ISSUE TITLE
Zeal 0.6.1 crashes on start on Windows 11 because of Qt5Network.dll

### ISSUE THREAD

**Issue by MoMeAk-Qin** [zealdocs/zeal#1371]
I use the Zeal 0.6.1, but it crashes on start. I have installed vs 2019 and my computer has vcruntime140.dll. When I use the proxy application -- Clash for Windows, the Zeal will crash. After I checked the Windows logs, it was an error in the Qt5Network.dll module that caused

**Comment by Yancey597** [comment]
I also use the Zeal 0.6.1 and Clash for Windows,.zeal crashes when using search , I try to close the zeal's proxy, but it doesn't work....

**Comment by MoMeAk-Qin** [comment]
> I also use the Zeal 0.6.1 and Clash for Windows,.zeal crashes when using search , I try to close the zeal's proxy, but it doesn't work....

you need to close the clash application

**Comment by Yancey597** [comment]
ok, I can use the Zeal  normally after closing Clash now, thanks

**Comment by Yancey597** [comment]
> > I also use the Zeal 0.6.1 and Clash for Windows,.zeal crashes when using search , I try to close the zeal's proxy, but it doesn't work....
> 
> you need to close the clash application



> > I also use the Zeal 0.6.1 and Clash for Windows,.zeal crashes when using search , I try to close the zeal's proxy, but it doesn't work....
> 
> you need to close the clash application


ok, I can use the Zeal normally after closing Clash now, thanks

**Comment by Yancey597** [comment]
> > I also use the Zeal 0.6.1 and Clash for Windows,.zeal crashes when using search , I try to close the zeal's proxy, but it doesn't work....
> 
> you need to close the clash application

ok, I can use the Zeal normally after closing Clash now, thanks

**Comment by JustusPan** [comment]
how could we solve this problem if we want to use Zeal and Clash at same time?

**Comment by trollixx** [comment]
Please check if v0.7.0 has the same issue.

**Comment by trollixx** [comment]
I believe this is fixed in Qt 6 based builds.
