### ISSUE TITLE
Build fails on Apple Silicon M1 pro

### ISSUE THREAD

**Issue by anmolarora** [zealdocs/zeal#1372]
I followed the [following instructions](https://github.com/zealdocs/zeal/wiki/Build-Instructions-for-macOS) for building zeal on macos, but it fails with the following error-

<img width="1114" alt="Screenshot 2022-02-24 at 20 58 39" src="https://user-images.githubusercontent.com/5461473/155554730-41f8f032-aa3a-426a-a78a-0742952b7e21.png">

Looked into it and found out that `qt@5` in `brew` doesn't ship with `QtWebEngine` for Apple Silicon

<img width="995" alt="Screenshot 2022-02-24 at 21 01 08" src="https://user-images.githubusercontent.com/5461473/155555291-8a5efcf4-b4af-4b59-a54d-d5776df2daee.png">

Has anybody had luck building zeal on Apple Silicon?

**Comment by shabbyrobe** [comment]
I have a fork I'm working on at the moment that migrates to Qt6: https://github.com/shabbyrobe/zeal

I'd be very happy to turn it into a PR at some point if it would be accepted but I'm quite sure there's more work to do. I will test on Linux at some point but can't help much with Windows. There are still a few issues but it works for my needs on M1.

Install instructions change to this:

```
brew install qt@6
brew install libarchive
export CMAKE_PREFIX_PATH="$(brew --prefix qt@6):$(brew --prefix libarchive)"
git clone https://github.com/zealdocs/zeal.git
cd zeal
mkdir build
cd build
cmake ..
make -j 8
```

**Comment by vmtest888** [comment]
> 
Hello, can you provide a compiled windows binary?

**Comment by shabbyrobe** [comment]
Unfortunately not, I don't have the required setup to do so. If you do find a way to build my fork on Windows, please let me know how you did!

**Comment by trollixx** [comment]
I don't have M1 hardware to test on, and MacOS is not officially supported. Qt6 support is already in the `main` branch, so in theory it should build just fine.

**Comment by trollixx** [comment]
@enviousjag you can comment out that line in `main.cpp`. It's an issue in Qt.
