### ISSUE TITLE
[0.6.1/master] Gradle DSL content is rendering incorrectly

### ISSUE THREAD

**Issue by NeveHanter** [zealdocs/zeal#1375]
The content is "cut" and the table of contents is broken in the attached screenshot:
![image](https://user-images.githubusercontent.com/3267401/157032731-d536e6bf-3ee2-49aa-96cc-537256b3e3b3.png)

Installed from the ArchLinux AUR package zeal, the same is reproductible with zeal-git which builds the version from the repo's master branch.

System: ArchLinux
Version: 0.6.1 (and version from the master branch)

**Comment by trollixx** [comment]
Looks like a problem with the docset. It renders fine in narrow window but then turns into this after a certain width is reached. I can reproduce the same problem in desktop browsers. @Kapeli can you please take a look?

**Comment by Kapeli** [comment]
I've fixed it. Thanks for letting me know!
