### ISSUE TITLE
The interface displays abnormally

### ISSUE THREAD

**Issue by 958117216** [zealdocs/zeal#1381]
When I open zeal in Ubuntu18.04, its interface is like this
![2022-03-29 11-40-25 的屏幕截图](https://user-images.githubusercontent.com/46185326/160528797-56603369-9d5e-40e2-bb54-a66673cedc42.png)

My computer screen resolution is 2560x1600, how should I solve this problem？

Thank you！

**Comment by trollixx** [comment]
Doesn't look like something Zeal itself could cause. Have you tried any other Qt apps? Maybe try a different theme.

**Comment by trollixx** [comment]
I could never reproduce this. A number of fixes for HiDPI screens went into both Zeal and Qt. It should display normally now. If not, please report.
