### ISSUE TITLE
some doc can't display, like bootstrap5 lots of examples display none

### ISSUE THREAD

**Issue by thefatwhale** [zealdocs/zeal#1382]
# I don't know about this project, I guess it used IE core? can't display some html5 or js features?
![image](https://user-images.githubusercontent.com/50515732/163706066-c9500f43-d9c2-47d6-9d1c-cdd956dba7a5.png)

**Comment by trollixx** [comment]
Fixed by migration to Qt WebEngine. Duplicate of #1468.
