### ISSUE TITLE
C# documentation?

### ISSUE THREAD

**Issue by PakoSparrer** [zealdocs/zeal#1383]
Hello everyone. Are you going to upload the c# documentation? It would be a very interesting contribution. Thank you very much

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.now.sh/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).
