### ISSUE TITLE
Scrapy

### ISSUE THREAD

**Issue by cristianjcdigital** [zealdocs/zeal#1384]
Hello,
Please attach the documentation for "Scrapy" & "Beautifulsoup4".

Greetings,
Thank you.

**Comment by lifeisfoo** [comment]
See https://github.com/zealdocs/zeal/issues/1312#issuecomment-766183527

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.now.sh/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).
