### ISSUE TITLE
Java SE17 doc, make close the app.

### ISSUE THREAD

**Issue by Nekko-Code** [zealdocs/zeal#1391]
when i enter in eny doc (classes, constants, ...) the app crash.

**Comment by Dominiquini** [comment]
Happens to me too!

**Comment by AlbaxBM** [comment]
I have the same problem!

**Comment by OrtizUriel112** [comment]
Me three :(

**Comment by SEEKnight** [comment]
me too

**Comment by Binjuan23** [comment]
I have the same problem.

**Comment by MarneusAugustusCalgar** [comment]
The bug is still unsolved :(

**Comment by Frandella** [comment]
It happens with Java SE15 too, i put "ja" in the search bar and it closed
![bug](https://user-images.githubusercontent.com/95258225/175797380-2ae542c9-4b21-4108-bbaf-292f34ad9e3d.png)

**Comment by trollixx** [comment]
Duplicate of #868.
