### ISSUE TITLE
Zeal cannot load offline docs when having a poor Internet connection

### ISSUE THREAD

**Issue by Hyffer** [zealdocs/zeal#1394]
Sometimes I have a poor Internet connection. And if I open up Zeal, it cannot load my offline docs, but showing pure white page.

I have tested some cases (both on Windows and Linux):

- If I just turn off my Internet connection, it works fine.
- If my network connection gets better, it also works fine.

So I assume that Zeal will detect Internet connection when launched. If connection is available, it will wait for the website's response first, rather than retrieving from local files.

Often no big deal, but it is quite annoying in my specific situation. Can it be an option to user whether using offline files first?

Anyway, thanks for this useful project!

**Comment by mquinson** [comment]
Do you still have the same issue when you uncheck the box "Check for updates" in the preferences?

**Comment by Hyffer** [comment]
Yes, still the same. Thanks for your help. And I suppose "Check for updates" means checking update for the application, not documents.
(as below, shows blank page with network connected)
![image](https://user-images.githubusercontent.com/58105986/179144324-237c5103-4ec2-4639-827b-7f7f658a26f3.png)

Also, I notice that it only happens with c and c++ docs, while my go and js doc downloaded works fine. It is definitely due to my network connection.

**Comment by mquinson** [comment]
Hello @trollixx,

it seems to me that this another case where the docset tries to download some resource online. You stated in #955 that no change was needed in Zeal as this was soon to be fixed in the docset themselves. Could you please tell us the current status?

**Comment by Hyffer** [comment]
I have went through #955, but it seems to be different. Some issues described in #955 no longer reappear on my laptop. I can use offline docset when disconnect from internet, zeal definitely load files locally.

What has being bothering me is having a poor network connection. To be fare, some websites and cdn services are blocked or have a very slow speed depends on network provider.

I am not good at network analysis. I tried to use wireshark but unable to grasp anything helpful. XD
(Ubuntu 22.04, Zeal 0.6.1, if it matters)

**Comment by w-ymir** [comment]
> Hello, if it's only some of the docsets, I think that this is because of #955. The docset references online scripts (eg `en.cppreference.com/w`) that are loaded if available, I guess. The best would be to close the current bug (#1394) and discuss further in the original one #955.
> 
> My guess is that the best solution would be to fix the docset to remove those scripts, but Zeal could be made more robust to this issue in the docsets, either by post-processing the docset on installation, or with a proxy or other network intercepter to discard these requests when displaying the resource.

Second this. Viewing a blank page and searching for this issue and locating external resources in the docset and waiting for the change -- this is quite a long run.
