### ISSUE TITLE
Can't tab complete PostgreSQL:

### ISSUE THREAD

**Issue by qgates** [zealdocs/zeal#1395]
When searching, if I type 'post' I expect the docset name to appear greyed for tab completion, ie. `PostgreSQL:`, but it doesn't.

Works with all other docsets but not with Postgres for some reason.

🙂

**Comment by laurentS** [comment]
I don't know why it is so, but try `psql:` instead of `postgresql:`.

**Comment by laurentS** [comment]
I don't know why it is so, but try `psql:` instead of `postgresql:`.

**Comment by qgates** [comment]
Thanks, didn't think to try that. Perhaps `postgresql:` should be added for consistency. I'm left wondering whether the issue is with the docset or zeal itself?

**Comment by omad** [comment]
This has been bugging me lately too!

The docset alias is defined in the dataset, although it appears the value can come from one of several places.

Information about a Docset is taken from `meta.json` and `Contents/Info.plist`.
<details>
<summary>In the PostgreSQL docset, it is from the `CFBundleIdentifier` tag in  `PostgreSQL.docset/Contents/Info.plist`
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
<key>CFBundleIdentifier</key>
<string>psql</string>
<key>CFBundleName</key>
<string>PostgreSQL</string>
<key>DocSetPlatformFamily</key>
<string>psql</string><key>DashDocSetFamily</key><string>unsorteddashtoc</string>
<key>isDashDocset</key><true/></dict>
</plist>
```
</details>

<details>
<summary>However, for Python3 it comes from meta.json. I can only use "python3" as an alias, not "python".</summary>

```json
{
    "extra": {
        "keywords": [
            "python3",
            "python"
        ]
    },
    "name": "Python_3",
    "revision": "0",
    "title": "Python 3",
    "version": "3.10.7"
}
```

</details>

I think it should be made clear somewhere in the UI what the alias is, to cover cases like this.

**Comment by trollixx** [comment]
In the next release search keywords will be visible in the docset manager. See #1617 for more details. Although this is an older issue, I'll mark it as a duplicate.
