### ISSUE TITLE
make add react native, unreal engine 5, resub, redux, material ui, moralis web3, supabase, websocket.io

### ISSUE THREAD

**Issue by testermumatstudio** [zealdocs/zeal#1398]
could you add these libraries I love this program react native, unreal engine 5, microsoft resub , redux, material ui, moralis web3, supabase and websocket.io please

**Comment by mquinson** [comment]
Do you know where the corresponding docset can be downloaded from?

**Comment by testermumatstudio** [comment]
> ¿Sabes de dónde se puede descargar el docset correspondiente?

Hello, do you mean the documentation of each one?

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.now.sh/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).
