### ISSUE TITLE
Where can I download the compiled, new beta version?

### ISSUE THREAD

**Issue by vmtest888** [zealdocs/zeal#1399]
Where can I download the compiled, new beta version?

**Comment by mquinson** [comment]
Are you looking for the windows version or the linux one? The recent builds seem to fail for windows: https://github.com/zealdocs/zeal/runs/7245563066?check_suite_focus=true

**Comment by trollixx** [comment]
Since migration to GitHub Actions, binary artifacts are attached to each [build check](https://github.com/zealdocs/zeal/actions/workflows/build-check.yaml) run.

**Comment by mquinson** [comment]
Thank @trollixx for all what you are currently doing!
