### ISSUE TITLE
Add more docsets in zeal

### ISSUE THREAD

**Issue by ghost** [zealdocs/zeal#1403]
Hi all!

#### 1. feature-name
Add more docsets in zeal.

#### 2. feature-description
It would be really cool if I could add more docsets in zeal, example:
- [rebol-lang](https://github.com/rebol)
- [red-lang](https://github.com/red)
- [melrose](https://ernestmicklei.com/melrose/introduction_melrose/)
- [swi.prolog-lang](https://www.swi-prolog.org/)
- [purescript-lang](https://www.purescript.org/)
- [WebAssembly-lang](https://webassembly.org/)
- [Elm-lang](https://elm-lang.org/)
- [factor-lang](https://github.com/factor/factor)
- [Frink-lang](https://frinklang.org/)
- [glicol-lang](https://github.com/chaosprint/glicol)
- [faust-lang](https://faust.grame.fr/)
- [nickel-lang](https://nickel-lang.org/)
- [wren-lang](https://github.com/wren-lang/wren)
- [Cello](https://github.com/orangeduck/Cello)
- [Neko](https://nekovm.org/)
- [Scheme](https://github.com/schemedoc)
- [Dao](https://github.com/daokoder/dao)
- [Pawn](https://github.com/pawn-lang)
- [Angelscript](http://www.angelcode.com/angelscript/)
- [nim-lang](https://github.com/nim-lang/Nim)
- [odin-lang](https://github.com/odin-lang)
- [ziglang-lang](https://github.com/ziglang)
- [Ri-lang](https://github.com/martincohen/Ri)

#### 3. Why?
- More contact with different programmers who use lesser known programming languages in zeal 

#### 4. References
- https://github.com/r-lyeh-archived/scriptorium
- https://www.simplilearn.com/best-programming-languages-start-learning-today-article

**Comment by zxeoc** [comment]
I think zeal has swift docset for now.

**Comment by zxeoc** [comment]
Hi raphael, I also think it's good to have more docsets. But I'm not the maintainer of the project. As I know, the docsets are kindly supplied by @Kapeli .
And you can add your own feed URL in the menu "Tool->Docsets->Add feed".
