### ISSUE TITLE
Expired certificate at api.zealdocs.org

### ISSUE THREAD

**Issue by ilpianista** [zealdocs/zeal#1404]
![Screenshot_20220622_120134](https://user-images.githubusercontent.com/529436/175002340-ea65424c-3b52-4288-8364-5f96e589507a.png)

**Comment by gzqx** [comment]
Getting same problem.

**Comment by redblade7** [comment]
Same problem here

**Comment by trollixx** [comment]
Automatic renewal didn't happen for some reason. This is fixed now.
