### ISSUE TITLE
<details> html is expanded when cursor hovers it

### ISSUE THREAD

**Issue by hydrargyrum** [zealdocs/zeal#1405]
I'm using zeal with Go docs, which contains a lot of `<summary>` and `<details>` tags. For example, on [some page](https://pkg.go.dev/unicode/utf8@go1.18.3) see the examples, which are expandable by clicking on them, then collapsible by clicking again.

When viewing the same page in zeal, `<details>` are collapsed. However, when hovering the cursor on any `<summary>` text, the corresponding `<details>` expands. I have to close them by clicking on them. Once they're closed manually, they don't open when hovering. Unless I refresh the page or visit another one. This behaviour is a bit irritating.

**Comment by omad** [comment]
I get the same behaviour on Linux in Zeal 0.6.1.

It's cleaned up in `master`, you have to click each time to open and close the `<details>` section, and the arrow stays in sync.

**Comment by hydrargyrum** [comment]
[0.6.1](https://github.com/zealdocs/zeal/releases/tag/v0.6.1) dates back from 2018! Maybe a new release for 4 years-worth fixes would be useful?

**Comment by hydrargyrum** [comment]
@trollixx is there any reason we might miss not to make releases from time to time?

**Comment by trollixx** [comment]
Fixed by migration to Qt WebEngine.
