### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by LuisAlberto22** [zealdocs/zeal#1408]
Hi, I Was downliading my docs then pressed the refresh button and my download get bugged and I had to restart my download again

**Comment by LuisAlberto22** [comment]
ohh and C++ docs is toooooo slow

**Comment by trollixx** [comment]
This is an old issue, but it is a known issue that if download is too slow and is interrupted, it has to be restarted. Please follow #430 for a updates on a possible solution.
