### ISSUE TITLE
Blurry text in dark mode

### ISSUE THREAD

**Issue by rotu** [zealdocs/zeal#1409]
In dark mode, light text on dark appears blurry in all docsets. This is especially evident on thin vertical lines, and I suspect it's an issue with antialiasing.

![image](https://user-images.githubusercontent.com/119948/177823209-d7ca289a-b70f-4169-9655-ea355cdabad1.png)

![image](https://user-images.githubusercontent.com/119948/177823298-81444421-18e8-43af-b51d-427359b62fdb.png)

**Comment by faktorsedam** [comment]
+1

**Comment by trollixx** [comment]
This looks like a problem with Qt WebKit rendering. After the switch to Qt WebEngine this should not happen anymore.

Please try the latest [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml). Binary artifacts are attached to each build.

**Comment by rotu** [comment]
thank you! I can confirm this is fixed on Windows. Also, loving the new dark sidebar and other GUI tweaks!
