### ISSUE TITLE
Any documentation about Python for datascience...

### ISSUE THREAD

**Issue by avinajera2011** [zealdocs/zeal#1412]
I need to know if there is any chance to get any documentation about Python data science.  Thanks a lot for the app.

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.now.sh/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).
