### ISSUE TITLE
Cannot play video

### ISSUE THREAD

**Issue by wangdemon** [zealdocs/zeal#1413]
I can play videos by opening HTML files directly with edge browser, but I can't open videos with zea

https://user-images.githubusercontent.com/20681339/178309772-d1de5456-03f6-43e1-a2b1-bd0be083743f.mp4

l

**Comment by trollixx** [comment]
The old webview didn't support any video payback. I think Qt WebEngine can play video but I have no docsets handy to test. You can try the latest code by downloading [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml).

**Comment by wangdemon** [comment]
I don't know why. The Qt environment on my two computers is the same, one can play videos, and the other cannot play videos
