### ISSUE TITLE
Where is the source code behind https://api.zealdocs.org/v1/docsets ?

### ISSUE THREAD

**Issue by mquinson** [zealdocs/zeal#1414]
Hello,

it seems to me that Zeal is downloading the list of all docsets from `https://api.zealdocs.org/v1/docsets`, but I fail to see how this data is generated. Could please someone point me to the right github project or something?

Thanks in advance,
Mt

**Comment by trollixx** [comment]
The server code is not public. It's something I really need to rewrite and wouldn't want to share it in its current form. The CI job that updates docsets can be found [here](https://github.com/trollixx/sync-job-com.kapeli.dash).

**Comment by mquinson** [comment]
Is there a way to feed Zeal with docsets that are manually downloaded or something? The problem is that if there is no such way, then Zeal is not a free software in the Debian acceptance...

**Comment by D-side** [comment]
@mquinson sure is, check out #161

**Comment by mquinson** [comment]
I fail to understand how this feature can be used. 

I was prospecting a little patch to propose a combo-box of existing URLs (as in eclipse marketspace), mainly to get a better grasp at the source code, and that's while I was following the execution flow of the docset's download that I had the doubt which led me to the current issue.

I fail to understand the expected format for a docset feed, how it's organized, how I could propose a new one, how I could divert it to a directory on disk instead of an URL to allow a really offline documentation system.

If anyone could enlight me, that'd be really appreciated. Thanks,

**Comment by trollixx** [comment]
@mquinson Docsets can be added using Dash XML feeds. You can find a lot of them [here](https://zealusercontributions.vercel.app/). Of course, it's also possible to simply unpack docset into the storage directory.

**Comment by adam-devel** [comment]
looking for this? https://github.com/Kapeli/feeds
