### ISSUE TITLE
Image & Javascript path

### ISSUE THREAD

**Issue by pzheng64** [zealdocs/zeal#142]
Hi Jerzy,

I'm Paul, a Web developer who loves your Windows software Zeal  very much.  It's quite useful in my everyday work.
One issue I have is that when I browse jQuery documentation, the script demo is not loaidng.  Also, some images are not loading.  Maybe this is due to some relative path problem.

Could you give me a hint?

My email is pzheng64@gmail.com
Skype: pzheng64

![20140510-002](https://cloud.githubusercontent.com/assets/1234847/2930722/2080586e-d79a-11e3-8123-b06a8f9e0cbb.jpg)
![20140510-003](https://cloud.githubusercontent.com/assets/1234847/2930723/208059cc-d79a-11e3-90db-d7bfdde41036.jpg)

Thanks,
Paul.

**Comment by trollixx** [comment]
JPEG support was a packaging issue and has been fixed in 4f363afa9dc98b049152cc3523e5690bce6bb883.

**Comment by trollixx** [comment]
Looks like now JavaScript examples work for the jQuey docset.
