### ISSUE TITLE
Instructions to build on Windows

### ISSUE THREAD

**Issue by ezxpro** [zealdocs/zeal#1425]
It would help if there were at least some basic instructions on how to compile zeal on Windows.
I got VS Community 2022, the MSVC toolchain, Qt, CMake and the appropriate vs extensions, have configured them, but still there's just so much going on that I can't solve on my own...

**Comment by trollixx** [comment]
Build instructions can be found in the [wiki](https://github.com/zealdocs/zeal/wiki/Build-Instructions-for-Windows) but they are somewhat out of date. Building on Windows is pretty straightforward these days thanks to `vcpkg`. I'll try to update the docs as well.

**Comment by wngtk** [comment]
I am trying to build zeal on Windows. But I do not know how to package it to msi file. `cmake --build .\build\ --target package --config Release -j8` generated installer is empty.

```powershell
git clone https://github.com/microsoft/vcpkg.git --depth=1
.\vcpkg\bootstrap-vcpkg.bat
.\vcpkg\vcpkg install --triplet=x64-windows
cmake -B .\build\ -S . "-DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake"
cmake --build .\build\ --config Release -j8
```

**Comment by trollixx** [comment]
Please see the updated [wiki page](https://github.com/zealdocs/zeal/wiki/Build-Instructions-for-Windows). Now featuring step by step instructions for building on Windows based on my own environment.
