### ISSUE TITLE
Does CI currently produce usable artifacts?

### ISSUE THREAD

**Issue by Adnn** [zealdocs/zeal#1428]
I recently discovered zeal via https://hynek.me/articles/productive-fruit-fly-programmer/.

I wanted to give it a try, but a 4 years old release feels a bit risky. 
I followed #1336, but it seems not release candidate are available at the moment. (Is that correct?)
The [download page](https://zealdocs.org/download.html) mentions CI builds, and redirects to appveyor. Yet as far as I can tell, the CI moved to github actions, with very recent builds successfully happening there.

Is there a way to consume the output from the CI build directly?
(I am not looking forward to installing Qt to run a local build ; )

Thank you for the project!

**Comment by trollixx** [comment]
Right now CI only produces AppImage artifacts. I'd like to add archives for Windows as well once I fix Qt 6 builds.

**Comment by trollixx** [comment]
This is finally done. Artifacts for Windows and Linux can be found attached to each build [here](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml).
