### ISSUE TITLE
meta.json is incorrect when loading from a feed

### ISSUE THREAD

**Issue by ppwwyyxx** [zealdocs/zeal#1436]
I have a feed URL `https://raw.githubusercontent.com/ppwwyyxx/dash-docset-tensorflow/master/TensorFlow2.xml` that currently points to this archive: `https://github.com/ppwwyyxx/dash-docset-tensorflow/releases/download/v2.10/TensorFlow-2.10.tgz`. The archive's meta.json has the following content:
```
{
    "extra": {
        "keywords": [
            "tf2",
            "tf"
        ]
    },
    "name": "TensorFlow 2",
    "revision": "0",
    "title": "TensorFlow 2",
    "version": "2.10"
}
```

However, if I load this feed to zeal, the downloaded docset has the following meta.json:
```
{
    "feed_url": "https://raw.githubusercontent.com/ppwwyyxx/dash-docset-tensorflow/master/TensorFlow2.xml",
    "name": "TensorFlow2",
    "title": "TensorFlow2",
    "urls": [
        "https://github.com/ppwwyyxx/dash-docset-tensorflow/releases/download/v2.10/TensorFlow-2.10.tgz"
    ],
    "version": "2.10"
}
```

The useful "keywords" information are not included. I expect the keywords to be present in the downloaded docset.

**Comment by trollixx** [comment]
In the this scenario Zeal has nowhere to know keywords from. User-generated docsets should specify `DashDocSetKeyword` in their `Info.plist`, which Zeal will respect.

**Comment by ppwwyyxx** [comment]
Why does "Zeal has nowhere to know keywords from"?

Currently, zeal can recognize 
```
  "extra": {
        "keywords": [
            "tf2",
            "tf"
        ]
    },
```
without problems. If I have a docset with such meta.json, keywords work perfectly.

So Zeal is already able to parse this from meta.json. I expect it to also do the parsing when downloading docset from feed URL, because why not?

**Comment by trollixx** [comment]
Zeal will overwrite `meta.json` that is packaged in a docset. This file is something Zeal uses internally and it's not intended to be provided by docsets. As I mentioned in the past, docsets need to set on `DashDocSetKeyword` property in `Info.plist` to provide custom keywords.

**Comment by trollixx** [comment]
There are also other properties that can be used to provide keywords, see [`docset.cpp`](https://github.com/zealdocs/zeal/blob/5cdad0e/src/libs/registry/docset.cpp#L153-L168). Just not `meta.json`. Eventually I hope to remove this file in favor a better format or a centralized docset metadata storage.
