### ISSUE TITLE
Ubuntu/debian build instructions should be updated

### ISSUE THREAD

**Issue by ezxpro** [zealdocs/zeal#1438]
Following the [instructions in the wiki](https://github.com/zealdocs/zeal/wiki/Build-Instructions-for-Debian-Family) will work absolutely fine if you're using Ubuntu and qt5(only issue right now is that you have to comment out the Git related stuff from `CMakesList.txt` found in the root folder).

However, if you're using debian, you'll need to fetch a few dependencies from a Ubuntu repo (like `PkgConfig`, if cmake complains about it, download the one from an old Ubuntu version, like 18.04. Ubuntu now uses zstd, which is not supported by dpkg in debian)

Apart of that, if you try to build using Qt6, either on debian or Ubuntu, a myriad of problems pop up (e.g **requires** QtWebKit and Qt X11 bindings, none of which exist on Qt6, here it also fails to solve the path to several dependencies). I think a disclaimer should be put on the wiki saying these instructions are meant for qt5

**Comment by ezxpro** [comment]
> The instructions mention Qt 5 packages so they are clearly not meant for a Qt 6 build so far.
> 
> I cannot reproduce any build issues based on those instructions. master builds fine here on both Ubuntu 22.04 and Debian 11 and I'm not aware of any third-party repo being used for one of the dependencies.
> 
> In case of build problems it would probably be good to have a bit more information, at least the complete console output starting with `cmake -B build`.

Ok, I was trying to build this with Qt6 on WSL (Ubuntu 20.04/Debian 11). I'll post the output here later.

**Comment by trollixx** [comment]
The wiki page has been updated.
