### ISSUE TITLE
There is no css style for local reading, only black characters on a white background, and you can only see the style when you open it in a browser.

### ISSUE THREAD

**Issue by bacon-001** [zealdocs/zeal#1444]
# There is no css style for local reading, only black characters on a white background, and you can only see the style when you open it in a browser.
![Snipaste_2022-11-21_18-35-32](https://user-images.githubusercontent.com/79966974/203029030-fb12f6b2-d548-41a3-be25-560692279dcf.png)

**Comment by Jaddeed** [comment]
same problem

**Comment by tophf** [comment]
Fix:
1. open `CSS.docset\Contents\Resources\Documents\developer.mozilla.org\static\css\main.XXX.css` inside the directory where Zeal stores the data in a text editor e.g. Notepad - `XXX` is a bunch of letters and digits.
2. find `@media(prefers-color-scheme:light)`
3. replace it with `@media screen` - note the space
4. save it and restart Zeal.

**Comment by trollixx** [comment]
This should be fixed in the `main` branch. Please try the latest [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml). Binary artifacts are attached to each build.

**Comment by tophf** [comment]
Yep, fixed:

![image](https://user-images.githubusercontent.com/1310400/232275229-c73ada56-8d12-4a99-bbd1-17ccadce2317.png)
