### ISSUE TITLE
Zeal makes Intel Macbooks switch to discrete GPU

### ISSUE THREAD

**Issue by alexcom** [zealdocs/zeal#1446]
I know that macOS is not supported officially. Nevertheless Zeal compiles perfectly under macOS. The only thing I noticed is that when launched it triggers more energy consuming AMD GPU.

**Comment by alexcom** [comment]
This seem to fix the issue: https://developer.apple.com/library/archive/qa/qa1734/_index.html

**Comment by trollixx** [comment]
Implemented in #1447.
