### ISSUE TITLE
C++ Docset cannot find the file specified

### ISSUE THREAD

**Issue by datMaffin** [zealdocs/zeal#1448]
Hi,

The C++ docset seems to not always be able to "find the file specified".
![image](https://user-images.githubusercontent.com/29998721/206003999-994e19df-275f-4724-89e4-680d23e6cb83.png)

Full text:

    Error opening C:/Users/marvin.dostal/AppData/Local/Zeal/Zeal/docsets/C++.docset/Contents/Resources/Documents/en.cppreference.com/w/cpp/chrono/operator%2522%2522d.html: The system cannot find the file specified

    Failed to load URL file:///C:/Users/marvin.dostal/AppData/Local/Zeal/Zeal/docsets/C++.docset/Contents/Resources/Documents/en.cppreference.com/w/cpp/chrono/operator%252522%252522d.html.

    QtNetwork Error 203

---

I first thought that this should be on the [Dash-User-Contributions](https://github.com/Kapeli/Dash-User-Contributions), but it was closed there: https://github.com/Kapeli/Dash-User-Contributions/issues/4035

**Comment by Kapeli** [comment]
This isn't a docset issue as far as I can tell (Dash has no issues loading the pages). Maybe the issue is caused by the percent encodings in the paths?

**Comment by datMaffin** [comment]
I just compiled the master zeal, and it seems to already work on Ubuntu 18.04 (HIDPI is a bit funky on that platform though ;) ):
![image](https://user-images.githubusercontent.com/29998721/206246110-b79f4231-6d04-4c51-aab0-cef2e223d484.png)

**Comment by trollixx** [comment]
Duplicate of #1278.
