### ISSUE TITLE
Building on Fedora 20. make error. zlib.h: no such file or directory

### ISSUE THREAD

**Issue by kaeltran** [zealdocs/zeal#145]
I'm using Fedora 20, trying to install zeal.
My steps:
1. download zeal-master.zip
2. unzip the file
3. change directory to zeal-master/zeal
4. run qmake-qt5 (works)
5. run make (got error):

In file included from quazip/quazip.h:31:0,
                 from zealsettingsdialog.cpp:16:
quazip/zip.h:56:18: fatal error: zlib.h: No such file or directory
 #include "zlib.h"
                  ^
compilation terminated.
make: **\* [zealsettingsdialog.o] Error 1

how can I deal with this :(

**Comment by LukeVideo** [comment]
Thank you needed that info for a failling compilation to!;)
