### ISSUE TITLE
[feature request] Allow shell variables in zeal.conf

### ISSUE THREAD

**Issue by cocoonkid** [zealdocs/zeal#1452]
[feature request] Allow shell variables in zeal.conf

I'd like to set a docset path to
```


[docsets]
path=$HOME/.config/Zeal/docsets/
```

or

```

[content]
custom_css_file=~/.config/Zeal/userContent.css
```

I have to manually change this for migrations everytime.

Thank you for your consideration!

**Comment by trollixx** [comment]
Duplicate of #643.
