### ISSUE TITLE
Docksets adding?

### ISSUE THREAD

**Issue by Blizz1800** [zealdocs/zeal#1453]
Hi guys, i'd love your app, but I wanna know if you have plans to add SFML docs, they are in the owners page to download it free in html version, yeah, but, i think's good have all-in-one for that, thanks ;D

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.now.sh/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).

Also see https://github.com/zealdocs/zeal/discussions/1334#discussioncomment-5565605 about SFML.
