### ISSUE TITLE
HTML, JavaScript and CSS reference color schema 

### ISSUE THREAD

**Issue by carrretero** [zealdocs/zeal#1458]
Hi, and thanks for creating this very necessary tool.

There is however an issue with the mentioned docs, HTML, JavaScript and CSS, the background & text colors are too close to each other in both light and dark mode, as a result the contrast and readability suffer great deal.
Running on Linux Mint Vera.

Light Mode:

![image](https://user-images.githubusercontent.com/80264616/216815669-44ef5233-32c3-4730-a636-4321b68fc073.png)

Dark Mode:

![image](https://user-images.githubusercontent.com/80264616/216815627-70c16c91-581f-4845-ba2c-76d60c5de103.png)

The rest of the docs that i have downloaded render as they should.

Kind Regards.

**Comment by Peter-Ries** [comment]
same on Endeavour with latest Plasma and breeze dark theme. Custom CSS with background #fff and color #000 have no effect. Obviously only the above mentioned docs. Rest seems to be okay.

**Comment by trollixx** [comment]
Please try the latest code from the `main` branch. [CI builds](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml) are now available. Binary artifacts are attached to each build.

The poor man's dark mode Zeal offers has a number of issues. I am investigating if we can switch to Chromium's native dark mode. More information is available in [QTBUG-84484](https://bugreports.qt.io/browse/QTBUG-84484).

**Comment by trollixx** [comment]
Fix requires a build with Qt version >=5.14.
