### ISSUE TITLE
点击JavaSE19闪退

### ISSUE THREAD

**Issue by hethereal** [zealdocs/zeal#1459]
打开软件后,点击JavaSE19会有一个短暂的加载过程,然后就突然退出了
系统: win11
版本: 0.6.1
没有打开任何代理软件
不知道是哪里出了问题,麻烦帮我看一下,谢谢了

**Comment by nomadbard916** [comment]
QT 的問題，0.7版出來前只能自己編譯 master 使用，才不會有這問題 
https://github.com/zealdocs/zeal/issues/1429

**Comment by trollixx** [comment]
Please create issues in English, I do not understand Chinese.
