### ISSUE TITLE
The key sequence 'Ctrl+PgDown' is ambiguous

### ISSUE THREAD

**Issue by ratijas** [zealdocs/zeal#1465]
Ctrl+PgUp and Ctrl+PgDown are two primary shortcuts to switch tabs left and right respectively. Strangely enough, Ctrl+PgUp works fine, but Ctrl+PgDown triggers this error and does nothing:

![Zeal - Ctrl+PgDown shortcut](https://user-images.githubusercontent.com/6737986/221404068-7369f779-4079-4a64-b970-0b30f7f99216.png)

That means somewhere in the code, two instances of QAction registered the same shortcut for themselves, and they fight each other.

**Comment by trollixx** [comment]
What's your desktop environment? I can't trigger this warning...

**Comment by ratijas** [comment]
Operating System: Arch Linux 
KDE Plasma Version: 5.27.3
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.8
Kernel Version: 6.2.6-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 970M/PCIe/SSE2
Manufacturer: ASUSTeK COMPUTER INC.
Product Name: G752VT

Can't rule out the possibility that my system shortcuts somehow collide, but this doesn't happen in other KDE apps.

I wanted to work myself on Zeal issues that I found that weekend, but ended up doing KDE stuff instead 😅

**Comment by ratijas** [comment]
Oh my, there is a bunch of vendored custom shortcuts handling in qxtglobalshortcut dir. Are those really needed?

**Comment by ratijas** [comment]
What an interesting implementation detail:

```cpp
    ui->actionNextTab->setShortcuts({QKeySequence::NextChild,
                                     QKeySequence(Qt::ControlModifier | Qt::Key_PageDown)});
    addAction(ui->actionNextTab);
    connect(ui->actionNextTab, &QAction::triggered, this, [this]() {
        m_tabBar->setCurrentIndex((m_tabBar->currentIndex() + 1) % m_tabBar->count());
    });

    // TODO: Use QKeySequence::PreviousChild, when QTBUG-15746 is fixed.
    ui->actionPreviousTab->setShortcuts({QKeySequence(Qt::ControlModifier | Qt::ShiftModifier | Qt::Key_Tab),
                                         QKeySequence(Qt::ControlModifier | Qt::Key_PageUp)});
    addAction(ui->actionPreviousTab);
    connect(ui->actionPreviousTab, &QAction::triggered, this, [this]() {
        m_tabBar->setCurrentIndex((m_tabBar->currentIndex() - 1 + m_tabBar->count()) % m_tabBar->count());
    });
```

Replacing "next" one with

```
    ui->actionNextTab->setShortcuts({QKeySequence(Qt::ControlModifier | Qt::Key_Tab),
                                     QKeySequence(Qt::ControlModifier | Qt::Key_PageDown)});
```

easily fixed the problem. But I wonder if this is an appropriate way.

**Comment by ratijas** [comment]
Conversely, setting only standard sequences works fine and does not trigger any "ambiguous" warnings, but of course only works for that one standard shortcut.

```cpp
    ui->actionNextTab->setShortcuts(QKeySequence::NextChild);
    addAction(ui->actionNextTab);
    // ...

    ui->actionPreviousTab->setShortcuts(QKeySequence::PreviousChild);
    addAction(ui->actionPreviousTab);
```

It seems like Qt internally fails to de-duplicate shortcuts which are essentially the same and bound to a single action.

**Comment by ratijas** [comment]
Reported upstream as <https://bugreports.qt.io/browse/QTBUG-112193>. Best we can do for now is to stop using standard shortcuts completely until that is resolved. On the other hand, the bug <https://bugreports.qt.io/browse/QTBUG-15746> mentioned in a `// TODO` comment currently — I can't reproduce it, and it was last updated long ago, so I assume it's been long fixed since.

**Comment by trollixx** [comment]
Thanks for looking into this! [QTBUG-15746](https://bugreports.qt.io/browse/QTBUG-15746) only affected some platform themes. I'll keep comment around just in case :)
