### ISSUE TITLE
some of the Bootstrap previews like dropdown, modals not working

### ISSUE THREAD

**Issue by ArtooS** [zealdocs/zeal#1468]
For some reason when I click on the buttons to "launch demo Modal" or click on the previews in the 'Dropdowns' section to view what a dropdown menu looks like nothing happens.  These features use to work but not sure what caused the demos to stop working.  Maybe it was a Windows update or when Zeal got updated or something else.   Not a big issue just wanted to point it out..

Using Zeal 0.6.1 and windows 10 Pro 22H2 Build 19045.2673 64-bit,

**Comment by trollixx** [comment]
Can you try the latest [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml) and see if the issue persists? Binary artifacts are attached to each build.

**Comment by trollixx** [comment]
Confirmed to work with the latest code.
