### ISSUE TITLE
Can it support Powershell?

### ISSUE THREAD

**Issue by gool123456** [zealdocs/zeal#1470]
Powershell is a new type of script for windows. It is recommended to add a branch 🥇 

script file type : *.ps

**Comment by trollixx** [comment]
I am not sure what you mean. Can you elaborate?

There's a user contributed [PowerShell docset](https://zealusercontributions.vercel.app/search?q=powershell).

**Comment by gool123456** [comment]
> I am not sure what you mean. Can you elaborate?
> 
> There's a user contributed [PowerShell docset](https://zealusercontributions.vercel.app/search?q=powershell).

GoodJob , This is exactly what I want !
