### ISSUE TITLE
Docsets are not available

### ISSUE THREAD

**Issue by qiannianzhihu** [zealdocs/zeal#1479]
After opening Zeal click on Tools and then click on Docsets a popup appears saying Server returned a corrupted docset list.
![cea34c2151af55f7a430465d9003843](https://user-images.githubusercontent.com/127476390/228839043-e221c1af-ad2c-4cbd-b3da-24191fbd8ee2.png)

**Comment by trollixx** [comment]
I do not see any issues with docset downloading. Are you using some kind of proxy or VPN?
