### ISSUE TITLE
Tray icon is displayed in the upper left corner in Ubuntu 14.04

### ISSUE THREAD

**Issue by zhoulike** [zealdocs/zeal#148]
![tray-icon](https://dl.dropboxusercontent.com/u/22403480/zeal.png)

This issue is similar with [issue 104](https://github.com/jkozera/zeal/issues/104) except that tray icon is not a black box. I'm using Ubuntu 14.04. Zeal is the latest version.

Any solutions?

**Comment by gausie** [comment]
This problem has returned for me.

**Comment by trollixx** [comment]
The problem has been fixed in 0.1 branch (see #321), and will be released as part of 0.1.2 release shortly.
