### ISSUE TITLE
mouse wheel does not work correctly when configured "one screen at a time"

### ISSUE THREAD

**Issue by marvinqu** [zealdocs/zeal#1480]
OS: Windows 11 Pro 22621.1344
zeal version: 0.6.1

problem:
when mouse wheel is configured to  scroll one screen at a time, it does not work in zeal. 
Roll the wheel one notch, only scroll a few lines(about 1 or 2 lines).

![image](https://user-images.githubusercontent.com/16775207/229113551-96df4866-7771-44fc-8996-538a56e39f3a.png)

**Comment by trollixx** [comment]
Can you try the latest [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml) and see if the issue persists? Binary artifacts are attached to each build.

**Comment by marvinqu** [comment]
Still the same.
I downloaded the 
zeal-0.6.2-dev.290+a89bed5-windows-x64
unzip it and tried,  scroll one screen still not worked, 
only scroll a few lines (about 1-2 lines)when roll the wheel one notch.

**Comment by trollixx** [comment]
I misread the original message. Just tested this and indeed couldn't find a way to make `QWebEngineView` respect the system scrolling setting. There is [QTBUG-103876](https://bugreports.qt.io/browse/QTBUG-103876), which is somewhat related to this.

**Comment by marvinqu** [comment]
thank you. I'm afraid I have to wait QT to fix this bug.
