### ISSUE TITLE
i can't see javascript docset in KDE plasma using DE dark theme

### ISSUE THREAD

**Issue by marcosfnsc** [zealdocs/zeal#1481]
- OS: archlinux
- zeal version: 0.6.1
- kde plasma version: 5.27.3 (default dark theme)
- kde frameworks version: 5.104.0
- Qt version: 5.15.8
- running on wayland

![2023-04-03_00-35](https://user-images.githubusercontent.com/48636651/229406363-19295dc0-2f6b-490b-9d2e-23a430db5cbd.png)

setting zeal to light or dark theme doesn't fix it

**Comment by trollixx** [comment]
Please try the latest code from the `main` branch. With Qt WebEngine it renders a lot better. On Arch Linux you can install `zeal-git` from AUR.

**Comment by marcosfnsc** [comment]
I installed zeal-git as suggested, I tested it in the docs I have here and even in the javascript one and it's fixed

but now bash has the same problem 😁

**Comment by trollixx** [comment]
Yep, the Bash docset is broken because of the fake dark mode the current code has. It renders totally fine with Chromium's native dark mode:
![image](https://user-images.githubusercontent.com/714940/232976743-1d77c1ed-524b-44b0-8f4f-64603f905636.png)

**Comment by marcosfnsc** [comment]
so the code that in the main branch is actually corrected, having only bash as an isolated case, thanks for the work done on zeal
