### ISSUE TITLE
Downloading a docset gives "SSL handshake failed." Custom feeds won't work.

### ISSUE THREAD

**Issue by Nyxa** [zealdocs/zeal#1482]
I tried looking at other issues that included SSL handshake failed, but none had a solution. I am on Kubuntu 22.10, and the error gives me nothing to work with. Running Zeal from the command line also does not offer much in the way of a solution. I tried using feeds directly (e.g. "newyork.kapeli.com/feeds/C++.tgz" and this will successfully download the file, but then call it an invalid docset.

Zeal seems like a really neat project so being unable to get it to work is pretty depressing. Is there anything I could do to fix this?

**Comment by cas--** [comment]
Same on Ubuntu 20.04 with 0.9.1. Looking at the issues, downloading the feeds seem fragile.

![image](https://user-images.githubusercontent.com/606038/229758823-6a791a11-12b1-4039-99ba-024fa4c3087c.png)

> tried using feeds directly (e.g. "newyork.kapeli.com/feeds/C++.tgz" ... but then call it an invalid docset.

Add an XML feed manually from the list https://github.com/Kapeli/feeds so either use the kapeli URL or github raw URL:

* https://kapeli.com/feeds/Python_3.xml
* https://raw.githubusercontent.com/Kapeli/feeds/master/Python_3.xml

It's an inconvenient workaround but at least gets a usable application

**Comment by trollixx** [comment]
I don't see any issues with certificates or anything. Are you using some kind of proxy or VPN?

**Comment by cas--** [comment]
I'm not using any proxy or vpn but just checked again and it is working now.

It would suggest an issue with the certs for a mirror domain that Zeal was redirecting to. I can now see that manually adding the feeds worked since the tgz URLs are http rather than https...

The lack of a full error trace or settings to modify was frustrating, what debug steps would you suggest to help diagnose in future? I'll certainly verify the listed mirrors with both http and https if the same error occurs.

**Comment by trollixx** [comment]
Both HTTP and HTTPS URLs should work. I'll check if there are additional error details we can show, that can be helpful for debugging.

**Comment by hyuuks** [comment]
@trollixx sir i got same problem, even after follow @cas-- instruction.

my machine is kubuntu 22.04 and my zealdocset is v 0.6.1

**Comment by DaniilSkLi** [comment]
Same error, EndevourOS (Arch Linux), Zeal built from AUR via yay (aur/zeal 0.6.1-3 (+44 0.59) (Installed)). VPN or proxy is not used. Got the same error after downloading from flatpak.
I apologize for possible mistakes, I don’t know English well, I translated from my native language through Google.

**Comment by trollixx** [comment]
This issue predates certificate expiration problem from the last week. I think #1521 offers a feasible workaround for issues with secure connection unrelated to certificates.
