### ISSUE TITLE
Target "Core" links to target "LibArchive::LibArchive" but the target was not found

### ISSUE THREAD

**Issue by cas--** [zealdocs/zeal#1484]
Trying to build from latest source 89e8445630ea results in the following errors:

```
CMake Error at src/libs/core/CMakeLists.txt:1 (add_library):
  Target "Core" links to target "LibArchive::LibArchive" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at src/app/CMakeLists.txt:10 (add_executable):
  Target "App" links to target "LibArchive::LibArchive" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

Seems a recent change to use imported target LibArchive::LibArchive in commit is the culprit: 74ca9bfef09ad5216b42fc1cc785734351e9726c 

The problem stems from building on Ubuntu 20.04 where cmake version is 3.16.3 but [LibArchive::LibArchive](https://cmake.org/cmake/help/latest/module/FindLibArchive.html) is new in cmake 3.17. 

I am not sure what solution you want to go for here, revert the change or bump the cmake required version...

**Comment by trollixx** [comment]
I usually target the latest Ubuntu LTS, which is now 22.04. But in this case it's very easy to retain support for CMake 3.16.

**Comment by trollixx** [comment]
@cas-- btw, it's impossible to open your profile in the mobile app :)
