### ISSUE TITLE
I used the doc2dash tool to generate the Polars document, but its content was not displayed properly

### ISSUE THREAD

**Issue by RuixiangS** [zealdocs/zeal#1486]
Problem description
All the content is compressed into a small scroll bar area, as shown below:
![image](https://user-images.githubusercontent.com/29591339/231759433-3a6eec99-86b8-4127-a970-1743f468aaa2.png)

expect work:
https://pola-rs.github.io/polars/py-polars/html/reference/

requirement:
numpy
pandas
pyarrow
hypothesis==6.71.0
autodocsumm==0.2.9
commonmark==0.9.1
numpydoc==1.5.0
pydata-sphinx-theme==0.13.0
sphinx-autosummary-accessors==2022.4.0
sphinx-copybutton==0.5.1
sphinx-design==0.3.0
sphinx==5.3.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-napoleon==0.7
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5

**Comment by trollixx** [comment]
Please give [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml) a try. Binaries are attached to each build. Docsets should render properly there.

**Comment by trollixx** [comment]
It looks very similar to the problem described in #1439. So it should work with the new code.

**Comment by RuixiangS** [comment]
> [它看起来与#1439](https://github.com/zealdocs/zeal/issues/1439)中描述的问题非常相似。所以它应该适用于新代码。

Thanks! It works great!
