### ISSUE TITLE
SSL Handshake Failed

### ISSUE THREAD

**Issue by bkrcokan13** [zealdocs/zeal#1496]
I get SSL Handshake error while downloading documentation

![image](https://user-images.githubusercontent.com/132247985/236111749-f8fd065b-8aeb-4541-8e4c-1a1a787ebde5.png)

**Comment by matazdt** [comment]
I've got a similar issue with this as well

**Comment by SpotlightKid** [comment]
The TLS certificate of `go.zealdocs.org` expired on 2023-07-27.

**Comment by trollixx** [comment]
This issue predates certificate expiration from the last week. Most likely it's the same problem as #1482. The proposed #1521 should provide a workaround for situations when establishing secure connections is impossible.
