### ISSUE TITLE
SQL Error: Unable to open database file

### ISSUE THREAD

**Issue by Haaruun-I** [zealdocs/zeal#1497]
Whenever I open the app, none of the docsets I download show up at all. If I open the app from the terminal, I get this error
![image](https://github.com/zealdocs/zeal/assets/22063464/78e80f3a-398d-4753-9e7f-fb473b2796c6)
If I open the folder where the docsets are stored, all the files are there
I am running the flatpak version of the app, on Fedora Workstation 38.

**Comment by trollixx** [comment]
This actually works as designed. By default Flatpak does not allow access to anything but `~/.var/app/$FLATPAK_ID` and `$XDG_RUNTIME_DIR/app/$FLATPAK_ID`.

Your docsets are stored in `$HOME/doc`. A workaround would be running Zeal with `--filesystem=home`.

See [Flatpak docs](https://docs.flatpak.org/en/latest/sandbox-permissions.html) for more information.
