### ISSUE TITLE
Windows Version and a way to limit search to particular language

### ISSUE THREAD

**Issue by violetkiwi** [zealdocs/zeal#15]
First of all big congrats to your project.

Please consider a real installer for windows in two flavors.

1.Base version with no docsets.

2.Compete version with all docsets

Please provide a way to limit search to particular language or API through specific format for searching by regular expression or something.

**Comment by trollixx** [comment]
Most docsets are provided by Dash. I don't think we'll provide an installer with bundled docsests anytime soon.

It's possible to have a docset downloader built into the installer, but I doubt it's usefulness.
