### ISSUE TITLE
无法查看文档

### ISSUE THREAD

**Issue by Nick5412** [zealdocs/zeal#1500]
一打开文档就闪退

**Comment by kkzi** [comment]
操作系统和崩溃时的文档是什么呢
如果您可以更详细地描述问题，协助开发者复现问题，那么问题会被更容易发现和修复

**Comment by xc2002** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by xc2002** [comment]
就是像图片中的那样,一打开文档,过了大概不到1秒钟,就自动退出程序了






&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zealdocs/zeal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月3日(星期六) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zealdocs/zeal] 无法查看文档 (Issue #1500)





 
操作系统和崩溃时的文档是什么呢
 如果您可以更详细地描述问题，协助开发者复现问题，那么问题会被更容易发现和修复

**Comment by trollixx** [comment]
Please use English to describe problem and the comments.

**Comment by Nick5412** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
