### ISSUE TITLE
no pytorch documentation

### ISSUE THREAD

**Issue by xiboqi** [zealdocs/zeal#1501]
it's a great software,but i can't find any documentation of pytorch which makes me sad

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.now.sh/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).

**Comment by trollixx** [comment]
https://zealusercontributions.vercel.app/search?q=pytorch
