### ISSUE TITLE
Java and Spring Error

### ISSUE THREAD

**Issue by RaynerSoto** [zealdocs/zeal#1508]
Java and Spring helps shut down the application at once without throwing exceptions

**Comment by SantiagoNoguera** [comment]
It's true, I download the Spring framework and Java domumentation but the application shut down when I try to see something of the documentation

**Comment by trollixx** [comment]
Duplicate of #868.

Until v0.7.0 is released, please build Zeal from `main` or give [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml) a try.
