### ISSUE TITLE
TLS initialization failed

### ISSUE THREAD

**Issue by guidomz** [zealdocs/zeal#1511]
This has been reported before here `https://github.com/zealdocs/zeal/issues/1243#issue-643456076` but it has been closed.

I get this same problem on version `v0.6.2-dev` when adding a docset and basically does not allow me to add a docset. I'm using Debian Bullseye, and not using a proxy.

I already updated some dependencies: `openssl` at version 3.0.9-1, `libssl-dev` at 3.0.9-1, `ssl-cert` at 1.1.2.

Running zeal in terminal, I get:

```
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
```

_Originally posted by @guidomz in https://github.com/zealdocs/zeal/issues/1243#issuecomment-1617116462_

**Comment by trollixx** [comment]
I am not sure what can be done here. There's no SSL specific code in Zeal. Qt is handling everything related to secure connections. I see this was previously [reported](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1030658) in Debian bug tracker but seemingly got resolved on its own.

**Comment by trollixx** [comment]
Have you tried AppImage [CI builds](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml)?

**Comment by guidomz** [comment]
I've resorted to using the appImage while I was in debian 11 (bullseye) but upgrading to debian 12 (bookworm) seemed to have been resolved, i.e., the problem I previously reported did not reappear with a non-appImage (installed) version. Thanks.
