### ISSUE TITLE
Zeal exited abnormally after loading docs

### ISSUE THREAD

**Issue by dongzhaolee** [zealdocs/zeal#1512]
I imported the docsets successfully. 
However, when I try to open the docs for Java SE15 or later versions, such as Java SE18 or Java SE19, Zeal exits abnormally. I have encountered this bug on **all versions above Java SE14**

**Comment by trollixx** [comment]
Duplicate of #868.

Until v0.7.0 is released, please build Zeal from `main` or give [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml) a try.
