### ISSUE TITLE
Hightlight from search hides the matched text

### ISSUE THREAD

**Issue by fcbertoldi** [zealdocs/zeal#1513]
The current matching result from the text search highlights the text with white on a white background, effectively erasing the text. 

![zeal-highlight2](https://github.com/zealdocs/zeal/assets/213208/364cd398-7fe4-4586-834b-bb5ddfbe5298)

I was able to override the default behavior with a custom CSS rule set in `Edit->Preferences->Content->Custom CSS File`:

```
::selection {
    color: red;
    background-color: yellow;
}
```

I'm using Zeal v0.6.1installed from Linux Mint's package manager, which uses Qt5.

Zeal version 0.6.2 compiled from the source using Qt6 does not have this weird behavior.

OS: Linux Mint 21.1
Version: 1:0.6.1-1.2

Dependencies:

libarchive13:
  Installed: 3.6.0-1ubuntu1
libc6:
  Installed: 2.35-0ubuntu3.1
libgcc-s1:
  Installed: 12.1.0-2ubuntu1~22.04
libqt5concurrent5:
  Installed: 5.15.3+dfsg-2ubuntu0.2
libqt5core5a:
  Installed: 5.15.3+dfsg-2ubuntu0.2
libqt5gui5:
  Installed: 5.15.3+dfsg-2ubuntu0.2
libqt5gui5-gles:
  Installed: (none)
libqt5network5:
  Installed: 5.15.3+dfsg-2ubuntu0.2
libqt5webkit5:
  Installed: 5.212.0~alpha4-15ubuntu1
libqt5widgets5:
  Installed: 5.15.3+dfsg-2ubuntu0.2
libqt5x11extras5:
  Installed: 5.15.3-1
libsqlite3-0:
  Installed: 3.37.2-2ubuntu0.1
libstdc++6:
  Installed: 12.1.0-2ubuntu1~22.04
libx11-6:
  Installed: 2:1.7.5-1ubuntu0.2
libxcb-keysyms1:
  Installed: 0.4.0-1build3
libxcb1:
  Installed: 1.14-3ubuntu3
libqt5sql5-sqlite:
  Installed: 5.15.3+dfsg-2ubuntu0.2

**Comment by trollixx** [comment]
As you mentioned, this has been fixed by the migration to Qt WebEngine.
