### ISSUE TITLE
Zeal cannot display pages in Polars docsets.

### ISSUE THREAD

**Issue by taozuoqiao** [zealdocs/zeal#1515]
The Polars docsets I use is from https://zealusercontributions.now.sh/ (from https://github.com/paw-lu/polars-dash-docset). I also tried generating Polars docsets myself. Zeal (0.6.1, Windows 11) cannot display whole pages normally in both cases. 

![image](https://github.com/zealdocs/zeal/assets/18346451/a21e3d4b-40e7-451a-b0e1-9579ec5820cf)

The pages should be displayed like https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_csv.html.

![image](https://github.com/zealdocs/zeal/assets/18346451/352b0d18-4e88-43d3-a865-c2b0cc3d6c4d)

**Comment by trollixx** [comment]
Please build Zeal from `main` or give [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml) a try. This should render properly with the new webview.

**Comment by taozuoqiao** [comment]
> Please build Zeal from `main` or give [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml) a try. This should render properly with the new webview.

Thanks very much, I have tried [zeal-0.6.2-dev.309+cee4e50-windows-x64](https://github.com/zealdocs/zeal/suites/14903737062/artifacts/849156680) in the CI build, and it does work.
