### ISSUE TITLE
request for feature: keyboard shortcut to switch to current tab

### ISSUE THREAD

**Issue by laoshaw** [zealdocs/zeal#1517]
after I input search keyword in the search bar, I want to switch to the right pane quickly.
I'm using alt+0 to do it, or ctrl+F to do it, can I have something like:
ctrl+c that will focus on the right side page so I don't need switch fingers to Alt from Ctrl, and I do not really need Ctrl+F here as I'm not searching anything.
Even better, providing vim style jkhl to navigate the right side document pane.
Thanks.

**Comment by trollixx** [comment]
Pressing `Enter` should do the trick. It will focus the web view. Please follow #10 for Vi-style navigation.
