### ISSUE TITLE
Certificate for go.zealdocs.org expired

### ISSUE THREAD

**Issue by The-Compiler** [zealdocs/zeal#1518]
When updating the docsets:

> Download failed!
> 
> Error: SSL handshake failed: The certificate has expired
> URL: https://go.zealdocs.org/d/com.kapeli/Python_3/latest

Apparently the certificate [expired](https://www.ssllabs.com/ssltest/analyze.html?d=go.zealdocs.org) around 7 hours ago.

---

On Linux (and possibly other Unix-like systems), you can use [libfaketime](https://github.com/wolfcw/libfaketime) to get around this:

`LD_PRELOAD=/usr/lib/faketime/libfaketime.so.1 FAKETIME="@2023-07-26 00:00:00" zeal`

**Comment by piotrlg9** [comment]
I'm so unlucky, I've just installed it on my Windows, same issue.

**Comment by mykolawasd** [comment]
This is certainly not a solution, but I also recently installed and in order to download the documentation I changed the date on my Windows system to the 25th when the certificate was still valid,  and I downloaded docs.

**Comment by piotrlg9** [comment]
@mykolawasd Thanks, works for me. 👍

**Comment by aksharvarma** [comment]
> Unfortunately still down.
> 
> Only Linux a bit more of a hassle to disable NTP and change your system date...

I got it to work by directly downloading the tar files via the explicit link (replacing Python_3 with what I wanted worked as long as I used the correct capitalization (as seen in zeal) and replaced spaces with underscores), moving it into the folder that zeal expects it in, and untaring. Starting up zeal after doing this showed those doctests as available. It still shows them as needing updates but until the certificate issue is fixed, this is a crude-ish work-around.

**Comment by DIGITALHUNTERS** [comment]
@mykolawasd Thanks it's working for me .

**Comment by The-Compiler** [comment]
> Only Linux a bit more of a hassle to disable NTP and change your system date...

On Linux, you can use [libfaketime](https://github.com/wolfcw/libfaketime) to get around this:

`LD_PRELOAD=/usr/lib/faketime/libfaketime.so.1 FAKETIME="@2023-07-26 00:00:00" zeal`

**Comment by gnbl** [comment]
Server and certificate issues seem frequent.
Last release 5 years old, no current CI artifact.
Ubuntu:
```
sudo apt install libfaketime
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1 FAKETIME="@2023-07-26 00:00:00" zeal
```
Thanks to The-Compiler (install path found with `dpkg -L libfaketime)`.

**Comment by Sam4uk** [comment]
Відкиваємо репозиторій 
[Kapeli/feeds](https://github.com/Kapeli/feeds)
у файлах XML беремо url і завантажуємо необхідний архів

Цей архів розпаковуємо у
~/.local/share/Zeal/Zeal/docsets/
Користуємось

**Comment by Nick268** [comment]
> Let's go to the repository [Kapeli/feeds](https://github.com/Kapeli/feeds) in the XML files, we take the url and download the necessary archive
> 
> Unpack the archive in ~/.local/share/Zeal/Zeal/docsets/ Have fun

Unfortunately i found this a bit vague.

I went here. https://github.com/Kapeli/feeds found a long list of .xml documents. What does "Take the url" mean? Take it from where to put where?

Puzzled!

**Comment by Nick268** [comment]
> I got it to work by directly downloading the tar files via the explicit link (replacing Python_3 with what I wanted 

Worked. All I am missing is the Icon. But that's not a problem.

Hopefully a new certificate is on its way.

**Comment by trollixx** [comment]
For some reason automatic renewal of the certificate didn't happen and had to be forced. The certificate has been updated.

**Comment by ptitfred** [comment]
> For some reason automatic renewal of the certificate didn't happen and had to be forced. The certificate has been updated.

Thank you :bow:
