### ISSUE TITLE
Donation via PayPal

### ISSUE THREAD

**Issue by sveggiani** [zealdocs/zeal#152]
There is a way to donate to the project using PayPal? If not, could you provide it? Thanks!

**Comment by jkozera** [comment]
@MetaMemoryT sounds good, though I don't think I'm going to have the time to review any bounties and claims. Looking at the [Bountysource FAQ](https://www.bountysource.com/faq#do-i-have-to-be-affiliated-with-a-project-in-order-to-put-a-bounty-on-an-issue), it seems anyone, even unrelated to the project, can create bounties, so feel free to do it.

In the meantime I'll update README to reflect my lack of commitment for this project, and remove the GreenAddress donation button, so perhaps in future it can be replaced with a [Bountysource Badge](http://blog.bountysource.com/post/87257081709/bountysource-badges).

**Comment by trollixx** [comment]
I have set up a Bountysource [team](https://www.bountysource.com/teams/zealdocs) and a repository integration, in case anyone would actually decide to donate or set bounties :smile:.

I guess this issue can be considered fixed.
