### ISSUE TITLE
Problemas al intentar abrir java SE9

### ISSUE THREAD

**Issue by NelsonZaraza** [zealdocs/zeal#1523]
Al momento de ingresar a Java SE9 se traba y se cierra

**Comment by trollixx** [comment]
English please? As much as I'd love to, I don't know all Earth languages. I bet this is about #868 pinned at the top.

**Comment by NelsonZaraza** [comment]
When entering Java SE9, it locks and closes.

**Comment by trollixx** [comment]
Yes, this is a duplicate of #868. Please try latest [CI builds](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml). Binary artifacts are attached to each build. Alternatively, you can build Zeal yourself from the `main` branch.
