### ISSUE TITLE
How to packaging a .exe installer on Windows ?

### ISSUE THREAD

**Issue by wngtk** [zealdocs/zeal#1525]
There only the build instructions on the wiki. How to make an installer for the result.

**Comment by yjy66630** [comment]
see "actions" tab
![Quicker_20230822_100208](https://github.com/zealdocs/zeal/assets/62711034/9c550035-be71-4ecf-a833-0af94b862ace)

**Comment by trollixx** [comment]
See [`pkg/wix`](https://github.com/zealdocs/zeal/tree/main/pkg/wix) folder for the old MSI packaging. It has not been updated for Qt 6 version. I am currently trying to move MSI build to use CPack, which is not straightforward. This is really the only work item that is remaining before v0.7.0 release.

**Comment by yjy66630** [comment]
邮件已经收到，不知道什么时候我会瞅瞅(OxO)

**Comment by CuteWaterBeary** [comment]
@trollixx please do complete the v0.7.0 version. The old version works great but I'd love to see the new features!

**Comment by trollixx** [comment]
JFYI, #1528 provides CPack based installer generation.

**Comment by CuteWaterBeary** [comment]
Can you upload the exe as a release for us then?
