### ISSUE TITLE
Regression: Back and forward shortcuts dont work with Qt WebEngine

### ISSUE THREAD

**Issue by kovidgoyal** [zealdocs/zeal#1531]
When zeal was based on Qt WebKit one could use alt+left/right to go back and forward. These shortcuts no longer work. Instead one has to click the back/forward buttons which is *much* slower.

**Comment by trollixx** [comment]
This was first broken by 03e0e1e05dec75ccc665f237be3bd6ae9cbca29f and some follow up UI refactoring.

So we cannot use `Alt+Right` and `Alt+Left` for navigating through the tree view. Need to find an alternative for that.

**Comment by trollixx** [comment]
@kovidgoyal I committed a fix, please test. Thanks for reporting the issue.

**Comment by kovidgoyal** [comment]
yes works fine thanks
