### ISSUE TITLE
Revisions compared as string / PHP docset outdated

### ISSUE THREAD

**Issue by cweiske** [zealdocs/zeal#1532]
The current PHP manual date is 2020-01-05, which is 3 years old.
PHP 8 happened since then, and many classes and functions are not available in the dash docset.

Please update this docset.

(Dash author said that this is a zeal issue: https://github.com/Kapeli/Dash-User-Contributions/issues/4565)

**Comment by cweiske** [comment]
docsetsdialog.cpp downloads the list of docsets from https://api.zealdocs.org/v1/docsets
It has PHP with revision 121, my local revision is 79:
```
$ cat ~/.local/share/Zeal/Zeal/docsets/PHP.docset/meta.json 
{
    "name": "PHP",
    "revision": "79",
    "title": "PHP"
}
```

`DocsetsDialog::processDocsetList` looks like as it should notice that.

----

I moved the `PHP.docset` directory away and re-installed the PHP docset. I now have the latest version.

So this seems to be a bug in update handling.
I'm using Zeal 0.6.1 from Ubuntu 22.04.

**Comment by cweiske** [comment]
I found it:
The latest PHP revision is 121, but my local one is 79.
When I change the local revision to 100, Zeal shows that an update is available.
When the local revision number is smaller than 100, an update is never shown to be available.

**Comment by cweiske** [comment]
And all this because DocsetMetadata revisions are strings, and a string comparison of `13` and `121` of course says that `13` is higher.

**Comment by trollixx** [comment]
Thanks for reporting and investigating! Just pushed a bit hacky fix.

Unfortunately, there's no backwards compatible way to fix this on the API side without resorting to prepending zeros to the revision number. It's something to address in future version of the docset list.
