### ISSUE TITLE
HTML "Attributes" (513): MANY deprecated; Several repeating 2,5,8+ times!

### ISSUE THREAD

**Issue by MichaelTheGamer** [zealdocs/zeal#1534]
It seems counter-intuitive and counter-productive to have several that are deprecated and thus, no longer of any real use aside from a pet project that will never see the light of day, if you will pardon the apt metaphor (IMO).  _Please_ understand: I am **not at _all_** trying to be harsh. No, many of the warnings that accompany these attributes specifically state that they are deprecated, non-standard, and obsolete. While the non-standard one is more for ones deemed "_experimental_", the same end applies in that one is really unable to use such elements or attributes.  
   And, though I am unsure whether this qualifies as a separate enough issue to warrant its own...well, Issue, it comes down to needing the same detailed review as the Obsolete/Deprecated Attributes, which is to go along and delete attributes deemed useless in one form or another.   
   Regardless, I am stating the second problem, which is that many of the 513 Attributes are repeats. What I mean is that ones like **align** which has 12 other Attributes named **align** below the previous one(s). And while this is near the upper limit of repeated Attributes, more than 50% of the 513 are `null`... or the equivalent of it since selecting any of the other (to use the same example Attribute) **aligns** will give the same definition with very minor exceptions. Certainly not enough for having their own listings and definitions listed.  Many, like **autocomplete** or **autofocus** are (only?) listed 5 times each, respectively.  And yet there are others, that though almost everyone (conservatively) at ***W3C*** would agree that all 9 listings of the Attribute **disabled** could easily have fit beneath a single definition with, at most, 3 "separate" uses, I can honestly verify that all 9 have obviously been dressed up in 5 or 6 different ways (there are still a couple that have an identical twin), depending on who you ask. But all do (of course) state that it is a Boolean value that either is, or is not. But there are, truly, several ways to use this Attribute (or absence of one). Still, this is the exception. But 2 of the 9 are still labeled as Deprecated and 3 are listed as Non-Standard. What chaos! But, HTML is truly an odd ***"Programming Language"*** to put it mildly...sort of.  Be that as it may, it does **NOT** deserve ... _that!_   

Respectfully, 
MichaelTheGamer

**Comment by trollixx** [comment]
All docsets are provided by Dash, so we cannot change the contents.

Implementing grouping of identical results should address this issue. Please follow #1032.
