### ISSUE TITLE
Cannot read from archive: gzip decompression failed

### ISSUE THREAD

**Issue by Alirezamn93** [zealdocs/zeal#1536]
After downloading some docsets, I got this error message `Cannot read from archive: gzip decompression failed.`
I'm using windows 10 and zeal 0.6.1

**Comment by trollixx** [comment]
Sounds like archives are not downloaded correctly. Can you try the latest [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yaml) on the off chance it is caused by something that has been fixed since v0.6.1?
