### ISSUE TITLE
zeal can not start

### ISSUE THREAD

**Issue by Janzenzzc** [zealdocs/zeal#1539]
Each startup error is reported as shown below:
![image](https://github.com/zealdocs/zeal/assets/34902304/30cee939-e64d-4220-be45-d4a6b13fc211)

System environment variables are also configured:
![image](https://github.com/zealdocs/zeal/assets/34902304/4ad66454-2d84-421f-b0d4-845fde07369d)

Rebooting the computer and trying a few times didn't work

So,can someone help me? Thank you very much!

**Comment by trollixx** [comment]
How did you install Zeal? Try the latest [CI builds](https://github.com/zealdocs/zeal/actions/workflows/build-check.yaml). Binary artifacts are attached to each run.

**Comment by trollixx** [comment]
Closing due to no response.
