### ISSUE TITLE
Tray Icon can not correctly displayed in KDE.

### ISSUE THREAD

**Issue by metalbrick** [zealdocs/zeal#154]
The icon of "edit-find" cannot load on KDE, 
it Seems that the method `QIcon::fromTheme()` of QT5 is not well supported on KDE 4.x, 
maybe import the tray icon from resources is a better solution.

**Comment by trollixx** [comment]
Since 8373aa9fd69b85bd9d5580d8d08af933e8b257d2 we fallback to icon in resources, so this problem should not happen anymore.
