### ISSUE TITLE
run the results of some examples 

### ISSUE THREAD

**Issue by JWleo** [zealdocs/zeal#1542]
zeal version:0.7.0
os version: windows

You cannot run the results directly from some examples in zeal in different gcc or other environment just like before

![image](https://github.com/zealdocs/zeal/assets/32316654/b6a8e014-e45a-4ae4-95f1-80e63b9e8c8e)

**Comment by trollixx** [comment]
Hi, the idea is cool, but there's no way to do that. Zeal is just a web browser with a few extras, it doesn't know how to build and run code.
