### ISSUE TITLE
Look for docsets in system path

### ISSUE THREAD

**Issue by lshprung** [zealdocs/zeal#1544]
Currently, Zeal only looks through a single path for docsets, as set in preferences (under "Docset Storage"). If Zeal were to optionally check for docsets in a system path on Linux/Unix-based systems (something like `/usr/share/Zeal/Zeal/docsets`), it would allow for docsets to be installed to the entire system. For example, a C docset could be installed on a Debian-based system from a package like C-Dash-Docset.deb or on a RHEL-based system from a package like C-Dash-Docset.rpm.

Curious to see if such a feature is within the scope of this project.

**Comment by trollixx** [comment]
Duplicate of #516.
