### ISSUE TITLE
Menu items text color same as background color

### ISSUE THREAD

**Issue by mjs7231** [zealdocs/zeal#155]
The menu items are the same color as the background color (black on black).  Its hard to get a screenshot of open menus, so you'll have to trust me.  When I mouse over the menu item it changes to white on orange so I can somewhat know whats going on. None of the other menus in my OS display this behavior (even other QT apps).

OS: Linux Mint 16
Controls Theme: Numix

**Comment by trollixx** [comment]
We do not force any special styling anymore, so the problem should be gone.
