### ISSUE TITLE
Possible regression: missing version and/or revision in meta.json

### ISSUE THREAD

**Issue by wdscxsj** [zealdocs/zeal#1559]
With v0.7.0, I notice some docsets have lost the `version` and/or `revision` fields in their `meta.json` after updating the docsets. For example, the LaTeX docset's `meta.json` becomes:

```json
{
    "name": "LaTeX",
    "title": "LaTeX"
}
```

The MySQL docset's `meta.json` becomes:

```json
{
    "name": "MySQL",
    "title": "MySQL",
    "version": "8.0"
}
```

Other affected docsets on my machine include Java SE20, PHP, SVG, and WordPress. They are always marked as "Update available". Neither updating nor deletion plus reinstallation avoids this issue. Perhaps related to #1532?

**Comment by trollixx** [comment]
And this is why I should write tests :(

**Comment by andrm** [comment]
It would be helpful if this would be released.

**Comment by wdscxsj** [comment]
My current workaround is to keep **two copies** of Zeal: v0.6.1 for updating docsets, and v0.7.0 as the viewer. The disk space cost for v0.6.1 is less than 100 MB.
