### ISSUE TITLE
Docsets grouped by context

### ISSUE THREAD

**Issue by bxschmidt** [zealdocs/zeal#1561]
Hi,
i propose the docsets being grouped by a kind of context and the user being able to switch context when switching to/working on another project.
f.e. for a Symfony-/PHP-Project search the following Docsets:
- Doctrine
- PHP
- Symfony
- Twig
then start working on dotNet-Project. Switch "context" and search Docsets:
- c#
- NugetA
- NugetB

Great project!

**Comment by trollixx** [comment]
Duplicate of #77. Please 👍 and subscribe.
