### ISSUE TITLE
Chocolatey update for `0.7.0` release?

### ISSUE THREAD

**Issue by DeveloperPaul123** [zealdocs/zeal#1563]
Will the new version be pushed out to chocolatey as well?

**Comment by naacbin** [comment]
> Yes. The recipe needs slight updates, but should be available soon.

Any update on this @trollixx as there is a new version available ?

**Comment by trollixx** [comment]
Done!

- https://community.chocolatey.org/packages/zeal/0.7.1
- https://community.chocolatey.org/packages/zeal.install/0.7.1
- https://community.chocolatey.org/packages/zeal.portable/0.7.1
