### ISSUE TITLE
Consider installing docsets into `$XDG_CACHE_DIR` (`~/.cache`)

### ISSUE THREAD

**Issue by intelfx** [zealdocs/zeal#1568]
On Linux, Zeal apparently extracts docsets into a subdirectory under `~/.local/share`. As docsets are in their nature "expendable" (i. e. merely a local copy of content available elsewhere), consider installing them into `~/.cache` instead. Additionally, consider creating a [`CACHEDIR.TAG`](https://bford.info/cachedir/) in the docset directory.

This might save bandwidth and/or disk space for users who perform backups of their data -- `~/.cache` would normally be excluded.

(This probably requires explicitly storing the _list_ of installed docsets elsewhere, so that the list itself would be preserved in case of a cache purge event.)

**Comment by jthvai** [comment]
> As docsets are in their nature "expendable" (i. e. merely a local copy of content available elsewhere)

This is only true for a machine that can depend on constant network connectivity - this is situational and use case specific. Storing docsets in `$XDG_CACHE_DIR` indicates to the desktop environment that the docset may be pruned at any time - which, for a user whose machine isn't connected to the internet, will render Zeal essentially useless when the cache is cleared.

The [Freedesktop spec](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html) states that `$XDG_CACHE_HOME` is used for "user-specific non-essential data files" - I would argue that the availability of docsets (both online and offline) is essential to the usage of Zeal.

Consider also the extra bandwidth that would be required to retrieve the docsets every time there is a cache purge event.

***

Consider excluding `~/.local/share/Zeal` from your backups instead.

**Comment by FichteFoll** [comment]
The folder where docsets are stored is configurable in the settings:

![image](https://github.com/zealdocs/zeal/assets/931051/9993e5ea-65aa-4913-8ba0-8fd779934f8d)

**Comment by trollixx** [comment]
As pointed out above I don't think categorizing docset storage as cache would be correct. Docsets are application data, and for many Zeal users redownloading them is not easy or not even possible. You can point Zeal to store docsets in another place to fit your setup. The default setting will not be changed.
