### ISSUE TITLE
How do I add a VTK offline document?

### ISSUE THREAD

**Issue by xjjgjmeng** [zealdocs/zeal#1577]
[VTK](https://vtk.org/doc/nightly/html/annotated.html)

**Comment by zchrissirhcz** [comment]
It seems `zeal` use the docs which `dash` provides. 

There is opencv docs provided in `zeal` which is generated from `doxygen`. I wonder if more doxygen generated C/C++ project docs can be provided, just as the request of VTK:

- [OpenCV](https://docs.opencv.org/4.9.0/)
- [Eigen](https://eigen.tuxfamily.org/dox/)
- [LLVM](https://llvm.org/doxygen/)
- [libstdc++](https://gcc.gnu.org/onlinedocs/gcc-8.3.0/libstdc++/api/namespaces.html)
- [VTK](https://vtk.org/doc/nightly/html/annotated.html)
- [GLFW](https://www.glfw.org/docs/latest/topics.html)
- [tgui](https://tgui.eu/documentation/latest-stable/annotated.html)
- [fmtlib](https://fmt.dev/latest/)
- [ogre](https://ogrecave.github.io/ogre/api/latest/building-ogre.html)
- [rttr](https://www.rttr.org/doc/master/classes.html)

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.now.sh/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).
