### ISSUE TITLE
Pop-up menu in the wrong screen

### ISSUE THREAD

**Issue by gaotongsh** [zealdocs/zeal#1587]
I am using v0.7.0 portable version.

I have a three-monitor setup. However, the pop-up menu of the menu bar will appear in the first screen from the left, regardless of the window Zeal is in.

Hope this screenshot can illustrate the issue. This screenshot captures the first and the second monitor. Zeal window is in the second monitor but the pop-up menu appears in the first.

![image](https://github.com/zealdocs/zeal/assets/12027397/2d93c04e-817c-4578-8e2a-58f7358f6751)

In addition, every new window (first open of main window, docset download window) appears in the first screen, not the current screen.

**Comment by gaotongsh** [comment]
In addition, every new window (first open of main window, docset download window) appears in the first screen, not the current screen.

**Comment by paco1333** [comment]
me pasa lo mismo con dos monitores

**Comment by trollixx** [comment]
Looks like an issue with Qt. There's not any custom code w.r.t. menus.

**Comment by trollixx** [comment]
I just updated CI to build with Qt 6.6.3. Can you try a [CI build](https://github.com/zealdocs/zeal/actions/runs/8541717048) to see if the bug is still there?

**Comment by gaotongsh** [comment]
> I just updated CI to build with Qt 6.6.3. Can you try a [CI build](https://github.com/zealdocs/zeal/actions/runs/8541717048) to see if the bug is still there?

Thanks for the fix! I can confirm the bug no longer exists in this build.

**Comment by gaotongsh** [comment]
Since this issue has been solved in v0.7.1, I will go ahead and close this.
