### ISSUE TITLE
.NET Framework docsets cannot be downloaded

### ISSUE THREAD

**Issue by TallonRain** [zealdocs/zeal#1594]
The option to download the docset for the .NET Framework is available, but it fails and reports the following error:
`Cannot extract docset NET_Framework: Unrecognized archive format`

There doesn't appear to be a way to resolve this in a straightforward manner.

**Comment by alexmercer007** [comment]
tengo el mismo problema

**Comment by bestMother** [comment]
I'm getting a similar issue and created a ticket with #1600 . From what I can see, the underlying Qt method calling this is related to a file path issue, but I don't believe that's the case as I've successfully downloaded a dozen or so other docsets. My hypothesis - I think the endpoint or some metadata incompatibility is the issue.

**Comment by TallonRain** [comment]
I did some digging and found that the .NET Framework feed appears to have been removed from Dash's official repo three weeks ago (as per [this commit](https://github.com/Kapeli/feeds/commit/fd061c558b64840e7a6b9fa98a02d9329fe266b6)) and subsequently delisted from Dash's website as a compatible feed. As such, it's likely that the target source Zeal was using has been taken down and a new docs feed will need to be set up.

**Comment by bestMother** [comment]
I've closed my issue - I ended up downloading a StackOverflow dump through KiwixJS for offline browsing and searchability. The downside is that it's pretty huge at around 80-100 GB. 

However, this does give you access to all posts and comments through January 2024. It's a huge repository that'll likely cover most things you need.

**Comment by trollixx** [comment]
I removed Android, Mono, .NET, Xamarin  docsets from the list.

@Kapeli any background on why these were deleted? Thanks.

**Comment by Kapeli** [comment]
These docsets have been deprecated some time ago (they were very hard to maintain/generate and used by few people). I've decided to remove them completely to save disk space.

**Comment by skornel02** [comment]
This is very frustrating and sad because in my country in the vocational schools you could actually use Zeal for offline help and now ".NET help is gone" (for standard installations) for many students.

**Comment by bb010g** [comment]
@Kapeli Are the generators for those docsets published anywhere, so any community members that care can pick up maintenance & generation from where you left off?

**Comment by Kapeli** [comment]
No, sorry.
