### ISSUE TITLE
doh set to ""  --  SystemOnly

### ISSUE THREAD

**Issue by killua99** [zealdocs/zeal#1599]
Latest version or update of Qt give me this kind of error.

https://stackoverflow.com/questions/77337521/qwebengineview-in-pyside6-not-loading-any-page

I wonder what could it be,

some quick links:

https://www.qt.io/blog/new-graphics-integration-in-qt-webengine-6.6-and-even-6.5.1

**Comment by trollixx** [comment]
Do you see the same issue in v0.7.1? It's built with Qt 6.6. And the latest CI builds have Qt 6.7.

**Comment by killua99** [comment]
now I can use it as usual ❤️
