### ISSUE TITLE
Android Docset Fails to Download - Unrecognized Archive Format

### ISSUE THREAD

**Issue by bestMother** [zealdocs/zeal#1600]
The Android docset fails to download upon starting it, reporting that the **archive format is unrecognized**. The same error occurs with the .NET Framework docset, so this could be related to #1594 .

![Screenshot of Error](https://github.com/zealdocs/zeal/assets/156981317/a6cf8ef0-a5ac-4585-b038-fbcb52634386)

**Comment by bestMother** [comment]
From what I briefly checked, the underlying Qt method calling this is related to a file path issue. However, that's probably not the underlying cause. I think the endpoint or some metadata incompatibility could be the issue.

**Comment by RomainSepulchre** [comment]
Hey, I have the same issue on my side. It also seems to happen only with the Android and Net Framework docsets. The download of the docset seems to stop finish instantly and the error happen at the start of the installation just like nothing was downloaded before the installation.

**Comment by RomainSepulchre** [comment]
I investigated a little bit and last month the feeds for these docsets have been removed from dash github https://github.com/Kapeli/feeds/commit/fd061c558b64840e7a6b9fa98a02d9329fe266b6 and since Zeal gets the docsets from Dash I guess the docsets files to download aren't available anymore.

**Comment by bestMother** [comment]
Thanks for the update. 

For now, I've downloaded a dump of StackOverflow and loaded it through KiwixJS for offline reference. Although it enables searchability, the size is very large at around 80-100 GB.
