### ISSUE TITLE
Incorrect path to brew's libarchive on ARM macOS

### ISSUE THREAD

**Issue by alt-romes** [zealdocs/zeal#1602]
Homebrew's default location for ARM/M-series chips macOSs is `/opt/homebrew/opt/libarchive/include` (see /opt/homebrew/opt/libarchive/include). This causes the `cmake -B build` to fail because `LibArchive_INCLUDE_PATH` is set to the path homebrew uses for Intel macs).

These are the offending lines:
https://github.com/zealdocs/zeal/blob/de213a74d8bd45b40638dd6d583ef82f819c14c0/src/libs/core/CMakeLists.txt#L34-L36

It would probably be better to get brew's prefix with `$(brew --prefix)` or to predicate the prefix on the architecture.
I don't know enough CMAKE to do this myself unfortunately.

Cheers

**Comment by zchrissirhcz** [comment]
A quick fix is
```bash
export LibArchive_ROOT=/opt/homebrew/opt/libarchive
cmake -S . -B build -G Ninja && cmake --build
```

**Comment by trollixx** [comment]
Fixed in 1621.
