### ISSUE TITLE
Bug when try update from 0.6.1 to 0.7.1

### ISSUE THREAD

**Issue by lordgodgiven** [zealdocs/zeal#1605]
Hello,

I'm currently using version 0.6.1 of zeal because version 0.7.1 has a bug. When I download the documentation, it's no longer available after restarting the application. On version 0.6.1, it's not possible to update, I get an "illegal value" message.

**Comment by trollixx** [comment]
Are you getting "Illegal value" message on startup or update check? If so, that's expected due to the backend migration to SSL. Unfortunately, v0.6.1 had insecure URL hard-coded.

Can you elaborate on the issue you are seeing in v0.7.0? There's no v0.7.1 yet.

**Comment by trollixx** [comment]
Update check in v0.6.1 no longer works due to hard-coded insecure URL. It can be disabled in settings. Docs not being available after installation indicates a problem with docset storage. Impossible to troubleshoot without more information.
