### ISSUE TITLE
how to download old docs,such as javascript

### ISSUE THREAD

**Issue by polarxy** [zealdocs/zeal#1609]
the latest javascript docs is:
<entry>
    <version>/128</version>
    <ios_version>1</ios_version>
    <url>http://sanfrancisco.kapeli.com/feeds/JavaScript.tgz</url>
    <url>http://london.kapeli.com/feeds/JavaScript.tgz</url>
    <url>http://newyork.kapeli.com/feeds/JavaScript.tgz</url>
    <url>http://tokyo.kapeli.com/feeds/JavaScript.tgz</url>
    <url>http://frankfurt.kapeli.com/feeds/JavaScript.tgz</url>
</entry>

but i want to download <version>/127</version>
what to do

**Comment by trollixx** [comment]
Right now would only be possible to do manually, see and subscribe to #208.
