### ISSUE TITLE
please add "docset feed URL" for customized docset

### ISSUE THREAD

**Issue by magicsky** [zealdocs/zeal#161]
I build some docset, and want to add to zeal. Now I have to copy them to `~/.local/share/zeal/docsets` , but dash have  "docset feed URL" .
![snip20140623_2](https://cloud.githubusercontent.com/assets/93135/3354725/b410663e-faa7-11e3-8bab-c22308d64926.png)

**Comment by trollixx** [comment]
Now it is possible to add a custom Dash feed to Zeal.
