### ISSUE TITLE
freedesktop zeal.desktop file is broken in the release archive

### ISSUE THREAD

**Issue by craftyguy** [zealdocs/zeal#1610]
The `assets/freedesktop/org.zealdocs.zeal.desktop` file has incorrect line endings in the release source archive hosted here on github. The file uses `CR` in the git repo, but it uses `CRLF` in the release source archive. Applications on e.g., Linux that follow the fd.o Desktop Entry Spec are unable to use it.

The release *tag* source archive (e.g. [v0.7.0.zip](https://github.com/zealdocs/zeal/archive/refs/tags/v0.7.0.zip
) and the git repo have correct line endings for `zeal.desktop`:

```
$ file assets/freedesktop/org.zealdocs.zeal.desktop: ASCII text
```

However the release source archive (e.g. [zeal-0.7.0.tar.gz](
https://github.com/zealdocs/zeal/releases/download/v0.7.0/zeal-0.7.0.tar.gz)) has incorrect CRLF line endings:

```
$ file
assets/freedesktop/org.zealdocs.zeal.desktop: ASCII text, with CRLF line terminators
```

From what I can tell, the release source archives are created in a Windows environment, in the same job that created the Windows builds for your app: https://github.com/zealdocs/zeal/blob/db781ed25670fc7e6df66349b158eed88eda629b/.github/workflows/release.yaml#L87 and https://github.com/zealdocs/zeal/blob/db781ed25670fc7e6df66349b158eed88eda629b/.github/workflows/release.yaml#L100

My guess is that the Windows env / build process is enough to change this file's line endings.

As a workaround, Linux distros and others can use the git tag source archives.

**Comment by trollixx** [comment]
Very odd. That's a static file which is not generated, so Windows or not should not matter. I'll investigate.

**Comment by trollixx** [comment]
Actually all text files in the release archive have CRLF line endings. I'll update release pipeline to create source archives on Linux.

**Comment by tanriol** [comment]
IIUC, the source archive uses CRLF line endings because `.gitattributes` marks a lot of files as `text` thus telling git to automatically convert end-of-line on checkout/checkin, and does not override the git's default `eol`, which is `crlf` on Windows.
