### ISSUE TITLE
Vulkan docset

### ISSUE THREAD

**Issue by hifron** [zealdocs/zeal#1613]
Vulkan docset missing, maybe also something about shaders docset.

Your toolset and built-in guides may have also some corporate counterparts and maybe some licensing for it(with some proper content and bundles to use and pay for(maybe on https://gumroad.com/discover  :)

**Comment by hifron** [comment]
https://registry.khronos.org/vulkan/specs/1.3/html/

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.now.sh/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).
