### ISSUE TITLE
Add Gtk, Fltk, and DearImGUI Docsets to Zeal via Dash

### ISSUE THREAD

**Issue by novaTopFlex** [zealdocs/zeal#1618]
# Introduction
I am currently a Linux enthusiast who seriously demands the creation of new docsets for different graphical toolkits, GTK, FLTK, and DearImGUI. Since you have packaged Qt4, Qt5, and Qt6 via Dash, I would like to have GTK 4.0 and earlier Gtk+2.0 and Gtk+3.0 documentation packages available as the toolkit may be utilized by a larger number of developers than Qt (unsure about that exactly).
# How to Fix
Unfortunately, we may be forced to speak with the organization directly about this issue, as with my earlier lack of Kotlin issue, in order to add GTK documentation.

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.now.sh/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).
