### ISSUE TITLE
flutter docs is missing

### ISSUE THREAD

**Issue by AbdurahmanAb** [zealdocs/zeal#1624]
I am new to Zeal and i was looking for official documentation of flutter but i can't find it

**Comment by trollixx** [comment]
Docsets are not part of this projects. All docsets currently available inside Zeal are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet, for example:

- [Feeds](http://zealusercontributions.now.sh/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate your own docsets following [this guide](https://kapeli.com/docsets).
