### ISSUE TITLE
"Check for update" does not find v0.7.1 when current is v0.7.0

### ISSUE THREAD

**Issue by zchrissirhcz** [zealdocs/zeal#1629]
Currently v0.7.1 is released, and my laptop installed v0.7.0, I guess it can be updated to v0.7.1 through the menu -> Help -> Check for updates. But it says "You are using the latest version". I'm not sure if this is a bug?

<img width="314" alt="image" src="https://github.com/zealdocs/zeal/assets/3831847/c7136a1b-71b0-4ad1-8958-743d82930911">

<br/>

<img width="238" alt="image" src="https://github.com/zealdocs/zeal/assets/3831847/a41b4339-c9a6-45fc-b3f2-c8b2c46b2989">

<img width="215" alt="zeal_3" src="https://github.com/zealdocs/zeal/assets/3831847/f21d1f03-8ffd-4e7c-8ccd-121c1258c3d6">

System information:
- Windows 11

**Comment by trollixx** [comment]
I've added v0.7.1 to the list. There's usually a delay in case some regression gets into a release.
