### ISSUE TITLE
No results found for `cmake: COMPILE_LANG_AND_ID` in zeal

### ISSUE THREAD

**Issue by zchrissirhcz** [zealdocs/zeal#1630]
I would like to search the keyword `COMPILE_LANG_AND_ID` in CMake document in Zeal, using Zeal v0.7.0, in CMake 3.29.3 document.

No results found for `COMPILE_LANG_AND_ID` in Zeal:
<img width="416" alt="zeal_4" src="https://github.com/zealdocs/zeal/assets/3831847/91a8a7a1-48b5-4b2f-8c5e-7450c74cf2e7">

And I can find `COMPILE_LANG_AND_ID` in original online CMake document:
<img width="788" alt="zeal_5" src="https://github.com/zealdocs/zeal/assets/3831847/307bb5d0-0e50-491a-905d-24c73c588d96">

The online CMake document seems does not provide 3.29.3 document anymore, so I also do a search in my local html document from where CMake 3.29.3 installed (`C:\soft\cmake\3.29.3\doc\cmake\html`), and it also get results:

<img width="728" alt="zeal_6" src="https://github.com/zealdocs/zeal/assets/3831847/f718a44b-0923-4075-89da-d72b26ba3c01">

I'm not sure if this is a bug of Zeal, or if this is expected output of Zeal.

**Comment by zchrissirhcz** [comment]
I also tried Zeal v0.7.1, there is no results for `COMPILE_LANG_AND_ID`.

**Comment by trollixx** [comment]
`cmake-generator-expressions(7)` page is definitely part of the docset, but no symbols are indexed. Maybe it's an oversight or Dash uses full text search instead of indexing each symbol on that page. @Kapeli could you comment please?

**Comment by Kapeli** [comment]
I've fixed this issue in CMake 3.29.4. Thanks a lot for letting me know about it!

**Comment by zchrissirhcz** [comment]
@Kapeli @trollixx Thanks for the fix. It works now.

<img width="790" alt="image" src="https://github.com/zealdocs/zeal/assets/3831847/b510f386-8432-44e3-a21f-40749d29b3fe">

For users like me, who installed CMake docset, and it shows CMake 3.29.3 locally, and no hint for "update available" in Zeal (but I saw C/C++ documents update available), just remove CMake docset, then re-install, then CMake 3.29.5 shows.

**Comment by zchrissirhcz** [comment]
I think the mentioned search issue is solved, so I close it now.
