### ISSUE TITLE
I can't find C# 

### ISSUE THREAD

**Issue by mesoelgn** [zealdocs/zeal#1633]
I'm new to Zeal and this is my first time using it, but I can't seem to find C#. What am I doing wrong?

**Comment by trollixx** [comment]
Unfortunately, it was removed from Dash, see #1594.

**Comment by mesoelgn** [comment]
Is there hope for C# to make a comeback?

**Comment by trollixx** [comment]
> Is there hope for C# to make a comeback?

Only if someone creates their own docset. I think all docs are in https://github.com/dotnet/docs. So it should be doable but may take some non-trivial amount of work.
