### ISSUE TITLE
Provide a way to tell cmake whether to use Qt5 or Qt6

### ISSUE THREAD

**Issue by tanriol** [zealdocs/zeal#1647]
As far as I understand, the cmake files just say that it should find "some" Qt, maybe Qt5, maybe Qt6, and depend on the version found by cmake using whatever magic it uses.

That may work badly if there are both, but only one can or should be used. In Gentoo we'd prefer to tell cmake which one should be used to match the package dependencies.

Is there a way to do that more correctly than just patching the Qt5/Qt6 mention out from CMakeLists.txt? Could one be exposed if there's currently none?

**Comment by trollixx** [comment]
I can't test right now but I think passing [`-DQT_DEFAULT_MAJOR_VERSION=<5 or 6>`](https://doc.qt.io/qt-6/cmake-variable-reference.html#qt-default-major-version) to CMake should do the trick. Without this configuration Qt 6 should be picked up if all components (`Concurrent WebEngineWidgets Widgets`) are available.

**Comment by tanriol** [comment]
Does not seem to work this way
```
$ cmake . -DQT_DEFAULT_MAJOR_VERSION=6                                                     
-- The CXX compiler identification is GNU 14.1.1                                                                     
-- Detecting CXX compiler ABI info                                                                                   
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Building unreleased code. Proceed at your own risk!
-- Found Git: /usr/bin/git (found version "2.45.2")
Calculated Zeal version: 0.7.2-dev.23+1067eae380c8
-- Installing in the same prefix as Qt, adopting their path scheme.
CMake Error at /usr/lib64/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by
  "Qt5WebEngineWidgets" with any of the following names:                                                             
                                                                                                                     
    Qt5WebEngineWidgetsConfig.cmake                                                                                                                                                                                                        
    qt5webenginewidgets-config.cmake                   
                                                          
  Add the installation prefix of "Qt5WebEngineWidgets" to CMAKE_PREFIX_PATH
  or set "Qt5WebEngineWidgets_DIR" to a directory containing one of the above
  files.  If "Qt5WebEngineWidgets" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  src/libs/browser/CMakeLists.txt:13 (find_package)
```
My system has core parts of both Qt5 and Qt6, but no longer has QtWebEngine 5 available.
Removing Qt5 from the `find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Core)` line results in a successful build.

**Comment by trollixx** [comment]
@tanriol I've added a new build option to force build against Qt 5, please try `-DZEAL_USER_QT5=ON`.
