### ISSUE TITLE
Java and Python docsets disappeared

### ISSUE THREAD

**Issue by rajabiy** [zealdocs/zeal#1650]
Some Docsets is disappeared from available docsets window. Even I couldn't find them in API https://api.zealdocs.org/v1/docsets

**Comment by wdscxsj** [comment]
Yes, the Java docsets are currently missing.

**Comment by trollixx** [comment]
It's a side effect of how Dash now [lists](https://github.com/Kapeli/feeds/blob/master/Java.xml) different versions of Java. Used to be one docset per major version, not it's just one docset for everything. I'll see if I can do a temporary workaround on the API server side or invest in #208 as that is the proper solution.

**Comment by trollixx** [comment]
I updated metadata to show Java docset again. But until #208 is implemented there's no way to install previous versions.

**Comment by trollixx** [comment]
Closing and pinning it for awareness.
