### ISSUE TITLE
Option to toggle sidebar visibility

### ISSUE THREAD

**Issue by trollixx** [zealdocs/zeal#1652]
### Discussed in https://github.com/orgs/zealdocs/discussions/1596

<div type='discussions-op-text'>

<sup>Originally posted by **stefanos82** January 26, 2024</sup>
When I read a long documenation, the sidebar distracts me.

Is there a way to either hide it or toggle it upon need?</div>

**Comment by trollixx** [comment]
@stefanos82 I added `Ctrl+B` shortcut to toggle visibility. Will be included in v0.7.2, which I will (hopefully) tag in a few days.

**Comment by stefanos82** [comment]
Nice! Let me pull the latest commits to give it a try!

Thank you @trollixx :+1: :100:

**Comment by stefanos82** [comment]
Chef's :kiss: :partying_face:

**Comment by stefanos82** [comment]
Reminder: You either need to add a shortcuts menu in Help menu bar with all shortcuts available or add the sidebar toggle shortcut in Edit; there's no way users to know this newly introduced hotkey actually exists.

**Comment by trollixx** [comment]
> Reminder: You either need to add a shortcuts menu in Help menu bar with all shortcuts available or add the sidebar toggle shortcut in Edit; there's no way users to know this newly introduced hotkey actually exists.

The View menu will come with merging #1266 and #1441. I'll add sidebar visibility option there as well. Might be in v0.7.3 or v0.8.0 depending on the timeline and other changes.
