### ISSUE TITLE
Zeal v0.7.2 crashes on startup

### ISSUE THREAD

**Issue by MrKeanu-V** [zealdocs/zeal#1660]
I installed Zeal v0.7.2 today. When running Zeal, the software will display in the start menu bar for a while, and then it will crash. After I turned off the proxy server, it still crashed when I opened the software. Then I uninstalled version 0.7.2, reinstalled 0.7.0 and finally didn't crash, what is the reason for this? My environment is Win10.

**Comment by trollixx** [comment]
Try this https://github.com/zealdocs/zeal/issues/1658#issuecomment-2351330914

**Comment by trollixx** [comment]
I will assume this is the same issue as #1658.
