### ISSUE TITLE
Zeal 0.7.2 on windows11 crashes on startup

### ISSUE THREAD

**Issue by leang521** [zealdocs/zeal#1662]
我当前的操作系统版本为windows11。之前使用过Zeal 0.7.1没有问题。
当我更新到Zeal 0.7.2版本后，每次打开都会崩溃。
之后我测试过Zeal 0.6.1、Zeal 0.7.0两个版本，也都没问题。所以问题只出现在Zeal 0.7.2这个版本上。

**Comment by trollixx** [comment]
Duplicate of #1658.
