### ISSUE TITLE
v0.7.2 wont launch (win 10)

### ISSUE THREAD

**Issue by CharlieJP05** [zealdocs/zeal#1664]
v0.7.1 does launch but when 0.7.2 is installed it starts and crashes before opening the window

**Comment by Kissaki** [comment]
Launches fine for me on Windows 11 23H2

**Comment by Kissaki** [comment]
Possibly duplicate of #1658

Try installing the VC Redist as mentioned there

**Comment by trollixx** [comment]
Duplicate of #1658.
