### ISSUE TITLE
Enable keywords

### ISSUE THREAD

**Issue by shawngiese** [zealdocs/zeal#167]
In MacOSX Dash, you can enable keywords to quickly focus your searches but, for the same docset, the keywords used in Zeal are different from the keywords used in Dash. It would be great that they used the same keywords.

I am pretty sure it is the DocSetPlatformFamily key in the plist that sets this but I cannot find that documented anywhere. That is what I changed for the keyword to appear in Dash 
https://github.com/jkozera/zeal/issues/new#issue_body_preview_bucketbut it does not seem to work in Zeal.

There seem to be 2 sorts of keywords... 
* one for each docset when you want to search a specific docset only. 
* one for the keyword 

Zeal seems to use the CFBundleIdentifier and CFBundleName and some sort of fuzzy matching where I do not have to identify an entire keyword but just part of it.

**Comment by trollixx** [comment]
The per docset keywords were fixed in #383.

#77 tracks progress on docset groups. There's also #421 for user-defined keywords.
