### ISSUE TITLE
Application terminates showing "zeal has stopped working" while loading zurp Foundation Docs

### ISSUE THREAD

**Issue by sirajulm** [zealdocs/zeal#169]
The Zurp Foundation Documentation was downloaded along with some other Documentations from this link
[http://kapeli.com/docset_links](http://kapeli.com/docset_links)
which provide documentation for Dash, but the Foundation Documenttion is causing the Appplication to terminate due to the following code( the application works normally when the code segment is removed)

    <section id="courses-banner-large">
        <div class="row">
            <div class="large-5 medium-5 columns banner-image">
                <img src="http://foundation.zurb.com/assets/img/responsive-banner-main.svg" alt="responsive design">
            </div>
            <div class="large-7 medium-7 columns banner-info">
                <h3>Get a running start with Foundation</h3>
                <p>Learn the fundamentals of the world's most advanced responsive framework in our <strong>intro to Foundation class.</strong> You'll hear from the creators themselves how to use Foundation to jumpstart your next project. <a href="http://zurb.com/university/courses" class="inline-hide">Learn more about classes »</a></p>
                <a href="http://zurb.com/university/foundation-intro?utm_source=Foundation%20Docs&amp;utm_medium=Large%20Banner&amp;utm_campaign=Intro%20to%20Foundation" class="button">Learn More</a>
                <a href="http://zurb.com/university/courses" class="learn-more hide-for-medium-up">Learn more about classes »</a>
            </div>
        </div>
    </section>

This code segment in the Foundation documentation pages are causing the zeal application to terminate prematurely. The removal of this code segment ensure the proper working of the application. Since this code segment is found in all the 55 html pages, all pages have to be cleaned up to ensure the application will not terminate when the specific page is loaded. The code segment was re-typed to enusure there are no special characters causing the issue, also the " » " symbol was replaced by the &raquo; to ensure html compatibility. But that too couldn't help to solve the problem.

**Comment by trollixx** [comment]
I believe the problem has been fixed. I've checked on Linux and Windows, no issues with Zurb Foundation docset.
