### ISSUE TITLE
Search input box optimisation

### ISSUE THREAD

**Issue by SynCap** [zealdocs/zeal#179]
Q1: In case if much docsets is downloaded, searching in is time eating process, even on fast machines (docs neded during hard work, whether is'nt?).
Very cool to get a request's respond immidiatly, but in dozen docsets it's time hard, becouse each typing is new request.

A1: Start seaching process on time delay in 1-3 seconds. Don't start immidiatly! Lets user took something. Don't take count of chars, just timer.

Q2: Why not to get an option in settings, that can be set 2 mode: fast search (by typing), and laizy - start search when start button (where is it?) clicked or <Enter> pressed? Or may be get a button close to searchbox to switch these modes?

Q3: Why not to clear searchbox in 2 step: after ":"(semicolon), and then before?

All of this, i seems, must improve the usability on large docsets

**Comment by dontdieych** [comment]
Arch Linux
zeal-git 0.0.0.556.09840e8-1

Input field is so blocking. I cannot type keys as usual speed. It must be typed so slowly. Or it screw order of input.

```
input -> ipunt
```

Quite serious problem to me.

**Comment by trollixx** [comment]
Lags during typing are covered by #265.

Regarding Q2, honestly, I don't see a reason to disable the real time search, as long as it's not freezing UI. For me the search is almost always instant, while I have dozens of docsets installed. So, there's a specific setup, that causes such slowdown.

So, for now I am closing this issue. If you believe, that Zeal needs a "search on <kbd>Enter</kbd>" option, for other than performance reasons, please, comment here.
