### ISSUE TITLE
QMenuBar 'nativeMenuBar' option should be disabled.

### ISSUE THREAD

**Issue by jglover** [zealdocs/zeal#180]
The QMenuBar 'menuBar' has its nativeMenuBar property enabled, with this enabled some window managers like cinnamon do not render the toolbar at all. Disabling it and recompiling fixed the issue.

**Comment by trollixx** [comment]
We do not force `nativeMenuBar` option anymore. Letting the platform plugin to decide the correct behaviour.

Closing as a duplicate of #134.
