### ISSUE TITLE
Missing dependencies on fedora 19

### ISSUE THREAD

**Issue by slaweet** [zealdocs/zeal#181]
Please, update the fedora 19 dependencies in the docs (http://zealdocs.org/download.html)
I got these errors when trying to install zeal.
```
Project ERROR: gtk+-2.0 development package not found
```
Solved by installing package `gtk2-devel`
```
In file included from main.cpp:1:0:
mainwindow.h:17:43: fatal error: libappindicator/app-indicator.h: No such file or directory
 #include <libappindicator/app-indicator.h>
```
Solved by installing package `libappindicator-devel`

**Comment by trollixx** [comment]
As of 53afd2b0aa3dc9cd7d65e427cee3c1f2e2fe2edc, `libappindicator` presence is automatically detected. Since Unity is not common on Fedora, there's not need in `libappindicator` support as well.
