### ISSUE TITLE
Conflicting Hot Key

### ISSUE THREAD

**Issue by kiddBubu** [zealdocs/zeal#183]
my zeal hot key is ALT+SPACEBAR, since my last update it hasnt worked and anytime i start zeal it gives me notice of a conflicting hot key. i dont know what the hot key is in the first place

**Comment by trollixx** [comment]
The default hot key binding has been changed in 2503c8af. For now `Alt+Space` is used only on Mac OS X, and `Meta+Z` on other platforms.

**Comment by Akronix** [comment]
I'm on Ubuntu 16.04 and Meta+Z doesn't work for me, I've tried also with Meta+X and It still doesn't work. I had to remap it to Meta+Ctrl+Z which does work.
Maybe Unity is catching the Meta+sth event only for itself? is anybody else experiencing this issue on Ubuntu? How can I check what is catching the event and why zeal doesn't launch?
