### ISSUE TITLE
QEventLoop: Cannot be used without QApplication

### ISSUE THREAD

**Issue by arichiardi** [zealdocs/zeal#184]
When opening zeal from command line (Ubuntu 14.04) I get the following:
```QEventLoop: Cannot be used without QApplication```

I know it looks like a minor issue, but the solution seems simple as well, as per this StackOverflow post:
http://stackoverflow.com/questions/10697107/qeventloop-cannot-be-used-without-qapplication

**Comment by trollixx** [comment]
Cannot reproduce as well. Feel free to reopen if the problem persists.
