### ISSUE TITLE
Zeal window empty: no text, no menus

### ISSUE THREAD

**Issue by cweiske** [zealdocs/zeal#185]
I installed zeal on Ubuntu 14.04 via the [PPA](https://launchpad.net/~jerzy-kozera/+archive/ubuntu/zeal-ppa) and got version  `0.0+1snapshot201406201331+0200-1`.

When starting it, I get the zeal main window without any text, and without menus. The only text I see is when right-clicking the browser pane ("reload").

![screenshot](http://storage8.static.itmages.com/i/14/0804/h_1407150021_2607508_cc5688e359.png)

**Comment by rudijs** [comment]
@k3rni This works well for me and is my preferred solution - thanks!

I'm using xubuntu on 14.04
