### ISSUE TITLE
RFC docset has no title and icon

### ISSUE THREAD

**Issue by cweiske** [zealdocs/zeal#186]
Installing the RFC docset from https://willnorris.com/2014/03/rfcs-for-dash-app via options -> docsets -> add feed `dash-feed://https%3A%2F%2Fraw.githubusercontent.com%2Fwillnorris%2Frfcdash%2Fmaster%2FRFCs.xml` gives me the guid as docset name: `e61c42d8-eea9-11....`.

This uuid is shown in the tree view docset list and the docset list in the options.
Also, there is no tree and no icon shown.

**Comment by willnorris** [comment]
I'm finally getting around to fixing this upstream.  Does zeal really require that the icon be in the `Contents/Resources/Documents` directory?  According to [Dash's docs](https://kapeli.com/docsets#addingicon), it expects it to be in `<docset name>.docset/icon.png`.  It'd be great if zeal could just read it from there as well.

Also, what size does zeal expect it to be?  Judging by b4fcfb7abdee5ca55e2295d9cd41c738dbb2e093, I'm guessing 32px?  (which would be consistent with Dash also)

**Comment by trollixx** [comment]
@willnorris Zeal expects 16x16 icon in `icon.png` and 32x32 in `icon@2x.png` for high resolution screens. That should be consistent with Dash.
