### ISSUE TITLE
Some doc in my win7 displays the unkown characters,what's wrong with it?

### ISSUE THREAD

**Issue by yokosogithub** [zealdocs/zeal#192]
This is my screenshot:
[link](https://drive.google.com/file/d/0B-4WgkgCPhA3Uk5sbFBLYWJWQUk/edit?usp=sharing)

**Comment by trollixx** [comment]
Looks like a rendering problem. Can you verify if the problem still exists in the [recent builds](https://bitbucket.org/jerzykozera/zeal-win32-binary-downloads/downloads)?

**Comment by trollixx** [comment]
Closing because of no feedback. Please reopen if problem persists.
