### ISSUE TITLE
openSUSE serious compiler warnings

### ISSUE THREAD

**Issue by DAP-DarkneSS** [zealdocs/zeal#196]
[   35s] ... running 02-check-gcc-output
[   35s] ... testing for serious compiler warnings
[   35s]     (using /usr/lib/build/checks-data/check_gcc_output)
[   35s]     (using /var/tmp/build-root/openSUSE_13.1-x86_64/.build.log)
[   35s] 
[   35s] I: Program returns random data in a function
[   35s] E: zeal no-return-in-nonvoid-function zealdocsetsregistry.cpp:87
[   35s] 
[   35s] I: Program returns random data in a function
[   35s] E: zeal no-return-in-nonvoid-function zealdocsetsregistry.cpp:87

**Comment by jkozera** [comment]
@DAP-DarkneSS can you please add libQT5Sql5-sqlite as a dependency? Seems it's missing, as per #248. Thanks!

**Comment by DAP-DarkneSS** [comment]
OK, let https://build.opensuse.org/request/show/280453 become approved.

**Comment by DAP-DarkneSS** [comment]
And the subject should be closed.
