### ISSUE TITLE
Hope to have an ordinary version number instead of '20140215'

### ISSUE THREAD

**Issue by spacewander** [zealdocs/zeal#203]
I suggest to use an ordinary version number like 'x.y.z' instead of using '20140215'.
Because:

1. using 'x.y.z' is more clear than '20140215', especially when we talk about the binary distribution.
2. since the current version of zeal is very different from one in Feb 15th, 2014.
3. using 'x.y.z', we can make the change log more clear, and more reasonable.

**Comment by jkozera** [comment]
@spacewander not resolved - reopening

**Comment by spacewander** [comment]
@jkozera I am sorry... I should close it after asking others' advice. I am very sorry about my impertinence.

**Comment by jkozera** [comment]
@spacewander don't worry, we all make mistakes, and it's good to close outdated issues. :) If you want do discuss anything, or perhaps just chat in general, please come to #zeal @ freenode IRC, we have some discussion going on there.

**Comment by trollixx** [comment]
Fixed with [0.1.0](https://github.com/zealdocs/zeal/releases/tag/v0.1.0) release.

**Comment by spacewander** [comment]
:+1:
