### ISSUE TITLE
deb package dependencies issue.

### ISSUE THREAD

**Issue by abcfy2** [zealdocs/zeal#206]
I use deepin 2014, which bundle with qt 5.3.

But the dependencies of deb package about qt is 5.2.

I think you should set qt version >= 5.2, not =5.2

**Comment by jalcine** [comment]
The block in the Qt project file only checks if it's less than 5.2 but doesn't set a hard dependency to be only at 5.2. What version does `qmake` report?

**Comment by trollixx** [comment]
This report is from 2014. We only provide a PPA repository for Ubuntu nowadays.

Zeal can be built with any Qt version >= 5.2. The minimal dependency will raise to Qt 5.6 once it comes out soon.
