### ISSUE TITLE
Missing meta for java and spring framework.Update or Reinstall them not working

### ISSUE THREAD

**Issue by xuelvming** [zealdocs/zeal#207]
Just like the title's suggestion, I can download those two document, but they lack the meta file. update or reinstall also can't solve the issue.
Hope you guys can fix it for us. I enjoy this software very much. Thanks.

**Comment by trollixx** [comment]
I tested all Java and Spring Framework docsets and couldn't reproduce the problem. Closing for now, but feel free to reopen, if you encounter the issue again.
