### ISSUE TITLE
Zeal doesn't display any menus - no way to get docsets!

### ISSUE THREAD

**Issue by feoh** [zealdocs/zeal#213]
KUbuntu 14.04.1

Since there is no Edit or other menu, I can't figure out how to get new docsets.

![image](https://cloud.githubusercontent.com/assets/330070/4852908/9bcd7f64-6080-11e4-9188-f5bf2c71d812.png)

**Comment by trollixx** [comment]
Closing as a duplicate of #185 and #134.
