### ISSUE TITLE
release 20141104 crash during download .net docset

### ISSUE THREAD

**Issue by ystannly** [zealdocs/zeal#222]
it stopped work and force to close.

![image](https://cloud.githubusercontent.com/assets/9417249/5025081/e1fb1b26-6b4e-11e4-9a7b-f35da145697f.png)

**Comment by JIghtuse** [comment]
Probably Windows-only problem. Tried it on Debian GNU/Linux, downloaded/unpacked fine.

**Comment by RobertinoValue** [comment]
It must be.
Because I also use Debian (CrunchBang and Jessie) and there are no problems there.

**Comment by trollixx** [comment]
I couldn't reproduce the problem with the recent master build on either Linux or Windows. I guess the problem has been fixed at some point. Feel free to reopen if crash still occurs after b054e4c76b12e5540397bf0d29e0eee610364c38.
