### ISSUE TITLE
New version 2014110 very slow, bugs with UI and font, unusable

### ISSUE THREAD

**Issue by anephew** [zealdocs/zeal#223]
Hello! New version 20141104 unusable. 

1) Hangs for 10 sec when selecting article... 

2) Have bug with UI and font.. What font you are using? I want to use my system font, for example Sergoe. Unable to read what I see now.   Win 7 64

![zeal](https://cloud.githubusercontent.com/assets/551514/5036006/25ba003c-6b8d-11e4-8a88-59c6813ec79b.png)

3) How to close tabs? I think needs closing "X" icon

I think the program needs optimization and redesign. Please, fix this main issues.
Stay on the previous version.Thank you

**Comment by jkozera** [comment]
The slowness could be a similar issue to #221.

**Comment by trollixx** [comment]
1. Should be fixed together with #221.

2. Most docsets bundle their own styles. Perhaps, Zeal needs configuration options for default fonts similar to browsers. User defined CSS file could be another option.

3. `Ctrl+W` and close button are now in place. Middle button click would be a nice addition.
