### ISSUE TITLE
Chocolatey Package with Zeal

### ISSUE THREAD

**Issue by cellx** [zealdocs/zeal#236]
Hello Jerzy Kozera,

first I would like to congratulate for developing this Zeal with the inspiration of Dash. I prefer use it for offline docs.

So I support your application and just pack a package for Windows "apt-get"-Clone Chocolatey with the Zeal version 20140620. 

You could find it on: https://chocolatey.org/packages/zeal 

Please feel free to test it. For the installation on your Windows you should have installed the chocolatey tool, more information on https://chocolatey.org/

With the version number 20140620 I have to change it to 1.0.20140620. Which number it should have for the next versions? 1.0.20141126 (zeal-github-shippable-20141126054732.zip) or?

I will try to change my package with newer version in next days.

You could see my Chocolatey/Zeal repository on: https://github.com/cellx/chocolatey-packages

Any comments would be highly appreciated.

Sincerely,
Kilian

**Comment by trollixx** [comment]
I am closing this in favour of #246. We need a proper versioning and we'll have it soon.
