### ISSUE TITLE
Zeal crashes on open: symbol lookup error

### ISSUE THREAD

**Issue by 1egoman** [zealdocs/zeal#240]
I'm running Ubuntu 12.04.

I ran these commands all as root:
```bash
add-apt-repository ppa:jerzy-kozera/zeal-ppa
add-apt-repository ppa:ubuntu-sdk-team/ppa
apt-get update
apt-get install zeal
```

and when running `zeal` from the terminal:
```bash
ubuntu@ubuntu:~$ zeal
zeal: symbol lookup error: zeal: undefined symbol: _ZZZN21Ui_ZealSettingsDialog7setupUiEP7�DialogE�KUlvE22_clEvE15qstring_literal
```

Any idea what's happening?

**Comment by trollixx** [comment]
Zeal version for Ubuntu 12.04 in the PPA is almost one year old, it's hard to tell what's wrong with it.

We've dropped support for Qt below 5.2 (which is not in `ubuntu-sdk-team/ppa`). As the result, we do not support Ubuntu 12.04 anymore. At least unless there's a reliable source of Qt 5.2+ packages for that Ubuntu release.
