### ISSUE TITLE
Will anyone offer me a 'open a new tab' icon?

### ISSUE THREAD

**Issue by spacewander** [zealdocs/zeal#242]
I am planning to add 'click to open a new tab' feature at this weekend.
Currently, my idea is **to add a  rightmost tab on the tabbar, which contains a 'create new tab' icon**. So that users can click the tab and open a new tab, just like what they are doing with Chrome or Firefox.

Now, there is a request, will anyone offer me **a pretty icon**, which represents 'create new tab'?

**Comment by jalcine** [comment]
Have you checked out the icomoon or noun projects icon sets? Most are free for non-commerical use.

**Comment by trollixx** [comment]
Zeal should rely on system icons. A fallback icon set would be nice, but is not a priority.
