### ISSUE TITLE
Incorrect docset order

### ISSUE THREAD

**Issue by stevenfrog** [zealdocs/zeal#244]
The docs are not in order.

![screenshot from 2014-12-28 18 41 33](https://cloud.githubusercontent.com/assets/1052002/5563655/c5521326-8ec1-11e4-8008-c5f43c387a8e.png)

If I add "jquery" at last, it will be in last, I hope we can see docs in order.

**Comment by stevenfrog** [comment]
I still hope you add this feature:
"Order just as character ignore case sensitive", or "user can change the docset name"

**Comment by jkozera** [comment]
@spacewander please try to avoid closing issues that are not completely resolved - reopening.

**Comment by smarter** [comment]
I think it'd be great if we could control the order of the docsets. I have two docsets installed, Scala and Java, my primary language is Scala but when I search for `List` I end up in the Java documentation because of the ordering.

**Comment by ssokolow** [comment]
To make sure nobody forgets while fixing the left pane, I'll just mention that this also applies to the "Downloadable docsets" and "Installed docsets" lists in the options dialog.
