### ISSUE TITLE
[pref] Allow us to "quit on close"

### ISSUE THREAD

**Issue by blag001** [zealdocs/zeal#245]
Hello, 
I use Zeal on ubuntu/unity, and I can't open back Zeal when I close it with the close button / *atl+F4*.
I don't want to use the Hot Key and don't want ghost software as back task, I use the unity dash when I want to run Zeal.

Can you add a "quit on close" option ? cause for now I need to kill the process every-time I forget to use the *ctrl+q*...

Thanks
blag

**Comment by spacewander** [comment]
Currently You can use `File > Quit` to quit Zeal if you don't like it running in background.
We will consider to add  "quit on close" option sooner if possible.

**Comment by blag001** [comment]
Thx for the reply.
yes, for now i use the `File>Quit` or the *ctrl+q*, but the *Alt+F4* is not something you can change easily XD
Thanks to consider this feature !

**Comment by jkozera** [comment]
We probably should always 'quit on close' if the tray icon ('hiding behavior = system tray') is not enabled, because when the tray icon is missing, there is indeed no proper way to quit the app after closing the window.

**Comment by trollixx** [comment]
That was implemented as part of the new system tray settings. Now Zeal always exits on window close, unless the system tray icon is enabled and the option `Hide to system tray on window close` is set.

**Comment by blag001** [comment]
ok, thanks a lot ;)
