### ISSUE TITLE
dash:// url scheme support on Windows

### ISSUE THREAD

**Issue by WoLpH** [zealdocs/zeal#247]
Mostly due to the lack of an installer on Windows there is no easy way to open Zeal right now. Because of this the Intellij plugin cannot properly support Zeal on Windows right now (relevant discussion: https://github.com/gdelmas/IntelliJDashPlugin/issues/36#issuecomment-69078880)

Here's an example of a Windows register file to support Zeal:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\dash]
@="Zeal Search (Dash Protocol)"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\dash\DefaultIcon]
@="C:\\Program Files (x86)\\Zeal\\Zeal.exe,1"

[HKEY_CLASSES_ROOT\dash\shell]

[HKEY_CLASSES_ROOT\dash\shell\open]

[HKEY_CLASSES_ROOT\dash\shell\open\command]
@="\"C:\\Program Files (x86)\\Zeal\\Zeal.exe\" --query \"%1\""

[HKEY_CLASSES_ROOT\dash-plugin]
@="Zeal Search (Dash Plugin Protocol)"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\dash-plugin\DefaultIcon]
@="C:\\Program Files (x86)\\Zeal\\Zeal.exe,1"

[HKEY_CLASSES_ROOT\dash-plugin\shell]

[HKEY_CLASSES_ROOT\dash-plugin\shell\open]

[HKEY_CLASSES_ROOT\dash-plugin\shell\open\command]
@="\"C:\\Program Files (x86)\\Zeal\\Zeal.exe\" --query \"%1\""
```

**Comment by trollixx** [comment]
We definetely need this, thanks! I will try setup a Windows environment and implement it.

**Comment by gdelmas** [comment]
please do NOT use dash:// scheme. it was the old way how plugins used to call dash and does not support multiple docsets. multiple docset filters is an integral part for good search results. zeal added support for this lately. of course it is possible to add dash:// scheme additionally to support other older plugins.

see: https://github.com/gdelmas/IntelliJDashPlugin/issues/36#issuecomment-69120565

**Comment by trollixx** [comment]
Now Zeal registers for `dash:` and `dash-plugin:` protocols. Zeal does not overwrites existing association, unless run with `--register` parameter. Similar `--unregister` parameter allows to remove protocol association. These options are especially convenient for use with installers.

In addition Windows 8 requires more work for a proper integration with the system, see #278.
