### ISSUE TITLE
Issue with query on OpenSUSE 13.2

### ISSUE THREAD

**Issue by Anatzum** [zealdocs/zeal#248]
In the GUI I am unable to search any of the docs I have downloaded. It works fine on my Ubuntu laptop just not in OpenSUSE. When I try and query via the command line I get the following error. "QEventLoop: Cannot be used without QApplication". I also get the following errors when starting zeal from the commandline. "QSqlDatabase: QSQLITE driver not loaded", "QSqlDatabase: available drivers: QMYSQL QMYSQL3", "QSqlQuery::exec: database not open"

**Comment by Anatzum** [comment]
I managed to fix this error. If anyone gets any of these warnings its because the libQT5Sql5-sqlite package is not installed by default in openSUSE 13.2. I quck trip to the yast software management will fix this this issue.

**Comment by DAP-DarkneSS** [comment]
OK, let https://build.opensuse.org/request/show/280453 become approved.
