### ISSUE TITLE
installing some docsets fails

### ISSUE THREAD

**Issue by schlamar** [zealdocs/zeal#250]
Some docsets, e.g. Python 2, cannot be installed. They looks as follows after download.

![unbenannt](https://cloud.githubusercontent.com/assets/238652/5680710/4dd04d14-9811-11e4-8623-28071dee0e8a.PNG)

After restart, they are completely gone.

**Comment by trollixx** [comment]
I cannot reproduce the problem. Could you verify it still occurs with the latest build from [here](https://bitbucket.org/jerzykozera/zeal-win32-binary-downloads/downloads)?

**Comment by schlamar** [comment]
This error still exists in the version from today (20150112054614).

I guess there is something wrong in your HTTP implementation because my proxy does some weird stuff: it downloads the file internally and checks for viruses before it forwards the file. During the download and scan it just sends some bytes every few seconds so the download doesn't get stalled. I assume you are closing the HTTP connection before you have received `Content-Length` bytes.

Please note, the proxy behavior is standard HTTP. Other HTTP implementations can handle this gracefully (curl, Python's requests, Java as Jenkins Auto Updater, ...).

**Comment by schlamar** [comment]
I just debugged this with PyQt (as you are using Qt's HTTP implementation):

If you start a download with a browser the proxy does a 307 redirect to a page showing the download progress. If you don't set a user agent, the proxy still assumes a browser HTTP client. So the simple solution is to set a custom user agent in the request header. So something like `req.setRawHeader("User-Agent", "Zeal 20150112054614")` at https://github.com/zealdocs/zeal/blob/b1005c32deef0c4f10e223ac1c8c5e62fa0e0aef/src/ui/settingsdialog.cpp#L601 should fix it.
