### ISSUE TITLE
[FEATURE REQUEST] - Make Doc-Set icons customizeable

### ISSUE THREAD

**Issue by zuernBernhard** [zealdocs/zeal#251]
How can the Doc-Set-Icons be customized ? If you have the docsets for Drupal 7 and Drupal 8 you have to select every search result item to check which of the two docsets it belongs to. 

Deactivating the other docset is a bad solution when you do a migration from Drupal 7 to Drupal 8 ;)

**Comment by trollixx** [comment]
The icons are coming from [Dash](http://kapeli.com/docset_links). You can simply replace any icon in `/usr/share/pixmaps/zeal` on Linux or `icons` subdirectory within Zeal executable directory on Windows.

**Comment by trollixx** [comment]
An icon placed within the docset directory should override the default one from [Dash](https://github.com/Kapeli/Dash-X-Platform-Resources/).

P.S. In that particular case (Drupal 7 and 8), perhaps @Kapeli could come up with two different icons? Like Drupal logo with a number in the corner or something else...

**Comment by zuernBernhard** [comment]
Thank you very much !!

**Comment by wosc** [comment]
Hm, when I put an `icon.png` into a docset folder, it has no effect; however putting a properly named png-file into `/usr/share/pixmaps/zeal` works.

**Comment by trollixx** [comment]
Oh, I guess I wasn't clear in my comment. I meant, that it _should_, but not already _does_ that. It was just a note to myself, that is why the issue hasn't been closed.

Sorry for the misleading comment.

**Comment by wosc** [comment]
No worries :) and do let me know if I can do something to help out.
