### ISSUE TITLE
menu is missing for Ubuntu 14.04 Gnome users.  Need to add solution to document.

### ISSUE THREAD

**Issue by sg552** [zealdocs/zeal#253]
Hi , 

  I found that many ubuntu guys meet this problem:  menu is missing under ubuntu 14.04 when using Gnome ( not the default Unity ). 
  The solution is quite simple: `$ sudo apt-get remove appmenu-qt5`
  but googling for this bug costs time. 

  So, please add this tip to the official site's Usage page. ( http://zealdocs.org/usage.html ) 

thanks 
Siwei

**Comment by ChuckDaniels87** [comment]
Thanks for this tip ;)

**Comment by henryfour** [comment]
@sg552 Thanks for your tips!

**Comment by trollixx** [comment]
Launchpad bug [#1307619](https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/).

**Comment by trollixx** [comment]
I have added (zealdocs/zealdocs.github.io@efddce4dbb4a1e7d5c0011a67b8c0bfb621db1fc) a warning notice in our [download](http://zealdocs.org/download.html#linux-ubuntu) page. I hope it is visible enough for our new users.

**Comment by sg552** [comment]
@trollixx   great, thanks!

**Comment by trollixx** [comment]
People keep running into this issue all the time, I wonder if there's an easy way to detect when menu bar is invisible...
