### ISSUE TITLE
The UI freeze when selecting article on windows platform

### ISSUE THREAD

**Issue by SongJoey** [zealdocs/zeal#258]
I think the problem is like #221 but not sure.

it's introduced from 1/12/2015 ~ now( I believe so), I'm using windows so I rolled back to the version of 1/7/2015.

how to reproduce
1. install the latest version
2. click the css docset ( especially when open this one, others also have this problem but not too obvious)
3. interface freeze and can't click or response anymore.

it seems that no one reported this problem, so I guess it might be ok on some other platforms.

**Comment by NoAnyLove** [comment]
The CSS docset works fine on my computer, but the Android docset freeze and don't reponse (showing Not Responding) for seconds on my computer.

I'm using Win 8.1 x64 and Zeal 20141123
