### ISSUE TITLE
Documentation Support for Mac OS X

### ISSUE THREAD

**Issue by sahilbabbar** [zealdocs/zeal#263]
There is no documentation and support for Mac OS X contributors.

**Comment by trollixx** [comment]
Hi. Zeal's primary platforms are Linux and Windows. You could try to build Zeal for Mac OS X, but it is not guaranteed to work. It's recommended to use [Dash](http://kapeli.com/dash) for Mac OS X.

I am not sure if we can provide Mac OS X related documentation. AFAIK, Dash uses docsets from X Code. Though, I'll check out if there's a way to bring Max OS X or iOS docsets to Zeal.

**Comment by autosquid** [comment]
how is this work going? expecting this feature.

**Comment by trollixx** [comment]
Some OS X and iOS docsets are available in Zeal, but no support for running Zeal on OS X will be implemented. Dash is a great tool for OS X based developers.

**Comment by marnen** [comment]
@trollixx Please reconsider this. Zeal has the advantage over Dash of being OSS. It seems strange for an OSS project to say "we won't support this on Mac OS because a non-OSS solution already exists".

**Comment by trollixx** [comment]
@marnen Please see #24. Zeal has no value without all the documentation it has access to. Currently Zeal users are enjoying almost 200 docsets from Dash in exchange for no OS X builds.

If someone is ready to commit their time and provide all docsets, then great, let's talk about it. But one should understand, that would be a full-time job with no pay.

You can still [build](https://github.com/zealdocs/zeal/wiki/Build-Instructions-for-OS-X) Zeal on OS X yourself, but do not assume any level of support. It might break anytime. I don't even have any OS X devices.

**Comment by serg060606** [comment]
Sorry for possible silly suggestion and Zeal works well thru Wine. If some1 would like use it as I do.
[http://saveimg.ru/pictures/27-04-17/507209d3cee5d2df4a83c6cfb805d910.png](url)

Regards
(c)

**Comment by trollixx** [comment]
@serg060606 lol, enjoy! :)

**Comment by marnen** [comment]
One word: BitKeeper. :)

(I've managed to sidestep this altogether by using devdocs.io.)

**Comment by xuhdev** [comment]
@marnen Did you really understand the issue here? It's not the Zeal team that does not want to support MacOS; it's the deal with Dash for their docset. If Zeal supports MacOS, the deal would end and Zeal would be in danger, and still no MacOS support will be available. Unless we can create docsets ourselves, there is no other way to workaround that deal.

**Comment by Gutem** [comment]
@marnen https://github.com/egoist/devdocs-desktop
