### ISSUE TITLE
Installing icons and binaries fails in case of %{buildroot}

### ISSUE THREAD

**Issue by phracek** [zealdocs/zeal#266]
I would like to ask you If you can add buildroot directive to zeal.pro file.

I am trying to package zeal to Fedora 21.
But If I specify buildroot then it is always installed under /usr/share/icons/... instead of %{buildroot}/usr/share/icons.... And of course build fails.

**Comment by trollixx** [comment]
I guess you need `INSTALL_ROOT` option for `make install`:

```bash
make INSTALL_ROOT=<BUILDROOT> install
```

Let me know if that helps.

**Comment by phracek** [comment]
Yes, thanks. INSTALL_ROOT the right variable.

**Comment by phracek** [comment]
Thanks for fixing. Do you have any github commit?

**Comment by trollixx** [comment]
I haven't done anything, that's a built-in qmake functionality. Not well-documented though.

**Comment by phracek** [comment]
I have created a fix for this issue. See pull request https://github.com/zealdocs/zeal/pull/270

**Comment by trollixx** [comment]
Hi, 

I've added a more standard `PREFIX` behaviour in 991d3f80e6fb454df66d887d8419a0dd9f7eea48. I hope it solves your problem.

`PREFIX_USR_SHARE` from #270 doesn't make much sense, because it should respect `PREFIX`.
