### ISSUE TITLE
Default browser font configuration

### ISSUE THREAD

**Issue by trollixx** [zealdocs/zeal#269]
Zeal should provide default font settings similar to browsers.

**Comment by FichteFoll** [comment]
pls halp

![kill it with fire](https://x0.at/yfG.png)

**Comment by trollixx** [comment]
The last screenshot looks so funny, I think we should reclassify this into
a feature.

On a serious note, I am slowly working on switching to the updated Qt
WebKit in our CI builds.

**Comment by FichteFoll** [comment]
You'll think about it differently after you worked with it for almost a week, trust me.
