### ISSUE TITLE
Include LICENSE file into releases

### ISSUE THREAD

**Issue by phracek** [zealdocs/zeal#271]
I would be glad If you can include
LICENSE file to ZIP file.
LICENSE file for GPLv3 can be found here http://www.gnu.org/copyleft/gpl.html if zeal is opensource

**Comment by trollixx** [comment]
Zeal is open source.

Our ZIP downloads are not really releases, but you are right about missing licence information.

**Comment by phracek** [comment]
I have packaged zeal in Fedora via COPR. http://copr-fe.cloud.fedoraproject.org/coprs/phracek/zeal/
