### ISSUE TITLE
Can increase the function directly read from *.tgz file, without the need to unzip all the files.

### ISSUE THREAD

**Issue by zjzdy** [zealdocs/zeal#273]
Can increase the function directly read from *.tgz file, without the need to unzip all the files. 
Because the *.tgz file decompression after take up more space. 
Like NET_Framework.tgz,NET_Framework.tgz is 473 MB,but NET Framework.docset floder is 2.31 GB.
You can extract the first dsidx, plist, json, xml and so on files, but Contents\Resources\Documents directory doesn't decompression. When needed, temporary decompression again. A bit like a CHM and zim file. 
This can greatly reduce the disk overhead, although a bit slow speed. 
This can be a optional that default off, but hard disk space tension user can to be choose on.
Of course. If can support other compressed file format is better. I think the xz format better than tgz format, so I want to convert tgz format to xz format, if you can.

**Comment by trollixx** [comment]
Please see #138.
