### ISSUE TITLE
Browser problem in Bootsrap 3

### ISSUE THREAD

**Issue by Nuruddinjr** [zealdocs/zeal#276]
Bootstrap 3 showing following errror on Zeal (Linux): 

Attention!
Looks like your current browser doesn't support the Bootstrap Customizer. Please take a second to upgrade to a more modern browser (other than Safari). 

How to fix it ?

**Comment by trollixx** [comment]
It looks like [check](https://github.com/twbs/bootstrap/blob/master/docs/assets/js/src/customizer.js#L482) for `blob:` protocol fails. According WebKit bug tracker it should work ([bug 121681](https://bugs.webkit.org/show_bug.cgi?id=121681)).

Anyway, what is the reason to use Bootstrap Customizer in Zeal?

The customizer creates a Gist, and then tries to download it as a ZIP-archive. Zeal doesn't support accessing non-local resources.

**Comment by Nuruddinjr** [comment]
I was reading bootstrap documentation on Zeal and found this -customizing part not working, thanks for quick response,  i wanted to find some variables there ..

**Comment by trollixx** [comment]
I think any work to make customizer work would contradict Zeal's agenda - documentation browser.

Closing this issue for now, but I am open to any arguments against my decision.
