### ISSUE TITLE
Windows Installer

### ISSUE THREAD

**Issue by trollixx** [zealdocs/zeal#279]
Looks like [WiX Toolset](http://wixtoolset.org/) is the way to go.

**Comment by manikantag** [comment]
Is installer necessary? Portable version is fine, isn't it?

**Comment by trollixx** [comment]
I think many users would like a properly installable software. Installer would also provide automatic registration of protocol handlers.

A portable version is a little bit different: it saves docsets in a directory with the application binary and uses .ini file for storing settings instead of Windows registry.

**Comment by manikantag** [comment]
Hmmm! I feel it's the reverse way as most want tools to be as portable as possible. Is there any specific advantages using registry entries over ini file? I m using othe portable tools, even with auto update capabilites.

Problem with using registry is I'll have to configure the tool settings across different computers *(it is quite these days we'll work with more than 1 computer)*.

**Comment by trollixx** [comment]
I guess everyone should be happy as long as we have both options available.

Honestly, I don't know much about Windows ecosystem nowadays, as I haven't been using it for about ten years. Even now I only test some features or catch bugs, but even our CI builds are produced using WINE :)

The use of Windows registry is just the default way provided by Qt. That's why I've added a designated build option, to make Zeal friendly to portable use scenarios.

Perhaps, later I'll add a configuration option for end users to choose how they want their settings stored.

Also, for people desiring to keep multiple Zeal installations in sync, there's a plan to provide a server-side synchronisation service.

**Comment by manikantag** [comment]
Fair enough. Thanks.

**Comment by jkozera** [comment]
Initial implementation is now available at https://github.com/zealdocs/zeal-packaging/tree/master/windows-wix

**Comment by sapioit** [comment]
Can't wait for the portable version for windows, however...
