### ISSUE TITLE
about docset and terms icon

### ISSUE THREAD

**Issue by wjljack** [zealdocs/zeal#291]
in recent update,i found that the docset and search terms list icons was disappeared,Is that by intension? to speed up searching or something else?

**Comment by trollixx** [comment]
Docset icons are now obtained from the server. So, if you had docsets installed, and updated Zeal, then your such docsets would miss icons. Simply download docsets again, and icons will return.

And I'll check about what has happened with symbol icons right away.

Thanks for reporting the problem!
