### ISSUE TITLE
dash-query protocol does not decode URIs

### ISSUE THREAD

**Issue by lowjoel** [zealdocs/zeal#292]
I'm trying a Shippable build.

Running Zeal with a query does not convert URI-encoded sequences, e.g. 'maintain_test_schema%21' should be converted to 'maintain_test_schema!'

**Comment by trollixx** [comment]
Please not that I haven't added decoding for `--query <...>` parameter, but only to queries passed as positional arguments (`zeal <search text...>`). Support for `--query` parameter will be removed in the future version 0.2.0.

**Comment by lowjoel** [comment]
I think that's fine, so long the application registers the correct command line parameters when `zeal --register` is used.
