### ISSUE TITLE
kapeli.com/docset_links not needed anymore?

### ISSUE THREAD

**Issue by Kapeli** [zealdocs/zeal#294]
As far as I can tell Zeal doesn't use it anymore, so is it safe to delete the [kapeli.com/docset_links](http://kapeli.com/docset_links) page?

**Comment by trollixx** [comment]
Hi Bogdan,

Yes, now Zeal relies on your [feeds](/Kapeli/feeds) repository, which is preprocessed by our API server.

So, that page can be removed. But could you wait a little bit until I make a new release of Zeal? Right now the last "official" release is from November 2014 and still uses your docset_links page.

**Comment by Kapeli** [comment]
Understood. I'm redesigning my website and the new version should be released sometime next week. I'll make sure to maintain the old structure.

**Comment by trollixx** [comment]
Thanks! I'll let you know when Zeal will no longer need that page.

**Comment by Kapeli** [comment]
@trollixx I completely forgot about this. Is it safe to assume the page is no longer needed now?

**Comment by trollixx** [comment]
@Kapeli, correct, we don't use that page for a very long time.
