### ISSUE TITLE
Segment Fault : close tab during searching

### ISSUE THREAD

**Issue by Alkaid-Benetnash** [zealdocs/zeal#295]
### System Information
+  Operating System: Archlinux 3.19.2-1-ARCH
+  core/**libarchive 3.1.2-8**
+  extra/**qt5-webkit 5.4.1-2**
+  local/**zeal-git 0.0.0.801.4bbffad-1**  <sub>from AUR</sub>

### Description

1.  Open zeal & download C docset
2.  search "scanf"
3.  click the first result
4.  close this tab
5.  zeal crash

### Information From *dmesg*

segfault at 18 ip 00007f13824d27b3 sp 00007ffce4f2db58 error 4 in libQt5Core.so.5.4.1[7f138239c000+4c1000]

### Please fix it

**Comment by trollixx** [comment]
Thanks for reporting!
