### ISSUE TITLE
No downloadable docsets found

### ISSUE THREAD

**Issue by barbuslex** [zealdocs/zeal#296]
Hi,

When i try to download docsets i get this error : 
http://imageswl.fr/i/BECHBJACADM

Can you help me please ?

Thanks

**Comment by pjimenezmateo** [comment]
I am getting the exact same error, could anyone look into it?

**Comment by Kapeli** [comment]
@trollixx This might be because my new website is live and it redirects `http://` links to `https://`. Should I disable this for the `docset_links` page?

**Comment by trollixx** [comment]
@Kapeli, old Zeal cannot follow redirects the docset list, so if you could temporarily disable HTTPS for that page, that would make current Zeal release work again.

@barbuslex, prebuilt development version of Zeal are available from [here](https://bitbucket.org/zealdocs/zeal-win32-binary-downloads/downloads).

**Comment by Kapeli** [comment]
Great. I've disabled the HTTPS redirect for http://kapeli.com/docset_links. Sorry for the inconvenience!

**Comment by barbuslex** [comment]
Work fine ! Thanks !
