### ISSUE TITLE
Built from source on Fedora 21; crashes on startup

### ISSUE THREAD

**Issue by lpar** [zealdocs/zeal#298]
Currently running Fedora 21 and Xfce. Installed the necessary Qt5 packages, successfully built a binary. However:

    % bin/zeal 
    libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
    Cannot mix incompatible Qt library (version 0x50400) with this library (version 0x50401)
    zsh: abort (core dumped)  bin/zeal

Any ideas how I could help track down the cause?

A working Linux binary for download would be really helpful.

**Comment by trollixx** [comment]
I believe you have not updated all Qt packages in your system (some are 5.4.1 and others are 5.4.0). You need to verify that all Qt packages have the same version.

**Comment by lpar** [comment]
The rest upgraded next time I did `yum update`, and I rebuilt the code and it now works. Thanks.
