### ISSUE TITLE
Failed to install zeal via ppa (Ubuntu 14.04.2)

### ISSUE THREAD

**Issue by yogex** [zealdocs/zeal#299]
Hi,

I got broken package issue when installing zeal via ppa. I have followed the steps mentioned in [Zeal's website](http://zealdocs.org/download.html) 

I'm running Ubuntu 14.04.2

     yogex@ubuntu:~$ lsb_release -a
     No LSB modules are available.
     Distributor ID:	Ubuntu
     Description:	Ubuntu 14.04.2 LTS
     Release:	14.04
     Codename:	trusty

The following is the error when installing:

    yogex@ubuntu:~$ sudo apt-get install zeal
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming. The following information may help to resolve the situation:

    The following packages have unmet dependencies:
    zeal : Depends: bsdtar but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.

I tried to install bsdtar manually via apt-get and I got this error:

    yogex@ubuntu:~$ sudo apt-get install bsdtar
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
    bsdtar : Depends: libarchive13 (= 3.1.2-7ubuntu2) but 3.1.2-7ubuntu2.1 is to be installed
    E: Unable to correct problems, you have held broken packages.

Could you assist me in resolving this? Is there anything that I miss?

**Comment by trollixx** [comment]
It looks like there was a problem with the Ubuntu repositories. `bsdtar` was older than `libarchive13`. But [now](http://packages.ubuntu.com/trusty/bsdtar) all dependencies seem to be consistent. Just update all repositories and try again.

**Comment by yogex** [comment]
Hi,

I tried to update the repositories and the issue's still occuring. Is there any way I can verify and fix my ubuntu packages?

**Comment by yogex** [comment]
Somehow my repo keep resolving the old bsdtar that referencing older libarchive13. I have resolved bsdtar package issue by manually installing the newer version 3.1.2-7ubuntu2.1 and then the installation works like a charm. Thank you.
