### ISSUE TITLE
Blank screen on Ubuntu 14.04

### ISSUE THREAD

**Issue by RasmusWL** [zealdocs/zeal#300]
Wanted to try this out, but is stuck with a blank screen

![screenshot](http://i.imgur.com/SHrXKhK.png)

Right clicking on the systray only gives me an option to quit.

I'm using i3 as my window manager (v 4.7.2)

Version installed (via ppa)
`0.0+1snapshot201411212141-1~211~ubuntu14.04.1`

```
$ zeal --version
zeal 20140215
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```

**Comment by trollixx** [comment]
It's a known problem (see #253) of Ubuntu users, who do not use Unity. The simple solution is to remove `appmenu-qt5` package.

**Comment by RasmusWL** [comment]
Until it's fixed, could you please add this information to the Download page? :)

**Comment by trollixx** [comment]
Yeah, I'll update the website before the next release :)
