### ISSUE TITLE
Sprout docset kaput!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [zealdocs/zeal#303]
The server for the Sprout docset doesn't erxist anymore.

**Comment by Kapeli** [comment]
SproutCore? http://docs.sproutcore.com/feeds/sproutcore.tgz works fine for me.

**Comment by trollixx** [comment]
SproutCore is listed on https://kapeli.com/docset_links, but is not available in [Dash docset feeds](https://github.com/Kapeli/feeds/), since they provide docset on their own.

For now a workaround is to add [SproutCore feed](http://docs.sproutcore.com/feeds/SproutCore.xml) to Zeal directly.

**Comment by trollixx** [comment]
Use #315 for tracking progress on a list of docsets hosted by third parties.
