### ISSUE TITLE
Docset search substring issues

### ISSUE THREAD

**Issue by vially** [zealdocs/zeal#304]
If you have both the Django (django:) and Go (go:) docsets installed and you try to search only the Go docset (e.g.: "go:errors"), results from the Django docset appear in the results.

Most probably this happens because Django ends with "go":  djan**go**

I haven't looked at the code but I assume currently the docset search is performed using a substring search while it should perform an exact search.

**Comment by trollixx** [comment]
Thanks for reporting!

**Comment by vially** [comment]
Awesome. That was quick!
