### ISSUE TITLE
Compass docset is not rendered correctly

### ISSUE THREAD

**Issue by KabbAmine** [zealdocs/zeal#309]
First of all, great work, the new features and improvements in the last zeal are awesome, thanks for that.

I have a (visual?) issue with compass docset, he's not rendered correctly in zeal (But works normally in the browser).
![zeal-compass](https://cloud.githubusercontent.com/assets/5658084/7201007/8daf564a-e50b-11e4-85fc-8d11daa74537.gif)
I suppose that Javascript is the culprit.

**Comment by trollixx** [comment]
Unfortunately, avaScript support was accidentally disabled in 0.1.0 release. :( Submitting a fix now.

**Comment by KabbAmine** [comment]
Thanks (I was waiting for the ppa update to confirm).
