### ISSUE TITLE
Network Error downloading docsets

### ISSUE THREAD

**Issue by w33zy** [zealdocs/zeal#311]
Version 0.1.0    

    Network Error
    Error downloading http://api.zealdocs.org/v1/docsets - server replied: Service Unavailable
    OK

Whenever I try to download a new docset I get this error

**Comment by talexand** [comment]
Same. The update also deleted all my old docsets.

**Comment by w33zy** [comment]
@talexand yeah, I had that problem too but didnt realize it was an issue with the app. 

I still have the previous version on my laptop and I copied the already downloaded docsets to this new install on my PC but they are not working correctly.

**Comment by trollixx** [comment]
There was a weird glitch with the server, not sure what caused it yet. Should work now, but requires more investigation.

Docset removal sounds like a bug. I'll push a fix later today.

Sorry for inconvenience, and thanks for reporting the problems!

**Comment by w33zy** [comment]
@trollixx thanks much for the quick reply. I wasn't inconvenienced at all, I appreciate this project too much.

**Comment by trollixx** [comment]
Created #313 for the docset removal issue.

**Comment by fshp** [comment]
@trollixx api still does not work

**Comment by hidjafar** [comment]
@trollixx
same here: server replied: Service Unavailable
offline docsets gone

**Comment by mofizul21** [comment]
Hi,

It may help you. I've found it helpful when I was got an error in ZealDocs- [How To Solve ZealDocs Opening Error In Windows ](http://www.spoilcoconut.com/how-to-solve-zealdocs-opening-error-in-windows/)So you may try.

Thanks
