### ISSUE TITLE
Allow bulk insert of docsets

### ISSUE THREAD

**Issue by talexand** [zealdocs/zeal#312]
The GUI prompt only allows a single URL insert at a time. Is there a way to add URLs in bulk?

**Comment by trollixx** [comment]
If you mean adding multiple Dash feed URLs at once, then there's no such feature at the moment. I didn't think that people could use more than several additional feeds. I see no problem in extending the UI. Thanks for the suggestion.

**Comment by trollixx** [comment]
Dash feeds are rare, and now I think it's just not feasible to implement this feature.

An alternative solution might be bulk docset installation as per #509.
