### ISSUE TITLE
Docsets are removed in case of failed update

### ISSUE THREAD

**Issue by trollixx** [zealdocs/zeal#313]
Zeal deletes existing docsets prior if downloading of their new versions fails.

**Comment by trollixx** [comment]
@talexand @w33zy Regarding docset removal you mentioned in #311. Are you sure that old docset files were actually removed? I cannot reproduce the problem. Old docset files could be removed only if new archive was successfully downloaded. Any details would be appreciated.

**Comment by w33zy** [comment]
@trollixx the actual issue I have is that if I copy my docsets from version 20140215 to the new version, they dont work. If i try to expand the function tree the application crashes.

I dont know if the docsets from the old version ought to be compatible with the new version

**Comment by trollixx** [comment]
Yeah, that problem (#310)  has been fixed already in branch 0.1. I'll prepare a new release today or tomorrow.

Please reopen this issue if the problem with docset removal occurs.
