### ISSUE TITLE
Zeal New PPA Issues

### ISSUE THREAD

**Issue by iammer** [zealdocs/zeal#314]
I am using zeal on Ubuntu 14.10

I started zeal and saw a message to update my PPA.  I followed the instructions and removed the old PPA and updated to the new one.  I did apt-get update/upgrade and saw a new version of zeal was installed.

However, none of the docsets I had previously downloaded are available.  I see that the docset path in options has changed from ~/.local/share/zeal/docsets to ~/.local/share/Zeal/Zeal/docsets.  I tried changing the path to point to my existing docsets but, they were not visible.  I changed the path back to the new location then copied the docsets from the old path to the new one, but I still am unable to see them.

**Comment by trollixx** [comment]
The problem is caused by #310 and a bug fix release 0.1.1 will be available shortly.
