### ISSUE TITLE
Zeal completely messed up after update (ubuntu 14.04)

### ISSUE THREAD

**Issue by sangimed** [zealdocs/zeal#316]
Hi, 
After updating Zeal by installing it from the new PPA, I ended up with this 
=> http://i.imgur.com/gEMIKLv.png

**Comment by danielbaak** [comment]
Hi @sangimed, I'm having the same issue. I noticed that the default docset directory moved from `~/.local/share/zeal/docsets` to `~/.local/share/Zeal/Zeal/docsets` but moving the docsets there only partially helps.

Now I've got only the Zepto.JS, Emacs lisp, and Spring Framework docsets working (out of almost all). 

I'm wondering if the docset format changed in breaking ways in the last upgrade?

**Comment by sangimed** [comment]
@danielbaak well actually I use a costume directory which is in another partition (ntfs) that I use also in the windows version of Zeal... Worked well with the previous version though :(
http://i.imgur.com/7zEpbEm.png

**Comment by trollixx** [comment]
I think the problem is caused by #310. I am going to release 0.1.1 shortly with fixes for found issues.

**Comment by sangimed** [comment]
okay @trollixx thank you very much !
