### ISSUE TITLE
Seems that the server has been broken?

### ISSUE THREAD

**Issue by armnotstrong** [zealdocs/zeal#319]
I just installed zeal in my debian box. And it seemed that the web api http://api.zealdocs.org/v1/docsets has been broken, is that true?
![screenshot from 2015-04-24 18 58 32](https://cloud.githubusercontent.com/assets/3839691/7317496/09954e42-eab4-11e4-8190-4111b5e76f07.png)

**Comment by CooCooooo** [comment]
I got the same problem @armnotstrong

**Comment by armnotstrong** [comment]
But it seems that v2 is working, http://api.zealdocs.org/v2/docsets how to config to using that?

**Comment by armnotstrong** [comment]
Oh, my bad, it's just a fallback info when particular api not exists.

**Comment by OldhamMade** [comment]
Seems to be back up now.

**Comment by trollixx** [comment]
Should work now. Looks like there was an issue (again) with our database hosting. Please, report any problems you notice.

**Comment by trollixx** [comment]
I've done some updates on the server side and moved our database to a different location. Looks like it's quite stable for now.

Reopen if the problem spawns again.

**Comment by trollixx** [comment]
Actually it's a duplicate of #311. Perhaps, there should be a separate bug tracker for server issues...
