### ISSUE TITLE
[Ubuntu] Zeal trayicon shows on top left

### ISSUE THREAD

**Issue by glymehrvrd** [zealdocs/zeal#321]
![screenshot from 2015-04-26 11 22 37](https://cloud.githubusercontent.com/assets/732769/7335759/981412d6-ec06-11e4-88cd-6eb83d137431.png)

After update to the lastest version, the position of trayicon is not correct.

**Comment by trollixx** [comment]
Oh, that's weird. Thanks for reporting!

**Comment by glymehrvrd** [comment]
I found a similar problem [here](http://www.webupd8.org/2014/11/viber-wrapper-indicator-hides-floating.html), caused by not using appindicator. So I tried to compile Zeal myself while forcing appindicator, but the problem still exists, that's odd..
The old version didn't have this problem.

**Comment by trollixx** [comment]
Actually, I thought `sni-qt` package should turn a system tray icon into an app indicator. Apparently, it doesn't.
