### ISSUE TITLE
Suppress Deprecated Zeal PPA

### ISSUE THREAD

**Issue by twodayslate** [zealdocs/zeal#324]
I'm on a machine with no internet. I don't have any repositories and cannot add any others. When I open zeal, it always shows the Deprecated Zeal PPA warning window. This limits the usage of zeal as you are then unable to search for things with the command line. For example, `zeal python:bomb` would not search for anything, instead putting all focus on the newly created warning window. 

Is there an option to suppress this warning window?

Thanks

**Comment by trollixx** [comment]
>  I don't have any repositories and cannot add any others.

How did you install Zeal in the first place?

The solution is to use the [new PPA](https://launchpad.net/~zeal-developers/+archive/ubuntu/ppa). I hope to update it with 0.1.1 today, but before that you can:

```bash
sudo apt-get install --reinstall zeal
```

or without reinstalling zeal:

```bash
sudo mv /usr/bin/zeal-bin /usr/bin/zeal
```

Our [old PPA](https://launchpad.net/~jerzy-kozera/+archive/ubuntu/zeal-ppa) won't be getting any updates.

**Comment by twodayslate** [comment]
I did an offline install. I copied the deb over and all it's dependencies that my system didn't already have. I didn't touch any PPAs. In fact, my system isn't even letting me add the new PPA.

**Comment by trollixx** [comment]
I see. Then use the second command as a hot fix.

**Comment by twodayslate** [comment]
That seems to have worked! Thanks!
