### ISSUE TITLE
[Ubuntu] Global menu is absent if window was hidden and shown again

### ISSUE THREAD

**Issue by trollixx** [zealdocs/zeal#327]
For example, when using global shortcut.

**Comment by trollixx** [comment]
Looks like a bug in `appmenu-qt5`. Reported as [LP #1451946](https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1451946).

**Comment by MMShreyas** [comment]
+1

**Comment by trollixx** [comment]
Closing as there's nothing to do from our side.
