### ISSUE TITLE
Clicking search result does not work properly

### ISSUE THREAD

**Issue by pszalanski** [zealdocs/zeal#328]
When I type in a search term, a list of results appears in the list of docsets. If I click on one of the results, the corresponding page is opended, but it does not jump to the name I clicked. For example, I type in "partition" to find the method of `str` in Python. When I click the desired result, it just opens the page, but stays at the top, instead of jumping to "partition".

**Comment by trollixx** [comment]
Good finding, fixed as well. Thanks!

**Comment by nzgrover** [comment]
Using Zeal version 3.1 and still seeing this same behaviour. That is, it opens the page but does not jump to the selected method.

**Comment by trollixx** [comment]
@nzgrover fixed as #651. In the future please do not post to old tickets.
Check for open issues, or create a new one and add a link.
