### ISSUE TITLE
Cannot set caret in search box by clicking

### ISSUE THREAD

**Issue by pszalanski** [zealdocs/zeal#330]
Clicking in the search box to move the caret has no effect. Also affects dragging to select text.

**Comment by trollixx** [comment]
@pszalanski Could you provide some details about your environment, Zeal and Qt versions? I need to be able to reproduce the problem to fix it.

**Comment by pszalanski** [comment]
Of course:
* Zeal stable installer
* Windows 8.1 and Windows 7, both x64

**Comment by trollixx** [comment]
Fixed in 0.1 branch. Thanks for reporting!
