### ISSUE TITLE
Add support for wxWidgets/wxPython documentation

### ISSUE THREAD

**Issue by MichalBliznak** [zealdocs/zeal#331]
Please, could you add support for wxWidgets/wxPython docsets to the Zeal's download manager? Third-party docsets can be found here http://wxpython.org/Phoenix/docsets/ but it would be nice to provide direct access to them via Zeal's download manager.

**Comment by trollixx** [comment]
Thanks for suggestion. I am planning to add a list of self-hosted docsets at some point (see #315), but no ETA at the moment.
