### ISSUE TITLE
queries with docset restrictions only match full docset names

### ISSUE THREAD

**Issue by lowjoel** [zealdocs/zeal#333]
If I'm looking for the `Enumerable` class in Ruby, I can search:

```
ruby:Enum
```

and it should show me the list. However, in 0.1.1, that will return me no results. I have to use

```
ruby 2:Enum
```

That seems counterintuitive.

**Comment by trollixx** [comment]
I think implementing #167 should fix the problem.

**Comment by lowjoel** [comment]
Interesting thing was that I think this used to work fine before 0.1... It's not new

**Comment by trollixx** [comment]
Looks like you are correct. 950a1220d7c21c244971a1ee213fcc616e2e7f8b changed the behaviour to fix #304. So, previously it worked well for ruby, but was really confusing on other cases (like `go` and `django`).

I don't see a good solution other than implementing keywords. Any other thoughts?

**Comment by lowjoel** [comment]
Instead of keywords, in the interim maybe you can match the start of string first. That way ruby and java matches, but go doesn't match Django.

Of course that's the short term fix. Keywords would be the correct solution.

On 8 May 2015 1:42 pm, Oleg Shparber <notifications@github.com> wrote:

Looks like you are correct. 950a122<https://github.com/zealdocs/zeal/commit/950a1220d7c21c244971a1ee213fcc616e2e7f8b> changed the behaviour to fix #304<https://github.com/zealdocs/zeal/issues/304>. So, previously it worked well for ruby, but was really confusing on other cases (like go and django).

I don't see a good solution other than implementing keywords. Any other thoughts?

**Comment by lowjoel** [comment]
@trollixx any comments on the idea?

**Comment by trollixx** [comment]
I am not sure how to implement such workaround properly. For example, with a straight forward check `an:` would match Android and Angular docsets. So, it's like introducing a lot of different keywords.

**Comment by lowjoel** [comment]
But there are no docsets named "an", would that be optimising for a scenario that doesn't exist? The problem in #304 was that there's no way to match "go" without matching "django". We can still match "android" without "angular" just by typing "and" or "ang".

This would be a good middle ground in the meantime while the keywords feature gets implemented. It's a little painful for met to use 0.1 because the IntelliJ Dash plugin is not able to generate proper queries (it won't be able to tell if it's Ruby 1.9 or Ruby 2, for example.)

**Comment by trollixx** [comment]
Okay, here we go. :)

**Comment by lowjoel** [comment]
I'll try the nightly build once that's out... thanks!

**Comment by lowjoel** [comment]
Thanks again! Works like a treat.

**Comment by trollixx** [comment]
@lowjoel  I've implemented keyword matching behaviour similar to Dash (see #383 for details). It would be nice if you could verify whether it works for you as well. The code is in 0.1 branch.

**Comment by lowjoel** [comment]
Hi @trollixx sorry for the loooong response time. I've tried 0.1.2 (26 Sept) and I THINK it works.

However, I use the Dash plugin for IntelliJ and I notice that it issues this command: `"C:\Program Files (x86)\Zeal\zeal.exe" dash-plugin://keys=ruby,rubygems,rails&query=helper_method/`

But in Zeal I only see 'helper_method', I don't see the keyword qualifiers. Not sure if it's because of this, or an unrelated bug.

**Comment by lowjoel** [comment]
Oh wait, I think you added another command line parameter --dash-query, let me change my registry settings...

**Comment by trollixx** [comment]
@lowjoel That's for reporting! It's a different bug, see #411.
