### ISSUE TITLE
Add Show Option To Zeal System Tray Icon

### ISSUE THREAD

**Issue by MMShreyas** [zealdocs/zeal#335]
The only option available to Zeal Tray Icon is Quit Option. A show option which would activate zeal would be nice.
 Use cases:
1)sometimes i would like to activate the zeal with mouse.
2)i recently forgot what hotkey i set for zeal . and Zeal will start minimized in system tray. i had to reinstall to get it back

**Comment by trollixx** [comment]
I have to know Zeal version, your operating system and desktop environment to assist you.
