### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by scarphin** [zealdocs/zeal#336]
Hi,
I became aware of Zeal about a week ago and I'm amazed how useful Zeal is. I'm grateful for what you've created, thanks to Zeal and of course to Dash for the docsets. I have a couple of very general suggestions to increase the usability (in my opinion) below:

1- I use Codeblocks (CB) for coding. It has a Help Plugin which can be configured very easily to collaborate with Zeal. No plugins nor any tweaks in the source code are needed to make Zeal work with it. I realized CB is not listed in Zeal's IDE Plugins list so you may want to insert an entry for CB there for CB users who may want to give Zeal a try. Below are the steps to configure Zeal for CB:
a- In 'Settings->Environment' select 'Help Files'
b- Click 'Add', enter 'Zeal' (or something else according to your preference), click 'OK' and click 'No' on the upcoming window titled 'Browse'
c- In the command line just above the red 'TIP: ....' text insert 'path/to/zeal_executable $keyword'
d- Check both 'This is the default help file...' and 'This line represents a full command...'
e- Click 'OK'
That's it. Usage is quite simple, just put the cursor on something you want to look for documentation and push 'F1' and then Zeal will be launched with a search query for the symbol under the cursor.

2- A command line parameter for Zeal (maybe something like '-newtab') to open a new tab for the incoming query would be nice so previous search window won't be replaced with the new search window.

3- I use a dark theme for everything possible and docsets come with a default black on white background (obviously). Currently I make them darker by inserting 'html { -webkit-filter: invert(90); }' in the css file(s) responsible for the docset. '90' is the amount of inversion and varies between '0-100'. I don't know how Zeal displays the docsets but is it possible to implement this functionality in Zeal (by Javascript or ...) somehow so the user can choose the amount of inversion in the settings and Zeal inverts the colors of the docsets when displayed?

Again thanks for Zeal.

**Comment by trollixx** [comment]
Hi, thanks for the feedback.

1. Indeed, the plugin list misses some IDEs which can be configured to use Zeal without additional plugins. I'll add Code::Blocks to the list. One question first. Is it possible to open a URL from CB instead of running a binary? With `dash-plugin:` protocol, which is the universal way to invoke Zeal, it would be possible to run Zeal without specifying  path to it.

2. That's a nice suggestion. Another way could be a settings option to open all external searches in new tabs. I'll think about the best flow.

3. Custom styling should be resolved by #268. Perhaps, I could make it part of 0.1.2 release, as it's really minor feature.

I'll leave this issue open until 1 and 2 are implemented. Any additional feedback is very appreciated.

**Comment by scarphin** [comment]
1- Yes, opening URLs instead of running binaries is possible in CB. In the configuration steps I provided, insert the URL in step 'c' instead of the command line and uncheck 'This line represents a full command...' in step 'd' and then CB will launch the browser to open the URL provided. I'm not sure if it can handle 'dash;' protocol though. Zeal installer asked me if I want 'dash:' and 'dash-plugin:' protocol support and I installed it but I couldn't find any information or usage examples regarding those. If you can point me to some documentation or examples on how to use 'dash:' and/or 'dash-plugin:', I can test further.

2- I think both a command line option to handle external queries and a setting for internal queries would be better.

3- Custom CSS, fair enough.

Btw do you provide any snapshots between releases so users can test new features between releases. Although I use qt4 frequently, I feel unwilling to go into the burden of configuring qt5 to build Zeal myself. ;)

**Comment by trollixx** [comment]
>  If you can point me to some documentation or examples on how to use 'dash:' and/or 'dash-plugin:', I can test further.

See https://kapeli.com/dash_plugins.

> do you provide any snapshots between releases

Windows CI builds for every push are available [here](https://bintray.com/zealdocs/windows-ci). No binary builds for Linux.

**Comment by scarphin** [comment]
1- I've run a couple of tests with 'dash:' and 'dash-plugin;' on CB's help plugin and as I suspected previously they are not implemented. So I think it's better to stick with defining the executable path as in my first post for now. Even more, different docset filters can be inserted by different menus items so I fail to see a handicap by using the designated path.

Thanks for the binary links, saved me a lot of trouble.

**Comment by trollixx** [comment]
If you are using binary builds (not the MSI installer), then protocol handlers should registered with `zeal --register` command.

**Comment by trollixx** [comment]
This is a very old ticket with unrelated requests inside.

1. I do not use Code::Blocks, but feel free to submit a PR to the [website repository](https://github.com/zealdocs/zealdocs.github.io) with IDE specific instructions.

2. I've created #845 to track progress separately.

3. Dark theme was implemented in 0.4.0 (#466). There's also a suggestion for a dark mode applicable to the whole UI (#811).
