### ISSUE TITLE
suggestion - option to limit search scope to one or several docsets

### ISSUE THREAD

**Issue by decalage2** [zealdocs/zeal#344]
It would be useful to have a simple option in the main GUI to choose the scope for searching: all docsets by default, or one docset (e.g. with a drop-down list on top). It could even be a selection of docsets, if you can have a widget with multiple selections.

That would make search faster (if each docset is indexed separately), and results would be more accurate. Usually I'm only searching in one docset at a time.

**Comment by trollixx** [comment]
A proper search groups/scopes implementation is in the roadmap, see #77 and #167.

For now to limit search scope you can use prefixes, e.g. `python:` or `ruby:`. The prefix approach is mentioned in our [poor documentation](http://zealdocs.org/usage.html) and README file.
