### ISSUE TITLE
Zeal window vanishes after switching workspaces in GNOME 3.16

### ISSUE THREAD

**Issue by tsdh** [zealdocs/zeal#345]
When I open the current git version of zeal on an GNOME 3.16 desktop and then switch to another workspace and back again, the zeal window has vanished.  In contrast, when I switch to a virtual terminal (`Ctrl-Alt-Fx`) and back again, the zeal window is still there.

I haven't tried with another desktop environment/window manager so I can't say if it's GNOME-specific.

When I start Zeal from the command line using `zeal --force` which also seems to keep it in the foreground and then switch to another workspace and back again, the zeal window has disappeared but the process hasn't exited (or given any output on stderr/stdout).  So it seems like it doesn't crash.

**Comment by trollixx** [comment]
I couldn't reproduce the problem with GNOME 3.14 on Fedora 21. I'll try with Fedora 22 (it has GNOME 3.16) shortly.

What is your distribution? Also Qt and Zeal versions are not mentioned in the report.

**Comment by tsdh** [comment]
I'm on Arch Linux.  The Qt version is 5.4.2, and I'm running the current git master of Zeal which I update daily.

**Comment by trollixx** [comment]
This is super old, and hopefully not happening any longer.
