### ISSUE TITLE
Some docsets without visible content

### ISSUE THREAD

**Issue by StephanFink** [zealdocs/zeal#346]
Hi,
I have the problem, that two of my three downloaded docsets seem to be without any content. Processing works fine, but the Arduino and ActionScript docsets are empty.
The index.html of both ones don't show anything in a brwoser, too.

![zwischenablagebild](https://cloud.githubusercontent.com/assets/1353708/8103533/810d9566-1029-11e5-8a34-6c0a4831bd81.jpg)

**Comment by trollixx** [comment]
I don't see any issues with Ardruino docset, but ActionScript is definitely broken. `index.html` page is empty even in Firefox and Chrome. It looks like elements are hidden with `display: none`, so I would assume that they should be shown with JavaScript, but no JS files are included. @Kapeli could take a look?

**Comment by Kapeli** [comment]
The ActionScript index page is `package-detail.html`, not `index.html`. `index.html` is definitely empty, but you should not access it.

Are there any other pages that have issues?

**Comment by trollixx** [comment]
@Kapeli I don't see other issues, so I'll update the index file information then. Thanks!

**Comment by trollixx** [comment]
@StephanFink In your case it looks like two docsets were not extracted properly. Please, try to remove and install them again. Also, what Zeal version are you using?

**Comment by trollixx** [comment]
I've updated index page info for the ActionScipt docset, it should be available after redownloading docset list and docset in Zeal.

I don't see any other issues with ActionScript or Ardruino docsets, so just waiting for a feedback from @StephanFink.

**Comment by StephanFink** [comment]
Thank you for your help and please excuse my late answer!

Maybe two weeks ago my ActionScript docset stopped working with Zeal 20140215. After that I have tried Build 20150602 (v.0.1.2). Some days later I noticed, that also the Arduino docset became useless.

Now ActionScript works again with the new Zeal version but there is no "methods tree" like in Processing. Also the search like "actionscript:Array" or "arduino:Array" doesn't work. With the old stable version I still cannot see anything from ActionScript.

**Comment by trollixx** [comment]
Have you tried removing both docsets and installing them again? The way docset metadata is stored has changed since the old 2014xxxx versions, so automatic update (and even a check for updates) isn't possible.

**Comment by StephanFink** [comment]
Yep, I deleted and reinstalled both docsets in both versions to individual docset paths.

**Comment by trollixx** [comment]
Something is definitely wrong, but I have no idea how to debug that. I've just tried the [latest stable build](https://bintray.com/zealdocs/windows-ci/zeal-stable/_latestVersion#files) on Windows 8.1, and it has not shown any issues.

**Comment by StephanFink** [comment]
Hi again,
I think I have found the problem. At work everything works fine and I copied the data on a stick. From there everything works fine, too.
It seems that Zeal cannot handle docsets on drives formated with exFat. NTFS and FAT32 don't make problems, but the same docset files stop working on my exFat drive. Oo

**Comment by StephanFink** [comment]
Since I have my docsets on my system partition, Zeal works fine. But it would be great to know whether Zeal will support exFat some time. Will it?

**Comment by trollixx** [comment]
Sorry for a long delay.

I honestly have no idea what could be wrong with exFAT. There's no any FS specific code in Zeal. I'll try to test with docsets on an exFAT partition.

**Comment by trollixx** [comment]
Fixed quite a long time ago.
