### ISSUE TITLE
Zeal Qt DLLs appear to clash with Qt installation

### ISSUE THREAD

**Issue by studoot** [zealdocs/zeal#347]
I've just downloaded the latest install of Zeal (as I hadn't updated it for a while) and had issues with that (the `libstdc++` was missing an export required by `Qt5Core`?), so went for a stable nightly (`zeal-stable-0.1.1-56-gab317d0`).

I unpacked the zip file, but on running Zeal, got the error shown below:

![zeal-error](https://cloud.githubusercontent.com/assets/799344/8126564/6e89f592-10e7-11e5-9085-93caaae1752f.png)

Seems that Zeal was picking up some of its own DLLs, and some from my Qt install @ c:\Qt\5.4\mingw491_32 - which it really shouldn't do, seeing as all the Qt it needs is distributed with it. 

I was able to work around this by adding a file `qt.conf`to the Zeal executable directory, containing the following text:

```
[Paths]
Prefix = .
```

Adding a file like this to the distribution would fix the issue or alternatively you could (I suspect, as this is something I've done in my own Qt apps) use `QApplication::setLibraryPaths` to explicitly set the application directory as the sole Qt directory.

**Comment by trollixx** [comment]
I've never encountered such problem during my tests of Zeal installed through MSI. I'll try to reproduce it on a clean Windows installation.

**Comment by trollixx** [comment]
I cannot reproduce this problem. Please reopen if it still occurs with the recent Zeal version.

**Comment by diego-betto** [comment]
Same here on win 10 64bit
Seems to work if installed for all users, fails with the same error if installed only for current user

**Comment by trollixx** [comment]
Will check the per-user installation case.

**Comment by trollixx** [comment]
I was able to reproduce the problem. For some reason per-user install lacks Qt plugins.

**Comment by trollixx** [comment]
According wixtoolset/issues#5481 `WixUI_Advanced` doesn't even support dual mode yet. More digging into WiX/MSI docs is required to get this fixed.

Unless somebody who knows WiX well can contribute a fix, I think I'll just disable per-user option. Portable version kind of covers that scenario already.

**Comment by trollixx** [comment]
Tracking the new problem in zealdocs/zeal-packaging#36, as it is unrelated to the original issue reported here.
