### ISSUE TITLE
Uneasiness with search feature and Ctrl+F search box can't be closed

### ISSUE THREAD

**Issue by amitbongir** [zealdocs/zeal#352]
Qt version 5.2.1
OS : Ubuntu 14.04.1 LTS.
Whenever I select one of the search items on the basis of my query, the page is shown from the beginning and not at the section as per the search item.
So I further do Ctrl+F search in the page and go to the desired section. But to continue scrolling the page I couldn't unfocus the search box unless I use the mouse. Further I couldn't find a way to close the search box.

**Comment by trollixx** [comment]
Hi. This problem has been fixed already by supporting <kbd>Escape</kbd> for hiding the in-page search box. Commit bbdfb4d3b08c9e83c9e3e95337b3b88b7e97e844, old issue #129.

Zeal 0.1.2 will include the fix, but I can't give an exact ETA on release date yet.

**Comment by amitbongir** [comment]
Thanks. Currently <kbd>Escape</kbd> returns focus to query box and not the page. Expecting the release to also support directing of search item to corresponding section of page and not the beginning.
