### ISSUE TITLE
Scrolling with touch screen or touch pad

### ISSUE THREAD

**Issue by FichteFoll** [zealdocs/zeal#356]
Sadly, Zeal does not support the two-finger gestures that allow scrolling on mordern laptops with a touch pad. I am assuming that touchscreens are not supported either since, afaics, they use the same API interface. It would be nice if this was added. I am on Win8.1.

**Comment by trollixx** [comment]
It's definitely something I need to look into. I am not sure whether Qt WebKit (our web view engine) has support for gestures (it's pretty much obsolete and unsupported), or maybe it can be implemented separately. I don't have a touch-enabled device, so it might take some time before I would be able to work on it.

**Comment by trollixx** [comment]
It should work as expected with modern Qt and Qt WebKit.

**Comment by FichteFoll** [comment]
I can't verify this on Windows anymore, but iirc this used to work on Linux with the previous version.

**Comment by trollixx** [comment]
The referenced code change had no effect for me on Windows, but it could have disabled the touch support on other setups. Anyway, should always work now.

**Comment by KMayne** [comment]
On Windows (Surface), I am able to use 2 finger scroll on the touchpad but using the touch screen does not scroll (highlights like using a mouse).

**Comment by trollixx** [comment]
@KMayne can you try the latest [CI build](https://bintray.com/zealdocs/windows-ci/zeal-portable-unstable)?

**Comment by KMayne** [comment]
It's exactly the same on the CI build

**Comment by trollixx** [comment]
From the original report:

>  I am assuming that touchscreens are not supported either

So I am closing this ticket, since touch pad works fine now. Please refer to #865 regarding touch screens.
