### ISSUE TITLE
Unable to build due to "Could not create output file error"

### ISSUE THREAD

**Issue by dufferzafar** [zealdocs/zeal#357]
I  am on Ubuntu 14.04, and this is what I get when I run make: 

```
cd src/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/dufferzafar/dev/clones/zeal/src/src.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory `/home/dufferzafar/dev/clones/zeal/src'
/usr/lib/x86_64-linux-gnu/qt4/bin/uic ui/forms/aboutdialog.ui -o /.ui/ui_aboutdialog.h
Could not create output file
make[1]: *** [/.ui/ui_aboutdialog.h] Error 1
make[1]: Leaving directory `/home/dufferzafar/dev/clones/zeal/src'
make: *** [sub-src-make_first-ordered] Error 2
```

Sorry, but I have no prior experience with Qt.

**Comment by trollixx** [comment]
I think something is wrong with your Qt installation. For some reason it uses `uic` from Qt 4. Try installing `qt5-default` package.

**Comment by dufferzafar** [comment]
Um, `qt5-default` is already installed, and when I run uic from the terminal, it is the qt5 version. 

![zeal - qt - package](https://cloud.githubusercontent.com/assets/1449512/8469700/f88b54ba-209c-11e5-96cc-c040af84d6e4.png)

**Comment by rpayanm** [comment]
Try with sudo.

**Comment by dufferzafar** [comment]
@rpayanm Sorry, but I don't get it. Are you suggesting that I run `sudo make`?

**Comment by rpayanm** [comment]
Normally "make" is without sudo, but you can try it or run all command with sudo or type:
$ su
# start again here

**Comment by trollixx** [comment]
It's been a while. Using `sudo` for building stuff is *always* a bad idea.

@dufferzafar were you able to build Zeal?

**Comment by dufferzafar** [comment]
@trollixx No, I was not. Still getting the same error.

**Comment by trollixx** [comment]
Have you tried to run `qmake-qt5`?

**Comment by sonictk** [comment]
I have the same issue as well when attempting to build zeal on my workstation at work. We cannot have sudo for administrative reasons.

```
cd src/ && ( test -e Makefile || /usr/bin/qmake-qt5 /home/yliangsiew/Git/zeal/src/src.pro -o Makefile ) && make -f Makefile
make[1]: Entering directory `/home/yliangsiew/Git/zeal/src'
uic ui/forms/aboutdialog.ui
Could not create output file
make[1]: *** [/.ui/ui_aboutdialog.h] Error 1
make[1]: Leaving directory `/home/yliangsiew/Git/zeal/src'
make: *** [sub-src-make_first-ordered] Error 2
```

Is there any other way I can get around this?

**Comment by trollixx** [comment]
The project has been massively reorganised, and I hope this issue (if it wasn't a problem in user's setup) is now fixed.
