### ISSUE TITLE
Search in subset of downloaded docsets

### ISSUE THREAD

**Issue by DimitrisK5** [zealdocs/zeal#360]
Hi!

I have downloaded *lots of docsets*, because I really need to have access to relevant documentation whenever I find myself in a situation where I'm offline, or behind a corporate firewall. On a regular day however, I only need to search in a couple of these docsets. Searching through **all** the docsets **every** time I write a keyword in the input field is overkill, it slows down searching, and it clutters considerably the results list.

I feel it's quite natural to be able to select the docsets where I want to search (e.g. through checkboxes in the main view, or in the docsets' settings view). Please consider adding this essential usability option.

**Comment by trollixx** [comment]
Hi, it's really a must have feature that's been reported a while ago (#77). I don't have any ETA at the moment, but it will be part of the future 0.2.x release, that I hope to start working on soon.

Closing this as a duplicate.
