### ISSUE TITLE
[Windows 7] - Mono Docset Crashes Zeal

### ISSUE THREAD

**Issue by xcjs** [zealdocs/zeal#362]
When downloading the Mono docset in Windows 7 x64, Zeal crashes.

**Comment by sonictk** [comment]
I can confirm that this happens as well. Fresh install of Zeal, trying it out on both work/home workstations, whenever it gets to downloading Mono's docset, Zeal crashes during the installation process.

**Comment by trollixx** [comment]
Should be fixed by a27905b504706833dcd58d68570ef67a88bdde25.

Zeal ran out of memory on big docsets, because we were keeping everything in RAM.

**Comment by trollixx** [comment]
Please, reopen if the bug still occurs with a fresh build of 0.1 branch.
