### ISSUE TITLE
Zeal via Homebrew?

### ISSUE THREAD

**Issue by benjaminfrank** [zealdocs/zeal#363]
Hi,

I really like Zeal/Dash (thanks!) but I admit I prefer Zeal as I can run it both on Linux (home) and Mac (work) and thus have the same program on both platforms (especially as I call Zeal interactively from emacs). 
I intended to add a homebrew formula for Zeal, however I just found https://github.com/zealdocs/zeal/issues/24, so I wanted to ask before I create any issues for anyone by creating this formula.
So would it be ok for me to add a hombrew formula for Zeal so I can enjoy it on mac os?

**Comment by Kapeli** [comment]
I'm against this for the same reasons I'm against distributing Zeal binaries for OS X (i.e. competing with Dash). The decision is not mine though, so wait for @trollixx.

**Comment by trollixx** [comment]
I'd really prefer to avoid distribution of Zeal on OS X. First of all, per our agreement with @Kapeli Zeal is not targeting OS X to avoid unneeded competition. Zeal is not an independent project, and heavily relies on Bogdan's hard work. All docsets are generously provided to Zeal users for free.

Another important issue is quality of Zeal. Having it in Homebrew would assume some sort of official support for OS X, while there's none. I don't have OS X machine, and Qt has a lot of issues with recent OS X releases. There might be a lot of bug reports I would not be able to address. Also Zeal really looks horrible on OS X. I do believe that allowing an easy installation of Zeal on OS X would result in many frustrated users and negative reviews.

While I can't forbid to run or pack Zeal in any possible way (GPL explicitly allows unconditional use of the software everywhere), there's no any intention from my side to create issues for Bogdan, as Zeal would not be even near close to its today state without his support.

**Comment by benjaminfrank** [comment]
I thought as much when reading #24, but asking doesn't cost much, eh?
I totally understand and will respect your points/arguments and close the respective homebrew PR.
Thanks.

**Comment by asimpson** [comment]
so in light of recent events, any change in sentiment regarding Zeal in homebrew?
🏃 💨

**Comment by trollixx** [comment]
Nothing can change as long as Zeal makes use of Dash docsets. Not until
someone would commit to maintain almost 200 docsets. :)

**Comment by xthilakx** [comment]
Appreciate the hard work by @Kapeli, but I hate paying every other month. Installing via Homebrew would have definitely saved me some time.

**Comment by Kapeli** [comment]
@xthilakx What do you mean by having to pay every other month? Dash 4 (the latest Dash paid upgrade) came out ~2 years after the previous paid upgrade (Dash 3) and users that bought in the past 3 months get to upgrade for free.

**Comment by trollixx** [comment]
@xthilakx I am not sure what you mean by "every other month". Dash is a
single purchase per major version. And I think price is more than
reasonable considering amounts people overpay for Apple's goods.

Aside from that, for us to release a macOS version, someone has to commit
to an unpaid full-time job of maintaining 200 docsets. Without docsets Zeal
is completely useless.

**Comment by raymusmunt** [comment]
> I think price is more than reasonable considering amounts people overpay for Apple's goods

I would prefer the pricing not be determined by your perception that Apple users are willing to pay more than something's worth.
