### ISSUE TITLE
[Gnome 3] Zeal Icon invisible on Notification Área

### ISSUE THREAD

**Issue by paulodiovani** [zealdocs/zeal#364]
On Gnome 3 notification area (`Super + M`) the Zeal Icon is not visible.

![screenshot from 2015-07-01 15 11 32](https://cloud.githubusercontent.com/assets/1295197/8461522/b7388efe-2003-11e5-8b88-f6d8f30124af.png)

**Comment by Tranquility** [comment]
It does work in Gnome 3.16.

**Comment by mdirik** [comment]
It doesn't work in GNOME 3.14.

**Comment by trollixx** [comment]
Is it still an issue? Implementation of the tray icon has changed since the ticket was filed.
