### ISSUE TITLE
Zeal Download Page is down.

### ISSUE THREAD

**Issue by philipphager** [zealdocs/zeal#367]
Hey I would like to try zeal,
but i can't download it :)

**Comment by trollixx** [comment]
I've just checked http://zealdocs.org/download.html and it opens fine. Or
are you talking about something else?

**Comment by vagusX** [comment]
@trollixx  I met that too

**Comment by trollixx** [comment]
Closing due to lack of feedback. I couldn't spot any issues with the download page.
