### ISSUE TITLE
Some docsets are not display correct

### ISSUE THREAD

**Issue by goldenages1989** [zealdocs/zeal#374]
![jserror](https://cloud.githubusercontent.com/assets/3285965/8646682/78e22752-2984-11e5-84c4-454f479ba8ed.png)

i get this when i search in javascript docset.

**Comment by trollixx** [comment]
Hi, I need more information about versions of Zeal, Qt and your operating system. Does it happen all the time?

**Comment by goldenages1989** [comment]
zeal version: 0.1.1
qt version: 5.4.1
operating system: wIndows 7 x64
and yes it happens all the time

**Comment by trollixx** [comment]
Duplicate of #359.
