### ISSUE TITLE
CLI control

### ISSUE THREAD

**Issue by Kwaadpepper** [zealdocs/zeal#375]
Would it be possible to have a new cli arg to retrieve results titles (prefixes) and docs like

zeal -d : 
php
bootstrap 3
angularsjs

zeal  -t  php: constants 
Constants
apc_define_constants
...

and if no prefix is given

zeal -t constants : 
php: Constants
php: apc_define_constants
...
wordpress: ms_cookie_constants
...

This kind of api would make me able to make better Synapse plugin for Zeal integration.

**Comment by trollixx** [comment]
Hi, I've explained my reasoning to avoid CLI in #368.

Closing this in favour of #400.
