### ISSUE TITLE
Possible Memory leak

### ISSUE THREAD

**Issue by voldyman** [zealdocs/zeal#379]
Zeal generally starts at 10.2 mb usage for my system but with every show hide window (using global shortcut) the memory usage increases.
![Initially](https://cloud.githubusercontent.com/assets/2378083/8764901/b7b1a4bc-2e11-11e5-9c94-74d1323f3c85.png)
![2-3 show/hide](https://cloud.githubusercontent.com/assets/2378083/8764902/bb7629f6-2e11-11e5-8357-a70a81003245.png)
![5-6 show/hide](https://cloud.githubusercontent.com/assets/2378083/8764903/be3e6cca-2e11-11e5-8d98-06df2f63709b.png)

valgrind also agrees 

```
==11966== HEAP SUMMARY:
==11966==     in use at exit: 433,013 bytes in 5,666 blocks
==11966==   total heap usage: 156,350 allocs, 150,684 frees, 47,198,818 bytes allocated
==11966== 
==11966== LEAK SUMMARY:
==11966==    definitely lost: 8,452 bytes in 132 blocks
==11966==    indirectly lost: 201,352 bytes in 4,493 blocks
==11966==      possibly lost: 5,380 bytes in 85 blocks
==11966==    still reachable: 217,829 bytes in 956 blocks
==11966==         suppressed: 0 bytes in 0 blocks
==11966== Rerun with --leak-check=full to see details of leaked memory
==11966== 
==11966== For counts of detected and suppressed errors, rerun with: -v
==11966== Use --track-origins=yes to see where uninitialised values come from
==11966== ERROR SUMMARY: 2994 errors from 37 contexts (suppressed: 8 from 1)
```

**Comment by trollixx** [comment]
Hi, thanks for reporting. I'll check this out more thoroughly after fixing some other important issues.

**Comment by trollixx** [comment]
I've tried to reproduce this issue, but I do not see any change in memory usage when I toggle the window visibility with the global shortcut.

@voldyman which Zeal version had this problem?

**Comment by voldyman** [comment]
it's version 0.1.1

**Comment by finelog** [comment]
It happened to me too.
I am using ubuntu 16.04, i3 wm, I opened a zeal and leave it there, after several days, when I move a floating window, it becomes strange, the window is moving very slowly and followed with shadows, which normally won't happen in i3. after some checking, I found zeal gui rendered slowly.
I don't know too much about the computer graphic, but I think zeal probably has memory leak in gpu or some other problems, I've been using zeal for a time and really like it, hope it would be better.
my pc info:mac mini 2014, I install a ubuntu 16.04 on it, zeal version is 0.2.1,qt version is 5.5.1.
sorry I couldn't provide more information.

**Comment by elvismdev** [comment]
Same for me here, my system is Ubuntu 16.04 in a Dell XPS 13 9350. Every time I open Zeal and leave it there to lookup my necessary docs all my system graphic goes very very slow while switching (ALT + TAB) between different apps I have open and working properly my IDE, browser, Zeal, etc. 

After closing Zeal everything goes back to normal.

If I do `top` from terminal and watch the CPU and memory usage  Zeal is always among the highest apps consuming memory going always to the very top when I'm switching to Zeal window and looking up some documentation.

![selection_026](https://cloud.githubusercontent.com/assets/3847077/18029515/02627c30-6c68-11e6-8ddb-b65fb278dd3d.png)

**Comment by trollixx** [comment]
Zeal keeps a lot of stuff in memory, that can cause some issues if there are many docsets installed. Also, I do believe there are many leaks in the old Qt WebKit. A few things have been fixed in Zeal too, so please give a freshly fetched code a try.

**Comment by trollixx** [comment]
No updates in a long time.
