### ISSUE TITLE
Shared libraries needed but not mentionned in the README.md

### ISSUE THREAD

**Issue by sammy44nts** [zealdocs/zeal#382]
Hello,

I had to compile zeal on Linux Mint Debian Edition and `make` shout an error about missing dependencies for **libqt5webkit5-dev** and **libqt5x11extras5-dev**. I would have loved to know I had to install it before compiling zeal.

The issue is for **libqt5sql5-sqlite** wich is not mentioned as a require in the README.md but when missing, it makes zeal crash silently while trying to install the docsets.

Regards,

**Comment by trollixx** [comment]
Please see my comment [here](https://github.com/zealdocs/zeal/issues/61#issuecomment-127123184).

I'll think about the best way of providing distro specific instructions.

**Comment by sammy44nts** [comment]
Thank you for this issue solved :-)
