### ISSUE TITLE
unable to build under FreeBSD

### ISSUE THREAD

**Issue by mjollnirpaul** [zealdocs/zeal#384]
Can s/o help please?  Maybe there's a lib missing or such?

[root@paul-lifebook /usr/local/src/zeal]# echo $QMAKESPEC
freebsd-g++
[root@paul-lifebook /usr/local/src/zeal]# echo $QTDIR
/usr/local/lib/qt5
[root@paul-lifebook /usr/local/src/zeal]# qmake
zeal.pro:7: Unknown test function: lessThan
[root@paul-lifebook /usr/local/src/zeal]#

**Comment by trollixx** [comment]
Hi, please post output of `qmake -v`.

**Comment by mjollnirpaul** [comment]
Hi Oleg,

thanks for taking care!

Am Mittwoch, 22. Juli 2015, 16:41:32 schrieb Oleg Shparber:
> Hi, please post output of `qmake -v`.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/zealdocs/zeal/issues/384#issuecomment-123908208
[root@paul-lifebook /usr/local/src/zeal]# qmake -v
Qmake version: 1.07a (Qt 3.3.8)
Qmake is free software from Trolltech ASA.

-- 
=|o)

**Comment by trollixx** [comment]
Wow, you have Qt 3.3.8. It is more than 8 years old. You need at least Qt 5.2.0 (5.5.0 is the latest version).

I am not aware how to install packages and updates in FreeBSD, so I can't really help with exact details.

Once you figure out how to get the recent Qt version, please let me know whether Zeal runs on FreeBSD at all.

**Comment by mjollnirpaul** [comment]
No, I had only the runtime of qt5, and the qt3 version of qmake.  Unfortunately, package names in FreeBSD are sometimes misleading, i.e. "qmake" is from qt3 and qt5-qmake was missing.
# pkg install gcc49
[ installed some qt5-* stuff but the following should be sufficient:]
# pkg install devel/qt5
# cd /usr/local/src/zeal
# qmake
[edit src/Makefile to use g++49, change '-std=c++0x' to '-std=c++11', and change to install to /usr/local instead of /usr]
# make
# make install

**Comment by trollixx** [comment]
So, at the end Zeal runs fine on FreeBSD, right?

**Comment by mjollnirpaul** [comment]
Am Sonntag, 26. Juli 2015, 09:28:54 schrieb Oleg Shparber:
> So, at the end Zeal runs fine on FreeBSD, right?
> 
Yes, "It just works" (tm).  Thanks for your help!
-- 
=|o)
