### ISSUE TITLE
docsets not displayed on ubuntu 15.04

### ISSUE THREAD

**Issue by amitbha** [zealdocs/zeal#388]
Zeal installed from official PPA, v0.1.1
After download, the docsets are not displayed in "Docsets" option list.

Run zeal in gnome-terminal, the error is 
"QSqlDatabase: available drivers: 
SQL Error: Driver not loaded Driver not loaded
QSqlDatabase: QSQLITE driver not loaded"

Install libqt5sql5-sqlite and works fine

**Comment by trollixx** [comment]
Thanks for reporting! I'll add the missing dependency for the upcoming 0.1.2 release.

**Comment by trollixx** [comment]
Further tracking in zealdocs/zeal-packaging#4
