### ISSUE TITLE
How can we sort search result in "See also" ?

### ISSUE THREAD

**Issue by Himanshu-Mishr** [zealdocs/zeal#389]
Hi,  below in "See also", how can we sort them ? It is difficult to search, as options are not in any order or is it suppose to be in that way?

![screenshot from 2015-07-31 22 49 04](https://cloud.githubusercontent.com/assets/1938285/9012985/ae23acc8-37d6-11e5-8935-d6f6ac99239f.png)

**Comment by trollixx** [comment]
There's no way to sort this block. Even more, it's generated in a wrong way - by finding all symbols on the same page, instead of relying on Dash TOC (see #386). Would an alphabetical sorting work better as an interim solution?

**Comment by Himanshu-Mishr** [comment]
Yes. If you can sort based on their types/categories, then it would better. With types I mean according to icons on left. Looks like they are already grouped under based on types(whether it is a modules, function, attribute or a class), but not sorted.
Thanks.

**Comment by trollixx** [comment]
Closing in favour of #386.
