### ISSUE TITLE
How to add the modx repository from Dash user contributed repos?

### ISSUE THREAD

**Issue by BigBlockStudios** [zealdocs/zeal#390]
How do I add the modx repository from the Dash user contributed repos? 

they pointed me at: 

https://github.com/zealdocs/zeal/issues/170

which I managed to figure out the feed location:

http://newyork.kapeli.com/feeds/zzz/user_contributed/build/MODX/MODX.tgz

However it gives an invalid docset error after downloading :( 

-thanks

**Comment by trollixx** [comment]
Hi,

I've just installed MODX docset and I cannot see any errors. There are duplicated items in the menu, but it still works fine. Could you explain exact steps you perform to install the docset?

**Comment by BigBlockStudios** [comment]
I went to options -> docsets and plugged in the url above in the add feed dialog

**Comment by trollixx** [comment]
That couldn't work, because `Add Feed` is intended for Dash XML feeds, not docsets directly. To add docset manually simply unpack the archive in your docset path.

On another note, I think it might be worth adding direct docset download capability to Zeal.

**Comment by BigBlockStudios** [comment]
That would be a great feature - myself, wouldn't want to manually have to d/l and update docsets every time a new one is released. It kind of defeats the purpose of an offline repository that should be updating in the background.

**Comment by trollixx** [comment]
#390 describes the idea of the direct docset download.
