### ISSUE TITLE
Build Error on fedora 22 Project ERROR: Unknown module(s) in QT: x11extras

### ISSUE THREAD

**Issue by KishoreVignesh** [zealdocs/zeal#391]
I cloned the git repository, Then ran qmake-qt5 commanad. Works fine.

when i run make, I get the following Error.

[kishorevignesh@localhost zeal]$ make
cd src/ && ( test -e Makefile || /usr/bin/qmake-qt5 /home/kishorevignesh/zeal/src/src.pro -o Makefile ) && make -f Makefile 
Project ERROR: Unknown module(s) in QT: x11extras
Makefile:42: recipe for target 'sub-src-make_first-ordered' failed
make: *** [sub-src-make_first-ordered] Error 3

**Comment by trollixx** [comment]
It tries to tell you that you need Qt X11 Extras module. Do Fedora the package name is `qt5-qtx11extras-devel`.

**Comment by KishoreVignesh** [comment]
Thank you so much Trollixx. Now no Issues. I was trying to build zeal for past two days for suck a silly mistake. anyways. if the make had said install that package. I would have not opened an issue. I would have not wasted your time.

**Comment by trollixx** [comment]
No problem, I hope to come up with distro specific instructions one day (#61) :)
