### ISSUE TITLE
Zeal crashes

### ISSUE THREAD

**Issue by davidwed** [zealdocs/zeal#394]
Zeal crashes if I add a custom docset feed.

This one:
http://rotemy.com/dash/msdn/msdn.xml

Its the msdn Library as docset.
Otherwise If I download the "http://rotemy.com/dash/msdn/msdn.tgz" directly, extract it and put it into the Docset storage folder, the docset works.

br

**Comment by JIghtuse** [comment]
Can't reproduce it on my machine (Debian Stretch, freshly built zeal from git).

**Comment by trollixx** [comment]
I think it's a Windows specific bug, I was able to reproduce it on Windows 7, but not on any Linux machine.

**Comment by trollixx** [comment]
Please, see #362 for details.
