### ISSUE TITLE
Zeal closes after docset download

### ISSUE THREAD

**Issue by Asura227** [zealdocs/zeal#397]
I have just installed zeal fresh.  I am using Linux Mint w/KDE desktop. When I attempt to download a new docset, just as the progress bar reaches 100% the program closes. When I reopen the list shows that I have no docsets.

**Comment by trollixx** [comment]
What docset were you trying to install?

**Comment by Asura227** [comment]
python 3  because that's what I'm currently studying

**Comment by trollixx** [comment]
I cannot reproduce the problem. How did you install Zeal? Do other docsets work fine, and only Python 3 causes the crash?

**Comment by Asura227** [comment]
I installed zeal through the terminal (apt-get), using the instructions on
the download page under the Ubuntu heading.
I tried:
AngularJS
Bootstrap 3
CSS
HTML
JavaScript
MySQL
PHP
Python 3
JQuery

**Comment by trollixx** [comment]
Do you have Qt SQLite plugin installed?

```
apt-get install libqt5sql5-sqlite
```

**Comment by Asura227** [comment]
To be honest I am unsure. I was having some other problems and I switched
to Linux mint with cinnamon d/e. That seems to have corrected everything.
Sorry to have bothered you.

**Comment by trollixx** [comment]
No problem. Zeal should warn when a runtime dependency is not available, instead of silently crashing.
