### ISSUE TITLE
Make docs easier to follow for Redhat installs

### ISSUE THREAD

**Issue by bnvk** [zealdocs/zeal#398]
Hallo. Thanks for making Zeal, it's perfect!!! Moving from MacOS to Linux and losing Dash was a bummer- glad there is a replacement :+1: 

However, I'm a bit hungup trying to build / install it on Fedora 21 computer. I was trying to follow this build guide https://github.com/zealdocs/zeal-packaging/tree/master/redhat but I seemed to have reached a deadend. Any help is much appreciated :)

**Comment by trollixx** [comment]
Hi, what step are you exactly on? Do you get an RPM package?

**Comment by bnvk** [comment]
@trollixx thanks for following up, sorry for my delayed response. When I follow the instructions in the above Redhat packaging doc, if I run the `yum-builddep zeal.spec` without sudo this is what happens:

```
[user@dev ~]$ yum-builddep zeal.spec
Loaded plugins: langpacks, post-transaction-actions, yum-qubes-hooks
Error: You must be root to install packages
```

However, when I run it with sudo, it completes fine, but the next steps fails on downloading the second file due to the directory not existing.

```
[user@dev ~]$ sudo yum-builddep zeal.spec
Loaded plugins: langpacks, post-transaction-actions, yum-qubes-hooks
Getting requirements for zeal.spec
 --> Already installed : libarchive-devel-3.1.2-11.fc21.x86_64
 --> Already installed : qt5-qtwebkit-devel-5.4.2-1.fc21.x86_64
 --> Already installed : qt5-qtx11extras-devel-5.4.2-1.fc21.x86_64
 --> Already installed : xcb-util-keysyms-devel-0.4.0-1.fc21.x86_64
No uninstalled build requires

...and then...

[user@dev ~]$ spectool --sourcedir --get-files zeal.spec
Getting https://github.com/zealdocs/zeal/archive/v0.1.1.tar.gz to /home/user/rpmbuild/SOURCES/v0.1.1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   121    0   121    0     0     46      0 --:--:--  0:00:02 --:--:--    46
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0Warning: Failed to create the file /home/user/rpmbuild/SOURCES/v0.1.1.tar.gz: 
Warning: No such file or directory
  0  892k    0   862    0     0    131      0  1:56:18  0:00:06  1:56:12   250
curl: (23) Failed writing body (0 != 862)
```

I'm new to Redhat and don't understand the packaging quirks and special cases that this is bringing up. In fact, I've never used this `.spec` method to install anything, so I apologize if I'm missing something super n00b like :tongue:

**Comment by trollixx** [comment]
It seems that `/home/user/rpmbuild/SOURCES` does not exist, so the file cannot be created there. I don't understand why `yum-builddep` does not create it automatically. I am not a RedHat/Fedora user myself, but I'll try it out in a VM over the weekend.

**Comment by trollixx** [comment]
Closing this super old report. The spec-file should build just fine.
