### ISSUE TITLE
Closing the options modal shouldn't quit Zeal application (Windows)

### ISSUE THREAD

**Issue by MikeMayer** [zealdocs/zeal#40]
At least on Windows when I click the X to close the options modal it closes the entire application in some cases.

I haven't had the opportunity to check any other platforms.

#### Reproduction steps

1. Open Zeal and Options
2. Dismiss Zeal with global hot key
3. Close options with X on modal
4. Use global hot key to get Zeal back
5. Notice Zeal isn't open anymore and process isn't present in ``` taskmgr ```

**Comment by trollixx** [comment]
Same situation occurs when main Zeal window is hidden by a click on the system tray icon.
