### ISSUE TITLE
Control+W closes left-hand tab, not current one

### ISSUE THREAD

**Issue by sunaku** [zealdocs/zeal#402]
In Zeal 0.1.1, the <kbd>Control</kbd>+<kbd>W</kbd> shortcut is closing the left-hand tab (if any) instead of the current tab. :scream: This is not consistent with the way all Web browsers handle that ubiquitous shortcut (close current tab).

**Comment by trollixx** [comment]
Oh, I believe I did fix this problem not once, and here we are :( Thanks for reporting!
