### ISSUE TITLE
Control-Click -> Open Link In New Tab

### ISSUE THREAD

**Issue by cpriest** [zealdocs/zeal#403]
Thanks @trollixx for writing this, it's excellent!  I'm a longtime Firefox user and am used to ctrl+click on a link opening in a new tab (middle click also does this in FF), both of these may be standard across all browsers..

I happen to use TabMixPlus for a feature I really like as well which makes Ctrl+T (new tab) clone the current tab and history.  It's very handy for "ok keep this tab where it's at and start a new branch."

Thanks much!

**Comment by trollixx** [comment]
Hi, thanks for suggestions.

I'll add support for <kbd>Shift/Ctrl+Click</kbd>, and middle click support. Unfortunately, there are some issues with implementing opening tabs in background.

While I am also a long term Tab Mix Plus user, I have never used its tab cloning feature. Such functionality might be useful, and I've created a separate ticket for that - $405.

**Comment by cpriest** [comment]
Excellent, thank you!

**Comment by ManuelSchneid3r** [comment]
Consider making shift click opening a entire new window and ctrl+click and middle mouse just a new tab. So the close tab on by middle mouse clicking. This is widely used behaviour the user is accusomed to.

**Comment by trollixx** [comment]
@ManuelSchneid3r Unfortunately, the current architecture does not allow multiple windows. I cannot even open tabs in background. :(

Providing a browser-like experience is one of the major goals.

**Comment by cpriest** [comment]
Thanks @trollixx

**Comment by ManuelSchneid3r** [comment]
Just installed zeal-git from aur. Even more amazing,. Thank you. @trollixx

**Comment by Shihira** [comment]
Thanks to @trollixx, we got the best substitute of MSDN on Linux.
Middle button clicking for new tab is now only supported in the doc view, while it's not yet available in the sidebar(doc list and searching view). Hoping for an implementation.

Thanks again.
