### ISSUE TITLE
not scrolling to item location

### ISSUE THREAD

**Issue by nicktime** [zealdocs/zeal#404]
Hi,

if e.g. I enter query "str.find" for Python 2 docset, opened page doesn't scroll to "find" location, just shows the top.
Open URL gives "file:///s/disp-ssd/zeal-docsets/docsets/Python_2.docset/Contents/Resources/Documents/doc/library/stdtypes.html#doc/library/stdtypes.html"
But if I click results in "See also" view, it scrolls correctly.
Open URL gives "file:///s/disp-ssd/zeal-docsets/docsets/Python_2.docset/Contents/Resources/Documents/doc/library/stdtypes.html#//apple_ref/Method/str.isalnum"
Ubuntu 14.04
Version 0.1.1

**Comment by trollixx** [comment]
It's been fixed some time ago: #328. I am preparing 0.1.2 release right now :)

**Comment by nicktime** [comment]
Cool, thanks, sorry for the duplicate.
