### ISSUE TITLE
No online docsets: connection closed.

### ISSUE THREAD

**Issue by alex-fgsfds** [zealdocs/zeal#406]
For some reason Zeal is unable to fetch any feeds with the error "Connection closed". ![error](http://i.imgur.com/3Park0F.png) Access for Zeal is enabled in firewall, but still. "Docsets" tab in Options is empty so I am unable to download anything from Zeal.

**Comment by trollixx** [comment]
Hi, something might be wrong with your internet connection. I do not see any past or present issues with our backend infrastructure.

**Comment by alex-fgsfds** [comment]
Maybe as well be, but (as usual) all connection seemed to be ok and Zeal's API handle opened in browser too. But eventually it worked though. Maybe there's need for longer timeouts in Zeal for cases like that with longer-than-usual API responses.

**Comment by scienceblossom** [comment]
Same problem here when downloading the documentation for the PHP. Tried it several times and stops around 30 to 40 percent. My connection is also totally fine.
