### ISSUE TITLE
Search for function doesn't display correct result?

### ISSUE THREAD

**Issue by SpenzeR** [zealdocs/zeal#407]
Hi

Im just testing this software, and I've added the PHP documentation.

However, when I search for "php:date" I can't find the "date" function. It finds all other php functions that starts with "date" but not the actual date function.(http://php.net/manual/en/function.date.php)

If I browse the list manually I find it.

**Comment by trollixx** [comment]
I do see the problem, but haven't caught it yet. Thanks for reporting!
