### ISSUE TITLE
Clicking File>Options>Apply resets shortcut in Ubuntu 15.04

### ISSUE THREAD

**Issue by hectorcanto** [zealdocs/zeal#413]
If I open the Options menu and click on apply without setting anything the shortcut is erased.

**Comment by trollixx** [comment]
This should be fixed by 033421231afc33842d15c4b3dcc054c5aef3439e. Released in 0.2.0.

**Comment by trollixx** [comment]
Please reopen if you notice this issue in 0.2.0.
