### ISSUE TITLE
Bundled qxtglobalshortcut

### ISSUE THREAD

**Issue by michel-slm** [zealdocs/zeal#414]
Hi,

I am working on packaging zeal for the Fedora distribution of Linux, and we used to have a rather strict guidelines about packages which bundled third-party dependencies. Thankfully the new guidelines is more reasonable, though it still requires official explanation from upstream as to why bundling is required.

Per the libqxt wiki,

> Qxt will likely not work with newer Qt versions due to usage of internal api. We recommend that you pick out the parts you want instead of using the entire libqxt.
> Most of Qxt is still valuable, but it's a fulltime job keeping up with the internal Qt changes. At the same time, Qt has become much more open to contributions, and we encourage everyone to contribute to Qt upstream instead of Qxt.

So it seems that, in this case, the bundling is recommended by the deprecated Qxt project's authors anyway, and from the commit log it looks like the qxtglobalshortcut code in zeal is properly being maintained.

If a Zeal contributor could comment on the bundling here it would be greatly appreciated - simply saying that, yes, the bundling is needed for the reasons stated above, and no, it is impossible to build against libqxt because it no longer works on newer Qt versions, that would suffice.

Thanks!

**Comment by trollixx** [comment]
Hi,

We have made quite many changes to the original `QxtGlobalShortcut`, making it effectively very different. I think now it's not even source compatible. I am planning to rename files and classes, and move them out of `3rdparty` directory to avoid possible confusions. So, Zeal simply cannot be built with the stock Qxt.

On another note, please be sure that there will be no issues with upgrading the package as new releases come out. Zeal relies on its backend server for docset catalogue and docset updates, as well as application version checks. There's a high probability of breaking changes in the server side API. Till Zeal reaches a more or less stable and feature complete state, I don't see much sense in backward compatibility for more than a few latest versions. Such support period might be way shorter than lifespan of a non-rolling-release distribution. If there are no obstacles with publishing new application versions to Fedora repositories any time, then simply disregard this paragraph.

**Comment by michel-slm** [comment]
Hi @trollixx ,

Ah, thanks for the confirmation. As for the rapid-changing nature of Zeal, that's no problem at all. We have an upstream release monitoring system at https://release-monitoring.org/project/7839/ so I'll get notified of new releases within hours. Planning to keep Zeal updated within a week or two for all our supported releases.

Thanks!
