### ISSUE TITLE
Windows key as modifier does not work in Windows 10

### ISSUE THREAD

**Issue by pszalanski** [zealdocs/zeal#418]
I am not able to use the Windows Key as a modifier, to set `Win+Z` as the shortcut, for example. This would be very handy to avoid conflicting shortcuts.

In **Windows 7** this worked just fine. After my upgrade to **Windows 10** it stopped working.

**Comment by trollixx** [comment]
It looks like we need change hotkey again :( Any suggestions?

**Comment by ChrisRast** [comment]
I use the left Alt key, would it work on all systems ?

**Comment by lusitania** [comment]
Could you shed some light onto why ``Win`` key isn't recognised (just curious)?

+1 for left Alt

Alt-y on QWERTZ keyboards, though.

**Comment by trollixx** [comment]
From [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646309%28v=vs.85%29.aspx):
> Keyboard shortcuts that involve the WINDOWS key are reserved for use by the operating system.

So, we have to come up with another default shortcut.

**Comment by pszalanski** [comment]
Oh noes! Well then this issue is invalid.

**Comment by trollixx** [comment]
Actually, it's not, since a new default needs to be found :)

**Comment by pszalanski** [comment]
One could argue that this would be a new / different issue. But have it your way :smile:

**Comment by lusitania** [comment]
The description of ``MOD_WIN`` sounds more like a recommendation to me rather than a restriction. IMO you are free to listen to any event and let the user decide. A short note mentioning this specific condition should suffice to make a responsible decision, defer any blame from you.

**Comment by trollixx** [comment]
True, it does sound like a recommendation, nevertheless <kbd>Win+Z</kbd> does not work in Windows 10. So I am thinking about another reasonable default.

**Comment by ManuelSchneid3r** [comment]
Why not just <kbd>Alt</kbd>+<kbd>Z</kbd>?

**Comment by trollixx** [comment]
Alt-Z might conflict with hotkeys for menu items or buttons.

**Comment by trollixx** [comment]
Any objections to <kbd>Ctrl+Alt+Z</kbd>?

**Comment by ManuelSchneid3r** [comment]
QWERTZ layout. :D

**Comment by trollixx** [comment]
> QWERTZ layout. :D

Somebody should be painfully executed for that. :( And for AZERTY as well.

If stretching fingers is not an option, then I am out of ideas for a good default.

Currently researching:
* <kbd>Ctrl+Return</kbd>
* <kbd>Ctrl+Alt+Return</kbd>
* <kbd>Ctrl+Alt+Space</kbd>

**Comment by ChrisRast** [comment]
Is there any way to detect the user keyboard configuration and then apply
the equivalent to the "Z" key from QWERTY ?
QWERTY => Z
QWERTZ => Y
AZERTY => W

2016-04-17 16:02 GMT+02:00 Oleg Shparber <notifications@github.com>:

**Comment by trollixx** [comment]
@ChrisRast I think detecting layout is possible, but feels like an overcomplication.

Perhaps, the best option would be not having any shortcut set by default at all, letting users to set anything they want.

**Comment by ManuelSchneid3r** [comment]
Found the idea of <kbd>Ctrl</kbd>+<kbd>Altl</kbd><kbd>Space</kbd> good because it is triggerable without looking on the keyboard and the right hand is not used. But I guess there are still some reasons against this combo. So I guess best way is to leave it up to the user.

**Comment by trollixx** [comment]
So be it, no default shortcut from now on.
