### ISSUE TITLE
Add Ubuntu 15.10 support in ppa 

### ISSUE THREAD

**Issue by pyprism** [zealdocs/zeal#419]

**Comment by jkozera** [comment]
Hmmm, is it necessary? Zeal is now a part of official Debian repositories, so it's available in Ubuntu as well now - http://packages.ubuntu.com/search?keywords=zeal&searchon=names&suite=all&section=all

That said, the [Download page](https://zealdocs.org/download.html) needs updating to reflect this fact.

**Comment by pyprism** [comment]
wow ! I didn't know that . Thanks :smiley:
