### ISSUE TITLE
Update PPA to 0.2.0 release

### ISSUE THREAD

**Issue by ricardoseriani** [zealdocs/zeal#423]
Please, update the ppa (https://launchpad.net/~zeal-developers/+archive/ubuntu/ppa) for the 0.2.0 release

**Comment by KabbAmine** [comment]
:+1:

**Comment by bdjurkan** [comment]
:+1:

**Comment by arichiardi** [comment]
:+1:

**Comment by klonos** [comment]
What the hell... :+1: :stuck_out_tongue: 

...just joking because I realize that +1ing doesn't actually get things done.

**Comment by arichiardi** [comment]
I think this is one of those tasks that just the owner of the ppa can do, otherwise I would have helped gladly. Awesome port BTW, I use it every single day.

**Comment by trollixx** [comment]
Wrong repo, see zealdocs/zeal-packaging#7 :smile: 

P.S. PPA packages are being built right now.
