### ISSUE TITLE
Could you please add Linux Manual :-P

### ISSUE THREAD

**Issue by Mark24Code** [zealdocs/zeal#425]
Could you please add Linux Manual :-P

**Comment by trollixx** [comment]
What do you mean exactly? Man pages?

**Comment by ismail** [comment]
Creating a docset out of http://man7.org/linux/man-pages/ would be nice (don't think this is a zeal TODO though).

**Comment by trollixx** [comment]
Looks like this one is a duplicate of #115 :) Support for native man pages is something to be done.
