### ISSUE TITLE
Meteor Js Docs

### ISSUE THREAD

**Issue by kebeeyong** [zealdocs/zeal#429]
Meteor Js docs  always shutdown my pc when i open it. please help we have tried it on several systems but result.

**Comment by trollixx** [comment]
Hm, I can't reproduce the problem with Zeal 0.2.0 on either Linux or Windows. Meteor docset works just fine. Please provide more information about your system and Zeal version.

**Comment by kebeeyong** [comment]
hp probook zeal 0.1.1

**Comment by trollixx** [comment]
Is it Windows (if so then which version) or Linux? Please also try Zeal 0.2.1.

**Comment by kebeeyong** [comment]
i use ubuntu 14.04, i have tried it with two other ubuntu laptop's and we have same problems, only with Meteor Js Docs, other Docs are working perfectly well.

**Comment by kebeeyong** [comment]
i use zeal 0.2.1 same issues too

**Comment by trollixx** [comment]
It's been a while. Do you still experience this problem? I can't reproduce it on Ubuntu 14.04 with either Zeal 0.2.1 or a newer build from the master branch.

**Comment by Sathors** [comment]
I cannot reproduce it either, using Virtualbox.

If you still have the problem, maybe you could have a look at the logs of your Ubuntu system (the logs are in /var/logs/).

**Comment by trollixx** [comment]
Closing due to lack of response.
