### ISSUE TITLE
zeal doesn't run when there's a broken downloaded docset

### ISSUE THREAD

**Issue by blackarcher21** [zealdocs/zeal#431]
on docsets properties, I have 86.107 files, 21377 folders, size 2.09 GB, size on disk 2.22 GB. temporary solution, I delete docsets location from registry so it set to default then I can open zeal, set docsets location to where I saved them. 

Zeal 0.2.1 on Windows 8.1 x64

**Comment by trollixx** [comment]
Closing if favour of #599.
