### ISSUE TITLE
Colon used for limiting docsets clashes with erlang while searching

### ISSUE THREAD

**Issue by joaocenoura** [zealdocs/zeal#432]
Colon ':' is used in erlang to refer uniquely a function within a module: `module:function`. Since colon is also used for filtering by a given docset, there's a naming clash and Zeal doesn't find what the user is looking for.

Say I want to find the function `insert` of the module `ets`.
If I search "ets:insert", Zeal interprets wrongly "ets" as a docset and doesn't produce any results.
If I search for "erlang:ets:insert" it works as expected/wanted but typing the prefix "erlang:" makes the task unnecessary slower.

**Comment by trollixx** [comment]
Exactly the same problem as #428.
