### ISSUE TITLE
Archlinux: package Error: Qt 5.2

### ISSUE THREAD

**Issue by amerlyq** [zealdocs/zeal#433]
Installing ```zeal``` from AUR:
```
Project ERROR: Qt 5.2.0 or above is required to build Zeal.
==> ERROR: A failure occurred in build().
    Aborting...
```
Dependencies from AUR wasn't fetched.
Whole ```qt5``` group is installed manually. No response.
Which exactly packages from qt5 I'm missing?
I'm exhausted to struggle with this issue each time I think to try zeal along two months.

**Comment by trollixx** [comment]
Zeal needs Qt 5.2.0 or later. If you don't have it, then something is definitely wrong with your system. `makepkg -a` should automatically install all required dependencies. Also, make sure you have `base-devel` package, see the following [article](https://wiki.archlinux.org/index.php/Arch_User_Repository#Prerequisites) for details.

Also, please keep in mind that [zeal](https://aur.archlinux.org/packages/zeal/) AUR package is supported by a 3rd party, so AUR comments might be a better place to ask for help.

**Comment by amerlyq** [comment]
Problem lies in installed both Qt4 and Qt5, therefore ```qtchooser``` in system when installing ```zeal``` wrongly returned ```QT_VERSTION=4.8.7```.
Hotfix for this problem is to install with switched main version:
````bash
$ QT_SELECT=5 sudo pacman -S zeal 
```

**Comment by trollixx** [comment]
Thanks for the details!

Now I see that It is actually explained in [Arch wiki](https://wiki.archlinux.org/index.php/Qt#Default_Qt_toolkit), but without touching Qt 4 for a long time I have never run into such problem.
