### ISSUE TITLE
Can't download docsets

### ISSUE THREAD

**Issue by beojan** [zealdocs/zeal#434]
Selecting a docset then clicking download does nothing.

**Comment by trollixx** [comment]
Are you just selecting the row or checking the check box? Also OS and Zeal version information would be helpful.

**Comment by beojan** [comment]
On 24/11/15 21:33, Oleg Shparber wrote:
> Are you just selecting the row or checking the check box? Also OS and
> Zeal version information would be helpful.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zealdocs/zeal/issues/434#issuecomment-159411451>.
> 
Using the Virtuality (https://github.com/luebking/virtuality) style on
Linux, the check box is invisible. This is not the case in other Qt5
applications.

-- 
Sincerely,

Beojan Stanislaus

**Comment by trollixx** [comment]
I've just tried Zeal and some other Qt 4 and Qt 5 applications with the Virtuality style. Basically everything looks terribly and unusable. Any other Qt style works just fine, but Virtuality messes up everything. I am not sure how that can be resolved on Zeal side.

**Comment by beojan** [comment]
It is indeed a very minimalistic style. However, this problem stems from doing something funny with the checkboxes like changing the foreground color. 

It can be fixed by following the user's system color settings instead of hardcoding colors in Zeal.

**Comment by trollixx** [comment]
Zeal doesn't do anything to affect the default styling. The only place with a custom rendering is the tree view with docset index and search results, but apparently it has no visual issues at all.

I have no idea, why everything is crippled so much in the settings window. No custom styles in use there.

**Comment by trollixx** [comment]
There are no custom styles applied in the settings dialog. If the problem is still there, please report it with the Virtuality style project.
