### ISSUE TITLE
Example search queries don't work

### ISSUE THREAD

**Issue by lusitania** [zealdocs/zeal#438]
Hi

I've tried to replay the example search query in ``https://zealdocs.org/usage.html``:

![python:searc](https://zealdocs.org/static/img/search_filter.png)
```
py:searc
```

That doesn't work. However, typing ``python:searc`` yields the results displayed. The example suggests that prefixes are considered substrings but Zeal apparently doesn't work that way. Is the example wrong? Has it been working in the past because (maybe) queries on the Python docset were (previously?) searched with ``py:`` instead of ``python:``?

Best

**Comment by danlamanna** [comment]
I also encountered this issue with the ```python:bomb``` example.

**Comment by trollixx** [comment]
Thanks for reporting! We really missing #167 here. I'll update the website to match the current behaviour.
