### ISSUE TITLE
Not gaining focus when called via integration, from background

### ISSUE THREAD

**Issue by lusitania** [zealdocs/zeal#440]
Hi

I'm using Zeal with PyCharm 5 and the Dash integration plugin. If I call upon a word and Zeal is in the background (not system tray) I see its icon flashing in the taskbar but it isn't gaining focus. It stays in the background. I need to Alt-Tab into foreground.

Windows 10

Best

**Comment by trollixx** [comment]
[`QWindowsWindowFunctions::setWindowActivationBehavior()`](https://doc.qt.io/qt-5/qwindowswindowfunctions.html#setWindowActivationBehavior) introduced in Qt 5.7 is supposed to fix this problem, but it didn't work for me out of the box. Will investigate further.

**Comment by trollixx** [comment]
Some information from Microsoft: https://blogs.msdn.microsoft.com/oldnewthing/20090220-00/?p=19083
