### ISSUE TITLE
dash-plugin: Add support for prevent_activation parameter

### ISSUE THREAD

**Issue by trollixx** [zealdocs/zeal#448]
According to [atom-dash](https://github.com/blakeembrey/atom-dash/commit/6ffa2598d2d179cfbd52baade670489337588b87) plugin, `&prevent_activation=true` parameter allows to invoke Dash in background. Zeal should provide such feature as well.

**Comment by trollixx** [comment]
@Kapeli are there any other undocumented parameters that Zeal should support?

**Comment by Kapeli** [comment]
`prevent_activation` is the only one.
