### ISSUE TITLE
Cannot download Pandas docset

### ISSUE THREAD

**Issue by MichaelAquilina** [zealdocs/zeal#451]
Although Pandas as listed as a docset on the [dash site](https://kapeli.com/dash), it is not listed as a download option in zeal. I tried manually extracting the tar file to `~/.local/share/Zeal/Zeal/docsets` but this does not seem to work either.

**Comment by JoeScottAnderson** [comment]
I have the same problem.

**Comment by trollixx** [comment]
Added!

**Comment by MichaelAquilina** [comment]
Can confirm it works. Thanks for this!

**Comment by JoeScottAnderson** [comment]
Yes, thank you! Works fine. 

 

Joe
