### ISSUE TITLE
Failing to install on Debian (from PPA or from source)

### ISSUE THREAD

**Issue by bnvk** [zealdocs/zeal#455]
Since there is no package in Debian, I tried using the Ubuntu PPA as that sometimes works. However, it fails with the following:

```
Ign https://deb.nodesource.com jessie/main Translation-en                                
Fetched 819 B in 7s (108 B/s)                                                            
W: Failed to fetch http://ppa.launchpad.net/zeal-developers/ppa/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
user@code:~$ sudo apt-get install zeal
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package zeal
```

I think I remember a friend once showing me some hacky way around this issue, but my sysadmin skillz / memory are failing me.

So I tried to compile from source. After installing what seemed to be the right packages `qt5-default qt5-qmake libarchive-dev` I get the following error:

```
cd src/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/user/zeal/src/src.pro -o Makefile ) && make -f Makefile 
Project ERROR: xcb-keysyms development package not found
Makefile:38: recipe for target 'sub-src-make_first-ordered' failed
make: *** [sub-src-make_first-ordered] Error 3
```

Any help would be much appreciated. I am using Debian Jessie!

**Comment by trollixx** [comment]
There are no packages for Debian in PPA, that's why the URL with `jessie` returns zero. Zeal is available in the official repositories for Debian [testing and unstable](https://packages.debian.org/search?suite=all&searchon=names&keywords=zeal).

You need `libxcb-keysyms1-dev` package for the `xcb-keysyms` dependency.

**Comment by bnvk** [comment]
@trollixx heya thanks for replying. I'm unable to use testing and unstable on my current machine- so compiling is my only option.

I was able to get it to compile, but in additional the lib you mentioned I also needed to install  `libqt5webkit5-dev` as well as `libqt5x11extras5-dev` which you may want to make note of somewhere :)

**Comment by trollixx** [comment]
https://github.com/zealdocs/zeal-packaging/blob/master/ubuntu-ppa/debian/control#L5

There are no per distribution instructions yet.
