### ISSUE TITLE
Jekyll docset

### ISSUE THREAD

**Issue by KabbAmine** [zealdocs/zeal#467]
Dash is providing a [docset for jekyll](https://kapeli.com/dash#docsets), so why zeal is not using it? I thought that both applications are sharing the same docsets.

Meanwhile, I'm using this [one](https://github.com/damir-cuturic/jekyll.docset) that looks up-to-date, it will be good then to integrate it officially to zeal or add it to #315 list.

**Comment by trollixx** [comment]
The recently added Dash docsets do not appear automatically in Zeal at the
moment.

I'll add Jekyll and a few other new Dash docsets later today.

**Comment by KabbAmine** [comment]
Ok, good then. The issue may be closed.

**Comment by trollixx** [comment]
Jekyll (from Dash) is in the catalogue now. #315 has been amended too.

**Comment by KabbAmine** [comment]
Thanks :+1:
