### ISSUE TITLE
AngularJS example rendering problem

### ISSUE THREAD

**Issue by tej-kweku** [zealdocs/zeal#469]
On both zeal of Windows and Linux, the example code snippets for the AngularJS docset render an empty div which is not that which is expected

**Comment by trollixx** [comment]
Are you talking about the empty rectangle that appears after clicking `Run online demo` button?

**Comment by tej-kweku** [comment]
yes, please

**Comment by trollixx** [comment]
The report is old, and the docset looks fine now.
