### ISSUE TITLE
Dash URL handlers do not work with KDE

### ISSUE THREAD

**Issue by trollixx** [zealdocs/zeal#471]
Reported in blakeembrey/atom-dash#31 by @dirtyvader:

> I use the zeal-git package on Archlinux, it contain the .desktop file and the scheme handler is registered (`xdg-mime query default x-scheme-handler/dash-plugin` return the right desktop file`).
But KIO Client complains about malformed url, it doesn't like a URI scheme without host.

> P.S. I'm on KDE/plasma 5

**Comment by dirtyvader** [comment]
@trollixx thanks !

`xdg-open dash-plugin://query=.SetFlags`
-> `Invalid hostname (contains invalid characters); source was "dash-plugin://query=.SetFlags"; scheme = "dash-plugin", host = ""`

**Comment by dirtyvader** [comment]
OK found something:
actually, `xdg-open dash-plugin:/query=.SetFlags` (with one /) open zeal, but query string is not take into account

**Comment by trollixx** [comment]
How about `xdg-open dash-plugin:query=.SetFlags`?

**Comment by dirtyvader** [comment]
@trollixx Oh yes! It works!

**Comment by trollixx** [comment]
Closing this, as it should be fixed in the Atom plugin (more [details](https://github.com/blakeembrey/atom-dash/issues/37#issuecomment-237140968)).
