### ISSUE TITLE
Application failed to start on Windows 7

### ISSUE THREAD

**Issue by MrLeeh** [zealdocs/zeal#477]
I downloaded the binary installer msi for Windows and installed Zeal on a Windows 7 platform.
When starting the application I get the following error:

> This application failed to start because it could not find or load the Qt platform plugin "windows".
> Available platform plugins are: minimal, offscreen, windows.
> Reinstalling the application my fix the problem.

Afterwards I get the following error message from Microsoft Visual C++ Runtime Library

> This application has requested the Runtime to terminate it in an unusual way. Please contact the
> applications' s support team for more information.

Found out the problem only appears when using the link from the Windows Startmenu. When starting the zeal.exe directly everything is fine. Wonders me because the Link points to "C:\Program Files (x86)\Zeal\" as working directory.

**Comment by MrLeeh** [comment]
Just found out that I have to set the environment variable `QT_QPA_PLATFORM_PLUGIN_PATH` to point to `c:\Program Files (x86)\Zeal\platforms` to get it working with the link. But actually this should not be necessary.

**Comment by trollixx** [comment]
It's really strange you needed the env variable to make it work. Qt is supposed to discover the plugin automatically. Do you have Qt SDK installed on your system?

**Comment by MrLeeh** [comment]
Yes I' ve got Qt 5.5 installed on my system. For me this issue seems to double with #347. I tried the workaround of adding qt.conf with

    [Paths]
    Prefix = .

and it worked out for me. Maybe just add the qt.conf to the binary installation and prevent such errors.

**Comment by trollixx** [comment]
I think I have found the reason: [QTBUG-41842](https://bugreports.qt.io/browse/QTBUG-41842). The solution is to use `windeployqt`, that patches hard-coded paths in QtCore binary.

Could you try [0.2.1](https://bintray.com/artifact/download/zealdocs/windows-ci/zeal-stable/zeal-stable-0.2.1-windows-x86.zip) build from CI? It does use `windeployqt` tool during packaging.

**Comment by MrLeeh** [comment]
Thanks. The build from CI works out of the box.

**Comment by trollixx** [comment]
Thanks for confirming. I'll make sure to use `windeployqt` for the installer packages as well.

**Comment by trollixx** [comment]
I'll keep this open as a reminder.
