### ISSUE TITLE
Keyword autocomplete is not updated on docset removal

### ISSUE THREAD

**Issue by trollixx** [zealdocs/zeal#478]

**Comment by drognanar** [comment]
I believe the fix for this issue is a part of my perf PR #460 (see 4883746349).
Do you want me to cherry-pick this into a separate PR?

**Comment by trollixx** [comment]
That would be great. Just add `(fixes #478)` to the commit message, and I'll merge it.

Just remove the part about the `Open in Browser` button, I am not sure that would build with QWebEngine.
