### ISSUE TITLE
Provide vi like keybindings

### ISSUE THREAD

**Issue by oblitum** [zealdocs/zeal#481]
It's quite common on Linux land to be able to at least scroll up and down with vi like keybinds like `j` and `k`. I see I can already find in page with `/` and exit find with ESC, which is nice. More bindings besides single line scroll like `CTRL-d` and `CTRL-u` (or just `d` and `u`) for half page scroll and `CTRL-f`/`CTRL-b` for full page scroll would be nice.

**Comment by Johnstone-Tech** [comment]
I have been using [Autokey](https://github.com/autokey-py3/autokey-py3) to simulate some simple vi keybindings, mainly navigation at the minute.

**Comment by trollixx** [comment]
Let's consider this a duplicate of #10. Both issues will be fixed with a unified approach of having configurable profiles for key bindings.
