### ISSUE TITLE
Start minimized is broken

### ISSUE THREAD

**Issue by wenLiangcan** [zealdocs/zeal#484]
My system is Arch Linux with Plasma 5. I built zeal from the newest source code.

**Comment by trollixx** [comment]
Looks like X11 only.

**Comment by hexchain** [comment]
I'm also on Arch Linux, with Awesome WM. The problem does not exist in v0.2.1 but in master.

`git bisect` shows that 8f157435abfc4d7d567ea3fb1a642a9fc42ed705 is the first bad commit.

**Comment by wenLiangcan** [comment]
It is worked again after building from commit 99af6ea (though I'm not sure it is fixed by this commit or previous ones).

**Comment by hexchain** [comment]
Did you upgrade to Qt5.6?

**Comment by wenLiangcan** [comment]
No, my Qt5 version is 5.5.1. @hexchain

**Comment by hexchain** [comment]
I've tried rebuilding Zeal master with Qt 5.6.0 but the problem still persists. Could you please double check whether it's really fixed?

**Comment by wenLiangcan** [comment]
I'm 100% sure it's fixed. And these are my Zeal settings:

![selection_005](https://cloud.githubusercontent.com/assets/1244181/13913978/605a69ba-ef86-11e5-984c-d0234116e8b9.png)

**Comment by wenLiangcan** [comment]
@hexchain I made a screencast

![anim](https://cloud.githubusercontent.com/assets/1244181/13914313/84cf7d74-ef88-11e5-94d6-37e561e19ecf.gif)

**Comment by trollixx** [comment]
@hexchain It indeed doesn't work with Awesome WM. Perhaps a bug there...

**Comment by trollixx** [comment]
I guess Awesome WM just ignores window hints in favour of its current layout preferences. There's nothing we can do about that. Please report with the Awesome WM project, if this is a problem for you.
