### ISSUE TITLE
Portable build support

### ISSUE THREAD

**Issue by trollixx** [zealdocs/zeal#486]
A portable build (`CONFIG+=portable`) has the following issues:

* [x] Docset list cache is always kept in the system's cache location for the application.
* [x] Partial downloads are kept in the global place for temporary files.

**Comment by vgturtle127** [comment]
@trollixx Just to clarify, this doesn't use the registry or AppData/ProgramData, right? In portable mode, I mean?

**Comment by trollixx** [comment]
When Zeal is built in the portable mode, an .ini next to the executable is used for storing settings.

**Comment by vgturtle127** [comment]
@trollixx OK, that makes sense.

Does Zeal default to using the registry otherwise?

**Comment by trollixx** [comment]
Correct. Zeal defaults to whatever Qt considers [a native format](http://doc.qt.io/qt-5/qsettings.html#Format-enum) on a particular platform.

**Comment by vgturtle127** [comment]
@trollixx Oh, OK. You could always just default to an .ini file, that way it would be portable no matter what. :wink:

**Comment by trollixx** [comment]
True, but it wouldn't be polite I think. :) I prefer to default to platform's standard way of storing settings.

**Comment by vgturtle127** [comment]
@trollixx Yeah, that's true. Thanks for this! :+1:
