### ISSUE TITLE
Cant open zeal from tray.

### ISSUE THREAD

**Issue by ManuelSchneid3r** [zealdocs/zeal#487]
![Pic](http://i.imgur.com/33C7ChV.png)

This is a blocker. I forgot my hotkey. Zeal is inaccessible.

Archlinux, zeal-git 0.2.1.10.g57185b4-1, cinnamon

**Comment by trollixx** [comment]
What's your desktop environment? AppIndicator menu has a Show/Hide item
(since 0.2.0). And a tray icon is expected to support single mouse clicks.

As a quick solution take a peek in `~/.config/Zeal/Zeal.conf`.

**Comment by ManuelSchneid3r** [comment]
Cinnamon 2.8.6-1. I checked this. The hotkey doesn't work either, but thats an other issue.

**Comment by trollixx** [comment]
Interesting. I'll need to install Cinnamon, and check. It's unclear whether
it is a tray icon or indicator.

Do you have `sni-qt` or `sni-qt5` package installed?

**Comment by ManuelSchneid3r** [comment]
>Do you have `sni-qt` or `sni-qt5` package installed?
No. I just installed `sni-qt` but nothing changes. However pacman desription says its a qt4 plugin. `sni-qt5` is not available in the official repos.

**Comment by ManuelSchneid3r** [comment]
I asume you reply per mail so probably you didnt notice the edits. Once again:

>Do you have `sni-qt` or `sni-qt5` package installed?

No. I just installed `sni-qt` but nothing changes. However pacman description says its a qt4 plugin. `sni-qt5` is not available in the official repos. 

Maybe this is of interest. I know nothing about tray icons and indicators, but somehow regardung userexperience there are two categoreies of tray icons: The first opens the app on leftclick, rightclick opens a context menu. The second opens the context menu on left click, right-click opens the context menu of the cinnamon systray applet, wich contains the systray icons. Zeal and Telegram behave like the latter.

**Comment by ManuelSchneid3r** [comment]
Additional things that may be helpful:

- Zeal and Telegram are both qt5. Goldendict (qt4) is of the first group.
- [This SO answer](http://stackoverflow.com/questions/17193307/qt-systray-icon-appears-next-to-launcher-on-ubuntu-instead-of-on-the-panel/17503036#17503036)

**Comment by trollixx** [comment]
Looks like the problem is Cinnamon specific:
https://github.com/linuxmint/Cinnamon/issues/4946

One of the comments mentions that it's possible to disable indicators
(icons which show menu on left click) via “System Settings” -> “General” ->
“Enable support for indicators”.

I need to figure out whether Cinnamon is compatible with Unity's
indicators. If so, a detection of Cinnamon in Zeal will fix the actual
problem.

**Comment by trollixx** [comment]
I've got Cinnamon 2.8.6 on Mint 17.3, and I cannot reproduce this. Zeal is always using tray icon, so I can do a left click to show and hide it. I am not sure how to make it an indicator...

**Comment by trollixx** [comment]
@ManuelSchneid3r, please verify that the problem is fixed for you.

**Comment by ManuelSchneid3r** [comment]
With support for indicators
![](http://i.imgur.com/P4LIOFx.png)
Without support for indicators
![](http://i.imgur.com/KViTspb.png)
zeal-git 0.2.1.44.ga96c79b-1

**Comment by trollixx** [comment]
Hm, I it's definitely not using indicator API.

What are values of XDG_CURRENT_DESKTOP and CINNAMON_VERSION environment
variables?

**Comment by ManuelSchneid3r** [comment]
XDG_CURRENT_DESKTOP=X-Cinnamon
CINNAMON_VERSION=2.8.6

**Comment by ManuelSchneid3r** [comment]
Just debugged it. USE_APPINDICATOR is somehow not set, detectAppIndicatorSupport not executed.

**Comment by trollixx** [comment]
Wait, you are using zeal-git from AUR, right? Install libappindicator-gtk2
[0], and then rebuild Zeal.

0. https://aur.archlinux.org/packages/libappindicator-gtk2/

**Comment by ManuelSchneid3r** [comment]
Okay eventually it works. libappindicator should be at least a optinal dep in the PKGBUILD. Furthermore somehow I encoutered moments where CINNAMON_VERSION was not set.

From the user experience point of view, I find this indicator annoying. The old style "toggle visibility on left click, context on right-click" was much more convenient.

**Comment by trollixx** [comment]
Yeah, UX is terrible. I don't know why everyone is switching to indicators.

I will add an optional dependency to the AUR package.

With the switch to Qt 5.5 (once Ubuntu 16.04 is out), I am going to remove
all custom handling for different kinds of system trays. What you
experienced initially is exactly that - QSystemTrayIcon with D-Bus backend.

Unfortunately, I don't see an API to tell what backend is being used do I
can add hide/show entry in case of it's an indicator.
