### ISSUE TITLE
zeal crash on openning

### ISSUE THREAD

**Issue by agentready** [zealdocs/zeal#489]
zeal crash every time I open it. In terminal I see this message --> 
```
Cannot determine index file for docset SQLite
QxtGlobalShortcut failed to register: Meta+Z
Segmentation fault (core dumped)
```
I've installed zeal from ppa and my os ubuntu 14.0.4

**Comment by trollixx** [comment]
What's your docset list? Looks like one of the docsets is corrupted. Any were manually installed?

**Comment by agentready** [comment]
Hi thanks for reply , here is my docset list --> http://pastebin.com/v1KRJfsk , I didn't manually installed anything. One thing I can remember while downloading a doc my laptop were hanged by another app and I did hard restarted the laptop.

**Comment by trollixx** [comment]
A corrupted docset might cause the problem somehow sneaking through the checks.

You can try to remove SQLite docset folder, and see whether it is the source of the issue.

**Comment by agentready** [comment]
Hi, Thanks again for the reply. Yes, after removing SQLite doc folder it only saying 
```
QxtGlobalShortcut failed to register: Meta+Z
Segmentation fault (core dumped)
```
After removing every docset folder, it is working except QxtGlobalShortcut.

**Comment by trollixx** [comment]
My guess is that that not fully downloaded docset was an issue. Unfortunately, it's hard do tell what exactly caused an issue, unless you kept all folders, so we could check which one was corrupted one by one.

I've fixed the index file issue with SQLite docset. Requires a reload of the docset database, and reinstalling of the docset itself.

`QxtGlobalShortcut` issue is interesting, what your desktop environment?
