### ISSUE TITLE
Dialog change for clarity

### ISSUE THREAD

**Issue by vgturtle127** [zealdocs/zeal#492]
I think the update window should read "You are using the latest version of Zeal" instead of "You are using the latest Zeal version". It is more clear and proper that way.

The option in the help menu should also be changed to "Check for updates..." instead of "Check for Update...". this looks much better and is more proper.

**Comment by trollixx** [comment]
Thanks for this and all other reports. Feedback is very appreciated! Our UI/UX definitely lacks attention.

**Comment by vgturtle127** [comment]
@trollixx Absolutely, I really like Zeal and I think it is the best offline documentation browser, so naturally I want to see it exceed and also maintain feature parity with other offline documentation browsers. :smile: Thanks for the quick resolution!
