### ISSUE TITLE
About dialog menu changes

### ISSUE THREAD

**Issue by vgturtle127** [zealdocs/zeal#495]
I think the "About" dialog could be changed to look more (for lack of a better word) organized.

Firstly, we should remove the "About" tab, since I don't think we are going to put anything else on the "About" dialog. :smile: 

After that, it should look like this (in my opinion):

**A simple offline documentation browser**

Zeal is open-source software licensed under the GNU GPL version 3 (GPLv3)

Website: zealdocs.org
GitHub: https://github.org/zealdocs/zeal
IRC: #zealdocs on Freenode

Copyright (C) 2016 Zeal contributors

Docsets are courtesy of Dash

Notice the lack of punctuation, I think it is unnecessary for this "About" dialog, due to how it is formatted.

Also change the link to GNU.org to the HTTPS version, to protect users.

Anyway, that's what I think. Feedback is appreciated.

**Comment by trollixx** [comment]
Getting to this one has taken more time than it should have.

The tab widget is there for the future use. I need to add a list of licences of all other open source projects Zeal utilises.

I'll fix links right away.

I am really not sure about punctuation. It seems to me that if a sentence starts with a capital letter, it should and with a period as well. I've checked a few about dialogues, and they do have complete sentences.

**Comment by vgturtle127** [comment]
@trollixx That's alright, people have lives and things. :smile: 

I agree about the punctuation, actually, now that I think about it.

Fixing the links shouldn't be terribly difficult, as mostly you just add an "S" to "http".

I didn't know you had .ui files, that's pretty cool.

The tabs are cool if you use them, but I see one tab on many about dialogs and it bothers me for some reason if there is only one tab. I have programming OCD or something. :stuck_out_tongue_closed_eyes:
