### ISSUE TITLE
Provide binary Linux packages

### ISSUE THREAD

**Issue by vmalloc** [zealdocs/zeal#5]

**Comment by trollixx** [comment]
We are not going to provide Mac OS X packages due to our agreement with Dash author.

More Linux binary packages will be available at some point (through [Open Build Service](http://openbuildservice.org/), I guess). Perhaps, some distributions would maintain Zeal packages on their own.

**Comment by trollixx** [comment]
Today many Linux distributions provide Zeal from their official repositories. Ubuntu PPA is kept up to date as well. I think this issue can be finally closed.

Any new packaging request should go to [zeal-packaging issue tracker](https://github.com/zealdocs/zeal-packaging/issues). There are currently two requests for [DEB](https://github.com/zealdocs/zeal-packaging/issues/11) and [RPM](https://github.com/zealdocs/zeal-packaging/issues/14) packages pending investigation.
