### ISSUE TITLE
Unpacking overload

### ISSUE THREAD

**Issue by Albatrosicks** [zealdocs/zeal#503]
Windows 10
100% HDD load when docset unpacking after downloading
![screenshot_20-02-03_29-02-29](https://cloud.githubusercontent.com/assets/16649264/13395964/877c0a16-df24-11e5-9281-e305707f79db.png)

**Comment by vgturtle127** [comment]
@Albatrosicks What do you mean "100% HDD load"? Do you mean that your hard drive is filling up or do you mean your hard drive is somehow working harder than it should? This would be a hardware issue, not a Zeal issue. Unless Zeal has some terrible code or something.

**Comment by trollixx** [comment]
Unpacking a docset can be creating hundreds of files on disk. I don't see
what is wrong with the high disk utilisation during this process. Does it
stop once a docset is installed?

**Comment by trollixx** [comment]
Closing this, because creating hundreds of small files does cause serious HDD load, there's nothing wrong about that. With #138 implemented things should get better.
