### ISSUE TITLE
Documentation request:  DOM and DOM Events

### ISSUE THREAD

**Issue by Withany** [zealdocs/zeal#504]
Hello,

Please include DOM reference as this is important for Javascript.

Thanks

**Comment by trollixx** [comment]
We don't actually produce any of the docsets. They all come from [Dash](https://kapeli.com/dash). If it's not already part of JavaScript or HTML docsets, then you could [contribute](https://github.com/Kapeli/Dash-User-Contributions) the docset, or at least create a request there.
