### ISSUE TITLE
update button is disabled after update

### ISSUE THREAD

**Issue by smsrkr** [zealdocs/zeal#505]
Suppose two docsets have updates available. I start updating the first one, then select the second while that's progressing.
Now after the first update is complete, the update button remains disabled even though current selection can be updated.
Using the 0.2.1 Windows release.
[<img src="http://i.imgur.com/nYWlFBv.png" >](http://i.imgur.com/nYWlFBv.png)

**Comment by trollixx** [comment]
Fixed in 0.3.0.
