### ISSUE TITLE
Chinese characters are corrupted after unpacking HTML docset

### ISSUE THREAD

**Issue by zjzdy** [zealdocs/zeal#508]
My system is Windows 7 zh_CN.
System default code is GBK.
In HTML.tgz\HTML.docset\Contents\Resources\Documents\mdn.mozillademos.org\zh-CN\docs\Web\HTML\Element\datalist$samples\ have a file is 示例426e.html.But file name is ê?ày426e.html in system.
![4](https://cloud.githubusercontent.com/assets/10596496/13548015/3c0903cc-e320-11e5-9028-96e9411ace72.png)

Then std::ifstream can't find file and QIODevice::read: device not open.

**Comment by vgturtle127** [comment]
@zjzdy Does this happen on an English Windows 7?

**Comment by zjzdy** [comment]
@vgturtle127 I don't know.Because I hadn't installed English Windows.You can try it.

**Comment by vgturtle127** [comment]
@zjzdy I am using Windows 10, so I don't know if the problem will exist since localization has changed a lot since Windows 7...

**Comment by trollixx** [comment]
Don't look in the commit above, it's not relevant, and does not include my attempt to fix the issue.

It looks like that there's no good way to fix this problem until [an issue](https://github.com/libarchive/libarchive/issues/587) in libarchive is resolved.

**Comment by trollixx** [comment]
Looks like I've missed `archive_entry_pathname_w()` which is hacky, but should fix the issue on Windows.

**Comment by vgturtle127** [comment]
@trollixx Oh, thanks. I had no idea!

**Comment by trollixx** [comment]
@zjzdy where exactly does your HTML.docset come from?

**Comment by trollixx** [comment]
I've committed a workaround, but I am unable to test it. Please grab a [CI build](https://bintray.com/zealdocs/windows-ci/zeal-unstable/view), and test. Let me know if the problem is solved or not.
