### ISSUE TITLE
Download doesn't work

### ISSUE THREAD

**Issue by bwalle** [zealdocs/zeal#512]
I compiled Zeal on OS X and discovered that (in current git 6cd537d21c82bb3cc53fa0951402ab098772a963) the download doesn't work.

I found out that listItem->data(ListModel::DocsetNameRole) is QVariant(Int, 0). Changing the enum value of either ProgressItemDelegate::ValueRole or ListModel::DocsetNameRole fixes the issue.

I'm wondering why the download works at all...

**Comment by trollixx** [comment]
Thanks for reporting, fixed!
