### ISSUE TITLE
Navigating to Scala methods is broken due to percent-encoded urls

### ISSUE THREAD

**Issue by smarter** [zealdocs/zeal#513]
Reproduction:
1. Download the Scala docset
2. Search for `foldLeft`
3. Notice that the first result is `scala.collection.generic.TraversableForwarder.foldLeft`, but if you click on it you get to the top of the page instead of getting to the method `foldLeft`

The URL of the method is `file:///home/smarter/.local/share/Zeal/Zeal/docsets/Scala.docset/Contents/Resources/Documents/scala/scala-library-2.11.8-javadoc/scala/collection/generic/TraversableForwarder.html#foldLeft[B]%28B%29%28%28B,A%29%E2%87%92B%29:B`

I solved this issue locally by reverting https://github.com/zealdocs/zeal/commit/2318f463fc34f989f3b8512334aa680fb3663f0f

**Comment by trollixx** [comment]
I am not yet sure how to fix this one without breaking nginx docset (#121).
