### ISSUE TITLE
error while compiling main.cpp

### ISSUE THREAD

**Issue by zombieleet** [zealdocs/zeal#515]
i get this error when i run make

compiling main.cpp
In file included from main.cpp:24:0:
core/application.h:50:5: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
     explicit Application(QObject *parent = nullptr);
     ^
main.cpp:28:30: fatal error: QCommandLineParser: No such file or directory
 #include <QCommandLineParser>
                              ^
compilation terminated.
Makefile:602: recipe for target '/.obj/main.o' failed
make[1]: *** [/.obj/main.o] Error 1
make[1]: Leaving directory '/root/zeal/src'
Makefile:39: recipe for target 'sub-src-make_default-ordered' failed
make: *** [sub-src-make_default-ordered] Error 2

**Comment by zombieleet** [comment]
i have fixed the problem already. after thorough googling . but i now get 
fatal error: QObject: No such file or directory
 #include <QObject>

**Comment by trollixx** [comment]
It looks like you have an issue with your Qt installation. Sometimes this happens when Qt 4 and Qt 5 get mixed up somehow.

Zeal requires Qt 5.2+ and a compiler that supports C++11. What are your OS, Qt and compiler versions?

**Comment by zombieleet** [comment]
i use debian , Qt version 5.6.0. Actually i pulled zeal again, and did qmake && make, so i don't get that error any more,. I need to install libqt5webkit5-dev, but when ever i do apt-get install libqt5webkit5-dev, the packages that needs to be removed before installing libqt5webkit5-dev are important packages e.g emacs, gdm3

**Comment by trollixx** [comment]
That's weird, it shouldn't ask you to remove anything. But it's really a question for the package maintainers.

On another note, for Debian testing and unstable Zeal is available from the [official repositories](https://packages.debian.org/search?suite=all&searchon=names&keywords=zeal).

**Comment by zombieleet** [comment]
even after fixing the dependency issue, and installing libqt5webkit5-dev i still get the same error

**Comment by zombieleet** [comment]
i installed zeal from the package manager and it worked. thanks very much
