### ISSUE TITLE
Previous tab keyboard shortcut not working

### ISSUE THREAD

**Issue by Code-Curious** [zealdocs/zeal#518]
The ctrl+tab shortcut for switching to the next tab does work, but the other one, `ctrl+shift+tab`for switching to the previous one does not. When I go to **Tabs menu**, it says the corresponding shortcut is `ctrl+shift+Backtab` instead of `ctrl+shift+tab`.

**Comment by trollixx** [comment]
[QTBUG-15746](https://bugreports.qt.io/browse/QTBUG-15746) is causing the problem. Adding a workaround for now...
