### ISSUE TITLE
Ubuntu - Gnome Desktop Unusable

### ISSUE THREAD

**Issue by drpain** [zealdocs/zeal#519]
Hi There,

According to the documentation:
https://zealdocs.org/usage.html

I should have a file menu, but on Ubuntu with Gnome desktop there is no **"After installing Zeal go to File ⟶ Options ⟶ Docsets to browse and download docsets."** 

Can anyone explain how to create docsets manually?

Please see the image below:
![Screenshot](http://i.imgur.com/nTEnhyi.png)

**Comment by jkozera** [comment]
See #253 - known issue with Ubuntu.

**Comment by drpain** [comment]
What a shame, tnx for the update
