### ISSUE TITLE
Tab bar for pages is never populated as a result there's only one tab

### ISSUE THREAD

**Issue by sudhirkhanger** [zealdocs/zeal#520]
Hi,

I am using zeal-0.2.1-1.fc23.x86_64 on Fedora 23 installed from the Fedora repository.

When I browse several pages I notice there's only one tab all the time. The tab bar is not populated with multiple tabs.

![snapshot114](https://cloud.githubusercontent.com/assets/841656/14043562/a7b94880-f2ab-11e5-81c6-6e9ac459a514.png)

**Comment by sudhirkhanger** [comment]
Looks like I might not be sure how tabs are suppose to work. I have to open them up manually. If I open more pages they all go in the same tab and then I use those two buttons in the left to browse history of each individual tab.

If that is the case please close this bug.

**Comment by trollixx** [comment]
Please try the following:
1. Click `Open in New Window` in a context menu of any link withing a page.
2. Middle click on a link.

**Comment by sudhirkhanger** [comment]
When I click on `Open in New Window` or middle click a link in page then indeed it opens in a new tab. Basically I need to manually open the tabs.

Another thing is clicking on `Open in New Window` causes Zeal to crash. I reported it via Fedora bug tracker here https://bugzilla.redhat.com/show_bug.cgi?id=1321356.

**Comment by trollixx** [comment]
Were you expecting a new tab for every item selected from the left pane?

The crash seems to be coming from WebKit, and that it now obsolete and not supported. Zeal will be switching to Qt WebEngine by default shortly. Support for Qt WebKit will be dropped after 0.3.0 is out.

**Comment by sudhirkhanger** [comment]
@trollixx I have just started using Zeal so yeah that's what I was expecting.
