### ISSUE TITLE
Double clicking on some of the Scala docset's Hierarchy sections makes Zeal crashed

### ISSUE THREAD

**Issue by wenLiangcan** [zealdocs/zeal#521]
Some pages of the Scala docset contain sections called `Content Hierarchy` or `Type Hierarchy`.

Below is the `Type Hierarchy` section of `CanBuildFrom` `trait`:

![selection_005](https://cloud.githubusercontent.com/assets/1244181/14113658/8020e1ee-f606-11e5-9d45-84f1be54c84d.png)

If the diagram is too large, it allows us to zoom in the details, double clicking on such a diagram makes Zeal crashed.

And I got messages like this from the terminal:

``` bash
$ zeal
[1]    27007 segmentation fault (core dumped)  zeal
```

**Comment by trollixx** [comment]
Looks like another Qt WebKit bug. Zeal is switching to Qt WebEngine by default, that should fix such issues. In the meanwhile you can build Zeal by yourself.

**Comment by trollixx** [comment]
This is an old report, and Scala docset no longer has the diagrams for the test case.
