### ISSUE TITLE
Check if docset storage is read only

### ISSUE THREAD

**Issue by okingniko** [zealdocs/zeal#522]
After  download docsets,  I can see the contents under _C:\Users\Administrator\AppData\Local\Zeal\Zeal\docsets_ on my PC , But I Cannot see them in **Installed docsets** section.

**Comment by trollixx** [comment]
Is it happening for any docsets or only some specific ones? What's your Windows version?

**Comment by okingniko** [comment]
I have tried several docsets(e.g. c, c++, boost, python2, markdown), but it doesn't work as expected.
My Windows version is Windows7_Ultimate_x64.
Hope you can give me some suggestions, Thank you :）

**Comment by alex-fgsfds** [comment]
The same for me. Windows 10, docsets are being downloaded and "installed", yet never show up under Installed docsets list nor in main window. But when I changed the default docset dir to C:\Zeal\docsets\, it started working properly. I guess there's something with folder permissions preveting Zeal to unpack them properly.

**Comment by trollixx** [comment]
@alex-fgsfds do you also work under Administrator account? What was the default docset storage path?

**Comment by alex-fgsfds** [comment]
Yes, I am under admin account. The default storage path was in /AppData. Didn't try to run the Zeal as an admin though.

**Comment by trollixx** [comment]
My guess is that running apps while logged in as Administrator, by default doesn't give then superuser permissions.

Zeal should check for this case, and notify if it can't write to the docset storage path.
