### ISSUE TITLE
Search results are slow to appear

### ISSUE THREAD

**Issue by ssokolow** [zealdocs/zeal#523]
While #265 seems to be about the GUI lagging while typing, I have a different "slow search" problem.

While I don't have a problem with GUI lag, I have 83 docsets installed and, even when using a prefix like `css:`, I find it can take several seconds for search results to appear. (I suspect this to be a combination of find-as-you-type and my use of a traditional 7200rpm rotating rust hard drive.)

I'm not sure how much can be done, but I thought I'd bring it up. (Might it help to add a checkbox for slow systems which defers the find-as-you-type until the lesser of X characters or Y seconds has passed to make effective use of the SQLite indexes, then filters within the in-memory results as more characters arrive?)

**Comment by trollixx** [comment]
Hopefully, #460 addresses the problem. While not the perfect solution, it makes search faster by running it in the multiple threads, and utilising additional caching. The change should make it into 0.3.0.

**Comment by ssokolow** [comment]
Good to hear. :)

**Comment by trollixx** [comment]
There were numerous improvements in the search and general performance. Please give a freshly built Zeal a try. I am closing this in favour of #265 to keep all search performance issues in one place.
