### ISSUE TITLE
under windows, the suggest functions list's word be truncated

### ISSUE THREAD

**Issue by huangwei1024** [zealdocs/zeal#525]
![image](https://cloud.githubusercontent.com/assets/667876/14316764/62e0cfd6-fc37-11e5-858a-22e833b8a2d1.png)

**Comment by trollixx** [comment]
The underlying logic has been significantly redone, and should not happen any more. You can give [CI build](https://bintray.com/zealdocs/windows-ci/zeal-unstable/view) a try, to see if the issues is actually fixed.

**Comment by trollixx** [comment]
Duplicate of #262, which is fixed now.
