### ISSUE TITLE
Where are docsets downloaded from?

### ISSUE THREAD

**Issue by djmattyg007** [zealdocs/zeal#530]
The title says it all really. I'm curious to know where the docsets are downloaded from.

**Comment by haiya512** [comment]
the famous docsets such as ansible whose website is stable, so I guess it is written in the code.

and you could add website(s) you want to download

**Comment by trollixx** [comment]
All currently available docsets come from Dash. You can see the list [here](http://kapeli.com/docset_links). Our redirect server just chooses a mirror closest to the user via GeoIP.

**Comment by djmattyg007** [comment]
Excellent, thank you very much!

**Comment by djmattyg007** [comment]
Actually I did have nother question - where are the feeds downloaded from that contain references to the docsets?
