### ISSUE TITLE
[UI] request for mono style icon

### ISSUE THREAD

**Issue by alim0x** [zealdocs/zeal#534]
![screenshot from 2016-04-16 23-51-55](https://cloud.githubusercontent.com/assets/4954007/14582103/4f865de4-042e-11e6-96da-c330fbcc2847.png)

This is current tray icon, I think maybe a single color icon is better for tray, just like other tray icon :)

**Comment by trollixx** [comment]
Usually icon themes provide icons for different applications, so I am not sure it's the right place to request an icon.

**Comment by alim0x** [comment]
OK... thanks for reply, maybe I should request it from icon theme :)
