### ISSUE TITLE
Crazy list issue (list item not showing well)

### ISSUE THREAD

**Issue by Z-Clive** [zealdocs/zeal#537]
Hello guys, again,

I am using the latest version of `Zeal` on `Windows 10`, and aside from the funny font thing, I've also encountered something really strange.

The problems are shown as follows (when searching `font.` with `.Net Framework` docset installed), I have marked the issues already:

![1](https://cloud.githubusercontent.com/assets/11990819/14597981/aa64976c-0582-11e6-821c-5cd1a430d96e.png)

**Comment by trollixx** [comment]
@Z-Clive it's been a while, but could you give a recent [CI build](https://bintray.com/zealdocs/windows-ci/zeal-unstable/view) a try? A lot of related code have been changed, hopefully fixing this problem as well.

**Comment by trollixx** [comment]
Oh, this issue is actually about truncated text, not the weird font. The truncation problem has been fixed some time ago (see #262).
