### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by octoruby** [zealdocs/zeal#541]
Zeal is currently not working on Windows 10. It launches, but nothing shows up and clicking on anything does not work (close button, 'open url',...)

**Comment by trollixx** [comment]
Were you able to open settings and install docsets at all?

**Comment by octoruby** [comment]
Oh sorry for my ramble, I am able to install docsets now. I will close this issue now, thanks for your reply sir!

**Comment by trollixx** [comment]
No problem, I should make the start page more helpful (#323).

**Comment by bogebaga** [comment]
hai GITTERS, i need somehelp here. zeal in my windows 10 still not working after installed in my machine. only show icon on my notification area.
