### ISSUE TITLE
Please update PPA  to support Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by ldsink** [zealdocs/zeal#542]
Please, update the ppa (https://launchpad.net/~zeal-developers/+archive/ubuntu/ppa) for Ubuntu 16.04 LTS (xenial)。

It raise an error when use `apt update`.
```
E: The repository 'http://ppa.launchpad.net/zeal-developers/ppa/ubuntu xenial Release' does not have a Release file.
```

**Comment by dylanpinn** [comment]
@ldsink Did you find a solution to this one? I am getting this error currently on 16.04 LTS.

**Comment by trollixx** [comment]
Come on people, it's in the [standard repositories](http://packages.ubuntu.com/search?keywords=zeal&searchon=names)! :)

**Comment by dylanpinn** [comment]
Thanks for the response. Would you appreciate a pull request to update the website to include this information for 16.04?

**Comment by trollixx** [comment]
I am updating it right now... Thanks.

**Comment by zuernBernhard** [comment]
I still get the same error in Ubuntu 16.04.1 what am I doing wrong ?

```
W: The repository 'http://ppa.launchpad.net/zeal-developers/ppa/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/zeal-developers/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
```

**Comment by dylanpinn** [comment]
@zuernBernhard try:

```
sudo add-apt-repository --remove ppa:zeal-developers/ppa
sudo apt update
```

**Comment by zuernBernhard** [comment]
Thx that solves the problem :+1:

**Comment by aman7681** [comment]
Thanks :+1:

**Comment by AnthonyWC** [comment]
Can we get zeal 1.0.3 update on xenial too?
