### ISSUE TITLE
Cannot view Mongoose docset on Ubuntu

### ISSUE THREAD

**Issue by perqin** [zealdocs/zeal#544]
I am using Zeal on Ubuntu 14.04.4 and I can't view Mongoose docset but others (I have tried Nodejs) work.

**Comment by trollixx** [comment]
What exactly doesn't work? Have you tried to reinstall the docset? I don't see any issues with it.

**Comment by trollixx** [comment]
Closing due to lack of response. Please reopen if the bug is still there.
