### ISSUE TITLE
Can't launch the app on windows 10

### ISSUE THREAD

**Issue by Stmanega** [zealdocs/zeal#545]
It was working fine before even on windows 10. Reinstalling it didn't solve the problem.
When I launch it, the icon on the taskbar  appears just for a while.

**Comment by uolcano** [comment]
The same problem on windows 7 today. Reinstalling or repairing didn't work.

**Comment by trollixx** [comment]
Wasn't able to get to this earlier. If this still is an issue, deleting Zeal's application data (` %LOCALAPPDATA%\Zeal`) should help.

**Comment by uolcano** [comment]
@trollixx thx, it works.

**Comment by TbhT** [comment]
@trollixx  yes, it works. when i restart the boot and the software, the problem is still . So i find the %LOCALAPPDATA%\ZEAL , but it has 2.5G. I'm curious why it was so large?
