### ISSUE TITLE
checboxes for docsets to update

### ISSUE THREAD

**Issue by smsrkr** [zealdocs/zeal#547]
add checkboxes to the installed docsets list for updating, giving a choice in between the two extremes of updating the lone selected docset and updating all of em.

**Comment by trollixx** [comment]
You can select multiple docsets by holding <kbd>Ctrl</kbd>.

I agree, the current UI is confusing and inconvenient, but checkboxes are not really a solution. I will be adding individual controls for each item of the both docset lists. My hope is to simplify docset management as much as possible.

**Comment by trollixx** [comment]
I am closing this, please follow #354 for updates. Thanks for the feedback!

**Comment by smsrkr** [comment]
Huh, didn't know that!
Thanks for the hint.
