### ISSUE TITLE
Crystal Docset

### ISSUE THREAD

**Issue by chun49** [zealdocs/zeal#550]
please,add crystal-lang doc

**Comment by trollixx** [comment]
No need to redact the original message, simply closing the issue is fine. Crystal docset is available [here](https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Crystal).

**Comment by chun49** [comment]
why not include official docs and standard lib API??

**Comment by chun49** [comment]
sorry my english so bad..

**Comment by trollixx** [comment]
It's a wrong place to ask such questions. All docsets are coming from Dash,
and at the moment Zeal provides direct access to the official docsets only.
Please follow #170 for the progress on allowing to download user
contributed docsets within the app.
