### ISSUE TITLE
Missing drop down menus and no buttons seem to work [gentoo]

### ISSUE THREAD

**Issue by dpnova** [zealdocs/zeal#553]
I've installed zeal using xmonad on gentoo:

```
*  app-doc/zeal
      Latest version available: 0.2.1
      Latest version installed: 0.2.1
      Size of files: 894 KiB
      Homepage:      https://zealdocs.org/
      Description:   Offline documentation browser inspired by Dash
      License:       GPL-3
```

but none of the menus do anything, see screenshot below:

![selection_516](https://cloud.githubusercontent.com/assets/229943/16437689/498f301c-3dec-11e6-9600-4e0aa63bf9bb.png)

I've seen previous issues regarding appmenu, but I don't actually have it installed.

Any ideas?
Cheers!

**Comment by trollixx** [comment]
I don't think it's a problem with Zeal. Do other Qt 5 apps work properly?

**Comment by dpnova** [comment]
You're right, I just checked designer on 5 and it also has this issue. Thanks for the reply!

**Comment by dpnova** [comment]
For reference this seems to be the issue impacting me: https://bugreports.qt.io/browse/QTBUG-29278

**Comment by trollixx** [comment]
Thanks for the info. Looks like the issue is Xmonad specific.
