### ISSUE TITLE
query input searches inmediately after each keypress

### ISSUE THREAD

**Issue by diddierh** [zealdocs/zeal#555]
When the query input is used this searches in the entire docsets for each partial phrase that is formed while the final phrase is typed, this makes the searches tedious because each search is slow and the intended search is the most of times for the final full phrase.

I suggest that after a keypress and before doing a search a period of time must pass (usually one second), this for waiting a new keypress.

**Comment by mrhota** [comment]
related to #559 (which rebases #460). Searches are so fast with that code that this may not be an issue once that gets merged.

**Comment by trollixx** [comment]
Fixed in fd11923a3c7638ea0932a0479db34ac94b5b1a70.

**Comment by diddierh** [comment]
tested work as intended, thanks
