### ISSUE TITLE
HTML escape sequences are show in search results

### ISSUE THREAD

**Issue by peschkaj** [zealdocs/zeal#556]
Using Ubuntu 16.04 with Zeal v0.2.1, HTML escapes are not properly displayed in search results:

![image](https://cloud.githubusercontent.com/assets/71570/16669257/5d44d824-4449-11e6-9b35-4710431f889e.png)

**Comment by trollixx** [comment]
Thanks for reporting. I can't find any other affected docsets, but C++. I am not sure it's not a docset bug.

@Kapeli should Zeal parse HTML sequences in titles of index items, or this one docset can be fixed instead?

**Comment by Kapeli** [comment]
This is a docset issue. It also seems to affect the Rails docsets.

I'll fix it and will release docset updates.

**Comment by trollixx** [comment]
Closing this per @Kapeli comment.

@peschkaj Expect the problem to go away with the next update of the C++ docset. Please let us know in case you notice similar issue again.

**Comment by peschkaj** [comment]
Sounds good. I'll give it a few days - I just updated my docsets and the
issue persisted, but I'm not sure when those updates were from.

On Sat, Jul 9, 2016 at 8:43 AM Oleg Shparber <notifications@github.com>
wrote:

> Closed #556 <https://github.com/zealdocs/zeal/issues/556>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zealdocs/zeal/issues/556#event-717813403>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAEXku6EGi3gXvU_4pxLeMO0NNhhIH12ks5qT8GRgaJpZM4JHe-u>
> .
>
-- 

Jeremiah Peschka

**Comment by Kapeli** [comment]
Check for updates again. I've just fixed it.

**Comment by peschkaj** [comment]
Thank you. That fixed it.

On Sat, Jul 9, 2016 at 10:14 AM Bogdan Popescu <notifications@github.com>
wrote:

> Check for updates again. I've just fixed it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zealdocs/zeal/issues/556#issuecomment-231544911>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAEXkjq05HkNG51pJBTyNlFEjODHTJ3Mks5qT9bfgaJpZM4JHe-u>
> .
>
-- 

Jeremiah Peschka
