### ISSUE TITLE
Zeal Crash on Arch Linux

### ISSUE THREAD

**Issue by BearzRobotics** [zealdocs/zeal#560]
After run the download command to acquire new docsets the app crash. When started from the command line i got this output  

Cannot determine index file for docset Common_Lisp
Cannot determine index file for docset Erlang
Cannot determine index file for docset Perl
Cannot determine index file for docset Qt_4
QxtGlobalShortcut failed to register: Meta+Z
Cannot determine index file for docset RubyMotion
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by trollixx** [comment]
Messages say that docsets were not installed properly. Cleaning up docset
storage directory should help.

It would be also great of you shared that directory, so I could fix the
crash.

**Comment by pkulev** [comment]
When I ugraded docsets with bad internet connection I got that error too with many docsets broken. Removing and downloading again helped, by it will be nice not to crash in such cases.

**Comment by trollixx** [comment]
Closing this because many related issues have been now fixed, and reports without docset directories provided are not very helpful.
