### ISSUE TITLE
Pin selected docset

### ISSUE THREAD

**Issue by wieczyk** [zealdocs/zeal#561]
When I am programming I am mostly focused on one docset. Currently I can put prefix with docset name, but it is not enough for me.

When I want to do new search I select whole string and delete it; then type new query. Each time I had to put docset name as prefix.  I could remove only part after docset's name, but it is much faster to remove whole string by shortcuts (shift + home; del) instead of trying to select everything without prefix.

It would be nice to select one docset in GUI.

**Comment by trollixx** [comment]
Using Escape key should give you the behaviour you want. But please be
aware, that might change in the future. I'm looking for something more
intuitive and convenient.

**Comment by wieczyk** [comment]
Thanks, using escape key is sufficient for me.

**Comment by trollixx** [comment]
Closing since the functionality is already there.
