### ISSUE TITLE
Search across specified docset

### ISSUE THREAD

**Issue by Yanpas** [zealdocs/zeal#565]
Please add possibility to search across only one specified docset. For example I want to search API of Java's String class, not C++'s.

If I could narrow search by categories too it would be even greater! (classes, functions etc)

**Comment by mrhota** [comment]
this is precisely what #529 provides

**Comment by trollixx** [comment]
You can already do that by using prefixes, like `c++:` or `javascript:`, unfortunately there's no easy way to know all prefixes for docsets, but most of them are just names.

**Comment by trollixx** [comment]
Closing this since the functionality is already there.
