### ISSUE TITLE
I am getting an 'illegal value' error when trying to load a docset or check for updates

### ISSUE THREAD

**Issue by buddylindsey** [zealdocs/zeal#566]
I used default `zeal` from apt repository for ubuntu. Then I added the PPA and did another install. Both resulted in the same problems.

When I installed the app it started just fine and everything 'looks' fine. When I go to see a list of docsets I get an error saying illegal value

![zeal_error](https://cloud.githubusercontent.com/assets/226303/16999961/28e2adc6-4e86-11e6-84d6-33941f1501d1.png)

I thought maybe files were corrupted, so I went to check the folder the docsets were supposed to be in and there is nothing in them:

![no_docsets](https://cloud.githubusercontent.com/assets/226303/16999945/1f87e08e-4e86-11e6-8fbf-303d34f8c786.png)

Finally, I thought maybe there might be a newer version so I tried the 'check for updates' button:

![no_update](https://cloud.githubusercontent.com/assets/226303/17000033/66830fb8-4e86-11e6-8d65-c2443a4ea827.png)

Any thoughts on how I can try to resolve this?

**Comment by buddylindsey** [comment]
And after a reboot zeal worked just fine. Odd.

I'll let a core dev close this so they can see it at least exists in case someone else hits it.

**Comment by trollixx** [comment]
Thanks for reporting! Zeal doesn't handle well any errors that occur during docset list retrieval. I need to look into that, and make it a reliable process.

**Comment by trollixx** [comment]
As I've said in https://github.com/zealdocs/zeal/issues/713#issuecomment-291035033 there's not much we can do here, other than improve the user experience a bit, and try to download the docset index again.
