### ISSUE TITLE
Remember the page that was last browsed, and show it after restart.

### ISSUE THREAD

**Issue by dejlek** [zealdocs/zeal#567]
One of the things I would like Zeal to do is to bring me back to the page I was last on. This is particularly useful when the docset contains GUIDES which are more/less like books, so you need to continue reading where you stopped...

**Comment by innermous** [comment]
I am already working on this in #548 pull request.

**Comment by dejlek** [comment]
Perfect, I am happy to close the issue! (I was browsing for the similar issue and somehow did not find the #78, probably because of the title...)
