### ISSUE TITLE
Add the "docset" panel which contains things like "docset" bookmarks.

### ISSUE THREAD

**Issue by dejlek** [zealdocs/zeal#568]
This is a complex feature, so I would understand if developers decide to ignore it.
However, it is a very useful feature, and I will try to be as short as possible about it...

At the moment, there is no way for user to add current pages to a single, per-docset list, so we can easily jump to them whenever we please. Therefore, I suggest we add (this should be optional, for those who want it), a new panel that is below navigational panel (or a dockable that can be placed anywhere), and where we see the bookmarked pages from the currently open docset. This panel can later surve other purposes, like having personal notes about currently open page of the currently open docset, etc.

**Comment by trollixx** [comment]
Bookmarks are planned #290. Although I haven't considered per docset bookmarks, any reason why that would be better than a browser-like implementation with global bookmarks?

**Comment by trollixx** [comment]
Closing this as a duplicate.
