### ISSUE TITLE
Crash on Archlinux

### ISSUE THREAD

**Issue by Plasticoo** [zealdocs/zeal#570]
I compiled and ran it from the bin folder created after the compilation.

Terminal output:

`λ  bin git:(master) ⨯ ./zeal
failed to get the current screen resources
QXcbConnection: XCB error: 170 (Unknown), sequence: 169, resource id: 90, major code: 146 (Unknown), minor code: 20
[0721/211446:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[0721/211446:ERROR:gl_surface_qt.cpp(199)] GLX 1.3 or later is required.
WARNING: Application calling GLX 1.3 function "glXCreatePbuffer" when GLX 1.3 is not supported!  This is an application bug!
[1]    1148 segmentation fault (core dumped)  ./zeal
`

Current linux version:
`Linux shodan 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux`

Any other info needed?

**Comment by trollixx** [comment]
Do other Qt 5 apps work for you? According to [QTBUG-45895](https://bugreports.qt.io/browse/QTBUG-45895) Qt requires GLX 1.3, and it unlikely that your system doesn't support that, unless it's super old or video driver is misconfigured.

**Comment by Plasticoo** [comment]
I failed to tell that I am trying to run it using X11 Forwarding. On my laptop, that is running Archlinux, it is running fine, now if I use X11 Forwarding, using KiTTY, on my Windows Machine, then that error appears.

**Comment by trollixx** [comment]
It looks like this problem has nothing to do with Zeal, but rather a bug  in Qt or a misconfiguration at some stage. Please reopen this ticket if the problem doesn't occur for any other Qt 5 apps.
