### ISSUE TITLE
the "also see" part is broken on KDE and qt5ct enviornment

### ISSUE THREAD

**Issue by wicast** [zealdocs/zeal#571]
![photo238409572018137598](https://cloud.githubusercontent.com/assets/2603937/17134896/658b1aaa-535f-11e6-976b-442ccd417183.jpg)

As the pic shows that all the words are missing.This is not happen in pure gtk environment , but I'm using qt5ct for better looking. And KDE has the same problem.

**Comment by trollixx** [comment]
This has been already reported in #540. So, this is something related to Qt environment or theme. Thanks for the details.
