### ISSUE TITLE
Fault: Python2 docset (X)ubuntu 14.04

### ISSUE THREAD

**Issue by Kentoseth** [zealdocs/zeal#573]
When starting Zeal:

```
zeal
Segmentation fault (core dumped)
```

After removing the Python2 docset, zeal starts again.

**Comment by trollixx** [comment]
I think the docset wasn't properly extracted. Redownloading it should help.

It would be great if you share the corrupted docset directory.

**Comment by Kentoseth** [comment]
@trollixx 

By "directory", do you mean the contents of the folder called: Python_2.docset ?

**Comment by trollixx** [comment]
Yeah, just the `Python_2.docset` directory. Pack it, and upload somewhere or email to oleg@zealdocs.org. Thanks!

**Comment by Kentoseth** [comment]
[Python_2.docset.tar.gz](https://github.com/zealdocs/zeal/files/391727/Python_2.docset.tar.gz)

File has been uploaded as a .tar.gz

After downloading, please run the following command:

`sha256sum Python_2.docset.tar.gz`

The output should be:

> c2e79f3e3086614ce35d3bf15b408153d970ed83f1045397032ac36d65b3d347  Python_2.docset.tar.gz

Thanks.

**Comment by trollixx** [comment]
Thanks for the file!

Apparently the crash was already fixed in the development branch. I have also discovered another issue with loading corrupted docsets, which leads to empty docsets to be visible in the docset list - fixing that one right now.
