### ISSUE TITLE
Crash on Windows 10 x64..

### ISSUE THREAD

**Issue by lubocheng** [zealdocs/zeal#575]
Actually it can't start ..I do not understand  what the windows event log says..just crash

**Comment by trollixx** [comment]
Which version of Zeal? Did it work before or never did?

**Comment by lubocheng** [comment]
the latest release... never work on Windows 10 x64,even when I update to  Windows 10 1607 recently ..

**Comment by Ivoz** [comment]
It has opened fine for me on Windows 10, x64, 1607, Zeal 0.21. I have Python 3.5.1 docs loaded in.

**Comment by lubocheng** [comment]
[the error](http://pan.baidu.com/s/1c2uSXva)  this shows what hpppens to me

**Comment by lubocheng** [comment]
Below is the crash report from path :
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_zeal.exe_69911531ce1437621dd8b289aa5f1460269afbb_5b44f5b6_19cfd4db\Report.wer

content as follows:
Version=1
EventType=APPCRASH
EventTime=131163158654562083
ReportType=2
Consent=1
UploadTime=131163158655822565
ReportIdentifier=e4dd3f51-6825-11e6-8b89-80fa5b29ef3a
IntegratorReportIdentifier=78d9d3d4-baf9-4999-8931-103192b20d18
WOW64=1
NsAppName=zeal.exe
AppSessionGuid=00000438-0002-0013-bfd6-aba632fcd101
TargetAppId=W:0000da39a3ee5e6b4b0d3255bfef95601890afd80709!0000da39a3ee5e6b4b0d3255bfef95601890afd80709!zeal.exe
TargetAppVer=1972//08//20:18:57:44!123b6a!zeal.exe
BootId=4294967295
Response.BucketId=d8a6b10a9c3132752deae89c325214c6
Response.BucketTable=1
Response.LegacyBucketId=107758732882
Response.type=4
Sig[0].Name=应用程序名
Sig[0].Value=zeal.exe
Sig[1].Name=应用程序版本
Sig[1].Value=0.2.1.0
Sig[2].Name=应用程序时间戳
Sig[2].Value=04f54da8
Sig[3].Name=故障模块名称
Sig[3].Value=zeal.exe
Sig[4].Name=故障模块版本
Sig[4].Value=0.2.1.0
Sig[5].Name=故障模块时间戳
Sig[5].Value=04f54da8
Sig[6].Name=异常代码
Sig[6].Value=c0000005
Sig[7].Name=异常偏移
Sig[7].Value=0001f92d
DynamicSig[1].Name=OS 版本
DynamicSig[1].Value=10.0.14393.2.0.0.256.48
DynamicSig[2].Name=区域设置 ID
DynamicSig[2].Value=2052
DynamicSig[22].Name=其他信息 1
DynamicSig[22].Value=2beb
DynamicSig[23].Name=其他信息 2
DynamicSig[23].Value=2beba6fb4680d73a8c78ca7c24ccdb46
DynamicSig[24].Name=其他信息 3
DynamicSig[24].Value=55d9
DynamicSig[25].Name=其他信息 4
DynamicSig[25].Value=55d99967bb17a659275eb2be623dc2da
UI[2]=C:\Program Files (x86)\Zeal\zeal.exe
UI[3]=zeal 已停止工作
UI[4]=Windows 可以联机检查该问题的解决方案。
UI[5]=联机检查解决方案并关闭该程序
UI[6]=以后联机检查解决方案并关闭程序
UI[7]=关闭程序
LoadedModule[0]=C:\Program Files (x86)\Zeal\zeal.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[5]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[6]=C:\Program Files (x86)\Zeal\Qt5Core.dll
LoadedModule[7]=C:\WINDOWS\System32\sechost.dll
LoadedModule[8]=C:\Program Files (x86)\Zeal\Qt5Gui.dll
LoadedModule[9]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[10]=C:\Program Files (x86)\Zeal\Qt5Network.dll
LoadedModule[11]=C:\WINDOWS\System32\ole32.dll
LoadedModule[12]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[13]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[14]=C:\WINDOWS\System32\SspiCli.dll
LoadedModule[15]=C:\WINDOWS\System32\CRYPTBASE.dll
LoadedModule[16]=C:\WINDOWS\System32\combase.dll
LoadedModule[17]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[18]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[19]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[20]=C:\WINDOWS\System32\USER32.dll
LoadedModule[21]=C:\WINDOWS\System32\MSASN1.dll
LoadedModule[22]=C:\WINDOWS\System32\win32u.dll
LoadedModule[23]=C:\WINDOWS\System32\SHELL32.dll
LoadedModule[24]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[25]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[26]=C:\Program Files (x86)\Zeal\Qt5Sql.dll
LoadedModule[27]=C:\Program Files (x86)\Zeal\Qt5WebKit.dll
LoadedModule[28]=C:\WINDOWS\System32\windows.storage.dll
LoadedModule[29]=C:\WINDOWS\System32\powrprof.dll
LoadedModule[30]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[31]=C:\Program Files (x86)\Zeal\Qt5WebKitWidgets.dll
LoadedModule[32]=C:\WINDOWS\System32\kernel.appcore.dll
LoadedModule[33]=C:\WINDOWS\System32\shcore.dll
LoadedModule[34]=C:\Program Files (x86)\Zeal\Qt5Widgets.dll
LoadedModule[35]=C:\WINDOWS\System32\profapi.dll
LoadedModule[36]=C:\Program Files (x86)\Zeal\libgcc_s_dw2-1.dll
LoadedModule[37]=C:\WINDOWS\SYSTEM32\MPR.DLL
LoadedModule[38]=C:\WINDOWS\SYSTEM32\DNSAPI.DLL
LoadedModule[39]=C:\WINDOWS\System32\NSI.dll
LoadedModule[40]=C:\Program Files (x86)\Zeal\libstdc++-6.dll
LoadedModule[41]=C:\Program Files (x86)\Zeal\libwinpthread-1.dll
LoadedModule[42]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[43]=C:\WINDOWS\SYSTEM32\WINMM.DLL
LoadedModule[44]=C:\Program Files (x86)\Zeal\icuin54.dll
LoadedModule[45]=C:\Program Files (x86)\Zeal\icuuc54.dll
LoadedModule[46]=C:\Program Files (x86)\Zeal\Qt5Qml.dll
LoadedModule[47]=C:\Program Files (x86)\Zeal\Qt5Quick.dll
LoadedModule[48]=C:\Program Files (x86)\Zeal\Qt5Positioning.dll
LoadedModule[49]=C:\Program Files (x86)\Zeal\Qt5Multimedia.dll
LoadedModule[50]=C:\Program Files (x86)\Zeal\Qt5Sensors.dll
LoadedModule[51]=C:\Program Files (x86)\Zeal\Qt5WebChannel.dll
LoadedModule[52]=C:\Program Files (x86)\Zeal\Qt5OpenGL.dll
LoadedModule[53]=C:\Program Files (x86)\Zeal\Qt5PrintSupport.dll
LoadedModule[54]=C:\WINDOWS\System32\COMDLG32.DLL
LoadedModule[55]=C:\Program Files (x86)\Zeal\Qt5MultimediaWidgets.dll
LoadedModule[56]=C:\WINDOWS\SYSTEM32\WINMMBASE.dll
LoadedModule[57]=C:\Program Files (x86)\Zeal\icudt54.dll
LoadedModule[58]=C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.14393.0_none_88fef4c26039fb25\COMCTL32.dll
LoadedModule[59]=C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
LoadedModule[60]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[61]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[62]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
LoadedModule[63]=C:\Program Files (x86)\Zeal\platforms\qwindows.dll
LoadedModule[64]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[65]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[66]=D:\Data Bank\日常软件\音速启动\Tools\常用软件\ListaryPortable\ListaryHook.dll
LoadedModule[67]=D:\Data Bank\日常软件\音速启动\Tools\常用软件\ListaryPortable\MSVCP120.dll
LoadedModule[68]=D:\Data Bank\日常软件\音速启动\Tools\常用软件\ListaryPortable\MSVCR120.dll
LoadedModule[69]=C:\WINDOWS\SYSTEM32\OLEACC.dll
LoadedModule[70]=C:\WINDOWS\system32\dwmapi.dll
LoadedModule[71]=D:\迅雷下载\Youdao\6.3.69.4001\WordStrokeHelper32.dll
LoadedModule[72]=C:\Program Files (x86)\Zeal\imageformats\qgif.dll
LoadedModule[73]=C:\Program Files (x86)\Zeal\imageformats\qico.dll
LoadedModule[74]=C:\Program Files (x86)\Zeal\imageformats\qjpeg.dll
LoadedModule[75]=C:\Program Files (x86)\Zeal\imageformats\qtiff.dll
LoadedModule[76]=C:\Program Files (x86)\Zeal\sqldrivers\qsqlite.dll
LoadedModule[77]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[78]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[79]=C:\WINDOWS\system32\rsaenh.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=已停止工作
ConsentKey=APPCRASH
AppName=zeal
AppPath=C:\Program Files (x86)\Zeal\zeal.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=EE44A77EDF9B68037E25EFA5F90F6483
MetadataHash=1566696825

**Comment by lubocheng** [comment]
I think I find the reason of crash finally. I once create E:\Zeal and E:\Zeal\docsets and also put some same  docset in the two folders. When you set "Docset storage" to the former , it will cause zeal crash.  Seems funny but depressed.
