### ISSUE TITLE
Replace QtWebKit with QtWebEngine

### ISSUE THREAD

**Issue by dunn** [zealdocs/zeal#581]
As of Qt 5.6.0, the WebKit module is deprecated (and no longer even part of the all-in-one source download) due to the security issues with the vendored version of WebKit (see https://blogs.gnome.org/mcatanzaro/2016/02/01/on-webkit-security-updates/ etc).

Are there plans to migrate Zeal to WebEngine?

**Comment by trollixx** [comment]
There are plans :)

In fact Zeal has supports WebEngine for quite a while (`CONFIG+=zeal_qtwebengine`). Unfortunately, not everything works yet, most notably keyboard shortcuts.

**Comment by trollixx** [comment]
With the recent [revival](http://qtwebkit.blogspot.ru/2016/08/qtwebkit-im-back.html) of Qt WebKit, I think there will be no point in working on complete Qt WebEngine support.

Qt WebKit provides much better integration with Qt, and carries a lighter footprint. With it being back and supported browsing all our current issues related to Qt WebKit bugs should be gone.

I'll setup CI builds with the new Qt WebKit once I get 0.3.0 out.

On a different note I hope to provide some kind of web view abstraction layer in Zeal, so replacing underlying engine would not be too painful. I have a very distant future plan to use MS IE/Edge engine on Windows.

Saying all that above, I am closing this issue as "won't fix", but I'd be happy to accept patches improving Qt WebEngine support in Zeal. It would require quite decent amount of work to bring Qt WebEngine support to the level we have for Qt WebKit, and I simply neither have enough time, no any interest in supporting two browser engines myself.
