### ISSUE TITLE
Texts are not antialiased

### ISSUE THREAD

**Issue by sajibsrs** [zealdocs/zeal#586]
WIN 10 x64
ZEAL 0.2.1

Looks like text are not rendering properly and not anti aliased. It's readable but disturbing to eyes. It should be better anti aliased and smoothed.

**Comment by trollixx** [comment]
I guess this is another QtWebKit issue, no quick fix at the moment, but we'll be switching to an updated QtWebKit soon. That should solve the problem.

**Comment by sajibsrs** [comment]
That's very nice. Thank you

**Comment by trollixx** [comment]
Merging all Qt WebKit related issues into #359.
