### ISSUE TITLE
Some suggestions to build a more convenient docsets download panel

### ISSUE THREAD

**Issue by eromoe** [zealdocs/zeal#587]
1. Currently, docsets download panel hides in  `file -> option -> docsets`, and the panel is really small. I think a independent big panel under a tab would be better.
2. No search box (very important , I need scroll a long time to find a docs. I also notice that type first letter of a doc name can jump to the section, but I don't think there are many people would realize this at first.)
3. Download doc freeze zeal(have to wait download complete). velocity does much better. It would be much better to create a backgroud job(not use checkbox to do multiple download, just a click button to add the doc to download schedule),  we can see another doc while downloading.

**Comment by trollixx** [comment]
1 & 2 are already implemented, just build Zeal from the `master` branch or use a [CI build](https://bintray.com/zealdocs/windows-ci/zeal-unstable/view) on Windows.

Background downloading is something still on my list.

**Comment by trollixx** [comment]
#842 was raised for support for background downloads. Closing this one as it's really hard to manage tickets with multiple points inside.
