### ISSUE TITLE
Javascript docset no icon

### ISSUE THREAD

**Issue by Yanpas** [zealdocs/zeal#588]
![_2016-09-01_11-34-23](https://cloud.githubusercontent.com/assets/7345761/18160888/195c67b0-7038-11e6-9314-bef8d8ad95ee.png)

**Comment by trollixx** [comment]
Looks like a corrupted download, just refresh the docset list, and reinstall the docset.

**Comment by trollixx** [comment]
Closing this, because it's a problem with the corrupted docset. I've created #599 for download verification feature.
