### ISSUE TITLE
Javascript: many  main articles are absent

### ISSUE THREAD

**Issue by xomrk** [zealdocs/zeal#590]
For example I'm looking for operators **if**, **for** or **while** and Zeal does not find proper articles. Almost all articles about main operators in JS are missing.
I'm running Zeal  0.2.1 with Qt 5.6.1 on Debian Stretch/Sid. 
Please help!

![screenshot_2016-09-03_18-15-37](https://cloud.githubusercontent.com/assets/15179155/18225755/77e8df8a-7203-11e6-892b-760dd17894ea.png)

**Comment by xomrk** [comment]
Well it looks like the html files from 'statement' directory are not displayed, though right keywords are found and displayed in search  (left) pane of Zeal.
These html files are located  in /JavaScript.docset/Contents/Resources/Documents/developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/statements/
May be another htmls are not displayed also but i didn't saw them yet.
Can anyone advice how to fix this problem?

**Comment by trollixx** [comment]
@Kapeli it looks like a docset problem, could you take a look?

**Comment by trollixx** [comment]
This happens because of case sensitivity. Zeal tries to open `developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/while.html`, while the file is `developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/statements/while.html`. Note the difference in `Statements` vs `statements`. Windows and macOS (by default) do not care, but Linux does.

**Comment by Kapeli** [comment]
Thanks for letting me know about this. I'll fix it the next time I update the docset.

**Comment by xomrk** [comment]
@trollixx TY very much!
@Kapeli good luck!

I changed the directory name manually, it works OK now. Will it be some kind of a problem next update and should I do some additional steps during next update?

 Zeal is very great and useful app, TY guys!

**Comment by xomrk** [comment]
@trollixx TY very much!
@Kapeli good luck!

I changed the directory name manually, it works OK now. Will it be some kind of a problem next update and should I do some additional steps during next update?

 Zeal is very great and useful app, TY guys!

**Comment by trollixx** [comment]
@xomrk, no need to do anything special for the update. Zeal removes all
docset files prior to installing a new version.

**Comment by xomrk** [comment]
@trollixx, TY again!

Best wishes!
