### ISSUE TITLE
Depending search

### ISSUE THREAD

**Issue by dix75** [zealdocs/zeal#591]
Can you add a new type of search, only for the current docset.
for example:
- I want search only in the jquery library? the second time I want something find in the C++ library and so on.  

It would be very useful.

**Comment by trollixx** [comment]
You can use `cpp:` prefix to search in the C++ docset, `jquery:` for jQuery.

**Comment by dix75** [comment]
Thanks. Greate!
A What about another combobox with those prefixes?

**Comment by trollixx** [comment]
Yeah, something like that is definitely required.

**Comment by trollixx** [comment]
Marking as a duplicate of #716.
