### ISSUE TITLE
missing results in search

### ISSUE THREAD

**Issue by e-orz** [zealdocs/zeal#593]
Hi,
There are sometimes missing results depending on the search.
Steps to reproduce:
1. Install Akka docset
2. search akka:Source (or just Source)
3. there is no scaladsl.Source only the javadsl one
4. But, when searching scaladsl.Source it is perfectly found

I built Zeal from sources. Git commit c9ec84fcb3ad41f07c6176882ed0f90e425346e7 from 11/9/2016

Thanks,
Eli

**Comment by trollixx** [comment]
Thanks for reporting, I'll look into this shortly.

**Comment by e-orz** [comment]
Thanks ! works now.
