### ISSUE TITLE
"Start" pages are gone

### ISSUE THREAD

**Issue by SchweinDeBurg** [zealdocs/zeal#598]
Just built Zeal from master (commit bdaba34a8c0bf70513040d9d9505f42c37825ede). Zeal starts, loads docsets, but when I am clicking any docset title in the left tree - nothing is happens. Before last commit(s) "start" pages of each docset was displayed on the right pane.

**Comment by trollixx** [comment]
Thanks for reporting, fixed!

**Comment by SchweinDeBurg** [comment]
Thank yum so much for this very quick fix! Zeal is a really great tool for software developers.
