### ISSUE TITLE
docset abbreviation

### ISSUE THREAD

**Issue by qcol** [zealdocs/zeal#601]
It would be a great help if you can to use docset abbreviation, for example: I set "l" for "laravel" docset, so I can use search filter: l:database . "j" for "jquery" allow to write j:select. Writing every time full name of docset is not comfortable.

**Comment by trollixx** [comment]
Configurable docset keywords are planned. For now you can just press Tab if
a suggestion is correct.

**Comment by qcol** [comment]
Thanks for info - zeal is great tool! :)

**Comment by trollixx** [comment]
Follow #421 for updates.
