### ISSUE TITLE
Zeal 0.3.0 not properly released?

### ISSUE THREAD

**Issue by michel-slm** [zealdocs/zeal#602]
The release page sitll marks 0.2.1 as the latest release, and there is no changelog for 0.3.0

**Comment by trollixx** [comment]
I'd say it's not released yet, just tagged. Writing a changelog and a blog
post is even worse than creating an installer for Windows, which I am
currently busy with. Hopefully I'll finish all that stuff over the weekend.

**Comment by michel-slm** [comment]
@trollixx aha, thanks. A Fedora user already asked for an update, right now I've only built the 0.3.0 tag for our development branch. Will wait for the official release.

**Comment by RealSkeptic** [comment]
Well, it is already in the repository and thus updated on all Ubuntu derivatives...

**Comment by trollixx** [comment]
Actually it's only in PPA, not in the official repositories. The
announcement is coming :)

**Comment by trollixx** [comment]
https://zealdocs.org/blog/2016/10/03/zeal-0.3.0-released.html :)
