### ISSUE TITLE
Version 0.3.0 search gives too many irrelevant results.

### ISSUE THREAD

**Issue by RealSkeptic** [zealdocs/zeal#603]
I have six docsets installed - Java SE7, Java SE8, Bash, Vim, MySQL, and JUnit (which I imported from Dash).

My main interest is Java, though. Previously, when I entered a class name, such as "Pattern" into the search box, I got the documentation for `java.util.regex.Pattern` in one of the top places in the results box.

Now, instead, I get tons of partial matches, method names, and what not. I need to scroll down considerably to find the class name.

Can you please change the search results display so that it displays, in this order:
1. Exact (case-sensitive) matches
2. Exact (case-insensitive) matches
3. Initial matches (case-sensitive), e.g. `PatternSyntaxException`.
4. Initial matches (case-insensitive)
5. Partial matches (e.g. `perl-patterns`,  `applyPattern`...)

So that users will be more likely to find what they were actually looking for? Or at least, add this ordering as an option in the preferences.

I would also suggest to allow the user to configure the order in which results from different docsets are displayed, so that if I mostly use Java, I'll see classes and methods from Java first).

Alphabetic order is not helpful in this case...

**Comment by trollixx** [comment]
I made some changes in the search logic, mostly to fix things like #593, and make search faster. Unfortunately, that also resulted in less relevant results, or result ordering. I'll see what I can do to improve the situation, without hurting performance. My ultimate goal is switching to SQLite's [FTS5](https://www.sqlite.org/fts5.html) engine, but that's a big undertaking.

**Comment by trollixx** [comment]
#614 should solve this problem.
