### ISSUE TITLE
Missing version specific search keywords (python, ruby, java, qt)

### ISSUE THREAD

**Issue by azmodude** [zealdocs/zeal#604]
Hi,

I have both the Python 2 and Python 3 docsets installed.
In zeal 0.2.x one could use the `python 2: function` and `python 3: function` prefixes/syntax to search in the respective docsets.
This seems to be no longer the case? `python: function` works just fine, the other return just nothing at all.

Thanks!

**Comment by trollixx** [comment]
Zeal tries to use the same logic as Dash ([details](https://github.com/zealdocs/zeal/issues/383#issuecomment-124315538)), and not use docset name as a prefix. Unfortunately, now now for Python 2/3 there's only `python:` prefix. Dash itself provides `python2:` and `python3:`, but I don't see where those are coming from. @Kapeli could you shed some light here?

**Comment by Kapeli** [comment]
In Dash those are hardcoded (because I was dumb back then).

The hardcoded cases are:

```objc
if([platform isEqualToString:@"python"])
{
    NSString *docsetName = docset[@"docsetName"];
    if([docsetName hasPrefix:@"Python 2"])
    {
        return @"python2:";
    }
    else if([docsetName hasPrefix:@"Python 3"])
    {
        return @"python3:";
    }
}
else if([platform isEqualToString:@"java"])
{
    NSString *docsetName = docset[@"docsetName"];
    if([docsetName isEqualToString:@"Java SE7"])
    {
        return @"java7:";
    }
    else if([docsetName isEqualToString:@"Java SE6"])
    {
        return @"java6:";
    }
    else if([docsetName isEqualToString:@"Java SE8"])
    {
        return @"java8:";
    }
}
else if([platform isEqualToString:@"qt"])
{
    NSString *docsetName = docset[@"docsetName"];
    if([docsetName hasPrefix:@"Qt 5"])
    {
        return @"qt5:";
    }
    else if([docsetName hasPrefix:@"Qt 4"])
    {
        return @"qt4:";
    }
    else if([docsetName isEqualToString:@"Qt"])
    {
        return @"qt4:";
    }
}
else if([platform isEqualToString:@"cocos2d"])
{
    NSString *docsetName = docset[@"docsetName"];
    if([docsetName hasPrefix:@"Cocos3D"])
    {
        return @"cocos3d:";
    }
}
```

**Comment by thorstenkampe** [comment]
I noticed this, too. `python 2` and `python 3` prefixes still worked with the CI build from September, 15th. So it must be very recent change.

**Comment by FichteFoll** [comment]
@thorstenkampe probably this one: https://github.com/zealdocs/zeal/commit/236eb007e4a2d8b9e83f9218d2fd4eba75c9b970.

This is pretty crutial for docsets where different versions matter (Python for me).

**Comment by FichteFoll** [comment]
I don't want to annoy, but could you perhaps raise priority for this issue? I need documentation on both Python 2 and 3 available but I get almost every entry twice now (and have to prefix with `python:`).

**Comment by trollixx** [comment]
There's no priority list. Whenever I get a free moment, I try to fix or
implement something. Sorry for inconvenience, but I cannot give any
promises. Zeal is not a commercial product, and is really slacking in
development pace.

This issue requires some server side work for a proper fix, so might take
some time.

**Comment by trollixx** [comment]
The following keywords are now available:

|Docset|Keyword|
---------- | ----------
|Cocos3D|`cocos3d`|
|Java SE6|`java6`|
|Java SE7|`java7`|
|Java SE8|`java8`|
|Python 2|`python2`|
|Python 3|`python3`|
|Qt 4|`qt4`|
|Qt 5|`qt5`|
|Ruby on Rails 3|`ror3`*|
|Ruby on Rails 4|`ror4`*|
|Ruby on Rails 5|`ror5`*|
\* Dash doesn't have version-specific keywords for the RoR docsets.

To make use of these keywords delete the affected docsets, update the docset list, and download the docsets back.

**Comment by azmodude** [comment]
Thank you very much, I'll try a new version from git later tonight,
