### ISSUE TITLE
Zeal crashes on start and quit

### ISSUE THREAD

**Issue by noamelf** [zealdocs/zeal#605]
Hi Zeal looks great, but unfortunately, it crashes randomly on boot and quit.
See [core dump](http://pastebin.com/AQ43DHR7).

I'm using Arch linux and installing Zeal with this [AUR package](https://aur.archlinux.org/packages/zeal-git/) (zeal-git 0.3.0.1.g0e6d4ff-1).

**Comment by trollixx** [comment]
Thanks for the report. The crash on quit may be the same as #595. Not sure about random crash on start.

I've updated the package to build with debug info enabled. Please update Zeal, and post a new stack trace. It should be more helpful, thanks!

**Comment by noamelf** [comment]
Here is the new core dump after reinstalling the package. I noticed there several different ones, some I'm attaching a few:
* On close: [1](https://gist.github.com/noamelf/9b518558d2504eb1130d099041fbb3cf), [2](https://gist.github.com/noamelf/e74acbc71a50fe34c0b7759be5774181)
* On open: [1](https://gist.github.com/noamelf/b551d8c2f27870830075de50a7b179f5)

**Comment by trollixx** [comment]
```
zeal[0x43a43b]
zeal[0x4303f1]
zeal[0x42c76a]
zeal[0x4217eb]
zeal[0x41f0dc]
```

It didn't work. :( No symbol information. You've got `zeal-git 0.3.0.1.g0e6d4ff-2` from AUR, right?

I don't know why, maybe something overrides the build configuration, or I used the wrong option. I'll update AUR once I figure out what's wrong.

**Comment by trollixx** [comment]
Another update, hopefully with meaningful traces this time. Please update, and see if stack traces will have references to the code.

**Comment by noamelf** [comment]
This is what I get after the update:
https://gist.github.com/noamelf/be6a6bf025b864cd52dee80ce2d52c08

**Comment by trollixx** [comment]
All debug info gets stripped out :( I really don't know why, I checked on
my machine and it's there.

Let me fix #595 first, and we'll see if that will fix your problem too. But
then for you it also crashes on start...

Alternatively, if you could just build Zeal manually in debug mode and run
it in gdb (easy with Qt Creator) that would definitely produce all the
necessary information.

**Comment by cmalard** [comment]
Hi, same on Ubuntu with this error : `zeal crashed with SIGSEGV in QCoreApplicationPrivate::sendPostedEvents()`

**Comment by the-james-burton** [comment]
I concur. I have had the following zeal crash errors on Linux Mint 17.3 (based on ubuntu 14.04), installed via the ppa (0.3.0)...

`*** Error in 'zeal': double free or corruption (!prev): 0x0000000000fad0c0 ***`

and

```
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES" 
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES" 
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES" 
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES" 
```

I also see the 'another instance' error quite a lot. Note that it doesn't always fail. Once running, it will work for a while (often days with standbys in between) before crashing.

Previous release 0.2.1 was flawless. Sadly, I can't now find the 0.2.1 version anywhere, either via PPA or a working .deb file, so I can't downgrade (not without building it, I guess) ;(

**Comment by ronjouch** [comment]
Zeal 0.3.0 also segfaults for me under Ubuntu 16.04.1LTS: `[1]    20295 segmentation fault  zeal`.

Unfortunately I am unable to provide more traceback / debug info, as Zeal doesn't crash when built from source from QtCreator (Qt 5.7.0). Feel free to ask for more info.

**Comment by thuandt** [comment]
@ronjouch I have same problem with you.

**Comment by dakira** [comment]
Same here. Zeal 0.3.0 segfaults on exit. On every start I get a message that Zeal might still be running (which it's not). Couldn't find any crashlogs and only get a segfault message in the terminal.

**Comment by trollixx** [comment]
Closing as a duplicate of #595. A fix is coming.
