### ISSUE TITLE
Building a Feed API for hexdocs.pm - Zeal segfaults when consuming gzip

### ISSUE THREAD

**Issue by johnhamelink** [zealdocs/zeal#606]
Hey there! 

I've been working on a small project to build a feed API which generates docsets from hexdocs using the hex.pm API. 

[You can take a look at what I have done so far here!](https://github.com/johnhamelink/hexdocs_docset_api)

When I build a docset and copy the resultant `<module_name>.docset` directory over to `~/.local/share/Zeal/Zeal/docsets`, Zeal reads them happily.

However I want to take this one step further: I want to use Phoenix to provide a feed API which will then periodically download and produce hexdocs for each module on hexdocs, triggered by someone requesting the documentation for the first time. I have all of this working!

When I try to use the feed endpoint with Zeal, however, it seems to not like the gzipped files I am creating, as it segfaults when it comes into contact with them. I'm using Erlang's `:erl_tar` in order to generate them. [You can see the code that does this here.](https://github.com/johnhamelink/hexdocs_docset_api/blob/master/lib/builder.ex#L125)

 I was wondering if:
- You consider the segfault a bug as it doesn't produce a helpful error?
- You have any insight as to specifically why the error is occurring in the first place?

**Comment by trollixx** [comment]
This is pretty cool, I think Erlang developers will greatly appreciate your
work.

I have no idea why it crashes, but it shouldn't be hard to figure out.
Could you share an sample archive for me to test?

On a separate thought I wonder if we could use your project to implement
Hex.pm-based docset source with prebuilt docsets. While setting things up
for your tool to work should be quite simple on a Linux machine, I bet that
would be huge pain for Windows users. I'd really like an automatic service
that would provide docsets on demand. What do you think?

**Comment by johnhamelink** [comment]
> I have no idea why it crashes, but it shouldn't be hard to figure out.
Could you share an sample archive for me to test?

Here you go, there's a few for you: [docsets.tar.gz](https://github.com/zealdocs/zeal/files/506369/docsets.tar.gz)


> On a separate thought I wonder if we could use your project to implement
Hex.pm-based docset source with prebuilt docsets. While setting things up
for your tool to work should be quite simple on a Linux machine, I bet that
would be huge pain for Windows users. I'd really like an automatic service
that would provide docsets on demand. What do you think?

@trollixx my plan is to have it up on a server for people to use - once one person requests a package, it updates it once a day and caches it for every other request :smile:

**Comment by trollixx** [comment]
@johnhamelink Could you check if #616 fixes the crashes for you? I cannot reproduce any with that fix applied.

**Comment by johnhamelink** [comment]
@trollixx So zeal doesn't segfault anymore, but I get an error that says `Protocol "" is unknown`.

**Comment by trollixx** [comment]
Where exactly the error message is coming from?

**Comment by johnhamelink** [comment]
@trollixx it's a popup dialog

**Comment by trollixx** [comment]
I guess the problem occurs when you are trying to use `Add Feed`, right? Could you share the feed?

**Comment by trollixx** [comment]
I can't reproduce the issue, closing this due to no response.
