### ISSUE TITLE
docset for AngularJS 1 is unavailable

### ISSUE THREAD

**Issue by cmalard** [zealdocs/zeal#607]
With the release of AngularJS 2, the docset [has been updated](https://github.com/Kapeli/feeds/blob/master/AngularJS.xml).
Problem: this is a whole new framework and its API is completely different from AngularJS 1.

Can you add a way to use an older version of a docset (like Dash :-) ) ?

Best

**Comment by cmalard** [comment]
Linked with #208

**Comment by cmalard** [comment]
Workaround : http://stackoverflow.com/a/39753532/2787235

**Comment by trollixx** [comment]
Cool, already linked to the ticket. Closing as a duplicate :)

Unfortunately, no ETA on the actual feature delivery.

**Comment by cmalard** [comment]
Should be fixed with https://github.com/Kapeli/feeds/issues/13
