### ISSUE TITLE
Docsets dialog has invisible operations preventing a close

### ISSUE THREAD

**Issue by FichteFoll** [zealdocs/zeal#608]
After updating docsets, I was unable to close the docsets window because apparently there still was some kind of operation actve. This is not visible anywhere in the UI. I was able to close the dialog after ~2min.

This is on 0.3.0 and Windows 7.

https://5.lithi.io/QM65X.webm

**Comment by trollixx** [comment]
I think the problem was caused by the old docset versions being removed. It's the only operation that is not visible, other two (downloading and unpacking) have visual indication in the UI. I should a removal indicator as well then.

**Comment by benklop** [comment]
@trollixx apologies for discussing this on the wrong forum. I don't think that in my case this could have been caused by old docsets being removed, because I had no old docsets - this was the first time zeal was installed on this machine (at least in this OS)
