### ISSUE TITLE
Docset storage path is not saved in portable version

### ISSUE THREAD

**Issue by GreatYYX** [zealdocs/zeal#609]
Hi there, it seems that zeal doesn't remember docset storage after restarting application. In zeal.ini file, there's nothing about docset storage directory (I think that's the problem). My environment is win7 x64 and the version of zeal is 0.3.0.

**Comment by trollixx** [comment]
It's not actually a bug if you are using a portable version. It is designed (see v0.1.0 [release notes](https://github.com/zealdocs/zeal/releases/tag/v0.1.0)) to use folder next to the executable for the storage. You can temporarily change it, but that's never saved. You can still manually edit `zeal.ini`, but that's not really a use case for the portable version.

**Comment by trollixx** [comment]
On another thought it's really confusing that the setting isn't stored. I guess we should leave this up the the user to decide what path to use.
