### ISSUE TITLE
Compile instructions should mention all dependencies

### ISSUE THREAD

**Issue by omouse** [zealdocs/zeal#61]
I installed the qt5-default and qt5-qmake packages and tried to compile zeal and was greeted by the following error:

    Project ERROR: Unknown module(s) in QT: webkitwidgets

I wasn't expecting that I would have to install more parts of qt5. It would be nice to know if I need to download extra packages in a Debian-based distro (like Ubuntu, Linux Mint, etc.)

**Comment by rbu** [comment]
Any progress on this issue? I am trying to compile this on Fedora and it fails with "Project ERROR: Unknown module(s) in QT: webkitwidgets", even though qtwebkit-devel is installed.

**Comment by trollixx** [comment]
@rbu, for Fedora you need `qt5-qtwebkit-devel` package.

**Comment by rbu** [comment]
Ah, yes that helps. I just realized that the web site has this information, but I was looking at the README. How about unifying this so either they link to the other or they can be copy and pasted when one is changed?

**Comment by trollixx** [comment]
[pkgs.org](http://pkgs.org/) might be helpful.

**Comment by sammy44nts** [comment]
In #382 I explain how to fix this issue.

**Comment by trollixx** [comment]
I've added a reference to all required Qt modules to the README file.

Listing distribution specific package names is something, that might make sense to add as a separate file or to the website.

**Comment by omouse** [comment]
@trollixx thanks! :tangerine:

**Comment by samacumen** [comment]
I have been trying to build this on raspberry pi B+, I see that the 'qtWidgets' folder is empty and while making I receive the "Project ERROR: Unknown module(s) in QT: webkitwidgets" error. I cannot download the "libqt5webkit5-dev" by apt-get install (as there isn't any for Raspbian build yet).

Any help is appreciated. Thanks!

**Comment by trollixx** [comment]
@samacumen It looks like [there is](http://archive.raspbian.org/raspbian/pool/main/q/qtwebkit-opensource-src/) `libqt5webkit5-dev` package for Raspbian. I am not sure why you cannot install it, I have never used Raspbian.
