### ISSUE TITLE
You dropped --query cmd switch

### ISSUE THREAD

**Issue by Eternalink** [zealdocs/zeal#610]
You dropped `--query` cmd switch and therefore broke the functionality of  Zeal sublime text plug-in. How are we supposed to use Zeal in that manner now? Please bring back the functionality. We should be able to search the docs through terminal.

You should also warn the users to first uninstall the old version in order to install the newer one.
I ended up with two Zeal with weird behavior on each. I recovered by uninstalling both and reinstalling the newer version.

OS: Windows 7
Zeal version: 0.3.0

**Comment by trollixx** [comment]
`--query` was scheduled to be deprecated quite a [long time](72484f575e9f94b8b77ab2d6db018370a9723194) ago. There's no need in it, you can just pass query as an argument, e.g. `zeal printf`.

Plugins should never run Zeal directly, but rather rely on [`dash-plugin` interface](https://kapeli.com/dash_plugins). So, file a ticket with the plugin, so it can be switched to use Dash URL scheme.

As for the second problem, sounds like a problem in MSI metadata, installing a new version should automatically replace older one. Created zealdocs/zeal-packaging#20 about that. I'll update the installer.

**Comment by trollixx** [comment]
Closing based on `--query` issue. Please in the future do not report unrelated issues together.

**Comment by trollixx** [comment]
I have updated release notes to indicate what plugins should use.
