### ISSUE TITLE
Hang on Windows

### ISSUE THREAD

**Issue by m4uro** [zealdocs/zeal#612]
Zeal 0.3.0 is hanging on Windows after I click on a searched item in the Qt docset. I have C++ and OpenGL docsets as well and those are working fine, but the Qt one causes the app to completely hang. This was not an issue on version 0.2.1

**Comment by kraml** [comment]
Could you try install Font Awesome doctset and see if Zeal hangs once you try to view it? If yes then you are having the same problem as I have in issue #532.

**Comment by DiglidiDudeNG** [comment]
Same here, hangs when I try to open Font-Awesome's docset.

**Comment by trollixx** [comment]
Then this is a duplicate of #532 :)
