### ISSUE TITLE
Zeal 0.3.0 remove docset not actually working

### ISSUE THREAD

**Issue by kraml** [zealdocs/zeal#621]
In 0.3.0 when remove a docset int the docset manager UI, it gets removed from the list and the main UI. However  files on the disk remain untouched and after restart Zeal the deleted docset just reappear in the list.

My system is Win10, tried portable and non-portable version.

**Comment by kraml** [comment]
Just compiled 0.3.1 by my own and above changes caused a new problem. After selected a docset in the manager UI and clicked the remove button, I got a popup dialog says "Remove **0** docset(s)?". Clicking Yes does nothing, just return to the manager UI.

**Comment by trollixx** [comment]
It's because I forgot to commit changes to the `docsetsdialog.ui` in #625. Please consider v0.3.1 not released yet :)

**Comment by trollixx** [comment]
@kraml, should be fixed now in the "new" 0.3.1. A stupid mistake :(
