### ISSUE TITLE
[feature request] support to search multiple docsets

### ISSUE THREAD

**Issue by stardiviner** [zealdocs/zeal#622]
Hope Zeal can support to search multiple docsets for a mode.
It is very useful in Emacs. https://github.com/jinzhu/zeal-at-point/issues/14

**Comment by trollixx** [comment]
Zeal can do that now: `c,cpp:printf`. Although plugins should use [`dash-plugin`](https://kapeli.com/dash_plugins) protocol.

**Comment by stardiviner** [comment]
Thanks. close now because it implemented.
