### ISSUE TITLE
Zeal 0.2.1 (Ubuntu 16.04) stopped launching since 0.3.0 upgrade.

### ISSUE THREAD

**Issue by bitwombat** [zealdocs/zeal#629]
Zeal 0.2.1 is what's in the Ubuntu 16.04 repos currently, but it stopped working once the 0.3.0 release became available.

Prompt is: "A new version 0.3.0 is available. Open download page?"

If I click Yes, Zeal exits.

If I click No, Zeal exits.

I know I can download 0.3.0 manually, but I like to keep as many things managed by the package manager as possible.  So, this is all FYI, unless there's an easy workaround (--force doesn't help).

**Comment by trollixx** [comment]
Sounds like a bug, it should just open a web page, not exit the app. You can also disable update check in the settings.

**Comment by twnaing** [comment]
I encountered the same problem. I updated using Zeal's repo.

> When the official package becomes outdated, our own PPA repository provides an up-to-date version. Run the following commands to use the PPA:

```
$ sudo add-apt-repository ppa:zeal-developers/ppa
$ sudo apt-get update
$ sudo apt-get install zeal
```

**Comment by bitwombat** [comment]
> You can also disable update check in the settings.
Ay, yup.  That brought it back to life.

In .config/Zeal/Zeal.conf, set:

````
check_for_update=false
````

Thanks guys!
