### ISSUE TITLE
crash with zeal 0.3 "Cannot determine index file for docset Common_Lisp"

### ISSUE THREAD

**Issue by teto** [zealdocs/zeal#631]
Another nearly systematic crash with zeal 0.3 from ppa on ubuntu 16.04.1.
"Cannot determine index file for docset Common_Lisp"

I didn't know how to copy as text the problems so here are screenshots.
https://transfer.sh/VNGeK/2016-10-14-123706-913x717-scrot.png
https://transfer.sh/OPjvN/2016-10-14-123627-913x717-scrot.png

**Comment by trollixx** [comment]
There's no `0.3` version, `0.3.0` or `0.3.1`? If `0.3.1`, then most likely docset wasn't downloaded correctly. Please pack and upload `Common_Lisp.docset` directory here, and then delete it.

**Comment by trollixx** [comment]
I've fixed index path for the Common List docset. Update you local docset list, and reinstall the docset to get the fix.
