### ISSUE TITLE
Error creating SSL context

### ISSUE THREAD

**Issue by sfetome** [zealdocs/zeal#634]
when i run self compiled version of zeal and trying to download new docset
it pop up this message box. i have searched in the code and found nothing.
```
---------------------------
Zeal
---------------------------
Error creating SSL context ()
---------------------------
Retry   Cancel   
---------------------------
```

**Comment by trollixx** [comment]
You need `ssleay32.dll` and `libeay32.dll`.

**Comment by sfetome** [comment]
copy these 2 dlls to the  `bin` directory fix this error.

**Comment by RILUKIA** [comment]
![capture](https://user-images.githubusercontent.com/29603689/33811896-7ce0ad42-de18-11e7-9ece-a417d07c28ef.JPG)

Please help me
