### ISSUE TITLE
Fedora 24

### ISSUE THREAD

**Issue by ddagricola** [zealdocs/zeal#636]
Please! F24

**Comment by alunux** [comment]
@ddagricola Want to help the maintainer? :) https://bodhi.fedoraproject.org/updates/FEDORA-2016-226fa7194c

**Comment by trollixx** [comment]
Packages for Fedora are maintained by Fedora devs/packagers, luckily
nothing to do with us. Looks like 0.3.1 is in testing, whatever that means
:)

**Comment by alunux** [comment]
@ddagricola Zeal 0.3.1 had been released for Fedora 24, you can update now :)

https://bodhi.fedoraproject.org/updates/FEDORA-2016-226fa7194c

**Comment by trollixx** [comment]
Closing per above.
