### ISSUE TITLE
Application quits when there is a new release

### ISSUE THREAD

**Issue by atleta** [zealdocs/zeal#637]
Hi,

I'm running version 0.2.1-2ppa1~wily1 and it stopped working. After launching it, it tells me that there is a new version and I can chose to open the download page or not. However, the app doesn't start. It doesn't make too much sense, since it's an offline app, not a client to an online service. To make things worse, there isn't an up to date version for ubuntu/debian as of now, so the app became unusable.

The quick fix is to block zeal from accessing the server, e.g. by starting it without a network connection...

**Comment by trollixx** [comment]
I guess it's a bug in Zeal 0.2.1, which can be worked around by disabling
update check in settings. Ubuntu 15.10 has reached its end of life, so the
PPA package will not be updated.

**Comment by atleta** [comment]
Well, I seem to have forgotten to update the ppa link during the last upgrade, now it's OK, thanks! 

(On a side note, disabling the check only works after you can start the app, for which you need to block its network access first. Just in case someone is stuck with the old version.)

**Comment by gerhard-tinned** [comment]
I had the same issue. The Linux Mint repository provided Zeal but the update was not jet in it. So Zeal stopped working. That is simply WRONG. It is nice that there is a reminder about the new version but it SHOULD NEVER stop working because of this.

**Comment by gerhard-tinned** [comment]
Oh, additional it seems the suggestion is not working either. When Zeal has once detected an update, even disconnecting from the network/internet did not allow me to start Zeal. :(

**Comment by trollixx** [comment]
Does that happen for Zeal 0.3.1?

**Comment by trollixx** [comment]
The problem still occurs with v0.4.0.

**Comment by skorokithakis** [comment]
A workaround is to set:

~~~
check_for_update=false
~~~

in `~/..config/Zeal/Zeal.conf`.

**Comment by trollixx** [comment]
Freshly installed Ubuntu 16.04, and I still cannot reproduce this. Can anyone procure a stack trace?

**Comment by skorokithakis** [comment]
@trollixx A stack trace for what? It doesn't crash, it just gives two options: "Open webpage, yes/no". Yes opens the webpage and quits, no doesn't open the webpage and quits. Both options lead to an unusable program.

**Comment by trollixx** [comment]
Neither option is supposed to exit the app, but rather close the message box (and open the browser in case of `Yes`), so I assume the app crashes instead.

**Comment by skorokithakis** [comment]
No, it seems to exit normally, with an exit code of 0 even.

**Comment by trollixx** [comment]
This is even weirder than an unreproducible crash.
@skorokithakis Can you run Zeal in debugger, and see what triggers the exit? Setting a break point somewhere [here](https://github.com/zealdocs/zeal/blob/686eda015da0713899ffb50ae1679c94f5f338dd/src/libs/ui/mainwindow.cpp#L240), and then stepping over should give the idea.

**Comment by skorokithakis** [comment]
Unfortunately I don't have a C++ toolchain installed :/ Are you getting the dialog box too, and it continues for you instead? It's very odd that I'm not seeing a crash, I'm running 0.3.1. Should there maybe be a `return` somewhere around here?: https://github.com/zealdocs/zeal/blob/release/0.3/src/libs/ui/mainwindow.cpp#L278

**Comment by trollixx** [comment]
Yeah, the app stays open for me. No idea what's causing it to close for everyone experiencing this problem.

**Comment by skorokithakis** [comment]
That's very odd. I tried to compile it but didn't get very far. If you want to send me a build that will log things to console, I'd be happy to run it.

**Comment by skorokithakis** [comment]
Oh, something interesting happened: I launched Zeal, it popped the window up, I clicked no *and it kept working*! I think I've discovered the bug, though, because the main window showed up *before* the popup:

I think there's a race condition where, if Zeal finds an update before it can show the main window, main window loading is blocked and the program just terminates if the user presses a button. If the main window shows before the popup, then it keeps working.

**Comment by skorokithakis** [comment]
Ah, no. It turns out the bug only shows up if you have Zeal set up to start minimized to tray. For some weird and random reason, it started non-minimized even though the setting was set, leading me to discover the difference.

**Comment by trollixx** [comment]
@skorokithakis thanks for tracking this down. Now I can reproduce the problem, and hopefully provide a fix shortly.
