### ISSUE TITLE
Cannot search Java SE7 and Java SE8 docsets

### ISSUE THREAD

**Issue by wenLiangcan** [zealdocs/zeal#639]
My Zeal binary was built from commit 6cb63ee. I have both JavaScript, Java SE7 and Java SE8 docsets installed but the search box can only autocomplete docset name of JavaScript. I tried to type the name of Java docsets manually but Zeal can show search results of neither Java SE7 nor Java SE8 docsets.

**Comment by bendem** [comment]
try `java se7:` or `java se8`. Alternatively, `java:` will work too.

**Comment by wenLiangcan** [comment]
@bendem Thank you, `java` is work, but not `java se7` nor `java se8` as I've reported.

**Comment by trollixx** [comment]
Duplicate of #604.
