### ISSUE TITLE
Language Option Documentation

### ISSUE THREAD

**Issue by lucianobragaweb** [zealdocs/zeal#64]
Seria legal ter a opção de ao baixar as documentações escolher o idioma.
Por exemplo: Sou do Brasil, e quero baixar a documentação do PHP em Português.

**Comment by trollixx** [comment]
All docsets are coming from [Dash](https://kapeli.com/dash), so someone needs to volunteer, and contribute docsets in different languages.

For now docset development is out of scope for the Zeal project.
