### ISSUE TITLE
Cannot search Ruby docset

### ISSUE THREAD

**Issue by turbod** [zealdocs/zeal#641]
Try to search for example inject, in the sidebar and in the center appear the Enumerable module, but dont jump to the method description.

**Comment by durandom** [comment]
same here. Tried to copy / untar from Dash, did not work either :(

**Comment by durandom** [comment]
@trollixx let me know if I can help to debug / test this

**Comment by MatiasFernandez** [comment]
Same here. Let us know how to help to debug
