### ISSUE TITLE
Add local docset to Zeal

### ISSUE THREAD

**Issue by emoon** [zealdocs/zeal#644]
Hi,

In Dash it's possible to add a local docset (if you are working on creating one) which is quite handy (also makes it possible to share one without setting up a feed etc)

Is this possible in Zeal? I looked around but wasn't able to find a way to do it in the UI.

**Comment by trollixx** [comment]
Simply put your docset in the storage directory (visible in the settings).

**Comment by emoon** [comment]
Ah. So simple :) Thanks!

**Comment by cmorty** [comment]
IMO it would be pretty awesome to add a  "Add local docset" button to the Docset window that does nothing but opening a path-selection-popup and copy the selected folder to the docset folder and maybe check, that it is a valid docset. This should be low risk, low effort, but help a lot.

**Comment by trollixx** [comment]
@cmorty Unfortunately, docset archives do not contain all the necessary information (e.g. icons, some metadata). Unless we switch to a custom format, there's no good way to support local archives properly.
