### ISSUE TITLE
Cannot search in Zeal using Dash plugin for Jetbrains products

### ISSUE THREAD

**Issue by Slaviro** [zealdocs/zeal#646]
Since v0.3.0 I can't search in Zeal anymore from Jetbrains products with Dash plugin. On v0.2.1 it worked like that:
1) Install Dash plugin
2) Reassing shortcut to search in Zeal
3) Click anywhere in code (I'm using IDEA 2016.2.5 from Android and Java development)
4) Press shortcut keys
5) Zeal opens (if not opened) and search results are shown.

Now after step 4 I see "Searching JAVA docksets in Dash" in the bottom of IDEA and nothing happens. 
v0.2.1 works fine.

My config:
Zeal 0.3.1
Gentoo Linux
IDEA 2016.2.5
Dash plugin for IDEA
Shortcut to search is Alt+Z.

**Comment by trollixx** [comment]
Most likely the plugin is trying to run Zeal directly with `--query`
parameter, instead of relying on `dash-plugin:` URL scheme. That was
deprecated long time ago, and finally removed in v0.3.0.

**Comment by Slaviro** [comment]
You're right. But really, it was the most convenient way to make it work without pain. Let me explain. If I want to open some king of URI in Java, I need to use Oracle java. It's OK but not all. Oracle Java needs libgnome to support URI opening, and it's a new dependecy. And even after you make java hadle URIs it's not a fact that your custom URI will be supported. So, maybe it wasn't a good idea to cut this feature?

**Comment by trollixx** [comment]
It's also possible to just execute Zeal binary with the query, that's what
URL handler essentially does. Simply removing `--query` and leaving the
actual query should work too for now.

**Comment by Slaviro** [comment]
Oh, thank you. It really works. I think the problem is solved then.
