### ISSUE TITLE
Prefixes for Rails 4/5

### ISSUE THREAD

**Issue by Sathors** [zealdocs/zeal#647]
Hi,

Are there different prefixes to search in rails 4 and in rails 5? I have tried some combinations, nothing works.

When I open the *.docset/Contents/Info.plist, both have the same CFBundleIdentifier set to rails.
Is this where the prefix is taken from?

It's similar to issue #604.

Thanks.

**Comment by trollixx** [comment]
Duplicate of #604.

**Comment by trollixx** [comment]
[Update](https://github.com/zealdocs/zeal/issues/604#issuecomment-260889546) on the new search keywords.
