### ISSUE TITLE
Sidebar does not show context relevant links

### ISSUE THREAD

**Issue by benklop** [zealdocs/zeal#651]
In a build from latest master, the sidebar no longer shows methods or other links for the documentation being viewed.

Initially when a page is viewed in a new docset, the sidebar populates with items from that docset, but not necessarily items that are in any way relevant to that page. Additionally, when viewing new pages within that docset, the sidebar doesn't update at all. So far this occurs with every docset I have tried, including ruby 2, Bash, PHP,  and Qt 5. The sidebar is actually completely non-present for other docsets, like Javascript, Java SE 8, and Python 2 (but I don't know if that's intentional).

Especially for the ruby 2 docset, this issue is crippling, because search doesn't work in that docset either (issue #641) so there's no way to jump to a specific part of the page.

**Comment by trollixx** [comment]
Thanks for reporting, fixed the regression. Unfortunately, related links are not updated as you browse, there's a feature request for that - #131.
