### ISSUE TITLE
Offline installed docsets don't have icon

### ISSUE THREAD

**Issue by abel406** [zealdocs/zeal#654]
I downloaded tgz files and then extracted them in the docsets folder.After i started Zeal and the new docsets appeared in the lis of installed one. But the ones i installed directly from tgz where not showing the corresponding icon untill i updated from the Zeal interface.

Is there any issue with the creation of tgz packages that prevent them to hace the icon inside ?
Is there another way to install tgz packages offline that parmit the Zeal program to show the corresponding item ? 

![zeal_no_icon](https://cloud.githubusercontent.com/assets/3779394/20392003/fb4146a8-aca3-11e6-8706-5d94fb28fd94.jpg)

Thnak you very much.

**Comment by trollixx** [comment]
It's not a bug, but rather how docsets are created. Docsets coming from
Dash don't have icons in them, so we provide icons when you fetch docset
list, and then save icon files during docset installation. A docset you
extract manually will lack icons.

**Comment by trollixx** [comment]
My only idea would be to add an ability for matching a manually installed docset to one from the list, not sure if it's worth it though.

**Comment by trollixx** [comment]
These docsets are provided by Dash, we have no control over them.
