### ISSUE TITLE
Some doc entries are missing in dev builds (Python?)

### ISSUE THREAD

**Issue by FichteFoll** [zealdocs/zeal#656]
Some doc entries are definitely missing in the current dev builds (post-0.3.1), for example `python:asyncio.BaseEventLoop.run_until_complete`.

To verify, I downloaded two portable builds and the Python 3 docset for each. The results are as follows:

zeal-portable-0.3.1-windows-x86:
![2016-11-19_01-59-17](https://cloud.githubusercontent.com/assets/931051/20451611/ca88f9da-adfb-11e6-9ac5-16fd5ae9c1e9.png)

zeal-portable-unstable-0.3.1-21-g143d9dd:
![2016-11-19_02-02-20_zeal](https://cloud.githubusercontent.com/assets/931051/20451651/3912d5e2-adfc-11e6-9b9e-c13816c9ee1e.png)

I also noticed that for a couple other entries the view isn't scrolled to the proper position anymore, but I don't have an example currently (can't remember).

**Comment by trollixx** [comment]
Looks like #650. Any missing items without underscores in their names?

**Comment by FichteFoll** [comment]
Yeah, certainly looks like it. Would also explain that I can't find `__getattr__`.
