### ISSUE TITLE
Request: Documentation for Electron

### ISSUE THREAD

**Issue by zombieleet** [zealdocs/zeal#657]
When will you guys be adding electron to your docset ?

**Comment by trollixx** [comment]
We don't work on docsets at all. All docsets you see are from Dash.

For Electron take a look [here](https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/electron), and then read [this comment](https://github.com/zealdocs/zeal/issues/170#issuecomment-71310603) on how to get it.
