### ISSUE TITLE
Italic Fonts on some Docs

### ISSUE THREAD

**Issue by elnasdgreat** [zealdocs/zeal#658]
Some of the Docs have italic fonts. Like the PHP doc. All of it is in italic font!
Can you please add an option for changing the fonts?
![1](https://cloud.githubusercontent.com/assets/19590512/20454332/85fd4bc2-ae78-11e6-8005-fbfcbc725261.jpg)

**Comment by trollixx** [comment]
This is another Qt WebKit issue :( Should be fixed when we switch to the new version of the engine. Marking as a duplicate of #359.

**Comment by trollixx** [comment]
Actually, I see this problem with the new Qt WebKit. Italic is coming from somewhere else...

**Comment by trollixx** [comment]
Somehow commenting the following in the CSS for Fira Sans font fixes the problem:

```
url('fonts/Fira/ttf/FiraSans-Book.ttf') format('truetype')
...
url('fonts/Fira/ttf/FiraSans-Medium.ttf') format('truetype')
```

Viewing php.net in Zeal also displays this bug.

**Comment by trollixx** [comment]
Still looks like Qt WebKit bug, just a different one...

**Comment by trollixx** [comment]
And here's the bug: annulen/webkit#270.

**Comment by annulen** [comment]
Fix will be released in Qt 5.12.3, see https://bugreports.qt.io/browse/QTBUG-73660

**Comment by trollixx** [comment]
@annulen thanks for the update!

I'll resolve the issue once we ship a new release with updated Qt.

**Comment by trollixx** [comment]
[Looks like](https://github.com/qt/qtbase/commit/736cc1d564a204f66b2a3dd8e12a34b64a38d971) the fix made it into 5.12.2. Will be released with v0.7.0 binaries.

**Comment by DenesKellner** [comment]
A horrible hack until the real solution happens:

- Go to `...../PHP.docset/Contents/Resources/Documents/www.php.net/manual`
- Find all `<body class="docs " style="">`
- Replace all to `<body class="docs " style="font-family:sans-serif">`

Yes it's a lot to replace.
But after that, it's a relief.

**Comment by Nickieros** [comment]
> Somehow commenting the following in the CSS for Fira Sans font fixes the problem:
> 
> ```
> url('fonts/Fira/ttf/FiraSans-Book.ttf') format('truetype')
> ...
> url('fonts/Fira/ttf/FiraSans-Medium.ttf') format('truetype')
> ```
> 
> Viewing php.net in Zeal also displays this bug.

@trollixx thanks, this works
I found this CSS file which contains FiraSans @font-face in PHP.docset\Contents\Resources\Documents\www.php.net\
and used regex to comment all FiraSans urls with truetype format in this file:
```
use regex
/(.*format\(\'truetype\'\))/
to replace it with
/*$1*/
```
