### ISSUE TITLE
[feature] Disable downloaded Docsets

### ISSUE THREAD

**Issue by n9r** [zealdocs/zeal#663]
Possibility to disable (not include in the search) particular docsets that are already stored on disk.

**Comment by jalcine** [comment]
Since it's a search, would this be considered a _filter_? Attempting to centralize language of the feature request to the domain it'd be affecting.

**Comment by n9r** [comment]
Effectively yes but could also improve efficiency on low spec machines.

**Comment by trollixx** [comment]
Duplicate of #77.
