### ISSUE TITLE
search need optimization

### ISSUE THREAD

**Issue by ooing** [zealdocs/zeal#664]
![image](http://ww1.sinaimg.cn/large/de90b49cgw1fa7ynfqa0dj20ch0ftgot.jpg)

it should order by start in "time"

**Comment by ooing** [comment]
time function should  first

**Comment by ilovesusu** [comment]
Classes should be displayed first

**Comment by ooing** [comment]
@ilovesusu  what to  do

**Comment by trollixx** [comment]
This has been partially improved as part of the fix for #603.
