### ISSUE TITLE
[Feature request] [Docs feed addition] Dark background, Snipaste docs

### ISSUE THREAD

**Issue by sng843ndf86nd8** [zealdocs/zeal#673]
Please add support this docs set: https://docs.snipaste.com/#/
Please make feature for night reading. Dark mode. To change white background of pages to dark or to invert colors. Text for bright color and background for dark.

Many thanks !

**Comment by trollixx** [comment]
We do not work on creating docsets, they all are coming from [Dash](https://kapeli.com/dash) or other sources.

As for dark theme, please follow #466.
