### ISSUE TITLE
Can't add new python's docsets.

### ISSUE THREAD

**Issue by sng843ndf86nd8** [zealdocs/zeal#674]
Today has been release new python 3.6.0.
I clicked Add feed, pasted links but it said invalid. I also tried to shorten links but didn't help.
I wanted add this:
https://docs.python.org/3.6/index.html
https://docs.python.org/3.6/tutorial/index.html

It's sad it can't be added for some reason 

Thank you

**Comment by trollixx** [comment]
You cannot add a webpage as a docset. You get a docset update immediately after it lands in Dash.
