### ISSUE TITLE
zeal in ubuntu ppa may not be the latest one

### ISSUE THREAD

**Issue by hujianxin** [zealdocs/zeal#675]

**Comment by trollixx** [comment]
The [PPA](https://launchpad.net/~zeal-developers/+archive/ubuntu/ppa) has 0.3.1, which is the latest version. It cannot be updated for Ubuntu releases prior to Trusty.

**Comment by hujianxin** [comment]
@trollixx Thanks for your reply. Now I know that the ppa version is the release version in github.
