### ISSUE TITLE
Unable to find specific entries with some search queries

### ISSUE THREAD

**Issue by FichteFoll** [zealdocs/zeal#677]
I'm unable to find `argparse.ArgumentParser.add_argument`, or basically anything related to `argparse`, unless I match "argparse" (and then some other conditions). This behavior occurs with `zeal-unstable-0.3.1-23-g8de33d1-windows-x86.zip` and `zeal-unstable-0.3.1-25-gc720633-windows-x86.zip`.

First, to show that the entries generally exist:

![2016-12-30_20-51-51_zeal](https://cloud.githubusercontent.com/assets/931051/21571703/103e779c-ced2-11e6-9253-801e39177677.png)

Now some examples where I'm unable to find anything related to it:

![2016-12-30_20-52-32_zeal](https://cloud.githubusercontent.com/assets/931051/21571704/103f1a9e-ced2-11e6-8c73-8a888e37fc4f.png)

![2016-12-30_20-51-19](https://cloud.githubusercontent.com/assets/931051/21571702/103e5992-ced2-11e6-8eab-b0327d447107.png)

![2016-12-30_22-30-37_zeal](https://cloud.githubusercontent.com/assets/931051/21572972/b718c2f4-cedf-11e6-84b0-8c3104751358.png)

![2016-12-30_22-30-49_zeal](https://cloud.githubusercontent.com/assets/931051/21572974/b8f91088-cedf-11e6-91d2-5841f350c837.png)

I was not able to find out any specific pattern to this or another reproduction case.

**Comment by jmacdonald** [comment]
I ran into this searching for `define_method` in Ruby. You can see that it exists on `Module`, here:

![definition](http://cap.wastedintelligence.com/Jan17-105712.png)

but nothing shows up when searching for it:

![missing](http://cap.wastedintelligence.com/Jan17-105749.png)

**Comment by FichteFoll** [comment]
@jmacdonald what is your zeal version? If you're on a stable build, you will be affected by #650.

**Comment by jmacdonald** [comment]
I'm manually building from source, from the `master` branch.

**Comment by trollixx** [comment]
This is a yet another bug in the fuzzy search logic. Looking into this. Also I am going to make fuzzy search optional.

**Comment by FichteFoll** [comment]
As long as it stays, I'm fine with it. Fuzzy searching is the best, assuming it works.
