### ISSUE TITLE
on download a docset and refresh list, download of library get hidden

### ISSUE THREAD

**Issue by paultejedaf** [zealdocs/zeal#678]
on download a docset and refresh list, download of library get hidden and retry download of same library, bar progress show value of first file and second file downloaded (on same time). On download's finish, app crashed.

Sorry my english
![image](https://cloud.githubusercontent.com/assets/5687572/21687370/c41f3354-d347-11e6-9a48-5fdecea2b9ef.png)

**Comment by trollixx** [comment]
After a docset is installed, it is moved to the `Installed` tab. Obviously the app should not crash, but I cannot reproduce this. Could you provide exact steps on how to get Zeal crash?

**Comment by trollixx** [comment]
Cannot reproduce, and no response.
