### ISSUE TITLE
Sort search result for best match AND(OR) add case sensitive search

### ISSUE THREAD

**Issue by Yanpas** [zealdocs/zeal#679]
Steps To Rerproduce:
1. Download Haskell docset
2. Try to locate `ST`
3. Your search result will be spoiled with some garbage that have "st" in it's name and there will be no ST, cause results are limited by N strings.

Ways to improve sitaution: 
* make case sensitive search optional
* sort results

**Comment by mcomella** [comment]
One possible workaround, if you have multiple docsets: you can filter by a single docset by typing "docset:<query>", e.g. "java:ArrayList". In Haskell's case, perhaps it's "haskell:"?

**Comment by mcomella** [comment]
I expect this to be fixed by #614, which was merged to master at the end of October (see also discussion on #603).

**Comment by Yanpas** [comment]
I've already entered `haskell:`, but there are still too many results

**Comment by WoLpH** [comment]
Not sure if #614 has been released yet but if it is, it's not working yet.

Here's another example:

    1. Download Python docset
    2. search for `type`
    3. Near the bottom you can find the `type()` calls

![image](https://cloud.githubusercontent.com/assets/270571/25842515/8e8b2bda-34a4-11e7-8fed-2bf2dc8bff16.png)

**Comment by trollixx** [comment]
@WoLpH Not yet, please wait for 0.4.0 or use a CI build.

**Comment by WoLpH** [comment]
Thanks, I'll try that. Or perhaps build it myself
