### ISSUE TITLE
Hangs on command line query

### ISSUE THREAD

**Issue by peclik** [zealdocs/zeal#681]
Zeal hangs on windows when started with some query on the command line:
* zeal-portable-unstable-0.3.1-25-gc720633-windows-x86
* any docset (e.g. bash)
* after starting with 'zeal.exe clear', the program hangs for tens of seconds and no keyword is found

On the other hand, if zeal.exe instance is running already and 'zeal.exe clear' is executed, the instance is activated and the given keyword shown.

**Comment by d-ram** [comment]
I think this is the same bug as #632, but this is written more clearsome ;-]

#632 is from October, and there's still no assignee.  I'm going back to 0.2.1, which worked great.

**Comment by peclik** [comment]
#632 seems the same, except it doesn't mention freezes.
I am using workaround: a script which launches 'zeal.exe' first, and then 'zeal.exe <query>'.

**Comment by trollixx** [comment]
Looks like [QTBUG-23378](https://bugreports.qt.io/browse/QTBUG-23378) is the source of the problem. The next release will ship with at least Qt 5.6, and solve this. I'll post an update once I make CI use newer Qt release.

**Comment by Kristinita** [comment]
@trollixx , when it is released 0.4.0?

Thanks.

**Comment by trollixx** [comment]
@Kristinita Soon. With #677 fixed it should be indeed soon.
