### ISSUE TITLE
Zeal crashes when removing a docset which is selected on the left pane

### ISSUE THREAD

**Issue by quantuumsnot** [zealdocs/zeal#683]
OS: Windows 7 x64
Zeal version: 0.3.1

How to reproduce:
1. Select a docset on the left plane
2.  Press on Tools -> Docsets -> Installed -> select the same docset and Press on 'Remove'
3. Zeal crashes with 'Not responding' window

**Comment by trollixx** [comment]
Looks like a duplicate of #659.
