### ISSUE TITLE
show ionic framework picture?

### ISSUE THREAD

**Issue by gudangw** [zealdocs/zeal#684]
how to fix this issue, to show ionic preview picture on zeal
screenshot on official web ionicframework
![ionic off](https://cloud.githubusercontent.com/assets/15372956/22375393/7ab40a7c-e4dc-11e6-9bc3-8eab96af5aee.jpg)

screenshot on my laptop
![ionic zeal](https://cloud.githubusercontent.com/assets/15372956/22375448/a8cacd1a-e4dc-11e6-9775-90cd46c0249e.jpg)

*sorry my english not good

**Comment by Kapeli** [comment]
This is a docset issue not a Zeal issue, so I'll answer.

Unfortunately I couldn't get the demo to work while offline (within a docset), so I had to remove it. There's no way to make it show currently.

**Comment by trollixx** [comment]
Closing per above.
