### ISSUE TITLE
Support for Notepad++

### ISSUE THREAD

**Issue by GaurangTandon** [zealdocs/zeal#687]
Notepad++ consistently ranks as one of the most used editors.
http://stackoverflow.com/research/developer-survey-2016#technology-development-environments

Do you have plans for supporting Notepad++ in the near future?

**Comment by trollixx** [comment]
We do not maintain any IDE or editor plugins. Please see [this page](https://kapeli.com/dash_plugins) about integrating with Zeal/Dash.

**Comment by GaurangTandon** [comment]
Oh, ok. Thanks for the info.
