### ISSUE TITLE
Attempt to use pkg-config on all platforms

### ISSUE THREAD

**Issue by RJVB** [zealdocs/zeal#689]
I did a quick test build yesterday to see if zeal is of interest to bundle as a MacPorts port. I had to patch 2 qmake files that assume that Mac builds never use pkgconfig to find dependencies. It'd be nice if you could provide an option variable for that. Would probably be useful too for MSWin users who use Cygwin.

**Comment by trollixx** [comment]
Switching to CMake should solve this I guess.

**Comment by RJVB** [comment]
While I'm all for preferring cmake over qmake the real issue here is the assumption that certain dependencies are found without querying pkgconfig. Switching to cmake won't solve anything if that assumption is ported to cmake too ;)

**Comment by trollixx** [comment]
Now cmake it should try to use pkg-build everywehre except `WIN32`. Maybe I'll test it with MinGW and/or Cygwin later, and reduce the scope to `MSVC` only.

**Comment by RJVB** [comment]
On Sunday February 19 2017 18:18:12 Oleg Shparber wrote:
>Now cmake it should try to use pkg-build everywehre except `WIN32`. Maybe I'll test it with MinGW and/or Cygwin later, and reduce the scope to `MSVC` only.

Good! I'm a bit swamped with other things but I'll try to test this ASAP.

**Comment by RJVB** [comment]
Works fine from what I can tell.

R.

**Comment by trollixx** [comment]
Great, thanks for the feedback.

**Comment by kraml** [comment]
The commit 89b9d91 on MinGW generates console program instead of GUI program. When started an console window shows.

**Comment by kraml** [comment]
@trollixx as you seems didn't receive an notification of my last comment.

**Comment by trollixx** [comment]
@kraml 054466ff586882f889dbc009b103b390ca6bd049 should fix that.

**Comment by kraml** [comment]
@trollixx Yes it did. Thanks.
