### ISSUE TITLE
Searching for single letter functions

### ISSUE THREAD

**Issue by mikebell** [zealdocs/zeal#698]
Is there an easy way to search for single letter functions e.g. Drupal 7 has a l() function?

At the moment searching l brings up hundreds of results (Drupal 7, Drupal 8 and PHP docsets installed).

I appreciate this is an edge case but wondering if there's some syntax for searching I can use.

**Comment by trollixx** [comment]
That should work with recent changes. On Windows you can try a [CI build](https://bintray.com/zealdocs/windows-ci/zeal-unstable/view).

**Comment by trollixx** [comment]
Fixed in the upcoming release.
