### ISSUE TITLE
Visual Studio Code(VSC) support

### ISSUE THREAD

**Issue by Gektorian** [zealdocs/zeal#701]
Are there any plans to add support for Visual Studio Code(VSC)?

**Comment by trollixx** [comment]
The [Dash extension](https://marketplace.visualstudio.com/items?itemName=deerawan.vscode-dash) should just work

**Comment by Gektorian** [comment]
@trollixx  I'm looking for windows version and this one seems to work only for macox

**Comment by trollixx** [comment]
I see. It is pretty easy to contribute a support for Zeal there. Just run `xdg-open` for Linux, or `cmd` (I think) on Windows with the same `dash-plugin:` URI.
