### ISSUE TITLE
Zeal should respect the user's cursor blink rate setting

### ISSUE THREAD

**Issue by mark-summerfield** [zealdocs/zeal#702]
I tried Zeal on Xubuntu where in the Keyboard settings I have turned off cursor blink. But the Zeal cursor kept blinking -- and this makes it unusable for me. (And for others, see: http://www.jurta.org/en/prog/noblink .) This applied to the default installed version (0.2.1) and also to a freshly built new version (0.3.1).

(I also tried it on Windows (0.3.1) and that correctly respects the cursor setting and doesn't blink.)

**Comment by trollixx** [comment]
We have no control over that. Please check what Qt platform plugin is being used on Xubuntu, and file a bug report for it, as it supposed to respect your environment settings.
