### ISSUE TITLE
Add keyboard shortcuts for better navigation

### ISSUE THREAD

**Issue by atleta** [zealdocs/zeal#703]
Hi,

I really miss the following shortcuts for a faster, more efficient (and trackpoint/trackpad/mouse free) use:
* F3 for find next in the documentation window. At the moment find only works as long as the find popup is open and it always (re)starts searching from the top of the page. However, while the popup is open, you can't navigate using the keyboard (PgUp/Dn or cursor keys).
* Ctrl+PgUp/Dn for navigating between the tabs
* A shortcut for getting back to the document viewer from the document search input field (after pressing Ctrl+K)
* Maybe a shortcut for starting a search so that the whole search string is selected, including the docset name. Maybe this could simply be done when pressing Ctrl+K the second time. (Yep, it can be achieved with Ctrl+A after Ctrl+K)

**Comment by trollixx** [comment]
With the new search toolbar coming in 0.6.0 search no longer resets every time.

**Comment by espdev** [comment]
I'd also like to add:

1. "Super" (windows) key modifier cannot be used in the global shortcut to show Zeal. I would like to set Super+Z for showing Zeal
2. It would be nice to have a shortcut to quick return to search bar (set focus on the search bar) on the tab

**Comment by atleta** [comment]
@espdev it might be your system/setup. I use ctrl+super+space for showing and hiding Zeal.

**Comment by espdev** [comment]
@atleta On Windows I cannot set a shortcut with "Super", the shortcut just do not typed in the field. `Ctrl+` works, `Alt+` works, any combination with Super does not work.

Shortcuts with "Super" work fine in other applications.

**Comment by trollixx** [comment]
Almost everything mentioned in this issue has been implemented over the years:

> F3 for find next in the documentation window. At the moment find only works as long as the find popup is open and it always (re)starts searching from the top of the page. However, while the popup is open, you can't navigate using the keyboard (PgUp/Dn or cursor keys).

Not done. Search toolbar needs to proxy some keys to the web view.

> Ctrl+PgUp/Dn for navigating between the tabs

Implemented.

> A shortcut for getting back to the document viewer from the document search input field (after pressing Ctrl+K)

<kbd>Enter</kbd> does this.

> Maybe a shortcut for starting a search so that the whole search string is selected, including the docset name. Maybe this could simply be done when pressing Ctrl+K the second time. (Yep, it can be achieved with Ctrl+A after Ctrl+K)

Not done. I will make Ctrl+K select everything if somethings is already selected.

**Comment by trollixx** [comment]
Marking fixed for v0.7.1.
