### ISSUE TITLE
Ruby Documentation Methods anchors don't work

### ISSUE THREAD

**Issue by IslamWahid** [zealdocs/zeal#706]
when viewing specific class , when i click on a function name from the side bar it goes to the page of the class not like other docs it should go to the part of the page where this function exists .

I don't know if this problem can be handled by Zeal or it's because of the Doc itself

**Comment by trollixx** [comment]
Please provide specific examples of non-working links, as I was unable to find any. Also, what version of Zeal are you using?

**Comment by vsuhachev** [comment]
Got same bug
Reproduce:
1) type 'ruby: CSV.head' at search box
2) click to CSV.headers method from search results. The document view is positioned start of document instead of headers method

linux, v0.3.1; docset 'Ruby 2'

**Comment by IslamWahid** [comment]
yes that's exactly the problem , and it only happens with the Ruby Documentation

**Comment by trollixx** [comment]
This has been fixed already in the `master` branch. See #641.

It's time to make a release.

**Comment by rufusroflpunch** [comment]
I'm continually bitten by this bug. Any chance of a release any time soon?
