### ISSUE TITLE
Line width of docsets incorrect/not displaying complete code

### ISSUE THREAD

**Issue by Jabro** [zealdocs/zeal#708]
In some cases Zeal does not display the full line e.g. for std::enable_if in the third example:
```
template<class T>
void destroy(T* t, 
             typename std::enable_if<std::is_trivially_destructible<T>::value>::type* = 0) 
{
```
the `= 0)` is not shown. The only way to show it is to select the text. This also seems to be the case for the official [c++ reference](http://en.cppreference.com/w/cpp/types/enable_if). But in Zeal the code Border around the code block suggests that everything within the border is shown.

![screenshot from 2017-03-23 09-22-17](https://cloud.githubusercontent.com/assets/1765251/24238392/63319330-0faa-11e7-938c-20d1e6c589ad.png)

**Comment by trollixx** [comment]
The issue persists even I open the file from the docset in Firefox, so I believe it's a docset generation bug. @Kapeli could you take a look?

**Comment by Kapeli** [comment]
I'm not able to replicate the issue inside Dash, in Chrome 57.0.2987.133 and in Firefox 52.0.2 in macOS 10.12.4.

If you can, try to fix the issue using Web Inspector and let me know what CSS to apply to the docset.

**Comment by Jabro** [comment]
I removed the width of 55em from site_modules.css:1
```

pre, div.mw-geshi {
    width: 55em;
}
```

**Comment by Kapeli** [comment]
Great. I've updated the C and C++ docsets to include that css.

**Comment by trollixx** [comment]
Looks good in the updated docset.
