### ISSUE TITLE
When will the new release 0.4.0 be published?

### ISSUE THREAD

**Issue by roesneb** [zealdocs/zeal#710]
Hi,

i wonder when the release 4.0.0 will be published?
All open tickets for the milestone are closed. 
The nightly builds are also behind.

I am grateful for the work you are doing!

regards Ben

**Comment by BarrensZeppelin** [comment]
Second this.
Just installed directly from the master branch. The new search engine is a lifesaver!

**Comment by roesneb** [comment]
The nightly builds are made with the master branch, right?
i've tested it on my virtual machine with windows 7 (#632) 
if command line queries are working and strangely sometimes it did and most of the time it did not.
I have to investigate further.

**Comment by trollixx** [comment]
There are a few outstanding issues and tasks that have to be addressed first:
* Fuzzy search needs to be optional - the current implementation is just too buggy.
* CI has to be updated to Qt 5.8 and [qtwebkit-ng](https://github.com/annulen/webkit).
* There's an outstanding [bug](https://github.com/annulen/webkit/issues/461) in Qt WebKit that causes a crash on HiDPI screens when dark mode is enabled.

At this time the release process is kind of manual, so I need to find time for that as well.

CI builds both `master` (unstable) and `stable` branches. Both in regular and portable editions.

**Comment by trollixx** [comment]
Fuzzy search is now disabled by default (7b1223b03dc0a12c871fea53017a6257bb443c2c).

**Comment by trollixx** [comment]
Just a short update, HiDPI bug has been fixed in qtwebkit-ng. Now I need to switch CI to VS compiler and make it use the new Qt WebKit. I'll post an update here once we have new CI builds.

**Comment by RickyWong33** [comment]
Really looking forward to get 0.4.0 coming.

**Comment by jkozera** [comment]
We've now managed to do an unstable CI build with Qt 5.9.1 and qtwebkit-ng - you can get it for Windows from:

- https://bintray.com/zealdocs/windows-ci/zeal-unstable/0.3.1-102-g57c9edd#files/zeal-unstable
- https://bintray.com/zealdocs/windows-ci/zeal-portable-unstable/0.3.1-102-g57c9edd#files/zeal-portable-unstable (portable)

Please test it, since it is likely to become the next release! :)

**Comment by thuandt** [comment]
When Ubuntu PPA will update new version?
Bintray seem only has Windows binary, current version 0.3.1 seem broken with me, I can search but can't click to entry in left

**Comment by trollixx** [comment]
@thuandt If you want to maintain the PPA, please let me know, otherwise no ETA. [Soon](https://wow.gamepedia.com/Soon).

**Comment by trollixx** [comment]
https://zealdocs.org/blog/2017/07/09/zeal-0.4.0-released.html
