### ISSUE TITLE
Skip mathcing for parameters, just method or class name?

### ISSUE THREAD

**Issue by sun1991** [zealdocs/zeal#711]
I have installed Java SE 7 docset, and type in "String" to search for definition of String class, but a lot of irrelevant entries displayed because they all have a String type parameters in method defition, which makes actual String class very hard to pinpoint. Can you add an option to skip match for parameters, just method or class name? Thanks!

version: 0.3.1

**Comment by trollixx** [comment]
Search is far from ideal in 0.3.1, it's partially fixed if you build Zeal from the `master` branch, or use our [CI builds](https://bintray.com/zealdocs/windows-ci).
