### ISSUE TITLE
Download doesn't work in Chrome

### ISSUE THREAD

**Issue by channprj** [zealdocs/zeal#714]
`Resource interpreted as Document but transferred with MIME type application/zip` shows on console in Chrome and do nothing with pending.

I think this is a Chrome issue or just my problem.. I'll close  this issuse when I find the cause of error.

**Comment by trollixx** [comment]
Where do you see that error message? What are you trying to download?

**Comment by channprj** [comment]
Sorry, It crashed with my chrome extension. Thank you for your help.
