### ISSUE TITLE
Can I use the source code build an Android app?

### ISSUE THREAD

**Issue by bobiscool** [zealdocs/zeal#715]

**Comment by trollixx** [comment]
A version of Zeal ported for Android has been requested (#454) in the past, but no work has been done for that. If you want to contribute towards the port, please let us know!

There's also [LovelyDocs](https://play.google.com/store/apps/details?id=com.lovelyhq.android.lovelydocs&hl=en).

If creating an independent app is on your mind, here's a quick brief on the situation:

* The source code is available under [GPLv3](https://github.com/zealdocs/zeal/blob/master/COPYING), so you can build a derivative work as long as your source code stays available under the same license.

* As for the content, we redistribute [Dash](https://kapeli.com/dash) docsets under an agreement (see #24). You'd have to secure a personal permission from the author of Dash if you want to do the same.

* Our server side services are currently provided only for users of Zeal, so please refrain from using them without asking first.
