### ISSUE TITLE
--version is segfaulting on Fedora 25

### ISSUE THREAD

**Issue by garry-cairns** [zealdocs/zeal#717]
I'm chasing down [an issue I'm having with the zeal-at-point emacs package](https://github.com/jinzhu/zeal-at-point/issues/33). I think it's related to zeal, which seems to be segfaulting when asked for its version as below.

    [garry-cairns@localhost ~]$ zeal -v --version
    Zeal 0.3.1
    Segmentation fault (core dumped)

This is a fresh install of Fedora 25 using the zeal package from the repository.

**Comment by garry-cairns** [comment]
I've reinstalled Ubuntu (gnome) and confirmed this seems Fedora specific.

**Comment by trollixx** [comment]
Thanks for reporting, any chance you could also collect a backtrace?

**Comment by garry-cairns** [comment]
Sorry just seeing this. I've uninstalled Fedora for now but I'll try running this from a live USB when I get a moment.

**Comment by bendem** [comment]
Cannot reproduce either from the current head (73ecfb944c6670abcb458eb4362ee1f9960f385d) or from the distro package. Using Fedora 25 x86_64

**Comment by trollixx** [comment]
Closing, please let me know if the problem can be reproduced.
