### ISSUE TITLE
Dark theme causes new QtWebKit TP5 to segfault?

### ISSUE THREAD

**Issue by auscompgeek** [zealdocs/zeal#719]

**Comment by trollixx** [comment]
It's not very helpful without details. What's your OS? Qt Version? When does the crash occur?

**Comment by auscompgeek** [comment]
Fair enough. This is on Arch Linux (hence Qt5 5.8.0). I believe this happens somewhere between the window being created and the widgets being painted — the window appears entirely black if I run it in gdb.

**Comment by auscompgeek** [comment]
I did a git bisect between v0.3.1 and HEAD: 318eef91e715ff568fcfa935840dc0772b66884d is the first bad commit.

As it turns out, I had the dark theme enabled in my config. Manually editing the config causes the segfault to disappear. This is starting to sound like a bug in the new QtWebKit; I'll do some more investigation.

**Comment by auscompgeek** [comment]
Ah. annulen/webkit#461. Go figure. Would explain why I wasn't able to reproduce this bug in qutebrowser just then.

**Comment by auscompgeek** [comment]
I think I'm going to comment out the `AA_EnableHighDpiScaling` anyway, it's causing images to render too large on my screen.

**Comment by trollixx** [comment]
`AA_EnableHighDpiScaling` should not affect image size. Perhaps, your system has wrong DPI information about the display.
