### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by ferronrsmith** [zealdocs/zeal#721]
/home/personal_git/zeal/.lib/libUi.a(shortcutedit.o): In function `Zeal::WidgetUi::ShortcutEdit::ShortcutEdit(QString const&, QWidget*)':
shortcutedit.cpp:(.text+0xb5): undefined reference to `vtable for Zeal::WidgetUi::ShortcutEdit'
collect2: error: ld returned 1 exit status
Makefile:71: recipe for target '../../bin/zeal' failed
make[2]: *** [../../bin/zeal] Error 1
make[2]: Leaving directory '/home/ferron/personal_git/zeal/src/app'
Makefile:43: recipe for target 'sub-app-make_first' failed
make[1]: *** [sub-app-make_first] Error 2
make[1]: Leaving directory '/home/ferron/personal_git/zeal/src'
Makefile:68: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2

**Comment by trollixx** [comment]
You need to do a clean build, since I've added missing `Q_OBJECT` macro in `ShortcutEdit`.
