### ISSUE TITLE
[Portable version] Docset directory does not stick when reopened

### ISSUE THREAD

**Issue by flashmech** [zealdocs/zeal#722]
Hello, I tried to update the docset directory but after the app closed, upon reopened, the default directory will be shown. It will be great that the docset directory sticks. Probably a setting in the .ini file? Cheers.

**Comment by flashmech** [comment]
The problem is I don't know what to add in the .ini file to make it remember the path. Do you have an example? Thanks in advance.

**Comment by trollixx** [comment]
```ini
[docsets]
path=path/to/docsets
```

**Comment by flashmech** [comment]
Thanks! This fix it for good. 👍

**Comment by trollixx** [comment]
Duplicate of #609.
