### ISSUE TITLE
Unresponsible UI with Scala docset after typing `scala:`

### ISSUE THREAD

**Issue by hsiktas** [zealdocs/zeal#723]
As soon as I type `scala:` into the search field the entire app freezes for +10 seconds and it results in 100% load on one CPU core.
This is happening on Windows 10 with the current 0.3.1 release and I did not notice this with the other docsets.

Can someone else reproduce this issue?

**Comment by trollixx** [comment]
Please try:
1. Reinstalling the docset.
2. The latest [CI build](https://bintray.com/zealdocs/windows-ci/zeal-unstable/view).

**Comment by hsiktas** [comment]
Unfortunately it is still happening with the CI build zeal-unstable-0.3.1-101-gc6003e1-windows-x86.zip and a reinstalled Scala docset.
![image](https://cloud.githubusercontent.com/assets/4571159/25595457/20d04ab0-2ec5-11e7-8efe-fd13016e4fb2.png)
If I switch over to for example the Java SE8 docset I can't notice any UI freezes.

**Comment by trollixx** [comment]
I bet it's another Qt Webkit bug. I'll post an update here once we switch CI builds to the new version of the Qt Webkit.

**Comment by chikei** [comment]
I can confirm [new CI build mentions here](https://github.com/zealdocs/zeal/issues/710#issuecomment-320739298) solved this issue

**Comment by trollixx** [comment]
@chikei Thanks for reporting!

**Comment by Yanpas** [comment]
Scrolling is still sluggish in zeal 0.4 on windows. Dragging vertical bar loads CPU a lot

**Comment by trollixx** [comment]
@Yanpas any specific examples I could reproduce?

**Comment by Yanpas** [comment]
I observe it on Windows 10, `python3:python3:bytearray` page. I drag side scroller and move it up-down quickily, cpu quickly goes 100%

**Comment by trollixx** [comment]
@Yanpas I can reproduce the slowness, not sure what causes it. Please create a new ticket for that problem. This one is about issues with Scala docset, which were reported fixed.
