### ISSUE TITLE
Sub filtering of docsets

### ISSUE THREAD

**Issue by mattbreeden** [zealdocs/zeal#724]
It would be great to be able to filter the categories within a docset during a search. The example provided at https://zealdocs.org/usage.html seems to be good, but that's not how it shows up when doing a search currently. It shows up like (see image below). The string module that is first on the example usage link isn't even in the box. You have to scroll down and find it.

I would love the ability to search `python:m:string` or `python:f:string` (or probably actually `python:module:string` since there are some collision issues with abbreviations).

![2017-05-01-181252_1170x1202_scrot](https://cloud.githubusercontent.com/assets/5240422/25600593/1de2bcf0-2e9a-11e7-94f0-dc523b9fe7dd.png)

**Comment by trollixx** [comment]
Major improvements to how the search is performed coming in 0.4.0. Please try to build Zeal yourself, or get a CI build. The problem you're seeing is hopefully fixed as part of #603. I don't think we need filtering by symbol type at this time, but feel free to open a separate feature request.
