### ISSUE TITLE
Open URL button opens Atom editor instead of a browser

### ISSUE THREAD

**Issue by FernandoBasso** [zealdocs/zeal#727]
When I click on "Open URL" in the top right button, Atom editor is launched. I assumed clicking that button would open my default browser in the URL with the “original” docs.

I run Arch Linux + Xfce. Is that a problem with my setup, perhaps, or something related to Zeal itself?

**Comment by trollixx** [comment]
It means that Atom is your default association for opening HTML files. Zeal doesn't have any special logic here, and simply asks your OS to open the file.
