### ISSUE TITLE
Ctrl-h does not do scoped search/pass in a string to Zeal 

### ISSUE THREAD

**Issue by Interagierende-Systeme** [zealdocs/zeal#728]
On Windows 7, using the Atom Editor, Ctrl-h does not return from a scoped search. Instead, it simply opens the Zeal Browser. This does not happen in Linux. I doubt this is an issue in the codebase, instead, I am probably doing something wrong. Has anyone else had this problem? Thanks.

**Comment by trollixx** [comment]
Could you try a recent [CI build](https://bintray.com/zealdocs/windows-ci/zeal-unstable/view)?

**Comment by trollixx** [comment]
This is being investigated in blakeembrey/atom-dash#49.
