### ISSUE TITLE
First start-up does not handle the dash-plugin:// URI correctly on Windows

### ISSUE THREAD

**Issue by szhongren** [zealdocs/zeal#729]
You can call `start dash-plugin://query=test` on Windows from the command line but Zeal does not start correctly if Zeal is not already running. Just `start dash-plugin://` works fine though, so there seems to be a problem with the parsing of the parameters.

**Comment by trollixx** [comment]
Could you try a recent [CI build](https://bintray.com/zealdocs/windows-ci/zeal-unstable/view)? It seems to be working fine with the fresh code base.

**Comment by szhongren** [comment]
That does appear to be fixed, hmm. Did you manage to reproduce the problem? I probably should have mentioned that I came across the problem while running the start command from Node's `child_process.exec()`.

**Comment by trollixx** [comment]
Most likely 4711e0cf3cf07e2d2eceba4adf26b6746c11ce09 fixed the problem since 0.3.1.

**Comment by trollixx** [comment]
Marking as duplicate of #681.

**Comment by szhongren** [comment]
Is this fix supposed to come with 0.3.2? I'm still getting it with my installed Zeal 0.3.1.

**Comment by szhongren** [comment]
Oh wait never mind. Unstable build, it's right in the name. Thanks!

**Comment by trollixx** [comment]
The next release will be 0.4.0.

**Comment by szhongren** [comment]
Sounds good. Thanks for your work on this!
