### ISSUE TITLE
Can not open boost documents

### ISSUE THREAD

**Issue by Joel-hou** [zealdocs/zeal#730]
![tim 20170516175049](https://cloud.githubusercontent.com/assets/11814908/26100439/742931ee-3a60-11e7-8c60-4cb6f2b19fd4.png)

Double click on the left zone doesn't show any of the documents

**Comment by trollixx** [comment]
This is pretty old, re-downloading the docset should fix such issues.

Implementing #599 will help to avoid similar problems in the future.
