### ISSUE TITLE
download doc crash 

### ISSUE THREAD

**Issue by avalond** [zealdocs/zeal#731]
download doc progress bar is too fast then zeal crash, version is 0.31

**Comment by kswaldemar** [comment]
Any step to reproduce? Never faced it before.

**Comment by trollixx** [comment]
Without specific details this report is pretty much useless. @avalond please provide the way to reproduce the problem, so we can fix it. Thanks.

**Comment by trollixx** [comment]
Duplicate if #788, which provides a way to reproduce the crash.
