### ISSUE TITLE
I'd like Zeal more if I could adjust character size.

### ISSUE THREAD

**Issue by RBM-GITHUB** [zealdocs/zeal#732]
I installed Zeal yesterday but removed it today because characters were too small for me to read but I couldn't adjust the size.

---

In Preferences, I could increase the "minimum font size" from 0 to 16 (points, maybe?), but it didn't make it bigger as I wanted.

My display was "sort of HiDPi"- which had a 1.5x denser display than ordinary. So I thought HiDPi settings didn't apply, which left characters too small to read.

---

Also I noticed that the scrolling wasn't so smooth. I read a lot on the screen, so smooth scrolling matters to me- sorry I can't help with that, I know none of C++ or Qt.

**Comment by kswaldemar** [comment]
> In Preferences, I could increase the "minimum font size" from 0 to 16 (points, maybe?), but it didn't make it bigger as I wanted.

That option work for me. You can increase it even more, say to 30.

**Comment by RBM-GITHUB** [comment]
@kswaldemar Oh, I was using Windows. Changing it had no effects on the actual letter size.

**Comment by kswaldemar** [comment]
@RBM-GITHUB Also on windows. On which docset you faced issue? For me it works with all docsets, which I use (boost, c++, qt, python3): selecting minimum font size 30 make letters really huge.
I'm using zeal 0.3.1

**Comment by trollixx** [comment]
@RBM-GITHUB Please try the latest [CI build](https://bintray.com/zealdocs/windows-ci/zeal-unstable/view). It should work much better on a HiDPI screen.

**Comment by trollixx** [comment]
This should be fixed with #111 implemented, marking as a duplicate.

Regarding smooth scrolling, I've created #789 to track that.
