### ISSUE TITLE
ZealDoc can't read Typescript file in Angular 2 docsets

### ISSUE THREAD

**Issue by Dadapas** [zealdocs/zeal#734]
ZealDoc can't read Typescript file in Angular 2 docsets

**Comment by trollixx** [comment]
Could you provide the specific steps to reproduce the problem? Thanks.

**Comment by Dadapas** [comment]
See the message​

2017-06-14 0:52 GMT+03:00 Oleg Shparber <notifications@github.com>:

**Comment by trollixx** [comment]
Can't reproduce this problem with the information provided.
