### ISSUE TITLE
Zeal freeze when do search in large page

### ISSUE THREAD

**Issue by eghojansu** [zealdocs/zeal#735]
It was happen when I do search in page in a large page like mysql docset. My guess is that Zeal perform searching every time I hit a key. As my type speed is quite fast, I suggest Zeal to perform searching after last key hit. Zeal need to add delay before perform search. 

Thank you for reading this, sorry for my bad english

**Comment by trollixx** [comment]
Are you talking about searching in a docset, or in a page withing a docset?

**Comment by eghojansu** [comment]
It was happen when I do search within a page (with ctrl+f shortcut). The page itself has huge content, and when I type in that search box, it start freezing.
I forgot to mention my OS and zeal version. 
Linux Ubuntu 16.04 64 bit
Zeal version 0.3.1

**Comment by trollixx** [comment]
Try more recent version of Zeal, and if you manage to reproduce this bug, please provide which pages specifically cause the freezing. I cannot reproduce this bug muself.

**Comment by trollixx** [comment]
Please reopen if the problem is still there.
