### ISSUE TITLE
[Feature Request] Search inside docset

### ISSUE THREAD

**Issue by dejlek** [zealdocs/zeal#737]
I apologise if this feature already exists.

I was trying to search only within specific docset, but when I search for something Zeal gives me result across all docsets so I end up seeing completely unrelated results (C++ and Java for an example).

If there is no way to do this, I would kindly request this feature to be implemented as that is probably something I will use all the time...

**Comment by SuperTitanjr** [comment]
You look at this in the zeal readme page

https://github.com/zealdocs/zeal#query--filter-docsets

**Comment by trollixx** [comment]
Please use `cpp:` or `java:` prefixes. And yes, we need better docs :(
