### ISSUE TITLE
incremental build failure

### ISSUE THREAD

**Issue by RJVB** [zealdocs/zeal#738]
I pulled the latest sources (#89b9d91938c47a7d73c1ec70f08d45ab8014179e -> #c6003e19b93cf45ba96d06b2e7b68efe88c501a3) and thought I only had to invoke `make` in my shadow build directory to get the latest binary.

Not so, so removed the CMakeCache.txt file as well as all CMake* directories in the toplevel build dir, re-ran cmake with the correct local arguments, *then* ran `make clean` followed by `make` and still got the error below. I had to wipe and recreate the entire shadow build directory, then the build completed without further issues.

I saw a commit mentioning .ui files and CMake, is it possible it introduced a regression (in addition to fixing something I didn't realise was broken)? FWIW, I did incremental builds before without any problems.

I saw that before on Mac but didn't want to report it until I could reproduce it on Linux ;)

```
[ 45%] Building CXX object src/libs/ui/CMakeFiles/Ui.dir/aboutdialog.cpp.o
cd /path/to/work/build/src/libs/ui && /opt/local/bin/clang++-mp-4.0  -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_URL_CAST_FROM_STRING -DQT_RESTRICTED_CAST_FROM_ASCII -DQT_USE_QSTRINGBUILDER -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DZEAL_VERSION=\"0.3.1\" -I/path/to/work/build/src/libs/ui -I/path/to/work/zeal-git/src/libs/ui -I/path/to/work/build/src/libs/ui/Ui_autogen/include -I/path/to/work/zeal-git/src/libs -isystem /opt/local/include/qt5 -isystem /opt/local/include/qt5/QtGui -isystem /opt/local/include/qt5/QtCore -isystem /opt/local/share/qt5/mkspecs/linux-g++-64 -isystem /opt/local/include/qt5/QtX11Extras -I/opt/local/include -isystem /opt/local/include/qt5/QtConcurrent -isystem /opt/local/include/qt5/QtNetwork -isystem /opt/local/include/qt5/QtWebKitWidgets -isystem /opt/local/include/qt5/QtWebKit -isystem /opt/local/include/qt5/QtWidgets  -O3 -g -std=c++11 -DNDEBUG -I/opt/local/include   -fPIC -std=gnu++11 -o CMakeFiles/Ui.dir/aboutdialog.cpp.o -c /path/to/work/zeal-git/src/libs/ui/aboutdialog.cpp
/path/to/work/zeal-git/src/libs/ui/aboutdialog.cpp:32:12: error: allocation of incomplete type 'Ui::AboutDialog'
    ui(new Ui::AboutDialog)
           ^~~~~~~~~~~~~~~
/path/to/work/zeal-git/src/libs/ui/aboutdialog.h:32:7: note: forward declaration of 'Zeal::WidgetUi::Ui::AboutDialog'
class AboutDialog;
```

**Comment by trollixx** [comment]
I am not a CMake guru, so not sure what exactly caused the problem. And I am not sure it makes much sense or even is possible to guarantee incremental building for a development branch.
