### ISSUE TITLE
Can't bring Zeal's main window to the front.

### ISSUE THREAD

**Issue by skywind3000** [zealdocs/zeal#740]
As a vim/atom editor user, I use this command to look up "print" in zeal from vim/atom:

```
D:\Program Files\zeal\zeal.exe dash://python:print
```

It worked, but the editor's window was still on the top level and occupied the full screen.

It seems no way to bring main window of zeal to the front after a url query ? If I calling zeal from a maximized editor window, there is no chance to see the zeal window instead of alt+tab ??

**Comment by trollixx** [comment]
Have you tried using [this extenstion](https://atom.io/packages/dash)?

**Comment by skywind3000** [comment]
Zeal window is still behind atom's window, when I am using this plugin to lookup keywords in atom.

step1: install atom-dash plugin in atom
step2: open some source file and click right mouse button on a keyword and select `Look up in Dash` in the context menu.
step3: zeal starts, and displays its window in front of atom, and shows the search result, first time is OK.
step4: active the atom's window to the front, and the zeal window is covered by the atom window.
step5: look up another keyword in atom, the zeal window should popup to the front, but it doesn't show itself as a top-level window.

**Comment by trollixx** [comment]
This problem has been reported before, but now I think we have a solution. Please follow the linked ticket.

Duplicate of #440.
