### ISSUE TITLE
UI problems under unity

### ISSUE THREAD

**Issue by atleta** [zealdocs/zeal#741]
Hi,

I've just switched to unity and after setting up zeal the way I used to use it (minimize to status bar or window close, hot key, and start minimized) I can't restore the window any more. The app just sits in the status bar, hot key doesn't work and the only item in the context menu is 'quit'. So no way to use it. Even exiting and restarting won't work because it starts minimized...

The problem is that the shortcut I picked (Meta+Shift+Space) wouldn't work (neither Alt+Shift+Space does) AND the context menu misses a restore option. So I had to edit the config file manually.

Another problem is that after closing and restoring the window, the window menu does not appear any more. (Even if the app is focused, the menu is not revealed when hovering the title bar, however underlying window will show its menu when hovering that. While Zeal still has the focus. Weird.)

**Comment by trollixx** [comment]
I believe you've built Zeal yourself. The current code from the `master` branch lacks Hide/Restore menu context items.

Unfortunately, global shortcuts are really bugged, and often don't work properly. (See #308 and #500).

Regarding the last issue please read the warning for Unity users [here](https://zealdocs.org/download.html#linux-ubuntu).

**Comment by atleta** [comment]
No, I've used the official package from the ppa. I can confirm that the hide/restore menu items are missing, that's the problem I'm reporting. The global shortcuts (sometimes) don't work properly and the app cannot be restored in any other way.

Regarding the menu issue, the warning talks about *non*-Unity environments: "Attention non-Unity users!" and I'm using unity. (But haven't seen the issue since then.)

**Comment by trollixx** [comment]
Right, my bad, that menu problem occurs for non-Unity users. For Unity users there's another one - #327.

Regarding Hide/Restore items, if you're on regular Zeal 0.3.1 from the PPA, then our detection for Unity fails. What Untuntu and Unity versions do you have?

**Comment by atleta** [comment]
It's ubuntu 17.04 with unity 7.5.0 (package version: 7.5.0+17.04.20170407.1-0ubuntu1)

**Comment by saierd** [comment]
The same thing happens on Ubuntu 16.04 since the latest update. I have installed version `0.4.0-1ppa1~xenial1` from the PPA and it doesn't have any restore entries in the context menu.

**Comment by trollixx** [comment]
It's a regression due to switch to `QSystemTrayIcon` instead of own implementation. I'll add `Show` to the context menu if environment is Unity. Not sure if there's any need in `Hide` item.
