### ISSUE TITLE
Zeal crashes on Linux (Arch/Antergos) when installing MySql docset.

### ISSUE THREAD

**Issue by vladimirov1** [zealdocs/zeal#743]
On windows there is no issue.

**Comment by trollixx** [comment]
Unfortunately, I currently don't have access to my Arch Linux, if you can reproduce this, please submit a stack trace.

**Comment by vladimirov1** [comment]
Fixed it manually. For some reason already installed docset was not visible in Zeal, and although docset installed it alowed new installation. After I deleted docset folder manually, new installation was flawless. 
Deleted docset folder was normal, not named deleteme.

**Comment by trollixx** [comment]
Without a stack trace or corrupted docset to reproduce the crash I can't fix this. Once #599 is implemented the problem will go away.

If you encounter a similar problem in the future, please create a ticket with the corrupted docset folder attached.

**Comment by trollixx** [comment]
Duplicate if #788.
