### ISSUE TITLE
Restore last opened tabs on startup

### ISSUE THREAD

**Issue by quanzhuo** [zealdocs/zeal#744]
Can you add such a new feature? This feature will sometimes very useful !

**Comment by anephew** [comment]
+1 This feature is missing

**Comment by trollixx** [comment]
Actually a duplicate of #78 .

**Comment by anephew** [comment]
This feature is missing. It takes a long time to return without bookmarks (https://github.com/zealdocs/zeal/issues/290) and last tabs to the current work (

Very much waiting for the both functions!

Thanks!
