### ISSUE TITLE
Docset cannot be installed if path contains non-Latin characters

### ISSUE THREAD

**Issue by MichaelSolotky** [zealdocs/zeal#747]
I'm trying to install some docsets, click the button with it, download goes till the end and it goes to installation process, shows 0% and then stops doing anything. The docset folder is empty. Docsets I tried to install are C++, python 2 and 3. I'm using windows 10.

**Comment by trollixx** [comment]
Sounds like a problem with file permissions. Could you confirm that Zeal has write access to the docset storage directory?

**Comment by MichaelSolotky** [comment]
Yes. I've also explicitly set common access to that directory and it didn't help.
Actually when zeal was firstly installed there was no any docset directory. I've found the path to it in zeal->preferences, but the directory there didn't exist. The path was standard: C:\Users\Михаил\Documents\zealdocs
And I think the cause is the folder name written in сyrillic.
I've replaced the path with this С:\zealdocs, tried again and it started to install docs.

**Comment by trollixx** [comment]
I was able to reproduce this bug. Seems like we are loosing UTF-8 somewhere...

**Comment by trollixx** [comment]
Quick investigation showed that libarchive fails to extract files to a path containing Cyrillic characters.

**Comment by trollixx** [comment]
De-prioritizing in hope to fix this by implementing #138.

**Comment by jimmylab** [comment]
Same thing happens when the path contains Chinese character on windows 8, either.
The default path is "C:\Users\佳欢\AppData\Local\Zeal\Zeal\docsets". I had to switched C:\ZealDocs to make it work.
