### ISSUE TITLE
auto redirect to spam page, often http://security60-e.com

### ISSUE THREAD

**Issue by gladx** [zealdocs/zeal#752]
in zeal 0.3.1 on Linux Mint 17.3 , when click on some external link, i auto redirect to spam page or advertisement site. and often see link  http://security60-e.com.
another problem is I can not kill zeal process 
`glad ~  $ ps aux | grep zeal`
`glad     30141  0.0  0.0  15800  2264 pts/4    S+   17:41   0:00 grep --colour=auto zeal`
`glad ~  $ sudo kill 30141`
`[sudo] password for glad: `
`glad ~  $ ps aux | grep zeal`
`glad     30153  0.0  0.0  15800  2172 pts/4    S+   17:41   0:00 grep --colour=auto zeal`
`glad ~  $ pkill zeal`
`glad ~  $ ps aux | grep zeal`
`glad     30162  0.0  0.0  15800  2140 pts/4    S+   17:42   0:00 grep --colour=auto zeal`

some screen shot here
http://s8.picofile.com/file/8301340342/45.png
http://s8.picofile.com/file/8301340376/40.png
http://s8.picofile.com/file/8301500426/42.png
http://s8.picofile.com/file/8301500984/54.png
http://s8.picofile.com/file/8301501000/55.png
http://s8.picofile.com/file/8301501042/00.png

**Comment by trollixx** [comment]
Is it possible that something infected your files? Otherwise it looks like PHP docset got infected somehow. @Kapeli any ideas?

**Comment by Kapeli** [comment]
As far as I can tell from http://s8.picofile.com/file/8301500426/42.png the issue is with the Yii docset.

I've tried replicating it and I'm not able to. Opening the "string" link correctly takes me to http://www.php.net/language.types.string.

@trollixx can you try to replicate yourself?

Steps I followed:
1. Search for `bootstrap\activeform::field` in the Yii 2.0.12 docset
2. Click the "string" link

**Comment by trollixx** [comment]
@gladx it looks like you're having issues opening external URLs. So, it's either infected HTML files of the docsets, or there's something on your computer or network that redirects you to that URL.

Try reinstalling the docsets and see if the problem persists.

**Comment by gladx** [comment]
@trollixx I remove all docsets and reinstall zeal but still i have problem.

**Comment by trollixx** [comment]
Then I think your computer or network is infected.

**Comment by gladx** [comment]
Ok, I reinstall my Linux Os and if i have same problem report it.
Thanks for Zeal :-)
