### ISSUE TITLE
Windows: dash:// and dash-plugin:// protocols are no longer supported

### ISSUE THREAD

**Issue by eranif** [zealdocs/zeal#754]
Hello,

I got this report: https://github.com/eranif/codelite/issues/743 from a CodeLite user who uses Zeal and he complains that the integration is broken with latest Zeal 0.3.1

To confirm that the problem is lying in Zeal and not in CodeLite, I did the following:

- Open Windows File Explorer and pasted this in the address bar: `dash-plugin://keys%3Dphp%26query%3Dfopen`
- Zeal launches but it hangs for about 2 minutes, it then shows the "start page" (no query result)

I then did:

- Uninstall Zeal 0.3.1
- Install Zeal 0.2.1, this is the latest known working version that supports the custom protocols (took me a while to found a binary installer on the web)
- Open Windows File Explorer and pasted this in the address bar: `dash-plugin://keys%3Dphp%26query%3Dfopen`
- Zeal works (instantly)

**Comment by trollixx** [comment]
I just tried with the latest code from the `master` branch, and it seems to work as expected.

**Comment by eranif** [comment]
i don't have access to master binary, however, if you look at the big i linked, you will see that my findings were confirmed by another person. 
are there any plans on releasing Master any time soon?

**Comment by trollixx** [comment]
You can try a [CI build](https://bintray.com/zealdocs/windows-ci/zeal-unstable/view). And yes, we are trying to get 0.4.0 out as soon as possible...

**Comment by eranif** [comment]
Ok, I have installed CI build.
It does not seem to hang (except for one time, but I could not make it happen again)

However, the original problem that was reported on CodeLite's issue tracker is reproduced (the query appears in the search box, but it does not seem to find anything)

I did some digging, and it seems that the problem is with the `keys` part of the URL:
If the query contains the `keys` part, then the query seems to be sitting in the search box and doing nothing. If I omit the `keys` part from the `dash-plugin` protocol, then the query is executed

For example:

This one:
`dash-plugin://keys%3DC%2B%2B%26query%3Dmake_pair` - **FAILS**. This one is the encoded version of the URI: 
`dash-plugin://keys=c++&query=make_pair`

But this:
`dash-plugin://query%3Dmake_pair` - **OK** .This one is the encoded version of the URI: 
`dash-plugin://query=make_pair`

**Comment by trollixx** [comment]
It's because the keyword/prefix for the C++ docset is `cpp`, not `c++`. Please try `dash-plugin://keys=cpp&query=make_pair`.
