### ISSUE TITLE
Windows: Uninstall do not remove custom protocol handlers

### ISSUE THREAD

**Issue by eranif** [zealdocs/zeal#755]
When uninstalling Zeal, the custom protocol handlers (`dash://` and `dash-plugin://`) are still in the registry.
This could be a real pain when you uninstall Zeal and then install a newer version on a different path.

These registry entries should be removed during uninstall:
```
HKEY_CLASSES_ROOT\dash-plugin\shell\open\command
HKEY_CLASSES_ROOT\dash\shell\open\command
```

**Comment by trollixx** [comment]
This is strange, [our installer](https://github.com/zealdocs/zeal-packaging/blob/master/windows-wix/zeal.wxs) creates those entries and should remove them when uninstalling. At least that's my understanding how WiX-created installer should work. Will check it out.

**Comment by trollixx** [comment]
It was a bug in the MSI installer, the new one (for the version 0.4.0) should properly remove the protocol handlers.
