### ISSUE TITLE
Downloading 'Wordpress' docset appears to hang on install

### ISSUE THREAD

**Issue by theundecided** [zealdocs/zeal#756]
I think ive narrowed a hanging instance (to the point I need to crash the app and restart. ).

I belive it has something to do with installing the 'wordpress' docset. 

side note..... id love it if there was a way to still use the app while installing an other docset. right now one can't both install a docset(s) and use a previously downloaded/installed docset.

**Comment by trollixx** [comment]
Please check your docset storage directory, and try removing any Wordpress related directories if any.

**Comment by shadyshrif** [comment]
I have the same issue. with clean zeal installation on windows 10
![image](https://user-images.githubusercontent.com/10328735/29602138-eb122a90-87ef-11e7-94cb-0e1463ee45d8.png)

**Comment by trollixx** [comment]
I can't reproduce the problem, but from your screenshot it seems like the issue is/was with the server.

For me downloading WordPress docset is just extremely slow.

@shadyshrif Do you see the same problem with any other docset?

**Comment by trollixx** [comment]
Seems like a network failure, no a bug in Zeal.
