### ISSUE TITLE
Windows: Zeal crashes downloading c++ docsets

### ISSUE THREAD

**Issue by illava** [zealdocs/zeal#757]
When the downloading process reached 99% and ready to install, it crashes. Works fine with other type of docsets(mysql doc I just installed).
![default](https://user-images.githubusercontent.com/29905553/29010192-223f336e-7b5c-11e7-906a-049c79144797.PNG)

**Comment by trollixx** [comment]
Please check your docset storage folder, and try removing any leftovers from the C++ docset.

**Comment by illava** [comment]
The problem solved by doing that, thank you.

**Comment by trollixx** [comment]
I think this is also a duplicate of #788.
