### ISSUE TITLE
Zooming option doesn't exists

### ISSUE THREAD

**Issue by AmrAdelKhalil** [zealdocs/zeal#759]
I'm reading ruby-on-rails documentation but the font is too small, So i tried to **zoom in** but i think this option is not offered in zeal.
OS: Linux-Ubuntu14.04

**Comment by trollixx** [comment]
Have you tried <kbd>Ctrl</kbd>+<kbd>Mouse Wheel</kbd>?

**Comment by AmrAdelKhalil** [comment]
It works, but i would prefer buttons instead of Ctrl+Mouse Wheel, I'm gonna close the issue now.

**Comment by trollixx** [comment]
Created #767 for keyboard shortcuts.
