### ISSUE TITLE
I changed zeal config to start minimized, now it wont start.

### ISSUE THREAD

**Issue by fullmooninu** [zealdocs/zeal#761]
All it shows is that little window to ask if you want to update, and doesnt matter if you select yes or no, it will close after.

I'm on ubuntu 16.04

Zeal 0.2.1

Is there a way to reset the config? I couldn't find a config file on my system and apt-get purge didn't help.

**Comment by fullmooninu** [comment]
if I start with this: zeal python:bomb

It then works

**Comment by fullmooninu** [comment]
I then removed the start minimized setting but it did not save it.

I started as sudo zeal python:bomb and removed the check for update and start minimized settings, which fortunately seems to be global as it is fixed now for my normal user.

Now longer an issue it's more of a bug report.

I still keep getting this error message:
Cannot determine index file for docset Perl

Would still like to know where zeal stores the config.

As a possible side note,my system is in french.

**Comment by fullmooninu** [comment]
Yep, now without sudo I can change configuration.

**Comment by trollixx** [comment]
> Zeal 0.2.1
That version is super old, please try 0.3.1.

**Comment by fullmooninu** [comment]
man, it's kinda useless using the ubuntu repos to install stuff -_-

**Comment by fullmooninu** [comment]
what can one do? switch to arch?

**Comment by trollixx** [comment]
@fullmooninu Good option. Or use [PPA](https://zealdocs.org/download.html#linux-ubuntu), unless you are on something older than 16.04.

*P.S. The PPA doesn't have v0.4.0 yet, which has been just released.*

**Comment by fullmooninu** [comment]
Ok thanks buddy.
