### ISSUE TITLE
Javascript documentation downloads points to wrong docset!

### ISSUE THREAD

**Issue by AnwarShah** [zealdocs/zeal#766]
As of this writing (1 September, 2017) the javascript documentation downloads the APIs/DOM documentation for javascript from this link https://developer.mozilla.org/en-US/docs/Web/API

The expected behaviour is to download this documentation instead https://developer.mozilla.org/en-US/docs/Web/JavaScript

**Comment by trollixx** [comment]
I've just downloaded the JavaScript docset, and I see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference as the index page.

**Comment by AnwarShah** [comment]
Strange! I've used the link from kapeli feeds repo (https://github.com/Kapeli/feeds/blob/master/JavaScript.xml) as I didn't have zeal installed and wanted to use the docs without zeal. Can you share the link from which zeal downloads the doc?

**Comment by trollixx** [comment]
Zeal uses exactly the same source of information. GitHub sends a notification on each update in the feeds repository, and then it's import into our docset list.

**Comment by AnwarShah** [comment]
@trollixx I think i've found the problem. I was testing the docset without zeal and the index page directly lands to the API/DOM documentation. In the zeal software, I get the correct page.

You may close this issue or change the landing page to the Javascript reference like in Zeal soft. Thank you.

**Comment by trollixx** [comment]
Glad you have figured it out.

Since we deliver docsets as-is from Dash. there's nothing to fix on our side.
