### ISSUE TITLE
Add keyboard shortcuts for zooming

### ISSUE THREAD

**Issue by trollixx** [zealdocs/zeal#767]
Zeal should support:
Zoom In - <kbd>Ctrl</kbd>+<kbd>+</kbd>, <kbd>Ctrl</kbd>+<kbd>=</kbd>
Zoom Out - <kbd>Ctrl</kbd>+<kbd>-</kbd>
Reset Zoom - <kbd>Ctrl</kbd>+<kbd>0</kbd>

**Comment by canab** [comment]
HTML content is over-scaled on big monitors. It could be at leas 1.5 times smaller. Zoom shortcuts or zoom option in settings would be helpful. Ctrl+MouseWheel works for zooming but zoom resets after relaunch.
