### ISSUE TITLE
NEED DOCS FOR NATIVESCRIPT

### ISSUE THREAD

**Issue by shrinathprabhu** [zealdocs/zeal#769]
I NEED DOCS FOR NATIVESCRIPT and REACT NATIVE

**Comment by bendem** [comment]
https://github.com/zealdocs/zeal#creating-your-own-docsets
https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/NativeScript
https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/React_Native
