### ISSUE TITLE
Zeal tray icon rename

### ISSUE THREAD

**Issue by MarekAG** [zealdocs/zeal#770]
Hi,
According to https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/709#issuecomment-327044263, can you rename Zeal tray icon to allow theming?

**Comment by SmartFinn** [comment]
@trollixx as far as I know, no. Just choose one from the most popular suffix of tray icon: `zeal-tray`, `zeal-panel`, `zeal-indicator`.

**Comment by varlesh** [comment]
Will be fine use another icon from system icon theme (if available):
```
QIcon::fromTheme("zeal-tray")
```
If not available `zeal-tray` > use original "zeal" as fallback icon. Sorry, i'm not programer and can not show example for this, but it's possible.
