### ISSUE TITLE
After 0.4.0 update, docs are removed

### ISSUE THREAD

**Issue by shadow198** [zealdocs/zeal#771]
update 4.0 after, docs is removed

**Comment by NoAnyLove** [comment]
Did you remove the docsets folder?

**Comment by trollixx** [comment]
Update should not affect your installed docsets. Please provide more information about your environment, and where docsets were stored.

**Comment by shadow198** [comment]
it's  ok  ,my  version docsets is stored in  C:\shadow\tool\zeal-portable-0.3.1-windows-x86\docsets,but version 4.0  docSet storage is  C:\Users\wangy\AppData\Local\Zeal\Zeal\docsets, It is recommended to record the previous version of docSet storage, replacing the 4.0 docSet storage
