### ISSUE TITLE
Ubuntu PPA missing v0.4.0

### ISSUE THREAD

**Issue by avalond** [zealdocs/zeal#772]
In ubuntu 16.04 can not update new version, my ubuntu zeal is 0.3.1,bit i click check for updates tell me new version is 0.4.0, i use apt-get update is not have new version, please check  ppa package is upload new version 

ppa repository i use this     sudo add-apt-repository ppa:zeal-developers/ppa

**Comment by tanepiper** [comment]
Can confirm I have the same issue

**Comment by cmalard** [comment]
Same here, the PPA is not updated, please update :-D
https://launchpad.net/~zeal-developers/+archive/ubuntu/ppa

**Comment by cmalard** [comment]
By the way, since I have the popup asking to update, Zeal immediately close itself so I can't use it anymore. @trollixx

**Comment by KeyHui** [comment]
I have the same issue @trollixx

**Comment by IslamWahid** [comment]
same here please fix it

**Comment by richarson** [comment]
As a workaround, edit Zeal's config file (~/.config/Zeal/Zeal.conf on Linux) and change:

```check_for_update=true```

with

```check_for_update=false```

So you can start Zeal again.

**Comment by trollixx** [comment]
I am not using Ubuntu anymore, so it might take some time to update the PPA. If anyone with DPKG experience wishes to volunteer, please let me know.

**Comment by Epskampie** [comment]
Hey @trollixx , I've managed to create some 0.4.0 builds using the zeal-packaging scripts. Please check them out: https://launchpad.net/~epskampie/+archive/ubuntu/zeal/

Ubuntu trusty didn't work, as you require qt5.5.1, which is not available for that version.

If you find these packages adequate, I'd be happy to become the ubuntu packager for Zeal. In that case, you can give my launchpad account the proper permissions on the official PPA: https://launchpad.net/~epskampie

**Comment by abforce** [comment]
@trollixx Please update the PPA. There's lots of people in need of the new Zeal. What programmers basically need: coffee, a PC and a fresh Zeal. Without Zeal we can't work `:)`.

**Comment by trollixx** [comment]
@Epskampie, I am travelling until Wednesday, will check it out once I am
back. Thank you!

**Comment by trollixx** [comment]
@Epskampie Hi, packages look good. I've added you to the Launchpad team, let me know if something is not working properly.

Please submit your "tweaks" to the zeal-packaging repo, so we could keep track of changes. Thanks!

P.S. I'll close this ticket once we have updated packages in the official PPA.

**Comment by Epskampie** [comment]
Cool, I pushed the packages for 0.4.0. Anybody with the [Official PPA](https://launchpad.net/~zeal-developers/+archive/ubuntu/ppa) should get it automatically through apt.

I made a [pull request](https://github.com/zealdocs/zeal-packaging/pull/29) for the changes to zeal-packaging.

**Comment by trollixx** [comment]
The official PPA has been updated to v0.4.0 thanks to @Epskampie.
