### ISSUE TITLE
Vcruntime140.dll missing

### ISSUE THREAD

**Issue by tinusstrydom** [zealdocs/zeal#773]
Have tried everything ,searched google etc. download Visual C++ Redistributable for Visual Studio 2015 and install etc. 
Everytime i open zeal it opens an error that say this file is missing ,maybe reinstalling will help.

Is there a way to get the old version ?

**Comment by DevCharly** [comment]
I have the same problem (Zeal 0.4 portable).

How did you solve it?

**Comment by tinusstrydom** [comment]
**Make sure** if you have 32 bit or 64 bit windows ,then go to
https://www.microsoft.com/en-za/download/details.aspx?id=48145
and download the right bit one for your system ,install .
Then reinstall or repair .
