### ISSUE TITLE
Limit search results to specific docs

### ISSUE THREAD

**Issue by Abu3safeer** [zealdocs/zeal#774]
Hello, 
I like the new feature Fuzzy search, but that caused to load much more results.
so Is there an options to search in only specific docs? 
example: I need to search for "alert" in javascript docs, but what happened is I see many results from other docs like PHP, MySQL and BootStrap.

So I think offering such a feature will be great.

**Comment by richarson** [comment]
It is already possible, see https://zealdocs.org/usage.html

I think for JS you have to use "javascript:" but I'm not sure.

**Comment by Abu3safeer** [comment]
I see, looks like i forgot about this feature, my bad.
Thank you @richarson .
