### ISSUE TITLE
zeal-0.4.0: Error creating ssl context(),  replace the libeay32.dll and ssleay32.dll can fix it.

### ISSUE THREAD

**Issue by zaazbb** [zealdocs/zeal#775]
when i use zeal 0.4.0, met a ssl error: Error creating ssl context().
i found that libeay32.dll and ssleay32.dll are exists under the bin dir.
i tried all the install packages (zip, 7z and msi), met the same error.

now i solve this problem by replace that two dlls.
(my new dlls download from https://indy.fulgan.com/SSL/openssl-1.0.2l-x64_86-win64.zip)

platform: win10 64bit.

**Comment by AStupidBear** [comment]
save issue

**Comment by Ferretaa** [comment]
I just want to confirm I had the same error, same platform Win 10 64bit Ver: 1607 
Hashes of dlls included in Zeal installer: 
libeay32.dll
  Md5: 4bdfca1ec851a73fc3821add2a4cd25c
  Sha1: b1e0a8fb75d495b69e07640600a44731412fdbb1
  Sha256: 254d44c1ac315acfeea1de1ea223688d10142847de09e8dc6489a187914a0541
  Sha512: b213d0d314ec8707f24b6d62b9550171e9b6cd577be0cee97792f915dedc6888e20b345378591d848fa3cb1dd82ef9a5e762a4ae40f0f2a2856c1c385e87179f

ssleay32.dll
  Md5: e30edd5e88332e8045d3883f79f17de1
  Sha1: d28c4d5fef76e9c07d151e019591d7e0d30c2189
  Sha256: 1d81060b5ae93cd60850947707488fce965862e2e48da145da775659a94c4cad
  Sha512: 37933642ea91c9c7995edf77b4b36cd5eaf0469e232c2dffcc98590987982de31e3f94af03c53eca996b600bb859cc5ab349145eb59d96ecec40f1c46ead5253

**Comment by trollixx** [comment]
This is strange. I just checked that on my PC (also Windows 10 x64), Zeal starts normally with DLLs provided. [ListDLLs](https://docs.microsoft.com/en-us/sysinternals/downloads/listdlls) also confirms that it uses exactly those, and not something else found on my computer.

Please check that all DLLs are only loaded from the installation directory, and `C:\Windows\...`.

**Comment by Ferretaa** [comment]
Ok using the DLLs supplied in the zeal installation - the error occurs and the neither ssleay32.dll and LIBEAY32.dll are loaded. After changing to the indy.fulgan DLLs zeal works and they are loaded from the installation directory and no other location. (The replacement DLLs are located in the exact same location as the installed DLLs just switching between them using  rename commands)

**Comment by trollixx** [comment]
I've managed to reproduce this, and the reason for failure is that OpenSSL libs we bundle are built with MSVC 2013, while the rest with MSVC 2015. So, some systems do not have `msvcr120.dll`, and OpenSSL fails to load.

**Comment by trollixx** [comment]
CI is now bundles OpenSSL built with MSVC 2015.

**Comment by trollixx** [comment]
v0.5.0 has been tagged. Binaries are coming shortly and will have this issue fixed.
