### ISSUE TITLE
Invisible text on high density monitors

### ISSUE THREAD

**Issue by jaan-hou** [zealdocs/zeal#776]
![image](https://user-images.githubusercontent.com/11814908/30240486-acc8ff0e-95a3-11e7-8c76-a73a029cd7aa.png)

**Comment by Joel-hou** [comment]
Windows 10 Pro, Version 1703

**Comment by davidzwb** [comment]
me too, use windows zeal 0.4.0, the c/c++ document is broken.

**Comment by Joel-hou** [comment]
It seems that CSS was not handled properly, you can copy from missing part of the document and the content exists

**Comment by trollixx** [comment]
@Kapeli could you please take a look?

**Comment by Kapeli** [comment]
The page displays fine in Dash, Chrome and Safari for macOS.

![screen shot 2017-09-12 at 10 01 52](https://user-images.githubusercontent.com/1445635/30312269-6990ca1e-97a1-11e7-88af-9a520e70bf45.png)

**Comment by 7sDream** [comment]
Similar situation

OS：Windows
Version：0.4.0
Docset：NodeJS

![image](https://user-images.githubusercontent.com/7822577/30780735-c4d359ee-a144-11e7-998b-edebc76f1703.png)

**Comment by Thesharing** [comment]
Same problem here, there are errors when displaying c++ document on windows 10, ver.1709.
Zeal version: 0.4.0

![snipaste_2017-10-22_14-37-54](https://user-images.githubusercontent.com/6576831/31858977-0fa16a08-b737-11e7-9df1-c55d4da49a7f.png)
![snipaste_2017-10-22_14-40-11](https://user-images.githubusercontent.com/6576831/31858978-0fd19bc4-b737-11e7-8468-f5b25ab8e7cf.png)

**Comment by trollixx** [comment]
Seems like a problem with font rendering in Qt WebKit. Perhaps related to #658.

**Comment by trollixx** [comment]
It seems that I cannot reproduce any of the problems here on my Windows 10 x64 laptop.

Does everyone here have a HiDPI display?

**Comment by Joel-hou** [comment]
Yes, my screen resolution is 2880x1620

**Comment by DaveyD** [comment]
I am having a similar issue, and yes I have a High DPI display 
I am using a Surface Studio with Windows 10 64bit
![Screenshot of issue in Javascript docs](https://github.com/DaveyD/Excel-Data/blob/master/screenshot_882.png)

**Comment by RJVB** [comment]
Qt/MSWin can use FreeType font rendering optionally, can't it? Cf. my annulen/webkit#703 which is on a normal-res screen and goes away when I switch to the FreeType fontengine.

**Comment by FlorianFranzen** [comment]
I have the same issue on NixOS 18.09 for the lastest C and C++ docset with Zeal 0.6.0 and a screen resolution of 2560x1440.

**Comment by frankli0324** [comment]
seems that this is fixed
tried with master CI build/Manual Build on Windows/MacOS running on a MBP
