### ISSUE TITLE
Problem with updating to 0.4.0 on Ubuntu 17.04

### ISSUE THREAD

**Issue by goofle** [zealdocs/zeal#778]
When I open zeal it says there's a new update available (0.4.0).
When I run `sudo apt install zeal` it says: `zeal is already the newest version (1:0.3.1-1)`.
How am I supposed to update to 0.4.0?

I was thinking maybe you could provide a `.deb` file?
I don't know if this is relevant but I'm using i3 wm.

**Comment by richarson** [comment]
Check #772

**Comment by richarson** [comment]
Specifically https://github.com/zealdocs/zeal/issues/772#issuecomment-328607558

**Comment by goofle** [comment]
@richarson Yeah, I saw it after I opened this ticket. I've added @Epskampie's ppa and updated from there. Everything seems to be all right.

**Comment by goofle** [comment]
@richarson by the way, I didn't have the issue of Zeal not working anymore after it showed me the update alert.

**Comment by trollixx** [comment]
Duplicate of #772.
