### ISSUE TITLE
Remove advertising on the start page

### ISSUE THREAD

**Issue by technician21** [zealdocs/zeal#779]
Thank you for your work
on this good doc's viewer, but new version has important issue - there is AD on the main page.
It's simple to remove, but how does this combine with your vision of free software movement?
Can you imagine man, xterm, midnight commander with ad?

Attract attention with an issue to this, I think, erroneous trend.

Thanks a lot.

base commit
https://github.com/zealdocs/zeal/commit/a90fef36dfa970427bf879b998897e95cafeeff1

**Comment by richarson** [comment]
Why do you think this clashes with the free software movement?

Remember: '“free” as in “free speech”, not as in “free beer”.'

Yeah, I don't like ads either, but this is so unobtrusive and easy to disable that it doesn't even annoy me :)

**Comment by trollixx** [comment]
I don't see any collision between open source philosophy and showing ads. Remember — open source doesn't mean free, although Zeal is free.

For those who cannot accept ads for "religious" reasons, there's an easy way to opt out in the settings.

If you're afraid of tracking, it's just Carbon ad, not Google's. You cannot really browse the internet with Zeal, and there's nothing to track with only one offline page. Again it's easy to disable the ad.

**Comment by technician21** [comment]
trollixx, richarson, have accepted your point.
Expect cost and ads on the store-window/website of the "free speech" software.
I feel free software strive to be a completed tool for work or fun.
From that side, suppose each software element have functional(not a garbage) goal like a book (not a glossy magazine).

Have an example of another approach of the development support(of course it's a big project) - Vim,
main page have instruction for support project, anyway this conscious action.
Another examples are voting for the features, donation on the patreon.com

Thanks again, can be closed.

**Comment by trollixx** [comment]
I don't like idea of asking for donations, because that would create a false expectation. I don't have much time to work on Zeal, so no guarantees about when something gets fixed or implemented. The ad just pays for some tiny running costs like domain name, code signing certificate and perhaps a cup of coffee once a month :)

**Comment by izahn** [comment]
FWIW, I don't find it so obvious how to remove the ads, so I've removed Zeal instead. I'm sure I'm not the only one.

**Comment by Porkepix** [comment]
> If you're afraid of tracking, it's just Carbon ad, not Google's. You cannot really browse the internet with Zeal, and there's nothing to track with only one offline page. Again it's easy to disable the ad.

However, you'll still at least get the first-run tracking. Which means user is already pinpointed as a user of your software. Maybe inform the user and offer him to disable it *before* first display would be nicer :)

It would be less of a problem if it were preloaded offline ads.

**Comment by trollixx** [comment]
@Porkepix Your point is valid, but one gets pinpointed anyway. Zeal checks for updates, docsets get downloaded, many docsets still reference external resources, etc. Even though there's currently no data collection in our own server side applications, it doesn't mean that service providers don't do that anyway. There's no privacy on the Internet :)

Speaking specifically about Carbon, in the long run I am considering replacing it with something less controversial, or even an in-house system.

For now I'll try to make it a bit more clear how to disable the ad.

**Comment by Porkepix** [comment]
Well… it depends from who are you trying to hide. A browser with the correct extensions hide yourself from advertisers, data brockers and all those trying to profile you, that's enough for me.

>There's no privacy on the Internet :)
This is wrong. Tor, or the Tor Browser have been designed specifically for this.

By the way, now that I think about it, I'm not a lawyer, but not asking the user *before* getting any of informations/ads might be against GDPR for european users.

**Comment by trollixx** [comment]
GDPR is an interesting subject. Although since we do not collect any data at all, it does not apply.

Also from [European Commission website](https://ec.europa.eu/info/law/law-topic/data-protection/reform/rules-business-and-organisations/application-regulation/who-does-data-protection-law-apply_en):

> **When the regulation does not apply**
> Your company is service provider based outside the EU. It provides services to customers outside the EU.  Its clients can use its services when they travel to other countries, including within the EU. Provided your company  doesn't specifically target its services at individuals in the EU, it is not subject to the rules of the GDPR.

At the same time my guess is that Carbon/BuySellAds should comply with the GDPR, but I am not sure what information they collect. At least I can only see total number of views and clicks, but nothing else.

**Comment by Porkepix** [comment]
>At the same time my guess is that Carbon/BuySellAds should comply with the GDPR, but I am not sure what information they collect. At least I can only see total number of views and clicks, but nothing else.
Yes, but the ad itself can't ask for user's permission nor store any authorization, so that's the software's work, as far as I understand it.

**Comment by trollixx** [comment]
FWIW, I am going to remove built-in ad in the future (most likely in 0.7.x). There are a few other less controversial monetization streams I am interested in pursuing.

**Comment by trollixx** [comment]
Repurposing the ticket to track removal of the bundled ads.
