### ISSUE TITLE
Visual Studio (not VS Code) integration

### ISSUE THREAD

**Issue by fcharron** [zealdocs/zeal#780]
Hi,

I'm surprised I couldn't find any information on the subject of Visual Studio integration of Zeal. Specifically, I would be interested in the possibility to assign a keyboard shortcut to a "search in Zeal" feature (very similar to what Velocity offers in their "Search In Velocity" extension).

Thanks

**Comment by trollixx** [comment]
We do not maintain any of the existing integration plugins. So, feel free to create one of your own for VS.

As a work around, the plugin for Velocity should work with Zeal too.

**Comment by fcharron** [comment]
Thanks a lot for the info! I will try the Velocity plugin. If it does not do what I want, I will consider creating an extension in my spare time.
