### ISSUE TITLE
Unreadable fonts on 0.4

### ISSUE THREAD

**Issue by empijei** [zealdocs/zeal#786]
I was a happy zeal user until 0.4 came out. Sadly the new release introduced a bug regarding font size:

![image](https://user-images.githubusercontent.com/1256049/31167211-940e1e70-a8f1-11e7-8b19-a3d382bf4ae5.png)

As you can see here, fonts for the menus and docset names are so small they are almost unreadable. (I kept the topbar in the screenshot for scale as my topbar has a font size of 10pt)

It started as soon as I upgraded to 0.4.

I am on Arch linux, with Awesome Window Manager on X.org.
My current version of zeal comes from arch repos and is community/zeal 1:0.4.0-1. I tried to recompile from master and got the same issue.

Please let me know if I can help with more info,logs,confs or anything else or if I can perform some additional operations/checks to help you with this. 

I like zeal and I would like to have the new version working :smiley:

**Comment by trollixx** [comment]
Do you have a HiDPI display? How did you setup Qt style? See [Arch wiki](https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications) for some details.

**Comment by trollixx** [comment]
Although, most likely it has nothing to do with the style, but rather Qt platform plugin can't retrieve your display's DPI for some reason.

**Comment by trollixx** [comment]
Check the output of `xrandr --dpi dpi`, and [this page](https://wiki.archlinux.org/index.php/HiDPI) in the case of a HiDPI display.

**Comment by empijei** [comment]
Hi @trollixx thanks for the reply.
I have a normal 1920x1080 HD monitor on my laptop, a Thinkpad Carbon X1

Here is the output of xrandr anyway:
```
$ xrandr --dpi dpi
xrandr: Cannot find output dpi
```

In this is the dpi command called on my main display:
```
$xrandr --dpi eDP1
```
xrandr exits with `0 status` but prints nothing.

You helped **solving the problem** anyways because the command `qtconfig-qt4` that I found on the wiki allowed me to tune font size and have a readable zeal UI.

Thanks for your help.

**Comment by trollixx** [comment]
I think this is a duplicate of #869.
