### ISSUE TITLE
Update PPA blocked

### ISSUE THREAD

**Issue by chrispincharles** [zealdocs/zeal#787]
It appears your update ppa for Ubuntu Artful (17.10 beta 2) using gnome shell is blocked(untrusted)

**Comment by trollixx** [comment]
How did you add the PPA to your system?

**Comment by trollixx** [comment]
Closing due to no response.

**Comment by j9ac9k** [comment]
Same issue here; on 17.10; `sudo apt-get update` results in the following error:

```
E: The repository 'http://ppa.launchpad.net/zeal-developers/ppa/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
ogi@xps-linux:~$
```

Installed the repository via the command `sudo add-apt-repository ppa:zeal-developers/ppa` as per the instructions.

**Comment by trollixx** [comment]
Ah, Artful. We don't have packages for it yet.

**Comment by trollixx** [comment]
@Epskampie could you add a package for 17.10 to the PPA?

**Comment by Epskampie** [comment]
@j9ac9k Artful Aardvark package added! 
@trollixx : see https://github.com/zealdocs/zeal-packaging/pull/31 as well

**Comment by trollixx** [comment]
@Epskampie Thank you! I've merged the PR.
