### ISSUE TITLE
Crash when there is a leftover docset directory

### ISSUE THREAD

**Issue by Hibou57** [zealdocs/zeal#788]
I updated all installed docsets. The next time I restarted Zeal it was from command line, which allowed me to notice this message:

    Could not load docset from '/home/<user>/.local/share/Zeal/Zeal/docsets/Python_3.docset'. Reinstall the docset.

But when I did so, I get this:

    [1]    10547 segmentation fault (core dumped)  zeal

Using 0.4.0 on Ubuntu Xenial (16.04) 32 bits.

**Comment by Hibou57** [comment]
I checked after removal of the old `Python_3.docset` directory, I can reinstall it without any crash, so that’s something which was in this directory which made Zeal crash. I made a back-up of that broken directory before removing it : see the attached archive below.

[Python_3.docset.tar.gz](https://github.com/zealdocs/zeal/files/1356998/Python_3.docset.tar.gz)

**Comment by trollixx** [comment]
I can reproduce the crash, thanks for reporting, and the corrupted directory sample!

**Comment by duytrung** [comment]
I dont know why updating this docset causes error:

![image](https://user-images.githubusercontent.com/2046672/31229073-10cff38a-aa27-11e7-8642-429ad1bedab9.png)

**Comment by trollixx** [comment]
@duytrung Your problem is unrelated to this ticket, see #775.

**Comment by bytesnz** [comment]
Another corrupted docset if you need it. Have been trying to download docsets over a really bad internet connection, which has lead to a lot of failed downloads and possibly the corrupt docsets (was downloading with an older version of Zeal [0.3,1 from the ubuntu repositories]), which has been a pain with a docset as big as the Javascript one. Might try manually downloading them from the server (https://github.com/Kapeli/feeds has the list of feeds for anyone looking for it) and then putting it in the correct place.

[JavaScript.docset_broken.zip](https://github.com/zealdocs/zeal/files/1386395/JavaScript.docset_broken.zip)

**Comment by trollixx** [comment]
@bytesnz thanks! I've narrowed it down, the fix is coming.
