### ISSUE TITLE
zeal-0.4.0: Update errors

### ISSUE THREAD

**Issue by stychos** [zealdocs/zeal#792]
On application launch Zeal says: "Zeal 0.4.0 is available. Open download page?"
If I press "Yes" it opens https://zealdocs.org/download.html and quits. This page haven't much information about how to get latest binaries for Debian. Also, there is no latest version in the Debian repositories.
If I press "No", Zeal quits.
In result I can't use Zeal at all.

OS: Debian sid.

**Comment by trollixx** [comment]
Duplicate of #637.

**Comment by trollixx** [comment]
Zeal just checks against the latest release, not specific to any distribution. It shouldn't quit after the message box is closed, it's a bug. See the ticket above for a workaround, and subscribe for updates.
