### ISSUE TITLE
Zeal stoped working when installing laravel docset

### ISSUE THREAD

**Issue by SamiruR** [zealdocs/zeal#799]
Im using Zeal 0.4.0 portable version on windows 7 64bit Ent. PC,
I have already installed Angular, bootstrap and Emmet docset in zeal,
but when i try to install laravel , program stopped working at thee 100% install completion.

**Comment by trollixx** [comment]
Until #788 is fixed you need to delete `Lavarel.docset` directory from the docset storage path, and then re-download the docset.

**Comment by trollixx** [comment]
Duplicate of #788.
