### ISSUE TITLE
Zeal not working on my Ubuntu 13.04

### ISSUE THREAD

**Issue by Himanshu-Mishr** [zealdocs/zeal#80]
Hi, Zeal was working awesomely  in elementary Os, when I switched to Ubuntu 13.04 , I installed it with given procedure on http://zealdocs.org/. 
It is showing some error. Here is the screenshot. ![screenshot from 2013-12-25 14 24 01](https://f.cloud.github.com/assets/1938285/1808217/4327d850-6d42-11e3-9535-c645a4dfdea5.png)
I know Zeal uses Super+Alt+Space bar. I think there is clash of some similar keyboard shortcuts. So I have changed keyboard shortcut for Super+Alt+Space bar from system setting (so that Zeal can use it). But then also it is not working.
I googled for issue but could not find solution for it.  Help me pls.

**Comment by trollixx** [comment]
The default global hot key has been changed to `Meta+Z`. Also all related code has been updated. This issue should not occur anymore.
