### ISSUE TITLE
MSVCP140.dll missing

### ISSUE THREAD

**Issue by luisaureliocasoni** [zealdocs/zeal#800]
Hi,

I have installed the Zeal 0.4 on  Windows 7 64-bits. In its msi and portable versions. But when I execute the program, the Windows abort the startup claiming that the MSVCP140.dll is not found. What program I must to install to fix it?

![image](https://user-images.githubusercontent.com/12179059/31640605-cf12a036-b2b5-11e7-84a0-c274a37342c3.png)

Regards,
Luís

_Sorry for my poor english._

**Comment by trollixx** [comment]
You need [Microsoft Visual C++ 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=48145).

**Comment by luisaureliocasoni** [comment]
Hi,

Sorry for my delay.

I installed the MS Visual C++ Redistributable. The program has started, but shows the following dialogues:

![image](https://user-images.githubusercontent.com/12179059/31915288-4b10b204-b824-11e7-882e-01ef70b6226a.png)

When I try to install a docset, the program aborts the download, showing the current error:

![image](https://user-images.githubusercontent.com/12179059/31915311-5f85a078-b824-11e7-8d11-4e5c9af888af.png)

What is happening?

Regards,

Luís

**Comment by trollixx** [comment]
@luisaureliocasoni That is caused by the bundled OpenSSL DLLs, see #775.
