### ISSUE TITLE
GNOME Shell search provider

### ISSUE THREAD

**Issue by intelfx** [zealdocs/zeal#804]
It would be very nice to have Zeal integrated into the [GNOME Shell search system](https://developer.gnome.org/SearchProvider/) — something like a search provider that talks to a Zeal instance.

**Comment by trollixx** [comment]
Interesting suggestion, thanks! I've been thinking for a while now about some kind of API Zeal could expose (e.g. #400), but it's not a near term project.

**Comment by ManuelSchneid3r** [comment]
As the author of the keyboardlauncher albert, I am looking forward to this feature. This would be amazing.

**Comment by ManuelSchneid3r** [comment]
I ask you to close this issue.

1. The suggestion is way to specific. (gnome shell only)
2. I'd rather not urge zeal devs to work for other projects. (given an API, gnome should implement this)

But actually #400 should get higher priority imo.

**Comment by trollixx** [comment]
Good idea, closing in favor of #400.
