### ISSUE TITLE
Crashes when downloading the Go docset

### ISSUE THREAD

**Issue by slotheroo** [zealdocs/zeal#805]
In the current version of Zeal (0.4.0) it crashes when I attempt to download the Go docset. I've been able to download other docsets without issue.

**Comment by trollixx** [comment]
Check your docset storage for `Go.docset`, and remove it if it's there.

**Comment by slotheroo** [comment]
Thanks, that was the issue. There was an old docset there that hadn't completed deleted. Deleting it manually allowed me to successfully download the new docset.

**Comment by trollixx** [comment]
Duplicate of #788.
