### ISSUE TITLE
Full dark theme

### ISSUE THREAD

**Issue by eromoe** [zealdocs/zeal#811]
Previous issue https://github.com/zealdocs/zeal/issues/466 add `Dark Mode` which only make main window dark. But that looks incongruous with other parts, especially left sidebar looks too shinning in dark mode.

Hope can embed a full dark theme .

**Comment by oblitum** [comment]
Does this make sense? I think it would require a lot of UI rewriting to achieve, maybe it's just better left as it is currently, at user option to match widgets with the system or specific style:

![](https://i.imgur.com/uIeZM0Q.png)

**Comment by trollixx** [comment]
@oblitum I guess this is more of an issue for Windows users, who do not have all the flexibility Linux DEs provide.

Styling Qt apps works on Windows as well, but most people are just not aware of it. So, I think the first step would be providing some docs on how to change Zeal's appearance with third party themes for Qt.

**Comment by trollixx** [comment]
I haven't tried (QDarkStyleSheet)[https://github.com/ColinDuquesnoy/QDarkStyleSheet] yet, but it looks promising.

**Comment by oblitum** [comment]
Agreed!

**Comment by technodrome** [comment]
Hello guys, is there a chance this is going to be a real thing? The app itself is extremely useful, just the interface is extremely bright. I know you have your own professional and private lives, just asking.

**Comment by nzig** [comment]
For those still looking for a solution:
Installing [Kvantum](https://github.com/tsujan/Kvantum/tree/master/Kvantum) worked for me. Note that after installing you need to followe the [instructions](https://github.com/tsujan/Kvantum/tree/master/Kvantum) on setting it as the default.

**Comment by ezxpro** [comment]
> For those still looking for a solution:
> Installing [Kvantum](https://github.com/tsujan/Kvantum/tree/master/Kvantum) worked for me. Note that after installing you need to followe the [instructions](https://github.com/tsujan/Kvantum/tree/master/Kvantum) on setting it as the default.

For those on Windows, no solution, apparently.

**Comment by oblitum** [comment]
> I don't understand why make a darkmode that only applies to a certain part of the window, but anyways.

@ezxpro because people with decent OS can then couple it to their dark desktop environment.

Zeal can only do its best to provide flexibility where it can (Qt styling), not where it cannot (Window decorations), that's generally responsibility of the OS.

**Comment by K8-and-a-half-1000** [comment]
> @ezxpro because people with decent OS can then couple it to their dark desktop environment.

If that's the case, Zeal should not support Windows at all, so a different project can fill in the gap.
Only half-supporting a platform ensures no-one will use it on that platform, an no alternatives get build over time.

**Comment by trollixx** [comment]
[Looks like](https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5) with Qt 6.5 we can get a dark mode support with Fusion theme. It doesn't look native but not too bad overall. To be honest, Qt never got Windows Vista style to look native. I think falling back to the Fusion theme is a good compromise.

**Comment by trollixx** [comment]
Sneak peek below. Also includes native Chromium dark mode.

![image](https://user-images.githubusercontent.com/714940/232266488-f4e16a58-308f-46d5-bf2a-7f6d02261b04.png)

The Fusion style looks quite good in the light mode too:

![image](https://user-images.githubusercontent.com/714940/232266567-714d0a49-d218-4bf9-a9a5-4f26b1314676.png)

I am kind of inclined to make Fusion the default style on Windows.

**Comment by ruslaniv** [comment]
> Sneak peek below. Also includes native Chromium dark mode.

Ok, great, but how can I use it on Windows?!
I'm still getting this horrendous glaring white sidebar on the left and on the top even when setting the mode to Dark in version   0.6.1

<img width="476" alt="image" src="https://github.com/zealdocs/zeal/assets/7631314/a9ef996a-a38b-4e7c-a429-d453213c183e">

**Comment by trollixx** [comment]
@ruslaniv this change is available in the `main` branch. You can try [CI builds](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml) until new version is released. Binary artifacts are attached to each build.
