### ISSUE TITLE
Host api.zealdocs.org not found

### ISSUE THREAD

**Issue by xspkwy** [zealdocs/zeal#812]
Version 0.3.1
When I open Tools/Docsets, it goes wrong like this:
![selection_001](https://user-images.githubusercontent.com/20251362/32316133-e051415e-bfe9-11e7-8127-5dbc98ddb38b.jpg)
So what's wrong here? 
Thanks

**Comment by trollixx** [comment]
Check your network, as `api.zealdocs.org` seems to work just fine.

**Comment by xspkwy** [comment]
When I search `api.zealdocs.org`, it just relinked to `https://zealdocs.org/`
and I ping `api.zealdocs.org`, it just stuck.
![selection_001](https://user-images.githubusercontent.com/20251362/32317010-5344e474-bfed-11e7-9ef8-c3cf6daa44d1.png)

**Comment by trollixx** [comment]
You can't ping that host. But if you get redirected in browser, that means you can actually reach it.

Does you Internet connection require a proxy?

**Comment by xspkwy** [comment]
Do you mean this?
![image](https://user-images.githubusercontent.com/20251362/32371601-701836c0-c0cc-11e7-8f94-f8a26d6fd2a1.png)
Besides, I tried with or without VPN, but both ways failed.

**Comment by trollixx** [comment]
Correct. Now check proxy configuration in Zeal (Edit -> Preferences -> Network).

**Comment by xspkwy** [comment]
Oh, I tried this way:
![image](https://user-images.githubusercontent.com/20251362/32371975-edd20130-c0cd-11e7-8184-34d466996b14.png)
and it turns out that 
![image](https://user-images.githubusercontent.com/20251362/32371989-fba41ec4-c0cd-11e7-89e4-d843d9dcc0b7.png)
When I switch to the 'System proxy configuration', the 'Host not found' problem again.

**Comment by trollixx** [comment]
What kind of proxy software are you using? Does it require authentication?

**Comment by xspkwy** [comment]
On, yeah, I used shadowsocks, and it had just broken down. 
Maybe that's the problem, I'll try to fix it first.
Thank you very much!

**Comment by trollixx** [comment]
Please let me know if this is actually a problem with Zeal, and I'll reopen.

**Comment by xspkwy** [comment]
OK!
Actually, I think that might be a problem for vpn users, especially for.Chinese users. But if I configer the proxy correct, everything goes well.
