### ISSUE TITLE
docset loading problem

### ISSUE THREAD

**Issue by Ghostboy-287** [zealdocs/zeal#820]
Hello, 
i'm using ubuntu 16.04 xenial and i installed zeal version 0.4.0 from ppa:zeal-developers/ppa

i downloaded some docsets like python, ruby, html ... and it works fine except with css 
i downloaded the css docset but zeal don't load it

ps: the css docset folder is present in .local/share/Zeal/Zeal/docsets near the ruby, html, python ones

**Comment by trollixx** [comment]
Try removing `CSS.docset` folder, and redownloading the docset.

**Comment by Ghostboy-287** [comment]
files may have been corrupted on the first download.
i downloaded again css docset without deleting it manually and it still not working.
but now after deleting those files manually like you said it works.

thank you for your instructions, and thank you for developing this useful project that i really i appreciate
