### ISSUE TITLE
Feature request: Resume & Retry. jqGrid docset

### ISSUE THREAD

**Issue by efrenba** [zealdocs/zeal#821]
Hi Zeal,

I need these feature be included:

1. Resume download and retry options
2. jqGrid docset: http://www.guriddo.net/documentation/guriddo/javascript/

Great software for offline developers
Thanx

**Comment by efrenba** [comment]
I've built the jqGrid's docset, what can I do to share it?

**Comment by trollixx** [comment]
Resuming downloads has been requested in #430.

You can contribute your docsets to [Dash User Contributed Docsets](https://github.com/Kapeli/Dash-User-Contributions#readme).

Please use search before creating new tickets, and avoid putting unrelated requests in one. Thanks!
