### ISSUE TITLE
Feature Request: Shortcuts

### ISSUE THREAD

**Issue by teslaNova** [zealdocs/zeal#824]
I really like this project. What's missing are shortcuts. 

I often switch through my editor and zeal to look something up (duh!) and it'd be neat to keep the mouse untouched if I want to search for something in the current tab by using a shortcut to focus the search textbox.

**Comment by trollixx** [comment]
`Ctrl+K`?

**Comment by trollixx** [comment]
I guess problem is the lack of documentation. Duplicate of #72.
