### ISSUE TITLE
can't find certain docs in JavaScript docset

### ISSUE THREAD

**Issue by GoodGuyNick** [zealdocs/zeal#826]
Zeal version: 0.4.0
Docset: JavaScript

The page for **Template literals** exist but you can't find it.
![you can't find it](http://i.imgur.com/dYFca7m.png)
![exist](http://i.imgur.com/mMMcpcH.png)

The same goes for **Object initializer**.

I think there are more docs that you can't find. I've discovered this when I was doing comparison with [devdocs.io](https://devdocs.io)

**Comment by Kapeli** [comment]
I'll try to fix this in the next docset update.

**Comment by trollixx** [comment]
Closing as there's nothing to do from my side.

**Comment by Kapeli** [comment]
I've fixed this in the latest JavaScript docset update. Sorry I forgot to update the issue.
