### ISSUE TITLE
is it possible to get the original styling for MySQL and PHP docs?

### ISSUE THREAD

**Issue by Abu3safeer** [zealdocs/zeal#827]
Hello Zeal team,
First I want to thank you for this amazing tool, it really saves a lot of time especially with fuzzy search.

but I noticed some styling issues for PHP and MySQL.
for PHP all text are italic, like this:
![image](https://user-images.githubusercontent.com/12091003/33237717-e3b53b66-d28b-11e7-9972-424232202ad8.png)
as you can see inside zeal everything is italic, I didn't mind it at the beginning, but by time it got me annoyed, reading is not comfortable, I ask for this because it is only italic inside Zeal, not in the browser (thought both of them are the same file!)

now about MySQL, 
![image](https://user-images.githubusercontent.com/12091003/33237734-c7bcf3c6-d28c-11e7-8403-c011bc8bdded.png)

Is it possible to have MySQL codes colored?
because it is not styled inside Zeal, some codes are too long that make reading them a bit difficult.

**Comment by trollixx** [comment]
The first one is a bug in Qt WebKit (#658), no idea about MySQL. All docsets come from Dash with no modifications.

**Comment by Abu3safeer** [comment]
so it is out of your control?

**Comment by trollixx** [comment]
@Abu3safeer yes

**Comment by trollixx** [comment]
The MySQL docset doesn't apply source highlighting. Checked outside of Zeal as well.

@Kapeli mind taking a look?

**Comment by Kapeli** [comment]
The [downloadable MySQL docs](http://downloads.mysql.com/docs/refman-5.7-en.html-chapter.zip) don't have syntax highlighting. I'll try to add it myself, but I've seen little demand for it (first user to ask for it), so it's not really a priority. Sorry for the inconvenience!

**Comment by trollixx** [comment]
I didn't know where the docs are coming from. Then it works as expected.

**Comment by trollixx** [comment]
Closing per above.
