### ISSUE TITLE
Zeal is Interesting. A Search Pop up Like Launchy would do good

### ISSUE THREAD

**Issue by sivaswami** [zealdocs/zeal#829]
I like Zeal and also tried fuzzy seatch. Its interesting.
The Search box is too little at top left corner. It would be doing better for a big search popup.
Something like what Sublime or Atom editors provide.
I feel A Pop up Like Launchy at OS level would be much helpful to directly search from OS.
Any plans for future ?

**Comment by trollixx** [comment]
A new in-page search toolbar is almost ready. It's similar to what Firefox has.

Regarding exporting search API to other applications, there's no current plans, but it's something that I'd like to address eventually. See #804 for a similar request.
