### ISSUE TITLE
Crash when using Ansible docs

### ISSUE THREAD

**Issue by opennomad** [zealdocs/zeal#830]
Tried with both 0.3.1 from ubuntu repos and 0.4.0-1ppa1~artful1 from ppa.

When attempting to open one of the ansible docs either via search or browse, zeal crashes. Tests with other docsets seems to not have that issue.

**Comment by trollixx** [comment]
Remove `Ansible.docset` from the docset storage directory.

**Comment by mcg** [comment]
Same issue here. Tried removing and re-downloading the Ansible docset. Same thing.

**Comment by Svolentin** [comment]
same

**Comment by trollixx** [comment]
Seems like the same problem as #464. What Qt WebKit version is in use?

**Comment by mcg** [comment]
@trollixx Mostly stock Ubuntu 17.10,  libqt5webkit5 (5.9.1+dfsg-5ubuntu1). Zeal(0.4.0) from PPA.

**Comment by Svolentin** [comment]
``` 5.9.1+dfsg-5```

**Comment by trollixx** [comment]
Qt WebKit 5.212 should have this bug fixed, but I am not sure where to get it for Ubuntu, except for [s390x](https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/3058/+build/13804260). Arch Linux ships it by default nowadays.

**Comment by trollixx** [comment]
I cannot reproduce this bug in my Ubuntu 16.04 VM with Zeal from the PPA.

**Comment by trollixx** [comment]
There's nothing to do about this from Zeal side. On the bright side Ubuntu 18.04 will ship with Qt WebKit 5.212.
