### ISSUE TITLE
Can't show any result in windows 10 (zeal portable 0.4.0)

### ISSUE THREAD

**Issue by AlphaGoMK** [zealdocs/zeal#831]
Zeal can't display any result :(
Could you plz help me 
![img](https://wx1.sinaimg.cn/mw690/006jxtqoly1fly35vgnmuj30p20hrdge.jpg)

**Comment by rodenmonte** [comment]
Looks like you haven't added any languages yet. 

Click on the Tools Menu, then select Docsets. A new window will open up containing two tabs, Installed and Available. Installed should be empty, but clicking on the Available tab will bring up a page of choices for languages. Click on a language and select "Download", which downloads and installs that language. Repeat for as many languages as you would like.

Then you can search for languages in that search bar. You can even type the language name, and then press tab to limit your results to 1 language.

Source: Fellow Windows 10 Zeal user.

**Comment by AlphaGoMK** [comment]
thanks for your comprehensive instruction.
zeal is now working well on my win10.
Thanks again.
