### ISSUE TITLE
Zeal feed seems different from Dash feed

### ISSUE THREAD

**Issue by dodumosu** [zealdocs/zeal#834]
I apologize in advance if this has already been addressed, but I have noticed this for a while, and thought I'd ask.
I have Dash installed and use it fairly regularly. I also sometimes work on a Windows machine with Zeal 0.4.0 installed. I have noticed a difference between the available docsets on both: Dash provides both the AngularJS (1.X) and the Angular (2+) docsets. Only the former is available on Zeal. I haven't checked if there are other discrepancies, but even refreshing doesn't show the Angular docset.

**Comment by trollixx** [comment]
I forgot that I need to update Angular related feeds in our index. Dash has changed its Angular related feeds according to @Kapeli:

> Those docsets are actually for "Angular for JavaScript". The AngularTS docsets are in the AngularTS.xml feed.
> 
> Please note though that I've deprecated all the Angular*.xml feeds and now only update Angular.xml. The Angular.xml feed contains docsets for Angular versions from 1.x to 4.x.
> 
> I know AngularJS 1.x isn't really "Angular", but I can't clutter the interface with "Angular", "AngularTS", "AngularJS" and so on. I'd rather just have one "Angular" option.
> 
> // @trollixx You should make Zeal use the Angular.xml feed if it doesn't already.

I'll update the index shortly.

**Comment by Kapeli** [comment]
Due to feedback from users following that comment I've since brought back the AngularJS feed. So Zeal should use Angular.xml for Angular 2.x+ and AngularJS.xml for 1.x.

**Comment by trollixx** [comment]
Angular docset has been added.
