### ISSUE TITLE
When updating latest spring framework's docset, error happens

### ISSUE THREAD

**Issue by yosaku01** [zealdocs/zeal#835]
The environment is Windows 10 64bit.
When I updating the latest spring framework's docset,  the progress reaches 99 percent, and one error message dialog shows as below graph
![image](https://user-images.githubusercontent.com/1314082/33538146-a08ebd92-d8fa-11e7-9651-1b22fd43f749.png)
The zeal version is 0.4.0

**Comment by yosaku01** [comment]
In windows 7 64bit environment, the same dialog shows.

**Comment by yosaku01** [comment]
In CentOS 7.4, this problem does not happen.

**Comment by trollixx** [comment]
Remove docset directory from your docset storage path. Duplicate of #788.

**Comment by yosaku01** [comment]
Thank you, I will try it.
