### ISSUE TITLE
"Network access is disabled" is shown if app starts before successful internet connection

### ISSUE THREAD

**Issue by Yanpas** [zealdocs/zeal#839]
I have Zeal in autostart on KDE Linux. Also Network Manager starts a bit slowly.

When I open Docsets window I see dialog box "Network access is disabled: Retry and Cancel". Retry doesn't work as well.

**Comment by trollixx** [comment]
Is it actually a bug? Are you sure that the Internet connection is up by the time you open docset dialog?

**Comment by Yanpas** [comment]
Yes. I'm writing this comment and it is still "disabled" in Zeal

**Comment by trollixx** [comment]
Might be a problem with Qt's Bearer API, as it doesn't detect network presence. Does the problem go away if you restart Zeal?

**Comment by trollixx** [comment]
Or first close and open the Docset dialog.

**Comment by Yanpas** [comment]
It goes away only after zeal restart

**Comment by trollixx** [comment]
Cannot reproduce with my Ubuntu 16.04 VM, which also using NetworkManager. For me Zeal always detects network status properly.

I tried to connect/disconnect network on VM level, then with NetworkManager, as well as stopping the service, and then bringing it back on.

Can you reproduce this problem any other way?

**Comment by Yanpas** [comment]
I reproduce it only at autostart. It seems to occur with rare circumstances with uncertain reasons. May be closed

**Comment by trollixx** [comment]
Closing, please reopen if you find a reliable way to reproduce the bug.

**Comment by trollixx** [comment]
https://codereview.qt-project.org/#/c/212187/ could be the fix for this problem.
