### ISSUE TITLE
Docset treeview sort key is invalid

### ISSUE THREAD

**Issue by Yanpas** [zealdocs/zeal#840]
For some reason jQuery is in the bottom of docsets
![image](https://user-images.githubusercontent.com/7345761/33738771-7ab533ea-dbab-11e7-993e-76191a6b4769.png)

**Comment by trollixx** [comment]
Case-sensitive search :)

**Comment by trollixx** [comment]
Since it's just a `<QMap<QString, ...>` at the moment, there's no easy way to change the order. Should be easier to address when I get to the new docset manager backend.

**Comment by trollixx** [comment]
Appears to be a duplicate of #244.
