### ISSUE TITLE
Zeal stopped working

### ISSUE THREAD

**Issue by vastrolorde** [zealdocs/zeal#847]
Zeal stopped working after downloading Flask Docset.

**Comment by trollixx** [comment]
Go to your docset storage, archive `Flask.docset`, and then delete the directory. Please attach the archive here.

**Comment by vastrolorde** [comment]
[Flask.docset.zip](https://github.com/zealdocs/zeal/files/1567113/Flask.docset.zip)

**Comment by vastrolorde** [comment]
it works well, when i deleted the flask docset. thanks a lot

**Comment by trollixx** [comment]
Thank you for providing the archive! I'll check why it was crashing in the first place.

**Comment by trollixx** [comment]
Zeal v0.5.0 correctly detects the problem with the provided docset, and doesn't crash.

**Comment by trollixx** [comment]
I think it was a variation of #788.
