### ISSUE TITLE
Zeal already running, terminating (ubuntu 12.04)

### ISSUE THREAD

**Issue by riccivr** [zealdocs/zeal#85]
I have a problem with Zeal in Ubuntu 12.04 LTS in which zeal is not closing correctly, i have to manually end the zeal process through GNOME System Monitor, and i don't know what the "Zeal already running, terminating" means because it's not working (i assume it supose to end up the process)

**Comment by trollixx** [comment]
Now there's now way to hide Zeal if tray icon is not enabled. This issue should be considered fixed.
