### ISSUE TITLE
Tag 'LLVM' is not autocompleted

### ISSUE THREAD

**Issue by nishanthkarthik** [zealdocs/zeal#850]
Zeal doesn't display autocomplete suggestions when I type `LLVM:`.

`<?xml version='1.0' encoding='UTF-8'?>
<plist version="1.0">
    <dict>
        <key>CFBundleIdentifier</key>
        <string>LLVM</string>
        <key>CFBundleName</key>
        <string>LLVM</string>
        <key>DocSetPlatformFamily</key>
        <string>LLVM</string>
        <key>isDashDocset</key>
        <true />
        <key>isJavaScriptEnabled</key>
        <true />
        <key>dashIndexFilePath</key>
        <string>index.html</string>
        <key>DashDocSetFallbackURL</key>
        <string>http://releases.llvm.org/5.0.0/docs/</string>
    </dict>
</plist>`

Please let me know how I can go about debugging this, since I am a newbie to Qt

**Comment by trollixx** [comment]
Which docset is this coming from? Might be a bug in keyword loading...

**Comment by nishanthkarthik** [comment]
You are correct. According to the `XML` spec, there should be no whitespace before the `xml` tag. The config snippet I pasted has a space before the first tag.

Can we deviate from the spec to skip all the whitespace in the beginning?

**Comment by nishanthkarthik** [comment]
This docset is from Dash user contributions repo

http://kapeli.com/feeds/zzz/user_contributed/build/LLVM/LLVM.tgz

**Comment by nishanthkarthik** [comment]
#852 fixes this issue

**Comment by trollixx** [comment]
It's a problem with the docset, not Zeal. The [must not](https://msdn.microsoft.com/en-us/library/ms256048(v=vs.110).aspx) be a white space prior to XML declaration.

@Kapeli `Info.plist` in the LLVM docset linked above is clearly invalid XML, could you fix it please?

**Comment by Kapeli** [comment]
I've fixed the docset.

FWIW, the docset worked fine in Dash before. I guess Apple is a bit more lax when it comes to XML. You might want to consider making XML parsing a bit less strict in Zeal, as this issue might happen in the future, especially with user contributed docsets.

**Comment by trollixx** [comment]
@Kapeli thanks for fixing. I'll consider making Zeal less strict.
