### ISSUE TITLE
When I click on the "Open in new window (tab)" page, I get the "Welcome" page

### ISSUE THREAD

**Issue by D1mon** [zealdocs/zeal#851]
zeal v0.5
RMB click on (a href="...")  and "Open in new window (tab)"

**Comment by trollixx** [comment]
@scienceblossom 0.5.0 doesn't have the fix, 0.6.0 does, but there's no official binaries yet, only [CI builds](https://bintray.com/zealdocs/windows-ci/zeal-unstable).
