### ISSUE TITLE
Javascript docset link to the upper page doesn't work

### ISSUE THREAD

**Issue by Yanpas** [zealdocs/zeal#853]
STR:
1. Click on the "Standard built-in objects"
2. Nothing happens

Workaround: use right click menu

![String apge](https://user-images.githubusercontent.com/7345761/34376584-7de43942-eafd-11e7-9cba-baf8c6cd792c.png)

**Comment by trollixx** [comment]
I can't find this page in the JavaScript docset. Mine looks like this:

![snip-gh853](https://user-images.githubusercontent.com/714940/34494976-b251ceda-effb-11e7-826d-f508f96bc26e.png)

**Comment by Yanpas** [comment]
Seems like js docset is being modified again
![image](https://user-images.githubusercontent.com/7345761/34499590-c9fd9c14-f017-11e7-94ce-096ba8af6603.png)
