### ISSUE TITLE
lua documents don't recognize url anchor.

### ISSUE THREAD

**Issue by amosbird** [zealdocs/zeal#854]
All lua documents (5.1, 5.2, 5.3) always open showing the top of the doc page.

**Comment by trollixx** [comment]
I cannot reproduce this problem with Zeal 0.5.0 and Lua 5.1 docset.

**Comment by trollixx** [comment]
@amosbird I don't know your system and Zeal version, but I suspect you have either old Zeal, or old Qt WebKit.

Please reopen if that's not the case.
