### ISSUE TITLE
Hardcoded docset index file paths

### ISSUE THREAD

**Issue by Kapeli** [zealdocs/zeal#855]
In Dash, some docsets don't have a `dashIndexFilePath` in their `Info.plist`, but still have an index page.

This is because these docsets were around when I added support for index pages in Dash, and instead of updating each and every one of them, I've hardcoded some paths within Dash.

Please consider changing Zeal to do what Dash does, to support these docsets fully: https://github.com/Kapeli/Dash-iOS/blob/4884835117038fad072afc99a0cbbb4f3fa474fa/Dash/DHDocset.m#L411-L432.

**Comment by trollixx** [comment]
Zeal already does that! If you take a look at http://api.zealdocs.org/v1/docsets, there you can see that some docsets have `extra.indexFilePath` property. I'll cross check our data with the source code you linked to be sure we covered everything.

**Comment by trollixx** [comment]
Will close this after doing the verifying the data.

**Comment by Kapeli** [comment]
Ah. I see.

A Zeal user (@zodmaner) contacted me because the index page wasn't working for the Common Lisp docset. The `indexFilePath` for Common Lisp is set correctly in the json, so maybe he downloaded the docset manually and Zeal didn't patch it?

**Comment by trollixx** [comment]
Yeah, that might be the real reason. Installing docsets manually doesn't really work in Zeal due to lack of metadata in the archives.

Just tested the Common Lisp docset, and it does have the index page.

**Comment by trollixx** [comment]
Okay, here's the list of hard-coded index pages:

- [ ] `dash-browse-index.html`
- [ ] `prototypejs/index.html`
- [ ] `sqlite/index.html`
- [ ] `documentation/Cocoa/Reference/Foundation/ObjC_classic/_index.html`
- [ ] `documentation/ToolsLanguages/Conceptual/Xcode_User_Guide/000-About_Xcode/about.html`
- [ ] `documentation/IDEs/Conceptual/xcode_quick_start/index.html`
- [ ] `package-detail.html`
- [ ] `docs/reference/packages.html` - [ ] `Arduino/index.html` - [ ] `output/en.cppreference.com/w/cpp.html` - [ ] `output/en/cpp.html`
- [ ] `clojure/api-index.html`
- [ ] `developer.anscamobile.com/reference/index.html`
- [ ] `docs.coronalabs.com/api/index.html`
- [ ] `developer.mozilla.org/en/CSS/CSS_Reference.html`
- [ ] `developer.mozilla.org/en-US/docs/CSS/CSS_Reference.html`
- [ ] `api/overview-summary.html`
- [ ] `haskell/index.html`
- [ ] `developer.mozilla.org/en/HTML/HTML5.html`
- [ ] `developer.mozilla.org/en/JavaScript/Reference.html`
- [ ] `developer.mozilla.org/en/JavaScript/Reference.html`
- [ ] `www.lua.org/manual/5.2/index.html`
- [ ] `www.lua.org/manual/5.1/index.html`
- [ ] `www.lua.org/manual/5.3/index.html`
- [ ] `nodejs/api/documentation.html`
- [ ] `nodejs/api/api/documentation.html`
- [ ] `perldoc-html/index-functions-by-cat.html`
- [ ] `res/index.html`
- [ ] `genindex-all.html`
- [ ] `topics/introduction.html`
- [ ] `introduction.html`
- [ ] `api.rubyonrails.org/files/RDOC_MAIN_rdoc.html`
- [ ] `scala/package.html` - [ ] `akka/package.html`
- [ ] `docs/welcome.html`
- [ ] `developer.mozilla.org/en/XSLT/Elements.html`
- [ ] `developer.mozilla.org/en/XUL_Reference.html`
- [ ] `genindex.html`
- [ ] `html/classes.html`
- [ ] `html/qtdoc/classes.html`
- [ ] `api.jquery.com/index.html`
- [ ] `helphelp.html`
- [ ] `partials/guide/index.html`
- [ ] `elisp/index.html`
- [ ] `docs/right-pane.html`
- [ ] `doc/man_index.html`
- [ ] `docs.go-mono.com/monoroot.html`
- [ ] `api/index.html`
- [ ] `mongo/genindex.html`
- [ ] `HyperSpec/HyperSpec/Front/index.htm`
- [ ] `api.jqueryui.com/category/all/index.html`
- [ ] `golang.org/ref/index.html`
- [ ] `documentation/ToolsLanguages/Conceptual/Xcode_Overview/About_Xcode/about.html`
- [ ] `documentation/Cocoa/Reference/Foundation/ObjC_classic/index.html`
- [ ] `documentation/ToolsLanguages/Conceptual/Xcode_Overview/index.html`

**Comment by trollixx** [comment]
Wow, such a mess. Seems like many of these paths are now irrelevant. I guess I'll close this ticket and make changes as users spot missing index pages.

**Comment by sergio-rivas** [comment]
@trollixx 

If a user wants to download a docset manually, how to do it? What are the metadata changes that need to happen? How to do it manually? Downloading docset via Zeal is not working (probably due to heavy censorship in Chinese internet).

**Comment by trollixx** [comment]
@sergio-rivas We have a lot of users in China (more than any other country), and they definitely can download the docsets.

When installing (unpacking) a docset manually, `meta.json` would be missing, and the docset would not have icon, and properly set index page. You can manually copy the bits you need from [here](http://api.zealdocs.org/v1/docsets).

Here's a sample `meta.json`:
```json
{
    "extra": {
        "indexFilePath": "output/en/cpp.html"
    },
    "name": "C++",
    "revision": "43",
    "title": "C++"
}
```
