### ISSUE TITLE
Zeal crashes occasionally

### ISSUE THREAD

**Issue by knight42** [zealdocs/zeal#857]
I installed zeal from community repository on ArchLinux. The version is:
```
$ zeal -v
Zeal 0.5.0
```

I have been experienced this for about a few weeks, and I found out that some docsets always cause zeal to crash, e.g. `mongodb`, `aws javascript`. From the following logs, it seems to be a double free problem. 
```
$ zeal
zeal.core.applicationsingleton: Singleton ID: p4TntKoKqZ7ZD6feD6XK0pQD9MN2AebmyfrFRhohhV0
zeal.core.applicationsingleton: Starting as a primary instance. (PID: 19096)
Cannot determine index file for docset Common_Lisp
Cannot determine index file for docset VMware_vSphere
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Empty filename passed to function
*** Error in `zeal': free(): invalid pointer: 0x00007f1980b5a3c0 ***
zsh: abort (core dumped)  zeal

```

Are there any more details I should provide?

**Comment by trollixx** [comment]
Do you have Oracle JDK installed?

**Comment by trollixx** [comment]
Also Common Lisp and VMware vSphere docsets are most likely corrupted.

**Comment by knight42** [comment]
@trollixx Yeah, I have `jdk` installed on my machine. Is it the root of the problem?

**Comment by knight42** [comment]
@trollixx wow, zeal works great after I uninstalled `jdk`. Thank you!

**Comment by trollixx** [comment]
Duplicate of #802.
