### ISSUE TITLE
Generate JavaDoc docset 

### ISSUE THREAD

**Issue by sivaswami** [zealdocs/zeal#858]
Hi,

I am trying to generate docset from Javadoc for some libraries (Example: Apache common collections)
I followed the provided link : https://kapeli.com/docsets
1. I couldn't find the preferences menu in maven.org. the link leads to search.maven.org.
Maven.org from Preferences > Downloads > Java Docsets
2. I found javadoc.jar for every library. But don't know how to generate a zeal docset and consume it locally.
Please clarify on the steps required.

**Comment by trollixx** [comment]
Zeal and Dash are two different applications. Zeal cannot (yet) generate docsets on its own.
