### ISSUE TITLE
Ubuntu PPA missing v0.5.0

### ISSUE THREAD

**Issue by ktomk** [zealdocs/zeal#860]
Like in #772, I would benefit from v0.5.0 using Ubuntu 16.04 LTS and would benefit from having it. I see in #772 the PPA is not that well supported and no issue so far so opening it.

Docs is here: https://zealdocs.org/download.html#linux-ubuntu

If there are any build instructions a quick hint is appreciated.

**Comment by trollixx** [comment]
Argh, I should definitely add contributing guidelines with information about such tickets. Creating a ticket will not bring a PPA update sooner. I do not maintain it myself anymore. Plus it's irrelevant to this repo (see https://github.com/zealdocs/zeal-packaging).

Anyway, CC @Epskampie :)

**Comment by ktomk** [comment]
following https://github.com/zealdocs/zeal/wiki/Build-Instructions-for-Debian-Family now ...

**Comment by ktomk** [comment]
Quick upgrade instructions:

~~~
cd workspace
git clone git@github.com:zealdocs/zeal.git
cd zeal
sudo apt-get install libqt5webkit5-dev libqt5x11extras5-dev \
  libarchive-dev libsqlite3-dev libxcb-keysyms1-dev
mkdir build && cd build
cmake ..
#  there is a failue hinting file "ECMConfig.cmake" 
# and also "../assets/CMakeLists.txt"
# a quick search reveals the missing component:
cd ../..
git clone git://anongit.kde.org/extra-cmake-modules
cd extra-cmake-modules
mkdir build && cd build    \ncmake ..
make && sudo make install
cd ../../zeal/build
cmake ..
make
sudo make install
# done.
#  comment: me kept zeal running, as on linux, just closeed it and 
# started it again, check the version in the version dialog, 0.5.0
~~~

![image](https://user-images.githubusercontent.com/352517/34503072-d2a0b87a-f016-11e7-8841-4083deba1ffc.png)

**Comment by trollixx** [comment]
Why not just use https://packages.ubuntu.com/xenial/extra-cmake-modules?

**Comment by trollixx** [comment]
Updated the wiki.

**Comment by ktomk** [comment]
> Why not just use https://packages.ubuntu.com/xenial/extra-cmake-modules?
Well, plain not knowing better. I'm not so much into Ubuntu/Debian packaging so far, but git clone looked fruitful to me so I just did that. Worked, but marked the resolution as "quick" I hope that is enough as a signal word... but you might be right. Anyway with the Wiki updated this perhaps just works out of the box w/o the second (`git://anongit.kde.org/extra-cmake-modules`) build `cmake .. && make` combo.

**Comment by davewongillies** [comment]
Paging @epskampie, can you bump the version of Zeal in the ubuntu ppa?

**Comment by Epskampie** [comment]
0.5.0 pushed to ppa repository.

@trollixx any way I can get a message when a new version is released?

**Comment by trollixx** [comment]
@Epskampie Thank you!

I've been thinking about a way to notify package maintainers about new releases and other relevant updates. I guess a mailing list would be the best option, but I am open to other ideas.

I tried pinging you on Gitter, but I guess you don't use it.

**Comment by Epskampie** [comment]
You're right, i don't use gitter. A mailing list for version updates and maybe some info on changed libraries would be excellent!

**Comment by davewongillies** [comment]
Github provides an atom feed for release too:

https://github.com/zealdocs/zeal/releases.atom

For other projects I follow, I've created an [IFTTT](https://ifttt.com) which notifies me.

**Comment by trollixx** [comment]
I thought about sending notifications based on GitHub releases. I can't think of any reasons to send an update to the package maintainers unrelated to a new release.

**Comment by trollixx** [comment]
In the meanwhile I've created a [wiki page](https://github.com/zealdocs/zeal/wiki/Package-Maintainers-and-Issue-Trackers) with a list of packages, their maintainers and issue trackers. The list is currently incomplete though.

@davewongillies Could you add instructions about IFTTT method to the "Information for package maintainers"?

Perhaps, I'll also create a mailing list (or just use a simple script) later.

**Comment by trollixx** [comment]
Anyway, this issue is now resolved.

**Comment by richarson** [comment]
Here's a list of distros/repositories with zeal packages:

https://repology.org/metapackage/zeal/versions
