### ISSUE TITLE
Question about qtwebkit-ng.

### ISSUE THREAD

**Issue by djmbritt** [zealdocs/zeal#864]
Hi there, 

So I downloaded the latest version of Zeal (0.50) and am experiencing the font rendering issue for Ubuntu 17.10.
I read that I need to update my qtwebkit-ng package, after some googling around I am still not sure how to do this.
I also already tried different minimum font sizes, but still experience this issue.
Can someone please point me in the right direction so I can solve this problem?

Thank you.

Screenshot for reference problem.

![screenshot from 2018-01-09 11-22-56](https://user-images.githubusercontent.com/3985738/34716293-ab8afbba-f52f-11e7-9490-a7242e9817a8.png)

**Comment by trollixx** [comment]
Right now I am not aware of an easy way to get the updated Qt WK on Ubuntu. It will be included in 18.04, and can be provided via PPA if someone would set that up.

**Comment by djmbritt** [comment]
Okay, thank you for your response.
Looking forward to it, will use 0.3.1 in the meantime.
