### ISSUE TITLE
Windows Defender slows docsets installation

### ISSUE THREAD

**Issue by Sy0xFF** [zealdocs/zeal#866]
At the moment I am facing an issue with windows defender while using Zeal. If I am downloading a docsets like Xamarin it takes me up to two hours to install.

Disabling Windows Defender Real-time protection will install the docset much faster..

system information:
Window 10 Fall Creators Update 
Zeal (0.5.0)

**Comment by trollixx** [comment]
This will be addressed by implementing #138.

In the meanwhile the only quick solution coming to mind (aside from pausing Defender during installation) is adding docset storage to Defender's exclusion list. Although, I would not recommend doing that, as there were reports of unpacked docset files getting infected.

**Comment by trollixx** [comment]
Closing, as there's no way for us to quickly address this problem.
