### ISSUE TITLE
Zeal crashes on user contributed Entity Framework docset

### ISSUE THREAD

**Issue by 0xced** [zealdocs/zeal#867]
Steps to reproduce:
1. Go to Tools → Docsets…
2. Click the **Add feed** button
3. Paste http://zealusercontributions.herokuapp.com/docsets/Entity_Framework.xml and click **OK**
4. Wait for the docset to be downloaded
5. Open the disclosure button of the *Entity Framework* docset to see the Attributes, Classes, Constructors, Conversions etc.
6. Click the disclosure button of Attributes (or any other) makes Zeal crash

Version: Zeal 0.5.0 running on Windows 8.1 Pro

**Comment by trollixx** [comment]
Reproduced, thanks for reporting!

**Comment by trollixx** [comment]
Technically it's a corrupted docset. The index table is named `SearchIndex` instead of `searchIndex`, so our format detection fails.

I don't know if we should actually support that. CC @Kapeli 

Obviously crashing is a bug either way.

**Comment by trollixx** [comment]
Okay, SQLite is completely case-insensitive, when it comes to SQL identifiers. Even ignores quotes in violation of the SQL standard. Some interesting read: https://www.alberton.info/dbms_identifiers_and_case_sensitivity.html

So we have to support situations like this, and there is nothing wrong with the docset then.
