### ISSUE TITLE
Java EE8, SE9, SE10 docsets cause crash

### ISSUE THREAD

**Issue by u3IFw2wfJ** [zealdocs/zeal#868]
Version: 0.5.0
OS: Windows 10  Home
When opening Java ee8 or Java se9 docset, the program will crash

`<EventData>
  <Data>zeal.exe</Data> 
  <Data>0.5.0.0</Data> 
  <Data>5a3598e7</Data> 
  <Data>unknown</Data> 
  <Data>0.0.0.0</Data> 
  <Data>00000000</Data> 
  <Data>c0000005</Data> 
  <Data>0000019c800c38f3</Data> 
  <Data>5f0c</Data> 
  <Data>01d38abdd4d2f921</Data> 
  <Data>C:\Program Files\Zeal\zeal.exe</Data> 
  <Data>unknown</Data> 
  <Data>caf5ba8c-7589-4f92-8b9b-49d89b315a67</Data> 
  <Data /> 
  <Data /> 
 </EventData>`

**Comment by trollixx** [comment]
Reproduced with the Java SE9 docset, and just a test Qt WebKit browse on[this](https://docs.oracle.com/javase/9/docs/api/overview-summary.html) page.

CC: @annulen

**Comment by trollixx** [comment]
[Backtrace](https://github.com/zealdocs/zeal/files/1624379/bt.txt) from [test-qtwebkit](https://github.com/OtterBrowser/test-qtwebkit).

**Comment by trollixx** [comment]
Zeal 0.5.0 ships with Qt WebKit built from http://code.qt.io/cgit/qt/qtwebkit.git/commit/?id=35655d5f4bad248ead1700b59c381cc568b4e98b

**Comment by blackjyn** [comment]
The problem also persists on Zeal 0.4 in Win 8.1 x64 too

**Comment by vgturtle127** [comment]
@trollixx I can confirm this issues persists on both 0.5 and 0.6 (latest commit). I am running 64-bit Windows 10. Crashes when I try to load Java SE9 docset.

**Comment by trollixx** [comment]
The problem is still there with Qt WebKit 5.212 [72cfbd7](http://code.qt.io/cgit/qt/qtwebkit.git/commit/?id=72cfbd7664f21fcc0e62b869a6b01bf73eb5e7da).

**Comment by vgturtle127** [comment]
@trollixx So does that mean it is a bug with Qt WebKit that hasn't been fixed yet?

**Comment by trollixx** [comment]
@vgturtle127 Yes, the bug is in Qt WebKit, and a few months back @annulen tested WebKit trunk, and apparently the problem is already fixed there. But it seems Qt WebKit still doesn't have it.

**Comment by vgturtle127** [comment]
@trollixx Ah, so has the bug reported to Qt WebKit?

**Comment by trollixx** [comment]
It wasn't reproducible with the most recent WebKit at that moment. So not sure if it's a bug with Qt WK, or the version WebKit that current Qt WK is based on.

**Comment by trollixx** [comment]
A bug report in QtWK is linked above.

**Comment by vgturtle127** [comment]
@trollixx Gotha, so more of a waiting game?

**Comment by vgturtle127** [comment]
@trollixx Oh, trust me I don't write any Java. 🤣 

I just am currently using it to assist in reversing some Java phone applications and SIM card stuff. 😃

**Comment by hellotuitu** [comment]
reproduce this bug with Java SE9 and windows 10.

**Comment by nirry** [comment]
reproduce this bug with Java SE9 and windows 10.

**Comment by jamescsy** [comment]
This bug reproduces with JAVA SE9 and windows 10.

**Comment by xcf007** [comment]
Java SE9 docsets cause crash ，too。My os is win7

**Comment by trollixx** [comment]
@xcf007 What is the version of Zeal?

**Comment by bradle11** [comment]
Happens on zeal-portable-0.6.1-windows-x64 for me

**Comment by xcf007** [comment]
> @xcf007 What is the version of Zeal?

zeal 0.6.1  latest version
