### ISSUE TITLE
can't open  C docset

### ISSUE THREAD

**Issue by baicaiaichibaicai** [zealdocs/zeal#871]
i download C,python3 and qt5 docsets and  only C docset have no content if i search something, if i click "Open URL" and if show content by my browser normal

zeal version : 0.5.0
QT version : 5.7.1
system version : debian 9.3

**Comment by trollixx** [comment]
Is it a completely blank page? Or only some parts are missing?

**Comment by baicaiaichibaicai** [comment]
hi,thank you for reply , is a completely blank page.
![2018-01-19-091403_788x544_scrot](https://user-images.githubusercontent.com/19709689/35129973-3dd9aaae-fcf9-11e7-9c32-00142da16348.png)
![2018-01-19-091333_845x332_scrot](https://user-images.githubusercontent.com/19709689/35129974-3e124468-fcf9-11e7-8bf8-b66b1c9faf22.png)

**Comment by agauniyal** [comment]
Same for C++ docset, this happened when my internet was down for some time but I've no idea why zeal behaved that way because it has already downloaded the documentation 🤔

**Comment by trollixx** [comment]
I think the problem is caused by old Qt WebKit, and missing web fonts. Updating to Qt WebKit 5.212 should address the issue. Alternatively, soon we should have self-contained installations via AppImage, Flatpak or Snap.

**Comment by MikaelBox** [comment]
Hi! I have same problem with Zeal. I have internet connection at home, and Zeal works fine. I downloaded several docsets (all of it works fine at home), packed it and took  to my working place, where there's no connection to internet. 
I get docsets from archive, start Zeal and not all of docsets works fine. C, C++ and Arduino - I see blank sheet. A page is revealed if I will wait some minutes. But next page from this docsets will opened with huge delay. 
When I select HTML docset, I see previous page what was opened early from another docset and HTML docset start page isn't opened. All of another pages from this docset works normally without delay. 

I've seen your proposals to update QtWebKit to 5.212, but I already have this version installed. 
Alternative app packages I can't find. 

In total, if I have internet connection then  Zeal works fine. If I've not internet connection then Zeal don't work correctly with some docsets.
