### ISSUE TITLE
Open Link in a new Window does not work as in previous versions

### ISSUE THREAD

**Issue by genom5** [zealdocs/zeal#875]
Selection via context menu.

After mouse click the link is open in the current tab (or window) and
a new empty tab (or window) gets opened

zeal version : 0.5.0
OS: MS Windows

In V 0.4.0 and before it worked without any problems.

**Comment by 14m3** [comment]
yeah, I have the same problem. 
zeal version : 0.5.0 portable
OS: Windows10

**Comment by trollixx** [comment]
Duplicate of #851.
