### ISSUE TITLE
The libarchive-3.2.1-win32-mingw492.7z download link in wiki is not accessable

### ISSUE THREAD

**Issue by 14m3** [zealdocs/zeal#876]
I want to build zeal on Windows myself. But libarchive download link provided in Wiki was not accessable .

**Comment by trollixx** [comment]
The file has been removed as we no longer build with MinGW. I suggest [vcpkg](https://github.com/Microsoft/vcpkg) for building dependencies on Windows.

**Comment by 14m3** [comment]
okay, i will try vcpkg
