### ISSUE TITLE
bug with opening a link in a new window(tab)

### ISSUE THREAD

**Issue by D0nQuixote** [zealdocs/zeal#882]
there's a bug when I open an inbound documentation link in a new window (or call it tab). what happens is that the link is opened in the current window where the link is, and a new window is opened to zeal homepage !!.
I am using Fedora 27 and the zeal version is 0.5.0, in the previous version it was working fine.
![sad](https://user-images.githubusercontent.com/20429907/35987134-99232d76-0d03-11e8-9c7f-9945f8ce17e0.gif)

**Comment by trollixx** [comment]
Duplicate of #851.
