### ISSUE TITLE
Open in new window function is not working correctly

### ISSUE THREAD

**Issue by m4uro** [zealdocs/zeal#885]
Zeal version: 0.5.0

Reproduction steps:
1. Right click on a link
2. Click "Open in New Window" in the contextual menu

Alternative reproduction steps:
1. Middle button click on a link

Expected:
A new tab is opened, showing the page represented by the link

Current:
A new tab is opened, and gains focus, but it is always the Zeal Welcome page. The original tab now displays the page represented by the link.

Observed in OS: Windows 10, Ubuntu 16.04

**Comment by trollixx** [comment]
Duplicate of #635.

**Comment by trollixx** [comment]
This problem is fixed in the `master` branch.

**Comment by trollixx** [comment]
I linked the wrong ticket earlier. #851 is the correct one.
