### ISSUE TITLE
zeal 0.6.0 fails to build due to some underlinking issue

### ISSUE THREAD

**Issue by david-geiger** [zealdocs/zeal#886]
Hi,

I tried to compile latest 0.6.0 release but it fails to build due to some underlinking issue, see the attached build log:

[build_log.zeal.txt](https://github.com/zealdocs/zeal/files/1734581/build_log.zeal.txt)

Regards,
David

**Comment by abn** [comment]
@david-geiger the specfile changes coming in with https://github.com/zealdocs/zeal-packaging/pull/37 should work file for EL and Fedora distros, I was able to build rpms successfully.

Once the merge is done, I'll publish it onto my copr repo. I'll get the official zealdocs copr configured as soon as I get the chance.

**Comment by abn** [comment]
Also note your build command needs to be fixed up, as things are today `-DBUILD_SHARED_LIBS:BOOL=ON` will not work. Replace it with `-DBUILD_SHARED_LIBS:BOOL=OFF` and it should work for you.

**Comment by david-geiger** [comment]
indeed with -DBUILD_SHARED_LIBS:BOOL=OFF if build fine now, thanks.

**Comment by trollixx** [comment]
@abn Is it something specific to RPM based distros, or a more generic issue? Zeal builds just fine on Ubuntu.

**Comment by abn** [comment]
@trollixx  in this particular case yes. To be more precise this is due to the `%{cmake}` macro as defined by Red Hat distros (and possibly other RPM based distros). 

```
$ rpm --eval '%{cmake}'

  CFLAGS="${CFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic}" ; export CFLAGS ; 
  CXXFLAGS="${CXXFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic}" ; export CXXFLAGS ; 
  FFLAGS="${FFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -I/usr/lib64/gfortran/modules}" ; export FFLAGS ; 
  FCFLAGS="${FCFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -I/usr/lib64/gfortran/modules}" ; export FCFLAGS ; 
  LDFLAGS="${LDFLAGS:--Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld}" ; export LDFLAGS ; 
  /usr/bin/cmake \
        -DCMAKE_C_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DCMAKE_CXX_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DCMAKE_Fortran_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
        -DCMAKE_INSTALL_PREFIX:PATH=/usr \
        -DINCLUDE_INSTALL_DIR:PATH=/usr/include \
        -DLIB_INSTALL_DIR:PATH=/usr/lib64 \
        -DSYSCONF_INSTALL_DIR:PATH=/etc \
        -DSHARE_INSTALL_PREFIX:PATH=/usr/share \
%if "lib64" == "lib64" 
        -DLIB_SUFFIX=64 \
%endif 
        -DBUILD_SHARED_LIBS:BOOL=ON
```

The last line sets the cmake `BUILD_SHARED_LIBS` variable to `ON`. This, iiuc, is required only if we are expecting to build shared libraries for third-party use (might be required in the future I guess). We override this by explicitly setting this to `OFF`.

[1] https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html

**Comment by trollixx** [comment]
I see. Then there's no need for me to change anything.
