### ISSUE TITLE
Color problems with Breeze Dark theme

### ISSUE THREAD

**Issue by sdicke** [zealdocs/zeal#892]
OS: Linux
Distribution: Antergos
Desktop Enviroment: KDE
Library versions: 
qt5-webchannel 5.10.1-1
qt5-webengine 5.10.1-1
qt5-webkit 5.212.0alpha2-12
qt5-base 5.10.1-2
qt5-quickcontrols 5.10.1-1

Some pages, for example obviously at least some bash pages and LaTex pages (I did not check this for all pages), have a coloring which make it hard to read.

**Comment by trollixx** [comment]
Can you attach a screenshot?

**Comment by sdicke** [comment]
![Screenshot 1](http://212.144.102.119/Screenshot.png)

**Comment by trollixx** [comment]
Strange, the screenshot is gone now...

**Comment by trollixx** [comment]
Ah, an external image. You can attach images directly to a comment, no need in using other any hosting.

**Comment by ElricleNecro** [comment]
Here is a screenshot taken using the dark mode of the application, for the bash main page:
![2018-05-24-130914_916x1078_scrot](https://user-images.githubusercontent.com/3876671/40482108-e70b099e-5f53-11e8-915e-ef0a4c6bdb8b.png)
It happens also for, at least:

- SQlite,
- some OpenGL pages,
- LaTeX,
- Julia,
- Common Lisp

**Comment by trollixx** [comment]
I guess it all depends on whether docsets override default styles or not. The web view tries to follow the system theme, and in many instances not correctly.

The solution would be providing sensible defaults for all the docsets. Will try to come up with something...

**Comment by intact** [comment]
You can enable custom css file in preferences.

Try something like this:

```css
body {
    background-color: #fff;
    color: #000;
}
```
