### ISSUE TITLE
zeal-0.5.0 ubuntu ppa trusty

### ISSUE THREAD

**Issue by sheershoff** [zealdocs/zeal#895]
Hey there. I've searched through issues and haven't found one. But 0.5.0 for Trusty (16.04) is missing. As I can see from 0.4.0 same issue thread, @Epskampie could help with this. And I see he did the work for 0.5.0 for other releases on the PPA. Is it possible to update the PPA to get 0.5.0 for Trusty?

**Comment by Epskampie** [comment]
16.04 is not called trusty, it's xenial. 0.5.0 is available for xenial. Rusty is end of life and will not be supported.

**Comment by trollixx** [comment]
Building for 14.04 won't work because Zeal requires Qt 5.5.1 or newer. Actually the only reason for supporting Qt 5.5.1 is Ubuntu 16.04, and I can't wait for 18.04 to bump minimally required Qt version.

My policy is to support only the latest LTS release.

**Comment by trollixx** [comment]
@Epskampie there's no need to build for Trusty, as it's just too old, and I don't see any benefit of spending our time on it.
