### ISSUE TITLE
Provide a release tarball

### ISSUE THREAD

**Issue by mulander** [zealdocs/zeal#897]
Please consider adding a source release tarball, the automatically generated github source downloads are not guaranteed to be immutable and are an issue for systems packaging zeal from source (like OpenBSD).

More information on the issue caused by automatic downloads:
  https://marc.info/?l=openbsd-ports&m=151973450514279&w=2

**Comment by trollixx** [comment]
I didn't know that GitHub's tarballs are not immutable. I will post manually created archives then.

**Comment by trollixx** [comment]
Each GitHub release now has three source tarballs attached to it.
