### ISSUE TITLE
7d39f3f breaks Ubuntu PPA

### ISSUE THREAD

**Issue by pandasauce** [zealdocs/zeal#898]
https://launchpadlibrarian.net/358993572/buildlog_ubuntu-xenial-amd64.zeal_1%3A0.6.0-1ppa1~xenial1_BUILDING.txt.gz

It looks like the PPA build job is expecting `zeal.pro` file to be present in order for the build to succeed. This was removed between 0.5 and 0.6.

**Comment by trollixx** [comment]
Thanks, but there's no need to report PPA failures, as all organization members get automated alerts.

**Comment by trollixx** [comment]
The PPA will be updated at some point, please note that v0.6.0 han't been officially announced.
