### ISSUE TITLE
Crash on search and selecting

### ISSUE THREAD

**Issue by Jeff4Success** [zealdocs/zeal#900]
This crash leave me unable to use the program. It will open up. I can select Java, and browse. Searching will let me enter 2-3 characters before the program closes. I've run it from command line, and here is the output:

zeal.core.applicationsingleton: Singleton ID: LcqKD-zjpYqvgN_A4p9rNvHoLWTxYV9UBb7Vnv9lN4w
zeal.core.applicationsingleton: Starting as a primary instance. (PID: 7493)
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Empty filename passed to function
free(): invalid pointer
Aborted (core dumped)

I would attach dump if I knew where to look. Everything in /tmp that is date/time is 0 length. Let me know where and I'll send files. But if it's my setup, I'll have to debug it then, lol.

`Linux BORGASUS 4.14.23-1-MANJARO #1 SMP PREEMPT Thu Mar 1 06:53:01 UTC 2018 x86_64 GNU/Linux`

`Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               30
Model name:          Intel(R) Core(TM) i7 CPU       Q 740  @ 1.73GHz
Stepping:            5
CPU MHz:             931.023
CPU max MHz:         1734.0000
CPU min MHz:         933.0000
BogoMIPS:            3459.17
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            6144K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm pti tpr_shadow vnmi flexpriority ept vpid dtherm ida`

**Comment by trollixx** [comment]
Do you by any chance have Oracle JDK installed?

**Comment by Jeff4Success** [comment]
Um, why yes I do.

**Comment by Jeff4Success** [comment]
Um, why yes I do.

**Comment by trollixx** [comment]
Duplicate of #802.
