### ISSUE TITLE
Uninstall after building from source and doing 'sudo make install'

### ISSUE THREAD

**Issue by Jeff4Success** [zealdocs/zeal#901]
I attempted some searches in this repository but need some assistance. How do I uninstall after building from source? I've tried `make -n install` but I can't follow it. Linux, Manjaro...

Sorry if I'm asking same questions others have answered before.

**Comment by trollixx** [comment]
In theory `sudo make uninstall`...

**Comment by Jeff4Success** [comment]
I tried it and it says
`make: *** No rule to make target 'uninstall'.  Stop.`
Should I be in a certain directory of the git clone? I tried a few.
Also, I uninstalled/removed oracle java and now Zeal is working nicely. I just want to install through repositories whenever possible, ya know, for that uninstall thing ;-)

**Comment by trollixx** [comment]
You should do that from the build directory, otherwise there's no makefile.

**Comment by Jeff4Success** [comment]
I'll close this in a day or two. Suffice to say, uninstalling doesn't work for me. I have a working Zeal so I'll celebrate the small victories.

**Comment by trollixx** [comment]
CMake indeed does not provide `make uninstall`. Please see [this StackOverflow answer](https://stackoverflow.com/a/44649542/721710) for more details.

A quick way to remove installed files (taken from the linked answer:

```
$ xargs rm < install_manifest.txt
```
