### ISSUE TITLE
Vim docset has rendering issues when loaded

### ISSUE THREAD

**Issue by DerekTurtleRoe** [zealdocs/zeal#903]
I am running version 0.5 and 0.6 (latest commit) of Zeal, and running 64-bit Windows 10.

Here is a screenshot:

![untitled](https://user-images.githubusercontent.com/3183676/37248412-5c9fff72-2497-11e8-936b-106fdcfe9849.png)

I've never seen this happen before, so not sure exactly what's happening.

Let me know if I can help with anything.

**Comment by trollixx** [comment]
Feels like a Qt WebKit bug, need to check against a freshly built one.

**Comment by vgturtle127** [comment]
@trollixx You mean you think it could be a bug in the internal Qt WebKit browser version that Zeal uses, and you want to test against building a newer version for Zeal?

**Comment by trollixx** [comment]
Yeah, we [have](https://bintray.com/zealdocs/windows-ci/qtwebkit/5.212.0_72cfbd7) it already, just need to update the CI configuration for Zeal.

**Comment by vgturtle127** [comment]
@trollixx Will there be an unstable CI build of that soon?

**Comment by trollixx** [comment]
0.6.0-2 has been rebuilt with Qt 5.10.1 and newer Qt WebKit. Please give it a try.

**Comment by trollixx** [comment]
Figured it out. The bug is fixed, but you might need to reset default size for the font font manually.

**Comment by vgturtle127** [comment]
@trollixx Alright, thank you!
