### ISSUE TITLE
VMWare vSphere doesn't show up in latest commit

### ISSUE THREAD

**Issue by vgturtle127** [zealdocs/zeal#906]
I can't get the vSphere docset to render when it is loaded, is there anything I can do to try and debug the issue?

**Comment by trollixx** [comment]
What do you see? An empty page?

**Comment by vgturtle127** [comment]
@trollixx No, it looks like it loads the background color, but that's it.

**Comment by trollixx** [comment]
The problem was caused by a non-standard path for docset's index page. Refresh docset list, and redownload the docset to fix it.

**Comment by vgturtle127** [comment]
@trollixx Thanks, man! You're on a roll today. 😉
