### ISSUE TITLE
Upload 0.6.0 Windows binaries

### ISSUE THREAD

**Issue by vaz-ar** [zealdocs/zeal#912]
Hello,

could you upload the 0.6.0 binaries ? The download link still point to the 0.5.0 version.

**Comment by trollixx** [comment]
Please do not create tickets about releases, that have not been announced. A github release doesn't mean that the version is ready for distribution. Until Zeal shows the update notification, it's not a public release.

**Comment by trollixx** [comment]
There will be no 0.6.0 binaries, as I want to release 0.6.1 instead that will include a few fixes for the bugs discovered in the tagged 0.6.0 code.

**Comment by lluke777** [comment]
When 0.6.1 version is planned do release?
