### ISSUE TITLE
Zeal crashes with CSS docset

### ISSUE THREAD

**Issue by naraesk** [zealdocs/zeal#913]
I'm using zeal 0.6.0 on Arch Linux. I have installed the CSS docset (and several other ones). When clicking on a entry in the properties category of CSS Zeal crashes reproducible. It does not crash on every entry, but on almost every 

Crash: e.g., animation, background-color, border, and many more
No Crash: e.g., aural, bleed

Here is the console output from a crash:

> $ zeal
> zeal.core.applicationsingleton: Singleton ID: rQj7kzX1NNa7f1dp7ZzCiPb2jteyu9KO6VTqxCVRpJA
> zeal.core.applicationsingleton: Starting as a primary instance. (PID: 27920)
> libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: iCCP: known incorrect sRGB profile
> [PIPELIGHT:LIN:unknown] attached to process.
> [PIPELIGHT:LIN:unknown] checking environment variable PIPELIGHT_SILVERLIGHT5_1_CONFIG.
> [PIPELIGHT:LIN:unknown] searching for config file pipelight-silverlight5.1.
> [PIPELIGHT:LIN:unknown] trying to load config file from '/home/naraesk/.config/pipelight-silverlight5.1'.
> [PIPELIGHT:LIN:unknown] trying to load config file from '/etc/pipelight-silverlight5.1'.
> [PIPELIGHT:LIN:unknown] trying to load config file from '/usr/share/pipelight/configs/pipelight-silverlight5.1'.
> [PIPELIGHT:LIN:unknown] sandbox not found or not installed!
> [PIPELIGHT:LIN:silverlight5.1] using wine prefix directory /home/naraesk/.wine-pipelight.
> [PIPELIGHT:LIN:silverlight5.1] checking plugin installation - this might take some time.
> [install-dependency] wine-silverlight5.1-installer is already installed in '/home/naraesk/.wine-pipelight'.
> [install-dependency] wine-mpg2splt-installer is already installed in '/home/naraesk/.wine-pipelight'.
> 000b:fixme:winediag:start_process Wine Staging 3.4 is a testing version containing experimental patches.
> 000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
> wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
> 000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
> [PIPELIGHT:WIN:silverlight5.1] embedded mode         is on.
> [PIPELIGHT:WIN:silverlight5.1] windowless mode       is off.
> [PIPELIGHT:WIN:silverlight5.1] linux windowless mode is off.
> [PIPELIGHT:WIN:silverlight5.1] force SetWindow       is off.
> [PIPELIGHT:WIN:silverlight5.1] window class hook     is on.
> [PIPELIGHT:WIN:silverlight5.1] strict draw ordering  is off.
> [PIPELIGHT:WIN:silverlight5.1] replaced API function CreateWindowExA.
> [PIPELIGHT:WIN:silverlight5.1] replaced API function CreateWindowExW.
> [PIPELIGHT:WIN:silverlight5.1] replaced API function TrackPopupMenuEx.
> [PIPELIGHT:WIN:silverlight5.1] replaced API function TrackPopupMenu.
> 0009:fixme:d3d:wined3d_dxtn_init Wine cannot find the txc_dxtn library, DXTn software support unavailable.
> 0009:fixme:ntdll:EtwRegisterTraceGuidsW (0x7b8d21a7, 0x7b970120, {aa087e0e-0b35-4e28-8f3a-440c3f51eef1}, 1, 0x70f588, (null), (null), 0x7b970120): stub
> 0009:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {aa087e0e-0b35-4e28-8f3a-440c3f51eef1}
> [PIPELIGHT:WIN:silverlight5.1] init successful!
> [PIPELIGHT:WIN:silverlight5.1] OpenGL Vendor: Intel Open Source Technology Center
> [PIPELIGHT:WIN:silverlight5.1] OpenGL Renderer: Mesa DRI Intel(R) Haswell Mobile x86/MMX/SSE2
> [PIPELIGHT:WIN:silverlight5.1] Your GPU is in the whitelist, hardware acceleration should work.
> free(): invalid pointer
> 0009:fixme:ntdll:EtwUnregisterTraceGuids deadbeef: stub
> Aborted (core dumped)

**Comment by trollixx** [comment]
Seems like Qt WebKit tries to load the pipelight plugin, which runs in WINE (!), and then crashes.

@annulen what do you think about blacklisting pipelight?

**Comment by annulen** [comment]
That's fine with me

**Comment by trollixx** [comment]
`QWebSettings::PluginsEnabled` is disabled by default, so Qt WebKit should not even attempt to load them.

**Comment by trollixx** [comment]
Same as #802. Nothing to do on our side, please follow annulen/webkit#755 for updates.
