### ISSUE TITLE
Enhance browser popup menu

### ISSUE THREAD

**Issue by Glandos** [zealdocs/zeal#925]
As far as I remember, in Zeal 0.4.0, the popup menu in the browser view had both "Back" and "Forward" entries, that disappeared in 0.6.0 (or 0.5.0?). It was extremely useful, since when browsing documentation, I usually have the mouse pointer in the middle of the page, using the mouse scroll. To go back, I right-click, then a really small move to the first entry, and release the button. This action is nearly as efficient as a mouse gesture.

Now, I have to move the mouse to the precise location of the "Back" button near tabs. Or use the keyboard, but my hand is usually over the mouse.

**Comment by trollixx** [comment]
The context menu has been replaced with a custom one in 0.6.0. I'll add Back and Forward items back.
