### ISSUE TITLE
How can i add a custom docset

### ISSUE THREAD

**Issue by suiyueranzly** [zealdocs/zeal#928]
I want to add a custom [apache commons](http://commons.apache.org/proper/commons-bcel/apidocs/index.html)  docset, how can i do it,thanks.

**Comment by trollixx** [comment]
Seems like it's available from http://zealusercontributions.herokuapp.com/

**Comment by trollixx** [comment]
Alternative you can create your own docset following [this guide](https://kapeli.com/docsets).

Closing since we don't work on docsets.
