### ISSUE TITLE
Add FontAwesome 5

### ISSUE THREAD

**Issue by skylarmt** [zealdocs/zeal#930]
I was disappointed to find the FontAwesome docs are for version 4.7.

**Comment by Kapeli** [comment]
I'm still working on updating the Font Awesome docset to version 5. This is because the docs have changed significantly and I'm having trouble getting them to work offline, as they're JS-heavy.

**Comment by skylarmt** [comment]
Maybe the best option would be getting a list of all the icons, then writing a script to generate simple HTML versions of the docs (maybe base it on the 4.7 docs, but change the colors to blue or something).  It wouldn't share the same codebase at all, but will be functional.

**Comment by trollixx** [comment]
Closing, since it's out of scope for Zeal.
