### ISSUE TITLE
connection closed

### ISSUE THREAD

**Issue by NiceKingWei** [zealdocs/zeal#939]
I have just installed zeal 0.6.0 on ubuntu 18.04. But I couldn't install any doc because the `conncetion closed` always occurred. I couldn't even install them by adding feed file manually. After that I read the feed file and get some urls. Surprisingly I could download from these urls, which indicated that my Internet connection is not closed. How can I fix it? Is there any way to install the doc manually?

**Comment by trollixx** [comment]
Does your Internet connection require using a proxy?

**Comment by chestnutme** [comment]
I solved this by add feeds from [Kapeli/feeds](https://github.com/Kapeli/feeds) manully.
Env: Zeal 0.2.1 on Ubuntu16.04

**Comment by trollixx** [comment]
You should really update to a more recent version.
