### ISSUE TITLE
Duplicate docsets without icon

### ISSUE THREAD

**Issue by 66beta** [zealdocs/zeal#94]
windows 7 32bit

![Duplicate docsets without icon](https://lh4.googleusercontent.com/-XAz6M2oJMLc/UuHm6lfAEUI/AAAAAAAAAWw/PW8V_qwcjEw/w539-h312-no/QQ%25E6%2588%25AA%25E5%259B%25BE20140124120649.png)

**Comment by trollixx** [comment]
We no longer provide own docsets, so no more duplicated docsets.
