### ISSUE TITLE
Cannot install any docset

### ISSUE THREAD

**Issue by navdeepio** [zealdocs/zeal#946]
![image](https://user-images.githubusercontent.com/9297865/40636722-c871b516-632a-11e8-8d5d-0a5ab1d14bb2.png)

Using latest zeal on archlinux

**Comment by navdeepio** [comment]
![image](https://user-images.githubusercontent.com/9297865/40636745-eaa9920c-632a-11e8-97cc-21bd75476b5d.png)

**Comment by trollixx** [comment]
Does double clicking docsets work?

**Comment by navdeepio** [comment]
nope :(

**Comment by trollixx** [comment]
Strange. I assume you tried the `Refresh` button, and restarting Zeal...

**Comment by navdeepio** [comment]
absolutely

**Comment by trollixx** [comment]
What is your Qt theme?

**Comment by navdeepio** [comment]
default? I'm using bspwm and no DE.

**Comment by trollixx** [comment]
Yeah, docset storage path currently has to contain only Latin characters (#747).

**Comment by trollixx** [comment]
I just noticed `Docset storage is read only.` on the screenshot. That's why nothing can be downloaded. It's not a bug.

**Comment by navdeepio** [comment]
looks like a recent update fixed it, closing this issue for now.

**Comment by hgolden** [comment]
I just cloned master and recompiled. I still get the `Docset storage is read only.`

I am running on Ubuntu Linux 18.04.1 LTS. I have installed all dependencies as specified in the Zeal wiki.

Please re-open this bug. Thanks.

**Comment by trollixx** [comment]
@hgolden `Docset storage is read only.` just tells you that Zeal cannot write to the directory. Check where your docset storage is, and then make sure file system permissions allow write access. You can also try to choose another directory for the storage.

**Comment by hgolden** [comment]
@trollixx  The first thing I did was check the file system permissions. They all appear correct (allowing write). I will try a brand new directory as you suggest.

**Comment by hgolden** [comment]
I created a new directory and I am able to load docsets to it. Therefore, I no longer request that this bug be reopened.

**Comment by brainplot** [comment]
I know I'm a bit late. I was experiencing the same issue because I had manually (i.e. without the directory picker) change the docsets path to a directory that didn't exist; Zeal wasn't able to create a new directory at the specified location, and the `Docset storage is read only.` message was shown.
I created the directory at the specified location and it worked as expected.
So the problem seems to be specifying a directory not present in the user's file system. At least that was the cause for me.

**Comment by trollixx** [comment]
@brainplot thanks for the info, a better diagnostic message would definitely be helpful. I'll look into making it more obvious why docset installation fails.
