### ISSUE TITLE
I request to add another helpful frameworks and useful and in demand programming languange

### ISSUE THREAD

**Issue by NickDoe** [zealdocs/zeal#947]
I request to add MATERIALIZE CSS FRAMEWORK and LATEST ANGULARJS 5 and 6 Cheat Codes.

**Comment by trollixx** [comment]
Creating and maintaining docsets not part of this projects. All docsets currently available inside the app are generously provided by [Dash](https://kapeli.com/dash).

Many docsets can be found on the Internet. Notable resources:

- [Feeds](http://zealusercontributions.herokuapp.com/) for Dash user contributed docsets.
- [Third Party Resources](https://github.com/zealdocs/zeal/wiki/Third-Party-Resources#docsets) wiki page.

You can also generate own docsets following [this guide](https://kapeli.com/docsets).
