### ISSUE TITLE
Building on Centos, Zlib.h error while installing PerlIO::gzip

### ISSUE THREAD

**Issue by onkarnath89** [zealdocs/zeal#949]
I'm using Centos6, trying to install PerlIO::gzip
error that I get is

> 
> gzip.xs:16:10: fatal error: zlib.h: No such file or directory
>  #include <zlib.h>
>           ^~~~~~~~
> compilation terminated.
> make: *** [gzip.o] Error 1
> 

how can I deal with this

I have tried many solutions from web but none of them worked. some of them are as below:

**yum install libpng libpng-devel**
Package 2:libpng-1.2.49-2.el6_7.x86_64 already installed and latest version
Package 2:libpng-devel-1.2.49-2.el6_7.x86_64 already installed and latest version

 **sudo yum install libpng-devel gd-devel zlib-devel perl-ExtUtils-MakeMaker**

Package 2:libpng-devel-1.2.49-2.el6_7.x86_64 already installed and latest version
Package gd-devel-2.0.35-11.el6.x86_64 already installed and latest version
Package zlib-devel-1.2.3-29.el6.x86_64 already installed and latest version
Package perl-ExtUtils-MakeMaker-6.55-144.el6.x86_64 already installed and latest version

**sudo yum groupinstall "Development Tools"**
Package flex-2.5.35-9.el6.x86_64 already installed and latest version
Package gcc-4.4.7-18.el6_9.2.x86_64 already installed and latest version
Package redhat-rpm-config-9.0.3-51.el6.centos.noarch already installed and latest version
Package rpm-build-4.8.0-55.el6.x86_64 already installed and latest version
Package 1:make-3.81-23.el6.x86_64 already installed and latest version
Package patch-2.6-8.el6_9.x86_64 already installed and latest version
Package 1:pkgconfig-0.23-9.1.el6.x86_64 already installed and latest version
Package gettext-0.17-18.el6.x86_64 already installed and latest version
Package automake-1.11.1-4.el6.noarch already installed and latest version
Package bison-2.4.1-5.el6.x86_64 already installed and latest version
Package libtool-2.2.6-15.5.el6.x86_64 already installed and latest version
Package autoconf-2.63-5.1.el6.noarch already installed and latest version
Package gcc-c++-4.4.7-18.el6_9.2.x86_64 already installed and latest version
Package binutils-2.20.51.0.2-5.47.el6_9.1.x86_64 already installed and latest version
Package patchutils-0.3.1-3.1.el6.x86_64 already installed and latest version
Package byacc-1.9.20070509-7.el6.x86_64 already installed and latest version
Package indent-2.2.10-7.el6.x86_64 already installed and latest version
Package systemtap-2.9-7.el6.x86_64 already installed and latest version
Package diffstat-1.51-2.el6.x86_64 already installed and latest version
Package elfutils-0.164-2.el6.x86_64 already installed and latest version
Package cvs-1.11.23-16.el6.x86_64 already installed and latest version
Package rcs-5.7-37.el6.x86_64 already installed and latest version
Package subversion-1.6.11-15.el6_7.x86_64 already installed and latest version
Package gcc-gfortran-4.4.7-18.el6_9.2.x86_64 already installed and latest version
Package 1:doxygen-1.6.1-6.el6.x86_64 already installed and latest version
Package intltool-0.41.0-1.1.el6.noarch already installed and latest version
Package git-1.7.1-9.el6_9.x86_64 already installed and latest version
Package ctags-5.8-2.el6.x86_64 already installed and latest version
Package cscope-15.6-7.el6.x86_64 already installed and latest version
Package swig-1.3.40-6.el6.x86_64 already installed and latest version
Warning: Group development does not have any packages.
No packages in any requested group available to install or update

Kindly help

**Comment by onkarnath89** [comment]
I posted here because of two reasons.
1) the error I am getting seems something like a C library issue.
2) I have seen discussions of linux modules over this panel, and this error is due to some or the other missing library, or something related to os.

**Comment by auscompgeek** [comment]
Huh? This is the _Zeal_ issue tracker, for discussion about the _Zeal_ project, and nothing else. Always has, always will be. Nobody here understands your problem, and we will not be able to help you.

**Comment by trollixx** [comment]
Closing as completely unrelated to Zeal.
