### ISSUE TITLE
Need Docset for REACT NATIVE (for zeal users)

### ISSUE THREAD

**Issue by prashaddey** [zealdocs/zeal#950]
It will be very helpful for everyone if anyone adds docset of REACT NATIVE as it has become one of the popular frameworks nowadays.

I'm concerned about this, [react-native-dash](https://github.com/dash-docs-community/react-native-dash) but, don't know how to use it.

Thanks in advance.

**Comment by auscompgeek** [comment]
It's already built for you and in the Dash user contributed docsets, just download it.

See #170.

**Comment by trollixx** [comment]
Dash and Zeal use the same docsets.
