### ISSUE TITLE
ppa doesn't work on 18.04

### ISSUE THREAD

**Issue by hryamzik** [zealdocs/zeal#953]
> The repository 'http://ppa.launchpad.net/zeal-developers/ppa/ubuntu bionic Release' does not have a Release file.

**Comment by ChaiTRex** [comment]
You might have better luck by reporting this to [`zealdocs/zeal-packaging`](https://github.com/zealdocs/zeal-packaging).

Clicking on the `dists` directory of your link, I see that `artful` is available. You can probably modify the appropriate `/etc/apt/sources.list.d` file to change `bionic` to `artful`.

**Comment by Wirone** [comment]
I've changed to `artful` and there isn't error anymore, but should it be "fixed" like this?

**Comment by ChaiTRex** [comment]
Oh, I didn't mean that as a fix for here, just as a stopgap for you right now while they hopefully fix it.

**Comment by trollixx** [comment]
v0.6.1 has been uploaded to the PPA.
