### ISSUE TITLE
Windows is too wide

### ISSUE THREAD

**Issue by hryamzik** [zealdocs/zeal#954]
I'm trying to use the app on GPD Pocket and window is much wider than my screen. I can make it even more wide but can't do the opposite. Screen is 1200x1920 rotated clockwise and scaled at 1,75.

**Comment by trollixx** [comment]
I can remove minimal window width limit, not sure if that will address the problem on such a unique device.

**Comment by trollixx** [comment]
In the `master` branch minimum window width has been reduced to 400px, that should let Zeal fit even with 3x scaling.

**Comment by hryamzik** [comment]
Awesome, closing this as I can't verify now, waiting for battery replacement.
