### ISSUE TITLE
Some problems with Zeal without internet connection

### ISSUE THREAD

**Issue by MikaelBox** [zealdocs/zeal#955]
Hi! I have same problem with Zeal. I have internet connection at home, and Zeal works fine. I downloaded several docsets (all of it works fine at home), packed it and took to my working place, where there's no connection to internet.
I get docsets from archive, start Zeal and not all of docsets works fine. C, C++ and Arduino - I see blank sheet. A page is revealed if I will wait some minutes. But next page from this docsets will opened with huge delay.
When I select HTML docset, I see previous page what was opened early from another docset and HTML docset start page isn't opened. All of another pages from this docset works normally without delay.

I've seen your proposals to update Qt WebKit to 5.212, but I already have this version installed.
Alternative app packages I can't find.

In total, if I have internet connection then Zeal works fine. If I've not internet connection then Zeal don't work correctly with some docsets.

P.S. My OS at home is Ubuntu 18.04, at work - Debian 9. If it's matter. Zeal version: 0.6.0

I saw same problem [here](https://github.com/zealdocs/zeal/issues/871)

P.P.S. Now I try it at home, C, C++ and Arduino works fine. But Vim looks like ... ![img](https://i.imgur.com/A67erHO.png)
and HTML start page isn't opened.

**Comment by trollixx** [comment]
The Vim problem has been fixed in unreleased 0.6.1 (#903).

I will check C, C++ and Andruino docsets for external resources.

**Comment by MikaelBox** [comment]
PostgreSQL docset has problem with his examples such as Vim docset. All of examples have a very small font

**Comment by vincent-herlemont** [comment]
@MikaelBox In Preference > Content, change Monospace Size.

**Comment by trollixx** [comment]
@Kapeli Ardruino docset references a bunch of external resources.

```
https://www.google-analytics.com/analytics.js
https://cdn.arduino.cc/header-footer/hxtufl6gko/create-nav-images/icons.svg
https://cdn.arduino.cc/header-footer/hxtufl6gko/en/header.html
https://cdn.arduino.cc/header-footer/hxtufl6gko/en/footer.html
https://cdn.arduino.cc/header-footer/hxtufl6gko/en/newsletter-modal.html
https://content.arduino.cc/website/social_icons/icon-facebook.svg
https://content.arduino.cc/website/social_icons/icon-twitter.svg
https://content.arduino.cc/website/social_icons/icon-gplus.svg
https://content.arduino.cc/website/social_icons/icon-instagram.svg
https://content.arduino.cc/website/social_icons/icon-github.svg
https://content.arduino.cc/website/social_icons/icon-flickr.svg
https://content.arduino.cc/website/social_icons/icon-youtube.svg
https://cdn.arduino.cc/header-footer/hxtufl6gko/images/burger_menu.svg
https://cdn.arduino.cc/header-footer/hxtufl6gko/images/icon_quotes.svg
https://cdn.arduino.cc/header-footer/hxtufl6gko/images/cart.svg
https://cdn.arduino.cc/header-footer/hxtufl6gko/images/icon_geolocation.svg
https://cdn.arduino.cc/header-footer/hxtufl6gko/images/global_user_profile.svg
https://cdn.arduino.cc/header-footer/hxtufl6gko/en/privacy-modal.html
https://cdn.arduino.cc/header-footer/hxtufl6gko/css/header.css
https://cdn.arduino.cc/header-footer/hxtufl6gko/css/footer.css
https://cdn.arduino.cc/header-footer/hxtufl6gko/css/newsletter-modal.css
https://cdn.arduino.cc/header-footer/hxtufl6gko/css/privacy-modal.css
https://cdn.arduino.cc/header-footer/hxtufl6gko/js/header.js
https://cdn.arduino.cc/header-footer/hxtufl6gko/js/footer.js
https://cdn.arduino.cc/header-footer/hxtufl6gko/js/newsletter-modal.js
https://cdn.arduino.cc/header-footer/hxtufl6gko/login.js
https://store.arduino.cc/cart/api/count?ajax=1
https://store.arduino.cc/cart/api/minicart?ajax=1
```

I think this should be addressed on your side.

At the same time I couldn't find any external requests triggered from the C++ docset.

**Comment by trollixx** [comment]
Actually, found a few in C++ as well:

```
//en.cppreference.com/DejaVuSansMonoCondensed75.ttf
//en.cppreference.com/DejaVuSansMono.ttf
//en.cppreference.com/DejaVuSansMono-Bold.ttf
```

**Comment by Kapeli** [comment]
Arduino: this docset has the `DashDocSetBlocksOnlineResources` key in Info.plist. Zeal should block all the HTTP requests.

C++: Dash displays pages using `file://` URLs. Due to this, `//en.cppreference.com/DejaVuSansMonoCondensed75.ttf` gets turned into `file:///en.cppreference.com/DejaVuSansMonoCondensed75.ttf` which later gets blocked by Dash because only file requests inside `.docset` folders are allowed.

Using `file://` URLs is dumb and poses other problems (I'm going to change it in the future in Dash), but could you make Zeal load URLs using a custom URL scheme so you could block these requests?

**Comment by trollixx** [comment]
I didn't know about `DashDocSetBlocksOnlineResources`, will look into supporting this option.

Using a different URL schema has been on my to-do list for a while, but it's not a trivial change. I think it will be part of finally switching to working with docsets without extraction.

Originally Zeal did block on non-local requests with `file://` schema, but I changed it in 4dcd7cf90bcf07fda00caa00252364541dc8ef1d to use HTTPS a while back, and now I cannot recall why I did that :)

**Comment by dan-t** [comment]
> Actually, found a few in C++ as well:
> 
> ```
> //en.cppreference.com/DejaVuSansMonoCondensed75.ttf
> //en.cppreference.com/DejaVuSansMono.ttf
> //en.cppreference.com/DejaVuSansMono-Bold.ttf
> //srv.carbonads.net/ads/.json?segment=placement:&callback=_carbonads_go
> ```

Is there currently any way to handle these external resources being offline? Or is it poosible to tell zeal not to look up these resources?

Thanks for any hints!

**Comment by StarOrpheus** [comment]
New dev here. @trollixx What about me implementing a local cache subsystem for external resources with optional upper storage limit?

**Comment by trollixx** [comment]
@StarOrpheus webview is supposed to cache those, so it's not that big of an issue. In general docsets should never try to access anything remote.

Also we are working on moving all the heavy lifting into a separate service, so adding any functionality to Zeal is not a good time investment.

**Comment by w-ymir** [comment]
> Actually, found a few in C++ as well:
> 
> ```
> //en.cppreference.com/DejaVuSansMonoCondensed75.ttf
> //en.cppreference.com/DejaVuSansMono.ttf
> //en.cppreference.com/DejaVuSansMono-Bold.ttf
> //srv.carbonads.net/ads/.json?segment=placement:&callback=_carbonads_go
> ```

`C++.docset/Contents/Resources/Documents/cdn.carbonads.com/carbon.js` still accesses `srv.carbonads.net` and `cdn4.buysellads.net`. It seems every html page in cppreference.com is using this js file.

**Comment by trollixx** [comment]
I believe all mentioned issues have been fixed in the `main` branch. Please try the latest [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml). Binary artifacts are attached to each build.

**Comment by trollixx** [comment]
All issues listed above have been fixed. I created #1538 to further research and implement per docset management of online access.
