### ISSUE TITLE
Typographical confusion

### ISSUE THREAD

**Issue by danielesk** [zealdocs/zeal#959]
Open the document, the layout is uncomfortable and uncomfortable. It is better to perfect it.

![pb](https://user-images.githubusercontent.com/10652829/42719741-91fee43a-874d-11e8-9b11-d28594901fdc.png)

**Comment by trollixx** [comment]
@Danielesk Chinese Windows by any chance?

**Comment by Danielesk** [comment]
@trollixx
yes yes.
It's Windows 10 Professional version.

**Comment by trollixx** [comment]
I guess then it's a problem similar to #536, just on Qt WebKit's side.

@annulen thoughts? In this scenario (unlike #816) characters are correct, but font and spacing are off.

**Comment by annulen** [comment]
This is a different bug certainly, looks like shaping failure
