### ISSUE TITLE
default `pre`, `code` and `samp` HTML elements have too small font size to even see them

### ISSUE THREAD

**Issue by rindeal** [zealdocs/zeal#960]
Dark font on dark background issue (https://github.com/zealdocs/zeal/pull/951) was probably just the tip of the issues with the default CSS properties gone wrong. In normal browser everything works without any modifications.

```css
pre, code, samp {
    font-size: 10pt;
}
```

worked for me as a temporary workaround.

## Screenshots

Page used: `Bash` -> `Builtins` -> `.`

### Before:

---

![image](https://user-images.githubusercontent.com/5360877/42901125-f9c3eae0-8aca-11e8-896a-b773e19dfeaf.png)

---

### After:

---

![image](https://user-images.githubusercontent.com/5360877/42901203-3b53a284-8acb-11e8-9817-43bcb7764ccd.png)

---

**Comment by auscompgeek** [comment]
Duplicate of #903

**Comment by trollixx** [comment]
@rindeal please try a [CI build](https://bintray.com/zealdocs/windows-ci/zeal-unstable).

**Comment by rindeal** [comment]
That worked, thank you.

**Comment by xueeinstein** [comment]
@trollixx It seems that the recent stable version 0.6.1 (built at 2018-10-11) didn't fix this issue. I am using Arch Linux [official build](https://www.archlinux.org/packages/community/x86_64/zeal/).

![zeal-bug](https://user-images.githubusercontent.com/3424201/50900537-74248380-1450-11e9-9e24-a51768e2f51c.png)

**Comment by trollixx** [comment]
@xueeinshtein reset the default font settings. 0.6.1 doesn't cause this problem anymore, but it does not revert the change already in settings.

**Comment by xueeinstein** [comment]
@trollixx thanks for your reply! It's much better now. BTW, I found that tuning up **Monospace size** in preferences significantly enlarges text in these tags.
