### ISSUE TITLE
Trusty builds in PPA are failing with "Cannot find file: zeal.pro"

### ISSUE THREAD

**Issue by ssokolow** [zealdocs/zeal#962]
According to the [package details](https://launchpad.net/~zeal-developers/+archive/ubuntu/ppa/+packages) on the PPA both the `i386` and `amd64` builds are failing for 0.6.0, leaving me stuck back on the 0.3.1 release included in the trusty LTS repositories.

(With a bug I was hoping to either upgrade away from or confirm the continued existence of and report.)

The culprit appears to be these lines in the [build log](https://launchpadlibrarian.net/358993628/buildlog_ubuntu-trusty-amd64.zeal_1%3A0.6.0-1ppa1~trusty1_BUILDING.txt.gz) (they appear the same for both arches):

    make[1]: Entering directory `/<<PKGBUILDDIR>>'
    qmake zeal.pro QMAKE_STRIP=:
    Cannot find file: zeal.pro.
    make[1]: *** [override_dh_auto_configure] Error 2

**Comment by ssokolow** [comment]
I don't have admin access to the `zeal-developers` PPA. 

You're talking about the proper way to build Zeal when my report is akin to "No matter how many times I re-download it, I receive a corrupted `.exe` installer.

**Comment by trollixx** [comment]
I just realized that you are talking about 14.04. You need at least 16.04 to build Zeal, although for the next release you will need 18.04.

**Comment by ssokolow** [comment]
Then why is the PPA still configured to attempt to build it for 14.04?

**Comment by trollixx** [comment]
What do you mean? There are old packages, but no new versions should be built for 14.04.

**Comment by ssokolow** [comment]
While I was looking through the repo, all of the information that jumped out (status indicators, build logs, etc.) gave the impression that it was still trying to build recent versions and failing.

I may have misinterpreted Launchpad's less-than-ideal UI design though.

**Comment by trollixx** [comment]
Hm, it does look like 0.6.0 was built for Trusty. Then you should be able to just install it.

**Comment by trollixx** [comment]
Okay, that's weird, and UI is indeed confusing. Not sure, what happened there. 0.3.1 should be the latest available version for Trusty.

@Epskampie did you try to rebuild a package for Trusty for some reason? I thought Launchpad would not let to submit updates for unsupported Ubuntu releases.

**Comment by ssokolow** [comment]
Note that Trusty is a Long Term Support release and is supported until April 2019 (14.04 + 5 years).

**Comment by trollixx** [comment]
I guess that's why it allowed to submit an update. Although, trusty is not in our [list](https://github.com/zealdocs/zeal-packaging/blob/master/ubuntu-ppa/ppa-upload.sh#L4).

I've decided a while ago to only support the latest Ubuntu LTS release. Basically that means that Zeal keeps compatibility with corresponding Qt version provided by the distribution.

**Comment by ssokolow** [comment]
Well, given that, I'm glad that 14.04 got stuck on a release where my only complaint is a bug which causes my Super+Z toggle to sometimes require a second or third press to actually hide the window.

Hopefully, when I find time to upgrade to 18.04, I'll get an equally reliable release.

**Comment by trollixx** [comment]
Hm, I deleted 0.6.0 for Trusty, but 0.3.1 did not reappear automatically. Perhaps it will after some time, or maybe not at all, not sure.

Anyway, I think going forward offering Snap packages is the best distribution channel for Ubuntu users.

Closing this, as there's nothing to fix.

**Comment by ssokolow** [comment]
Assuming it works as advertised, snap *does* sound like the best option.
