### ISSUE TITLE
Xorg process high CPU usage when Zeal is running

### ISSUE THREAD

**Issue by guoqiao** [zealdocs/zeal#965]
I am using Ubuntu 16.04, and install zeal recently.
I notice once I start zeal, my computer becomes very slow.
And in `htop` command, I can see this process is using high CPU:
    
    /usr/lib/xorg/Xorg -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch

And once I quit zeal, the process goes back to peace.

**Comment by guoqiao** [comment]
@trollixx 
My docsets:

- Ansible
- Docker
- Jinja
- Nginx
- Python 2
- Python 3

**Comment by aliilgimdemirel** [comment]
I have a similar 'issue' in my 16.04 also. With time (even when I am not using it for hours) It makes the frame rate of my OS drop. Things become 'slow-mo' looking but are still functioning perfectly. When zeal is closed, all is back to normal instantaneously.

My docsets:  
* Bash
* C
* C++
* CMake
* Markdown
* Python 3
* Qt 5
* Vim

It has always been like this I recall (maybe for at least a year)

**Comment by guoqiao** [comment]
@aliilgimdemirel  great to know I am not alone.

**Comment by trollixx** [comment]
Please also report Zeal version

**Comment by trollixx** [comment]
Sounds very similar to the old #211...

**Comment by guoqiao** [comment]
@trollixx  I am using Ubuntu 16.04, my zeal is installed by apt.
Thank you for reminding me the version, I just upgrade to latest version by doing:
```
sudo add-apt-repository ppa:zeal-developers/ppa
sudo apt-get update
sudo apt-get install zeal
```
Seems like the problem is gone.
So you are right, it's because I am using an old version. 
But I guess any one who is using zeal on Ubuntu 16.04 without adding ppa will have same problem.
