### ISSUE TITLE
Does zeal support uri invocation?

### ISSUE THREAD

**Issue by TheNetAdmin** [zealdocs/zeal#967]
I'm trying to invoke zeal from other tool though uri, I noticed that zeal support cli invocation, but does it support uri? I've not found related posts or issues yet.

Thank you.

**Comment by trollixx** [comment]
Zeal supports dash [URL schemes](https://kapeli.com/dash_plugins).

**Comment by TheNetAdmin** [comment]
Thank you very much, I'll see to it.
