### ISSUE TITLE
windows 0.6release

### ISSUE THREAD

**Issue by Danielesk** [zealdocs/zeal#969]
@trollixx 
When will the Windows 0.6 release be released?

**Comment by Danielesk** [comment]
![123](https://user-images.githubusercontent.com/10652829/43992185-e8d4823a-9dad-11e8-9b35-2ffe3cabc5b8.png)


I want to know if these two buttons work? The two buttons I have seen since I installed it are always grayed out and I can't click update.

**Comment by intact** [comment]
Update is broken #964
