### ISSUE TITLE
Docset download seems to be successful, but install error 

### ISSUE THREAD

**Issue by GayanEranga1992** [zealdocs/zeal#978]
Docset download seems to be successful (Kapeli/feeds list) but i install docset folder this unzip tgz docset pakage thin i lonch launch zeal browser my manually  added docset very slowly no image icon ????????????? how to install docset manually you can add this feature

**Comment by trollixx** [comment]
Do you have folders with non-Latin characters in the path to the docset storage?

**Comment by trollixx** [comment]
Unfortunately, docset archives do not contain all information that Zeal needs (icons, search keywords, some other), so manual installation results in a poor user experience.

**Comment by GayanEranga1992** [comment]
i go to Kapeli/feeds github page open xml file copy url  and dowanlad tgz file unzip my docset folder i add 2 images,mate file
