### ISSUE TITLE
Bundle VC++ redistributable with Zeal for Windows

### ISSUE THREAD

**Issue by nishanthkarthik** [zealdocs/zeal#979]
On a bare Windows 7 environment without admin access, the `api-ms-win-crt-runtime` is missing. Since I don't have admin access (because work), I don't have a way of installing the runtime. Can we bundle this with the installer?

https://msdn.microsoft.com/en-us/library/ms235299.aspx

**Comment by nishanthkarthik** [comment]
Please let me know if you need an additional hand in dev/testing

**Comment by CorruptComputer** [comment]
@trollixx Could you just bundle installer that as a pre-install dependency for Windows 7 and 8? It looks like 8.1 and 10 already come with it.
