### ISSUE TITLE
Click the ">" of CMake docset's first label "> s", Zeal crash

### ISSUE THREAD

**Issue by tokenarky** [zealdocs/zeal#980]
1. Platform: Windows, Manjaro Linux
2. Version:   0.5.0
3. Docset:   CMake
4. Action:    Click the ">" of CMake docset's first label "> s"
5. Result:     Zeal crash

![zeal_2018-08-25_16-36-22](https://user-images.githubusercontent.com/17881318/44616596-246c6380-a885-11e8-9115-f7ad9187a0d4.png)

**Comment by trollixx** [comment]
Weird, seems like a corrupted docset. I'll double check.

**Comment by trollixx** [comment]
@Kapeli The CMake docset is corrupted, there are a dozen records with `type` set to `NULL`:

![gh-970](https://user-images.githubusercontent.com/714940/45591345-47d37d00-b91e-11e8-9d06-e74fe4f33291.PNG)

**Comment by trollixx** [comment]
I've added a check in Zeal to prevent this crash.

**Comment by Kapeli** [comment]
@trollixx thanks for letting me know. I'll fix it ASAP.
