### ISSUE TITLE
Bootstrap 3 content missing

### ISSUE THREAD

**Issue by sharun-s** [zealdocs/zeal#987]
Using Zeal 0.6.0 on ubuntu 18.0.4. I have downloaded both the Bootstrap 3 and Bootstrap 4 docsets. Bootstrap 4 works fine. With 3 I get only the index. I checked the .local/share/zeal directory of both and docs are missing for 3.

**Comment by trollixx** [comment]
Try to delete and redownload the broken docset

**Comment by sharun-s** [comment]
Thanks! That resolved it.
