### ISSUE TITLE
Provide mysql version 5.7 documentation

### ISSUE THREAD

**Issue by Danielesk** [zealdocs/zeal#988]
Can you provide documentation for mysql version 5.7? The default is 8.0; the version is differentiated like the supplied java document.

![java_doc](https://user-images.githubusercontent.com/10652829/45254494-c6bf3780-b3ab-11e8-8d51-b6566c7affa0.png)

**Comment by auscompgeek** [comment]
Duplicate of #208.

**Comment by trollixx** [comment]
per above
