### ISSUE TITLE
Windows: Can't remove desktop shortcut - (all users install)

### ISSUE THREAD

**Issue by nmat** [zealdocs/zeal#991]
OS: windows 10
Zeal: 0.5.0

During install (all users on this computer) there is no way to ask Zeal to not install a desktop shortcut. When zeal is installed then a desktop shortcut is created but that can't be removed.

Uninstalling zeal removes the shortcut but it seems that there is no way around not being able to have the shortcut created on desktop. Can this be optional in the install and also that it can be removed from the desktop?

I have tried to:
1. Right click delete (but does not work)
2. Drag icon to trash (does not work)

This only happens on installing the application for all users on computer.

However reinstalling with only my user after installing it with (all users) causes error with QT not being found for the launch of application. So the only way to have it installed after installing it with all users is to keep it for all users.

**Workaround:**
Install zeal for only my user in advanced.

**Comment by trollixx** [comment]
The MSI package lacks many features, and has a bunch of issues. :(
