### ISSUE TITLE
Windows: Pages with * (star) in URL cannot be opened

### ISSUE THREAD

**Issue by mmaulwurff** [zealdocs/zeal#994]
![zeal-star](https://user-images.githubusercontent.com/742823/45663942-4e870d80-bb33-11e8-84ca-4fac0a4ca06e.png)

Example: std::shared_ptr page in C++ documentation contains a link to
file:///C:/Users/kromm/AppData/Local/Zeal/Zeal/docsets/C++.docset/Contents/Resources/Documents/en.cppreference.com/w/cpp/memory/shared_ptr/operator*.html

This can be considered a docset's problem, though.

**Comment by trollixx** [comment]
Linux and macOS allow asterisks in file names, Windows doesn't. I think this will stay open until #138 gets implemented.

**Comment by trollixx** [comment]
Marking this as a duplicate of #1009, which is not Windows specific, but caused by the same underlying problem, and contains more discussion.
