### ISSUE TITLE
Update macOS build instructions

### ISSUE THREAD

**Issue by dakira** [zealdocs/zeal#995]
Hey,

I tried the [build instructions](https://github.com/zealdocs/zeal/wiki/Build-Instructions-for-macOS) in the wiki but it seems Zeal moved to using cmake instead of qmake/make  since those instructions were written.

Do you have any updated hints on building Zeal on a Mac?

**Comment by dakira** [comment]
@trollixx thanks, I'll try to figure it out. Which version of Qt5 would you recommend?

**Comment by markwu** [comment]
I have a homebrew formula if you want to try it.

https://github.com/markwu/homebrew-personal/blob/master/Formula/zeal.rb

Please keep cmake in version 3.12.0. It will failed to build zeal in newest cmake version 3.13.0.

**Comment by markwu** [comment]
it is error messages came from cmake 3.13.0 and qt 5.11.1.

```
Last 15 lines from /Users/markwu/Library/Logs/Homebrew/zeal/01.cmake:
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LibArchive: /usr/local/opt/libarchive/lib/libarchive.dylib (found version "3.3.3")
-- Found SQLite: /usr/lib/libsqlite3.dylib (found version "3.24.0")
-- Configuring done
CMake Error: AutoUic (Registry): The uic executable "" does not exist
```

**Comment by trollixx** [comment]
Seems like you don't have `uic` installed. It should be part of the Qt installation.

**Comment by markwu** [comment]
The uic executable is there, I fixed that problem after downgrade cmake to 3.13.0. I guess it is the bug of cmake.

But new error messages comes, I still trying to figure it out:

```
==> Downloading https://github.com/zealdocs/zeal/archive/v0.6.1.tar.gz
Already downloaded: /Users/markwu/Library/Caches/Homebrew/downloads/317934405fce17c9a1ce09ff56d59254224b67e098b2d531d0fe801f88d34796--zeal-0.6.1.tar.gz
==> Patching
patching file src/libs/core/CMakeLists.txt
==> cmake ..
Last 15 lines from /Users/markwu/Library/Logs/Homebrew/zeal/01.cmake:
  any of the following names:

    Qt5WebKitConfig.cmake
    qt5webkit-config.cmake

  Add the installation prefix of "Qt5WebKit" to CMAKE_PREFIX_PATH or set
  "Qt5WebKit_DIR" to a directory containing one of the above files.  If
  "Qt5WebKit" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  src/libs/core/CMakeLists.txt:13 (find_package)
```

**Comment by trollixx** [comment]
It just tells you that Qt WebKit is missing. It's not part of the standard Qt distribution.

**Comment by markwu** [comment]
Then, I need to figure out how to add it back, I got `qt` `5.11.1` from `homebrew` bottle.

**Comment by markwu** [comment]
The last webkit submodule for qt is verion`5.9.1`, there is no submodule for 5.11.x.

**Comment by dakira** [comment]
@markwu that's exactly the problem I had. :)

**Comment by markwu** [comment]
Maybe port to `qtwebengine` is the way to go, seems `qtwebkit` does not maintain for 1 years.

**Comment by markwu** [comment]
cmake `3.13.1` already fixed the uic excutable bug, you can use it instead of `3.12.4` now ...

**Comment by markwu** [comment]
Finally, I can build zeal with Qt 5.11.1 and QtWebKit 5.212.

**Comment by markwu** [comment]
Here comes with my personal Tap https://github.com/markwu/homebrew-personal

You can follow this instructions to install zeal with `qt 5.11.x` and `qt-webkit 5.212`

```
brew tap markwu/personal
brew install qt
brew install qt5-webkit
brew install zeal
```

If you want to install zeal with `qt@5.5`, you have to extract it first. Please follow the instructions to install it:

Use `brew extract qt@5.5 YOURTAP/PATH` to restore qt@5.5 formula to your tap. And move it to homebrew/core tap path, and rename the file to `qt@5.5.rb`, and remember open it and change the class name to `QtAt55`.

```
brew tap markwu/personal
brew install qt@5.5
brew install zeal-qt@5.5
```

**Comment by markwu** [comment]
I try to build zeal master branch with --HEAD, it works.

**Comment by trollixx** [comment]
Any volunteers to update the [wiki](https://github.com/zealdocs/zeal/wiki/Build-Instructions-for-macOS)? :)

**Comment by markwu** [comment]
Sorry, English is not my native language.  I will leave my formula there, and if someone can update the document, I'll be appreciated.

If you want to host and maintain the brew formula, you are okay to go.

**Comment by dakira** [comment]
I'll try to replicate this in the next couple of days and update the wiki.

**Comment by pryorda** [comment]
I'm testing this now will update in a few.

**Comment by pryorda** [comment]
` cp -Rp /usr/local/Cellar/zeal/HEAD-a64dadc/Zeal.app ~/Applications/Zeal.app `

**Comment by razzfox** [comment]
I needed to run
```
brew install libjpeg libpng
```
before `qt5-webkit` would complete successfully.

**Comment by sunjie21** [comment]
> Any volunteers to update the [wiki](https://github.com/zealdocs/zeal/wiki/Build-Instructions-for-macOS)? :)

are there any plans to port from Qt WebKit to Qt WebEngine?

**Comment by dakira** [comment]
I finally updated the build instructions in the wiki. :)

**Comment by frankli0324** [comment]
https://github.com/zealdocs/zeal/commit/090f5270545c24c7840fb199b994b382b5606323

On MacOS, you need to enable loopback aliases other than 127.0.0.1 manually:

`sudo ifconfig lo0 alias 127.0.0.22 up`

**Comment by markwu** [comment]
> [090f527](https://github.com/zealdocs/zeal/commit/090f5270545c24c7840fb199b994b382b5606323)
> 
> On MacOS, you need to enable loopback aliases other than 127.0.0.1 manually:
> 
> `sudo ifconfig lo0 alias 127.0.0.22 up`

What's will happened if I don't enable  loopback aliases?

**Comment by markwu** [comment]
Okay, now I know what's going on.

![image](https://user-images.githubusercontent.com/196861/77747971-88a36a80-705a-11ea-993d-6e8a2bafe2ed.png)

**Comment by markwu** [comment]
Maybe I should create a daemon for this https://medium.com/@david.limkys/permanently-create-an-ifconfig-loopback-alias-macos-b7c93a8b0db ?

**Comment by frankli0324** [comment]
sure yes

**Comment by trollixx** [comment]
I don't use macOS much, it doesn't route all `127.*.*.*` addresses by default? I picked `127.0.0.22` to reduce possibility of conflicts.

**Comment by markwu** [comment]
> I don't use macOS much, it doesn't route all `127.*.*.*` addresses by default? I picked `127.0.0.22` to reduce possibility of conflicts.

Mac doesn't route all `127.*.*.*` by default I guess, therefore I need to add alias for it.

Does linux and windows route all `127.*.*.*` by default?

**Comment by frankli0324** [comment]
> Does linux and windows route all `127.*.*.*` by default?

yes

**Comment by trollixx** [comment]
I have just pushed a change to use `127.0.0.1` instead of `127.0.0.22`. Hopefully that will make it work out of the box.

**Comment by markwu** [comment]
Do you use different port when change it to use 127.0.0.1? 

For many developers, they installed local http server, it use 127.0.0.1 and localhost.

There might have some problems if you use the default 80 port.

**Comment by markwu** [comment]
@trollixx  I saw you use port other than 80. Thanks!

I also removed the loopback alias daemon from this formula.

**Comment by trollixx** [comment]
> @trollixx I saw you use port other than 80.

Yes, a random non-priviliged port is selected on every run.

**Comment by markwu** [comment]
I already update the wiki documents about building zeal on macOS. Since there is no need for qt5-webkit, I already removed it and related patches from my formula.

It is so good that zeal adapt WebEngine, the life become easier.

**Comment by sikmir** [comment]
Zeal can be installed from macports: https://github.com/macports/macports-ports/pull/7444.

**Comment by RakibFiha** [comment]
> I try to build zeal master branch with `--HEAD`, it works.
> 
> You can build master branch with the following instructions
> 
> ```
> brew tap markwu/personal
> brew install qt
> brew install qt5-webkit
> brew install --HEAD zeal
> ```

Is working as of 27th of August 2020

**Comment by markwu** [comment]
@RakibFiha  Just following the wiki, it should be work.

https://github.com/zealdocs/zeal/wiki/Build-Instructions-for-macOS
