### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by rugk** [zealdocs/zeal#998]
It would be nice, if this was available as a flatpak (on https://flathub.org/)

**Comment by trollixx** [comment]
That's the plan. @barthalion was looking into that, but then I was too busy at the time. I merged his #911, but haven't figured out yet what the next step should be.

**Comment by bilelmoussaoui** [comment]
@trollixx Do you need any help with this one?

**Comment by barthalion** [comment]
I do have a ready manifest already, just didn't submit it to Flathub yet.

**Comment by bilelmoussaoui** [comment]
@barthalion perfect!! hope to see it soon on Flathub :+1:

**Comment by trollixx** [comment]
This will be done once flathub/flathub#665 is merged.

**Comment by trollixx** [comment]
@barthalion Thank you!
